### ISSUE TITLE
HazeOver "fake window" shouldn't be listed

### ISSUE THREAD

**Issue by fturcheti** [lwouis/alt-tab-macos#102]
First of all, thank you for the effort of creating this app. I use HyperSwitch for a long time, but it breaks from time to time and it's future is not clear. So, it was a great surprise to discover AltTab, and I'm willing to help if I find a way to. Now, to the issue I'm facing…

---

[HazeOver][] is a "distraction dimmer for Mac", like the old [Isolator][]. It "dims" the background by displaying a "fake window" between the active window and the windows from other apps. When this "fake window" is active, i.e. HazeOver is turned on, it shouldn't be listed in the AltTab selector. This is what the user would expect, as this window should not be recognized as a proper window. HyperSwitch get this right, excluding this window from its listing. But AltTab display it. 

<figure>
<img alt="Screenshot of AltTab listing HazeOver fake window" src="https://user-images.githubusercontent.com/365403/71627042-1d6b0900-2bcf-11ea-8ea9-69422c133615.png">
<figcaption>Screenshot of AltTab listing HazeOver fake window</figcaption>
</figure>

[HazeOver]: https://hazeover.com/
[Isolator]: https://www.willmore.eu/software/isolator/

**Comment by lwouis** [comment]
Hi! Thank you for sharing your issue!

To give you some perspective, from a technical standpoint, windows are provided by macOS either from the CoreGraphics APIs or from the Accessibility APIs. There are actually private, undocumented APIs which is we use to perform things that public APIs can't do, but overall APIs are either of the CG or AX family.

The point being that the windows you get from either of these APIs family are very messy. Chrome "find in page" search box for instance is implemented by Chrome for some reason as a window, and from a technical perspective, there is no way to differentiate a window that the user perceive as a window, and a window that the user perceive as not a window.

The current code in alt-tab is a very primitive check on window dimensions (a "real" window should  be more than 200px wide and 200px tall). I've seen the Hammerspoon project use a list of app names.

I'm really not sure how we should move forward with this issue of discriminating between windows. I'm open to proposals :)

**Comment by fturcheti** [comment]
I can't give great technical advises because I have no experience developing macOS software, but I tested Hammerspoon's switcher (I'm a Hammerspoon user too, but its switcher was a lot buggier compared to HyperSwitch when I tested it) and it works properly in this situation, like HyperSwitch. 

Searching Hammerspoon's source code for the list of [ignored apps][] I couldn't find HazeOver (although Isolator is there). Another info I should add: HazeOver has a Preferences window, and this window, that's a "proper window", is not ignored by those apps, different from its "fake dimmer window".

So I was thinking that maybe there is some property of the "fake window" that Hammerpoon and HyperSwitch are taking into account when filtering them… 

[ignored apps]: https://github.com/Hammerspoon/hammerspoon/blob/d47d16d80064ab0f26f3b0626d248e446b375262/extensions/window/filter.lua#L142-L152

**Comment by lwouis** [comment]
I investigated further. From the CG APIs, the only attributes we could use to discriminate would be size of windows, which we use already, and title. In the case of HazeOver the title is the empty string. However, there are some actual windows that have an empty title, for instance Line (see #12).

I focused first on CG APIs as they don't impact performance much since the object is there, and it's just an attribute lookup. For the AX APIs, looking at attribute is actually expensive as the call goes to the WindowServer and back to fetch the info. I found that the `subrole` attribute has a suspicious value in the case of both HazeOver, and the Chrome search box.

I added that filtering, and it seems to fix your specific issue. Another problem with the AX APIs, outside of performance, is that it's not available on other-space windows. Luckily here, HazeOver overlay is only present on the current space, so we can always check its `subrole`. However for other apps that have windows on other spaces, we would not be able to filter on `subrole` as we don't have an `AXUIElement` object for other-space windows.

@fturcheti Could you please check out the [new release 2.0.3](https://github.com/lwouis/alt-tab-macos/releases/tag/v2.0.3) and let me know if that fixes it for you? Thank you!

**Comment by fturcheti** [comment]
@lwouis Thanks for investigating the issue the issue! I tried the new release and the problem is _almost_ resolved.  

> Luckily here, HazeOver overlay is only present on the current space […]

Unfortunately that's not true. When I started the test that fake window HazeOver creates was not present in AltTab window listings, so I thought the problem was fixed. But I was testing solely on my Macbook and I often use HazeOver with two monitors, so I decided to plug my external monitor to test that scenario too. And the issue occurred again. The screen of the external monitor is recognized as another space and that invalidates the assumption above, bringing the issue back.

**Comment by lwouis** [comment]
Quite annoying indeed.

When i worked on v2, i settled on a solution but there was another i
considered and maybe would fix this issue, as well as be more robust
solution going forward:

Use the trick of spawning an invisible window on each space so that we can
access windows from other spaces without resorting to private APIs. This is
demonstrated by SpaceSwitcher (
https://github.com/bigbearlabs/SpaceSwitcher).

I will give it a try if i managed to find time at some point. The downside
would be that the user would need to manually visit the space. That
reasonable though i think.

Also i'm not sure it actually helps give the AXUIElement from other spaces.
Again, this needs experimentation.

**Comment by fturcheti** [comment]
Thank you again for the effort on trying to fix this.

**Comment by lwouis** [comment]
> Also i'm not sure it actually helps give the AXUIElement from other spaces. Again, this needs experimentation.

I actually tested a minute ago, and even when i bring the preferences window in space 2, I can't get the `kAXWindowsAttribute` from the `AXUIElement` from the space 2 windows. I think the solution I mentioned above helps with focusing windows from other space as you can focus your own app window if you have an invisible one in every space, then you can just focus the target window in that space. Currently I use a private API to bring the window into the current space, get the `AXUIElement`, then put it back in its original space, then focus it.

I don't know how we could discriminate windows better. I would love to know how the other closed-source apps do it

**Comment by fturcheti** [comment]
> I don't know how we could discriminate windows better. I would love to know how the other closed-source apps do it

I don't know if this can help, but Hammerspoon's windows switcher treats this HazeOver issue the right way.
