### ISSUE TITLE
Always on top simulator moving desktops

### ISSUE THREAD

**Issue by PolCPP** [lwouis/alt-tab-macos#1021]
Not sure if Alt-tab or Big sur issue. But i found a strange issue when dealing with the ios simulator and Alt-tab.

Let's say i have VS Code and iOS Simulator on Desktop 2, i have Stay on Top selected on the ios simulator.

I move to desktop 1 cycle through alt-tab and select the ios simulator, instead of moving to desktop 2,  the simulator is brought to desktop 1.

**Comment by lwouis** [comment]
This is normal behavior from the Simulator. You can confirm by using the built-in app switcher, and sure enough, it does the same thing as AltTab.

It seems that the "Stay on Top" option makes the window behave the same as the `Assign to: All Desktops` built-in macOS feature. That is: the window is on all Spaces, and focusing it brings it to the active Space, instead of focusing it on the Space it was on previously.

![image](https://user-images.githubusercontent.com/106195/123642972-deb71d00-d85e-11eb-8adc-b400bd74435f.png)
