### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by izhakjakov** [lwouis/alt-tab-macos#1025]
**Is your feature suggestion related to a problem? Please describe.**
I am a new user and I have some questions about the app but I don't a see "Help" or "FAQ" section.

Or a link to some forum or chat where I can ask questions

**Describe the solution you'd like**
A "Help" or "FAQ" section
And a link to some forum or chat where I can ask questions

**Describe alternatives you've considered**
Asking a question in github but I do not want to contaminate the project's repo

**Comment by izhakjakov** [comment]
While on it would anyone be able to tell me how to get the name of the window I would like to add to the blacklist?

![image](https://user-images.githubusercontent.com/18270061/124511070-31cf2980-dda3-11eb-88cf-f1717fca1a1f.png)

**Comment by lwouis** [comment]
For a chat, you can go on our discord: https://discord.gg/CVEPeDufJa

There is no help manual in the app. I don't think many people use these anymore these days. It would be lots of efforts for little results. In the case you mentioned, it would be better to spend the energy in improving the UX, which we have a ticket for already: #539 

Regarding a forum or FAQ, I consider github issues here to be just that. You can search keywords in issues and get help from people discussing in the tickets. Here for example, i know that people already asked this question. Here is an example of someone sharing how to get the bundleID: https://github.com/lwouis/alt-tab-macos/issues/858

Note that these are identifying apps, not windows. There is no way to identify windows technically. Their names can change, and their internal IDs change when you close/reopen them.

**Comment by izhakjakov** [comment]
Well I'm sure you know better than me 😄

I still think in app doc would be useful and still use these since I don't like to disturb people with stupid question (I can't always tell whether a question is stupid or not 😅).  I also like to check it out from time to time and discover new features (specially when I start using a new app)

That said this might not be a priority for at this stage and improving the UI might be more important.  
<br>
Thank you for your answer.  The solution from issue #858 work for me :)

**Comment by lwouis** [comment]
I appreciate you took the time to share this. To be honest i'm nostalgic of the time where people actually read manuals and manuals were made with care, before the internet made everyone lazy and disincentivized companies from making good manuals.

I wish we could roll that dial back when it was more sane, but i have to adapt to our times. These days people google issues and ask for help before looking at docs.

I'm glad to see people who read manuals still exist. It warms my heart. I wish it was the norm, and not the rare case for which it doesn't make sense to optimize for, unfortunately

**Comment by ElhemEnohpi** [comment]
I wouldn't mind a bit more documentation. Maybe in the "Configuration" section on the home page? Or the GitHub wiki. But in-app would also be good. I do actually use the little "question mark" link in all the Apple System Settings.

For example, I had to spend quite some time playing around with AltTab's "Appearance" settings, before I figured out what the various sliders and switches do, and how they interact with each other (and I'm still not clear on a few). I will need to do the same for the "Controls" section, but I haven't had time yet. A few simple explanations of them in one place would be helpful I think.

**Comment by lwouis** [comment]
@ElhemEnohpi I think your suggestion is also answered with my previous answer:

> It would be lots of efforts for little results. In the case you mentioned, it would be better to spend the energy in improving the UX, which we have a ticket for already: https://github.com/lwouis/alt-tab-macos/issues/539

Except in the specific case you mentioned, of the Appearance tab being a mess, we have it discussed under this ticket: #351.

In other words, if I had a few weeks in front of me to work on improving the experience of someone trying to change their AltTab preferences, I would rather spend them implementing #351. I think it would result in an app that's intuitive to tweak, and that doesn't need any form of external documentation. Settings would have little text paragraphs describing them, or question marks with tooltips, or diagrams and other visual aids, etc.

**Comment by ElhemEnohpi** [comment]
Thanks for enabling the Wiki. I made a page there with some basic things. Maybe some of it can eventually be migrated to in-app descriptions or tooltips, if that helps. I also learned a few things, so that's good too...

A couple of things that came up in the process, sorry if there are already issues for these:

- I don't see much difference between the "macOS" and "Windows" themes, except for rounded corners. Is there something else?
- I didn't finish describing the checkboxes at the bottom of the Appearance tab yet. What are "status icons"?
- The "fullscreen" green button on the thumbnails doesn't seem to work, I just get the "error" sound.
- I thought there might be a keyboard command corresponding to the fullscreen button, in addition to Q, W, M, that correspond to the other buttons.
- I thought there might be a button to hide the app, corresponding to the H key.
- I'm still a bit mystified by how the "rows of thumbnails" setting affects the size of the thumbnails. Starting from the defaults, if I change from four rows to one row, the thumbnails get much larger, and the height of the display window maximizes, with a lot of blank padding below the thumbnails. I don't know how to explain what's going on there.

**Comment by ElhemEnohpi** [comment]
I watched the video - I'll make some comments in #351 . Thanks for answering the questions above. I finished off the descriptions of the checkboxes. I wish I could better understand/explain the thumbnail/window size sliders. Maybe it's just my eyes, but I can't seem to detect any fade-out animation, although I can see one in the built-in app switcher...

The coloured buttons and the keyboard commands not being consistent is just something I noticed because I was writing about it. I didn't really think about whether I'd use them. I do use app hiding all the time though.
