### ISSUE TITLE
Let the app run without Screen Recording permission, in degraded mode

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#1082]
_Originally posted by @alber70g in https://github.com/lwouis/alt-tab-macos/issues/1081#issuecomment-902592313_

> Showing only app names... like at this point what's the improvement over the built-in app switcher?

Multiple reasons:

1. on a managed laptop it's not possible to use the app 
2. you can still switch windows instead of apps, what you cannot with the built-in switcher
3. built in switcher cannot customize for switching between apps on different spaces, where AltTab can ("Show window from" option)
4. built in switcher doesn't account for hidden tabs and making them visible (AltTab does that, e.g. Microsoft Teams doesn't activate the window with the built in switcher, so AltTab is a huge plus)

**Comment by lwouis** [comment]
A big concern I have with having this degraded me be possible is the impact on the onboarding/permission story. I spent a lot of time on the permissions story. I'm very happy with the current state. I think it's better than a few big name commercial mac apps.

![image](https://user-images.githubusercontent.com/106195/130249549-c7f90e48-54b3-4295-8b68-ca20390f240f.png)

This window blocks access to AltTab. You have to make both section go green. It's kind of gratifying/gamified that way. It goes green in real-time cause I'm listening to the status (no public API for this; was hard to achieve). Furthermore, if the user later remove one of the permissions *while the app is running*, it will detect it, and quit and come back to show this guard window.

With a possible degraded version without Screen Recording, I worry how to communicate the right way. Users have very limited attention span these days, and tend to click without reading. Today this is ok because the window is blocking them until they check the right boxes. Tomorrow with this feature, they could get in the app, and think the app is broken because "there are no thumbnails of windows like on the website's screenshots!". We also probably would want to provide a way to bring the permission window at any point so the user can find the instructions again and confirm "Ok so the permission I need to enable thumbnail is... Screen Recording ok got it". Without that, they may not know which one is required. They may even not know they are running in degraded mode after a while, or if they skimmed through the permission window the first time. We probably want to show some little orange dot next to AltTab icon in the menubar and/or some orange icon next to some text in the preferences that says "You're running in degraded mode. You can see window titles and screenshots by *granting the app more permissions* (italic text is a button to open the permission window)"

I keep mentioning "orange" things because I guess on the screenshot above, we would show the Screen Recording section as orange, or yellow? To signify that it's not great but possible. We would probably want to add a confirmation prompt if the user wants to pursue without it "Are you sure you don't want to grant Screen Recording permission? Without it, the app will not...".

Another way I was thinking about would be more visuals. Next to Screen Recording would be 2 screenshots of AltTab. One with titles and thumbnails, one without. That way the user quickly sees the 2 options. We could also show this for Accessibility with some visual to indicate focusing a window is possible, or it is not.

**Comment by alber70g** [comment]
To make the user extra aware of the features that he's missing out on when not enabling Screen Recording, a second window could open that verifies that the user really does want to not enable Screen Recording.

1. A button can be added that says: "I do not want to enable Screen Recording"
2. A second window opens with the text
    I acknowledge that disabling Screen Recording
    - [ ] disables previews in the app-switcher
    - [ ] disables window titles in the app-switcher
    Confirm (button)

This way you prevent accidents, and you inform the user about the consequences. Furthermore the preference window could have an yellow banner with the text: "Running with limited functionality as **Screen Recording**-permission is disabled"

**Comment by ggedde** [comment]
Agreed!
I spent a lot of time trying to use this without that permission enabled.  I tried disabling it after I turned off Thumbnails and Titles, but that doesn't work and it still requires that permission even if you are not using it.

I do not need Thumbnails or Titles and having this permission enabled is a HUGE security issue. If someone hacks your app they can get access to all kinds of sensitive content. 

* Not to mention this could be a violation of GDPR, HIPAA, and many others.
I would strongly recommend that this gets resolved as soon as possible.
I really think that security should be the default, so I would recommend that this is disabled and that Thumbnails and Titles are disabled by default, then when a user turns on one of those features, then the request for that permission is asked.

@lwouis I agree that your permission screen IS THE BEST I have ever seen and your assumptions for showing degraded mode would work fine I think. I still think having it off by default would be best for security, but I know your concern was users may think it is broken without those features, so I would recommend that you show more screenshots without thumbnails and titles and then show them with thumbnails and titles, but add a Notice next to it saying "In order to show thumbnails and titles you will need to grant permissions for Screen Recording, etc" So I think it is just how you present it and that could address your concern. In the end, do what you think is best, but I do think it is very important to allow some way to use it without that permission enabled.

Thanks.

**Comment by sterafix** [comment]
I would as well love to be able to use AltTab without giving access to screen recording. I don't like giving permissions like this if it's not absolutely essential. I don't really need the preview of the windows, icons would be more than sufficient.

**Comment by unixb0y** [comment]
Is there anything new about this? On some machines, the permission can't be granted and it would be cool to still use the program.

**Comment by lwouis** [comment]
@unixb0y i think @alber70g [drafted a nice UX to deal with this degraded mode](https://github.com/lwouis/alt-tab-macos/issues/1082#issuecomment-903780057). Now it's about someone taking the time to implement it. This UX has a lot of new UI and ramifications in the app so it's quite a large scope.

**Comment by ADTC** [comment]
Hey, I suggest just adding a button on bottom left corner of the permissions blocker called "Run in Degraded Mode..." and this shows a dialog with a text box, with this label above: "[explanation, yada yada...] `\n\n` Please type in _degraded_ to confirm.". The OK button disabled until the correct keyword is typed.

This is a technique some apps and websites use for very serious actions. GitHub uses this for deleting a repository - you have to type in or paste the full repository name. People can still blindly click checkboxes if it gets them through, but typing is an exercise that requires some thinking.

For stronger protection, disable pasting in the text box. Typing with a keyboard input of any kind must be mandatory.

PS: I'm assuming if one of the permissions is successfully granted, it can still be used to enhance the experience.

**Comment by mijorus** [comment]
I'm interested in this feature too.

There is no need IMHO to show thumbnails in the app switcher.

**Comment by ADTC** [comment]
It depends on how you use it. I ended up disabling the thumbnails myself. I now choose between Alt-Tab, Mission Control and App Expose as I work - whichever is most convenient. Only the latter two shows thumbnails.

**Comment by theodopolopodous** [comment]
Would be very happy to have this feature

The main feature I use is hiding minimised apps from the CMD-Tab menu.  So any way to turn off the screen recording would be appreciated

(esp as I was recently hacked and very cautious now.  Not that I think it was through this app, but any unnecessary monitoring and recording might get ruled out)

**Comment by mestradev** [comment]
I agree, there should be the option to run the app without screen recording permissions. I never use thumbnails either.

**Comment by h4x0rlol** [comment]
Very interested in this feature too

**Comment by JuanPabloOS** [comment]
Do you know why "it's not possible to use the app on a managed laptop"? 

I have limited permissions to what I can do in my work computer, so I need to ask for help when installing a new application, I see that some of my colleagues can use the app in their laptops where they have full access.

**Comment by andreasscherman** [comment]
Would love to see this too. I was hoping that removing permission while not showing preview would let me pass through, unfortunately it still blocks it when opening.

**Comment by FalconFour** [comment]
Of course I don't want this app to have "screen recording" permission! I have it on another computer, and it frequently pops up in bright purple in my status bar saying it's "observing my screen". Talk about creepy! I know about the limitations and requirements of APIs, and the reasoning behind asking for that permission, but it is no less creepy and intrusive. I would gladly live without the previews/screenshots in order to just let me alt+tab (Cmd+Tab) windows instead of applications, in most-recently-used order. The window-switching mess of MacOS switching applications instead of windows has just become too much to bear - it's a daily, constant annoyance.

Very frustrated that there's no way to consciously decline this permission and still run the app without that functionality. Maybe MacOS makes users _too_ aware of permissions that apps have, in a way that degrades the user experience by making it seem far creepier than it is, but that seems to be the Mac way of doing things. Having that purple "pill" on the status bar makes it feel strongly like someone is watching the screen like TeamViewer, and it's far more intrusive than it has a right to be.

**Comment by lwouis** [comment]
A workaround for people who are worried, until we implement this ticket: install an app like LittleSnitch, and block all networking for AltTab. That way you can rest easy about fear of the app leaking your screen. All images or video that could be recorded (nothing actually is, in reality) would remain on your device and couldn't be sent to anyone else.

**Comment by ADTC** [comment]
I think some users can't use AltTab at all, since they are using a locked-down device that doesn't even allow them to grant the screen recording permission.

FWIW, if the "Hide window thumbnails" checkbox is checked, it looks like the screen recording permission is never used. (Is that right? It's not really necessary for capturing titles, right? In that case, your onboarding story looks wrong.)

In this case, the onboarding story dialog can have the same checkbox (or a button with the same label) which allows bypassing the screen recording permission, and in the Settings, this checkbox should be permanently checked and disabled, with a note that screen recording permission is needed to uncheck it.

**I pledge sponsorship if you do this, _and_ the other thing I asked (multi-line titles). _Who else here would like to pledge?_** 🙂

> BTW note that once the user has decided to bypass, this choice should be remembered, until the user enables screen recording permission and then disables it again. This is to prevent the onboarding story dialog from showing every time AltTab starts.

**Comment by lwouis** [comment]
@ADTC please read the discussions in this thread. These topics have been addressed multiple times.

> It's not really necessary for capturing titles, right?

It is. That's why we say it is in the Permissions Window. Without Screen Recording permissions, we can't grab the titles of windows.

Apple bundled a lot into that new Screen Recording permissions. It's necessary from small things like window titles up to large things like literally recording the entire screen at 60ps. So AltTab gets shown in purple like we are recording the screen, when in fact we are sending a few calls to grab a few screenshots of windows, and asking for their title.

Apple design is a bit all-or-nothing, and users get scared when the purple UI shows up. The only thing we can do is offer this Degraded Mode, which will have anonymous windows, without title of screenshot, just the app names. To me it seems useless, but a few people have said they would use it like this.

I'm open to it, that's why this ticket is still open, however we need to work on the UX, as has been discussed many times. See [my concerns](https://github.com/lwouis/alt-tab-macos/issues/1082#issuecomment-902745497) and a [first draft of the UX](https://github.com/lwouis/alt-tab-macos/issues/1082#issuecomment-903780057).

**Comment by webuniverseio** [comment]
With https://wiki.keyboardmaestro.com/manual/Window_Switcher (part of keyboard maestro), which does not have a screen recording permission, I checked that it captures titles and icons in the same way as alttab in "hide thumbnails" mode.

I'm sure that others find screen recording permission scary at first, especially when they start using this app (or for reasons like that thread about Sonoma purple screen sharing icon). Another alternative to using something like little snitch (pretty cool tool, thanks for mentioning it!) is to review source code and compile yourself.

Anyway thank you so much for alttab, it is a life saver.

**Comment by lwouis** [comment]
@raayu83 I think they may be getting the titles from another API that us. We use the accessibility APIs. It's better for us for [these reasons](https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1112220163). I think they may be using the CG APIs. These have [downsides](https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1142326018).

We may move to using CG for the specific case of this Degraded Mode. However, it would create all sorts of problem, as discussed in the links above, as well as [this one](https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1140475138). The titles from the CG and AX APIs are sometimes different, and AX is more accurate. In other words, the titles would sometimes be incorrect if we did that.

The general issue with this ticket is that there is little demand for this Degraded Mode. It's quite a niche feature. Yet it's a lot of work to draft the spec for it, and even more to implement it. As a reminder, #1179.

I'm hoping that someone will step up and share a nice spec, then share a PR 🙏

**Comment by spirosag** [comment]
@lwouis I didn't know how much I rely on alt-tab until I moved to a managed mac for work.  Totally understandable that this would need a lot of effort. Do you have any alternatives to suggest for us that can't give extra permissions due to restrictions?

**Comment by jdaln** [comment]
Also looking forward to this feature

**Comment by RaLtYwor** [comment]
I was about to try this app, but the fact that from the very beginning, there was no way to use it without mandatory screen sharing, and also the fact that at least three years after the request for this functionality, it still hasn't been added, is quite concerning.

I absolutely don't need previews of my apps, just their icons, basically the same as the default alt-tab on MacOS, but without some apps. The fact that despite this, I'm forced to share my screen makes this app useless for me. I'm immediately deleting it and certainly won't be able to recommend it to anyone for use 👎

**Comment by sterafix** [comment]
> [...] it still hasn't been added, is quite concerning.

This is a free-to-use open-source app. You are welcome to add features that you are missing instead of complaining that a free app doesn't fulfill all your needs.

**Comment by lwouis** [comment]
@RaLtYwor 

> I'm immediately deleting it and certainly won't be able to recommend it to anyone for use 👎

This reads like a customer complaining about a purchase. This project is volonteer work.

Your behavior is akin to walking into a dog shelter and complaining to the people there. Volonteers that decide to come and work on this project on their weekends and evenings, asking nothing in return. Showing up there as a new face. No one knows you. You haven't contributed anything so far. And complaining right away to the volonteers there.

Please consider that other people have their own lives. Not everything revolves around you. Not everyone thinks it's a problem to have screen sharing permission required to display thumbnails and window titles. Not everyone needs to hear that you're not perfectly happy with this app you downloaded for free.

I'm not talking about providing constructive criticism instead of complaining for others to do the work for you. I'm talking about being polite. Maybe nicely ask first, see if you can get traction with other people here. Look for workarounds. Finally, it would be very reasonable to conclude that this app is not perfect for you, and moving on quietly. You can refrain from sharing your inner dialog.

**Comment by ADTC** [comment]
I am super happy with this app. One of the few apps that I consider essential in macOS for productivity features that Apple has refused to bake into the OS (or couldn't, due to patents). Thank you for giving this away for free. ❤️

**Comment by RaLtYwor** [comment]
@lwouis ah yes, of course, how could I forget that nobody is allowed to voice their negative opinion or concerns about OSS. Since this ticket has been sitting here for 3 years, and all it has is "oh gee, I'm so happy about this user story that forces the user to enable screen sharing that I don't want to do anything towards 'degraded mode'", then all the dissatisfied people just need to shut up. Well, thank you for your behavior, just one more reason to never touch any software released by you.

**Comment by lwouis** [comment]
You're allowed to voice your negative opinions. You did it, didn't you? No one is censoring you.

My message above was to make you aware that it's not considered appropriate to go to a volunteers project and start criticizing people working there, as a newcomer. I'm sharing social norms with you, as you seem unaware of how your actions are perceived. It is useful, in general, to be careful and polite in society. If everyone is too self-centered, society is not a nice place.

**Comment by justinnoel** [comment]
This conversation has led me to donate once again to this great project. 

I've tried (and paid for) several others and this OSS project wins hands down.

Yes, I would prefer to not allow screen recording, but the app is perfect otherwise. 

Thanks so much for it @lwouis!

**Comment by sterafix** [comment]
@RaLtYwor it's also your tone and your choice of words that's the problem here, at least for me. It's like going to one of these guys who are making huge soap bubbles in the city center to entertain kids and telling him, that his soap bubbles are ugly as hell and no one should be looking at / enjoying them. 

I myself also dislike that one can't use the app without granting screen sharing permissions! That's a privacy no-go for me (not 100% sure if that's justified though, but that's another topic). So: I, 3y ago, added a comment to this issue in which I stated my opinions in a friendly way (constructive criticism). Then, I subscribed to it and since then I am waiting and hoping that this issue would be solved eventually, such that I can use the app. However, @lwouis would need to change his opinion on the importance of the user onboarding/permission story for this. I think that the chance of this happening is at its lowest if you are being rude and unfriendly.

**Comment by FalconFour** [comment]
> However, @lwouis would need to change his opinion on the importance of the user onboarding/permission story for this.

And that's exactly why we're here. I, too, am following along this conversation with the hopes that maybe something will knock some sense into the developer and stop requiring this permission with no degradation path. I'm stuck using a lesser, paid app (Contexts) that hasn't been updated in ages and has bugs with new MacOS (hijacking desktop-switches, e.g. when an app goes full-screen)... but at least it doesn't want to constantly record my screen.

People freaking-out in arms about Microsoft Recall, which is a gigantic company exposed to gargantuan amounts of legal trouble for that feature, but yet AltTab gets a pass because it's doing effectively the same thing as a small-time app? Hm. People are funny.

I think the anger is justified, *specifically* because the dev denies it's a problem.

**Comment by lwouis** [comment]
@FalconFour 

> maybe something will knock some sense into the developer

> the dev denies it's a problem.

This is wrong. I'm in support of adding this feature.

I scrolled up to see my previous messages to try and understand how you got the wrong idea. After reading, I don't understand how you read it and thought that i'm opposing it.

The only reason this ticket is still not implemented already is that there is a lot of work to spec and implement it. Please see the pinned ticket #1179 to understand why tickets are not being implemented quickly these days.

**Comment by webuniverseio** [comment]
This conversation has led me to donate as well. Alt-tab is definitely essential for me. 
I reviewed the code since it is open source and compiled a local version for privacy reasons, and as it was suggested earlier, for those extra paranoid (count me in), there is Little Snitch, which is amazing at blocking and monitoring **all** unwanted traffic from any program.

**Comment by ADTC** [comment]
@lwouis just lock this unproductive thread. For what it's worth, when I have thumbnails turned off and I only have icons and titles, I don't see any purple icon indicating that screen recording is happening. That's good enough for me, given the difficulty of implementing this.

I'm not sure how it grabs titles without triggering the purple icon though since you said that grabbing titles needs screen recording permission. Based on your previous comments, I believe it uses an API that's only exposed via screen recording permission but doesn't actually require you to record the screen.

**Comment by jayr434** [comment]
I'd like to throw in my support for the Degraded Mode feature. Sucks that people can be a bit rude about requests on here, but I'm sure people like me (who have to follow compliance rules related to screen recording on company machines) are looking forward to any update.
Cheers btw, apps with this minimal of overhead aren't easy to find.

**Comment by lwouis** [comment]
Hi,

I played around with a PoC today, to see how much work would be required. Here are some observations:

* I just removed all Permission Code to test what would happen. It was very easy. The app worked right away
* Accessibility Permission is necessary, otherwise keyboards shortcuts don't work which would make the app unusable. Degraded Mode should only be about not granting Screen Recording permission.
* The new Appearances from v7.0.0 work really well out-of-the-box with this degraded mode. All 3 styles can be used. AppIcons and Titles are particularly nice, since thumbnails are gone.
* Titles of windows were showing. I specifically remember that without the Screen Recording permission, titles were not showing previously. I think macOS may have changed this between Catalina where they introduced this new permission I think, and Sequoia where I'm testing today. In any case, we could release as-is, and see feedback of users on previous macOS versions, and fix things then if we need.
* We would need to condition the screenshot() call by checking the new preference, to avoid wasting time with the call, in case we are in Degraded Mode.

In terms of UX, I think we need 2 things:

* A way to opt into the Degraded Mode. It should be a bit hidden like those "text with no background and outline" buttons where you don't even notice the option is there at first (e.g. on a website, to unsubscribe). Once it's chosen, it's a preference, so it remains chosen on further launches. Some sketch of how the UI could be:  
  ![image](https://github.com/user-attachments/assets/88439095-cd2c-4f0f-8996-557b91c33e26)

* A way to opt out. It should be easy to find. There should also be a permanent reminder that the app is running in degraded mode, so a user who opted in by mistake/impatience is not stuck there. I think some banner in the menubar menu would be nice:    
  ![image](https://github.com/user-attachments/assets/f280f51a-b6b5-4a14-8812-8d9d6f2d1785)

@Allsochen there are 60 upvotes on the OP. Maybe this feature could be a win. It doesn't seem like lots of work, and would be useful to many people who can't use AltTab at work because of strict company policies.

Thank you 🙇

**Comment by ADTC** [comment]
Nice work! Make that 61 🙂 

PS: It's `Grant permission` btw.

**Comment by lwouis** [comment]
Hi everyone,

Here's a [local build with this feature implemented](https://github.com/user-attachments/files/17422543/AltTab.zip).

Could you please try it out and share your feedback here?

Thank you 🙇

**Comment by FalconFour** [comment]
Thanks for working on this! As a small makeup for being a snarky jerk, I'm also throwing in my support on Patreon (and with the rest of my ever-growing Patreon subs, that means it's for the long term, ha). ❤️ 

I gave that build a try (M1 MacBook Pro running Sonoma 14.6.1), and unfortunately I don't have good results. I use Cmd+Tab habitually, and when I configure that shortcut, it merely disables the OS switcher - giving nothing of its own to take its place. I also tried "reset preferences and restart", and then tried the default Option+Tab - still nothing, no switcher, and no action. I quit AltTab and the system switcher returns under Cmd+Tab.

Really appreciate the effort, and I hope it's a quick fix! If there's any place I can grab logs to post, let me know.

**Comment by lwouis** [comment]
Thank you @FalconFour. A video of the issue, showing the menubar at the top, would help to understand what's happening 👍

**Comment by FalconFour** [comment]
You got it: https://youtu.be/jzn8rS5ORlg
It's hard to demonstrate "not doing anything at all" though 😅 so I explain in text doc.

**Comment by lwouis** [comment]
> Hi everyone,
> 
> Here's a [local build with this feature implemented](https://github.com/user-attachments/files/17422543/AltTab.zip).
> 
> Could you please try it out and share your feedback here? If there are no bugs, it will be in the next release.
> 
> Thank you 🙇

Could more people from this thread please help testing this? Without your help, the release will continue to be delayed.

Thank you

**Comment by justinnoel** [comment]
Downloaded and testing now.

**Comment by spirosag** [comment]
> > Hi everyone,
> > Here's a [local build with this feature implemented](https://github.com/user-attachments/files/17422543/AltTab.zip).
> > Could you please try it out and share your feedback here? If there are no bugs, it will be in the next release.
> > Thank you 🙇
> 
> Could more people from this thread please help testing this? Without your help, the release will continue to be delayed.
> 
> Thank you

I’m getting the “can’t be opened because Apple can’t check it for malicious software” error pop up when I try to run it.

**Comment by ADTC** [comment]
> I’m getting the “can’t be opened because Apple can’t check it for malicious software” error pop up when I try to run it.

It's probably a dev build that's not recognized by Apple. To bypass the protection, you have to right-click the file (or Control-click for the purists) to get the context menu, then choose Open. (Or you can try File > Open in the menu bar.)

You will get a different version of the error with a button to run the app anyway.

**Comment by maxchang3** [comment]
> Hi everyone,
> 
> Here's a [local build with this feature implemented](https://github.com/user-attachments/files/17422543/AltTab.zip).
> 
> Could you please try it out and share your feedback here? If there are no bugs, it will be in the next release.
> 
> Thank you 🙇

It works perfectly for me on macOS version 15.0.1.

**Comment by mracos** [comment]
Been using the past couple days and working perfectly for me 💙 


| version alt tab| version mac | example | deny | message |
|--|--|--|--|--|
| ![Screenshot 2024-10-28 at 14 52 55](https://github.com/user-attachments/assets/e53e9c65-7e09-4433-bcca-01e5c015c21e) | ![Screenshot 2024-10-28 at 14 15 08](https://github.com/user-attachments/assets/961faeb2-5a90-4bbf-a811-ee9cd12e37d2) | ![Screenshot 2024-10-28 at 14 54 58](https://github.com/user-attachments/assets/c281068e-0c04-4676-8e2d-6b2b4b770488) | ![Screenshot 2024-10-28 at 14 54 16](https://github.com/user-attachments/assets/1a1621aa-26ff-4787-a5ac-357bdf524aa8) | ![Screenshot 2024-10-28 at 14 53 57](https://github.com/user-attachments/assets/651b035a-b1bb-4342-b249-779d634011cf) |

**Comment by justinnoel** [comment]
Working fine for me too.  Maybe add an option to hide the menu item banner about running without screenrecording?

**Comment by mnj** [comment]
Thank you for implementing this limited functionality mode, I will happily miss out on the thumbnails, to not have the screen recording icon flashing, I keep thinking ms teams somehow is in a meeting, so super confusing for it to light up all the time.
