### ISSUE TITLE
Show on: "Active screen" isn't working.

### ISSUE THREAD

**Issue by Andrew-Helmer** [lwouis/alt-tab-macos#1129]
**Describe the bug**

Show on: "Active screen" doesn't seem to be recognizing when my active screen changes. It always shows on the same screen, regardless of which screen I am working on.

**Screenshots / video**

I can't record both displays so it's hard to show. But in this video, I first show AltTab working on the current Active Screen, say Monitor #1. Then I move AltTab to my other monitor, Monitor #2, which should change the Active Screen, but when I use it, it shows up on the same screen. Then I select a different window on Monitor #2, start typing into the window on Monitor #2 (just to make sure the keyboard is active), then activate AltTab, and it still shows up on Monitor #1.

**Steps to reproduce the bug**

In AltTab version 6.24.0, macOS Big Sur 11.5.2, with two monitors connected to the Mac (not mirrored). I also have "Displays have separate Spaces" unchecked in the Mission Control System Preferences. Not sure if that's important.

1. In AltTab preferences > Appearance, set "Show on:" to "Active screen". 
2. Initiate Shortcut 1 (for me this is with Cmd + Tab, by default it would be Alt + Tab), to see which screen AltTab shows up on. 
3. Open a window on the _other_ screen, select that window and type something to make sure it's activate. 
4. Initiate Shortcut 1 again. 

For me, AltTab still shows up on the first screen, even though that is no longer the active screen. I would expect it to show up on the other screen.

https://user-images.githubusercontent.com/43101294/132927017-5aef4387-a66b-496b-9946-83fd9c206248.mp4

**Comment by lwouis** [comment]
I was able to reproduce the bug. I think it only happens because `Displays have separate Spaces` is unchecked. When unchecked, multiple screens become one extended "screen".

Look at the very straightforward source code:

![image](https://user-images.githubusercontent.com/106195/133870261-dddecbdb-04ae-4dfb-9cb5-1f4c70cb5653.png)

We are calling `NSScreen.main`, which documentation from Apple says:

> Returns the screen object containing the window with the keyboard focus.

I found this [StackOverflow explaining the history, and why the API is incorrect now](https://stackoverflow.com/questions/56268640/nsscreen-mainscreen-misleading-documentation).

**Comment by lwouis** [comment]
I re-implemented finding the key-window manually instead of using Apple's bogus `NSScreen.main` API. I tested on the 2 use-cases that were an issue, and it works correctly for me now, regardless of the `Displays have separate Spaces` checkbox. As a reminder, the 2 use-cases are:

* if the active screen shows a fullscreen app, it always returns screens[0]
* if NSScreen.screensHaveSeparateSpaces == false, and key window is on another screen than screens[0], it still returns screens[0]

The workaround will ship in the next release of AltTab 👍

**Comment by Andrew-Helmer** [comment]
This is great, thank you so much!!
