### ISSUE TITLE
Add option to be able to include the desktop in the switch list

### ISSUE THREAD

**Issue by Mehechiger** [lwouis/alt-tab-macos#1134]
**Is your feature suggestion related to a problem? Please describe.**
Not exactly. It is juste a comparison with HyperSwitch — if you trigger HyperSwitch and there are no windows, it would focus the desktop.

**Describe the solution you'd like**
I would like to have an option to be able to control whether I want the desktop to be included in the window list.

**Comment by lwouis** [comment]
> if you trigger HyperSwitch and there are no windows, it would focus the desktop.

I launched HyperSwitch to understand how the UI is presented for this feature you mention. It looks like this to me:

https://user-images.githubusercontent.com/106195/133869386-f5ea7d1c-120a-4aa2-82c5-cbd5c6c33996.mov

It doesn't look clear what it is, and what it's supposed to do. I'm a bit confused on what you would want AltTab to add.

Could you please explain in great details what you would like to see added to AltTab? You current description is really not enough to understand what you have in mind, currently.

**Comment by Mehechiger** [comment]
Sorry I wasn't very clear. The feature I would like to have is not exactly what HyperSwitch does, but is further inspired by it.

Suppose you had some windows open, and you closed then one by one until every single one is closed.
The focus will stay on the application (eg. Messages.app) whose window was the last to be closed — it won't automatically switch to the desktop.
If you trigger HyperSwitch now, there will be a small semi-transparent square (the empty HyperSwitch window selection panel) appearing in the middle of your screen.
Then your desktop is focused.

By "the desktop is focused", I mean, if you have something on your desktop (hard drives, files, etc.), you can now select them with your keyboard (intitial letter, arrow keys, etc.).

With AltTab, if you trigger it in the same condition (no windows of any application open, but Messages.app is focused),
nothing will happen, Messages.app will stay focused.

What I would like AltTab to do, is to have such an option:
- If disabled, behaves exactly as it does currently.
- If enabled, the desktop will also be included as a window and shown in the window selection panel.
   Thus, whether currently you have any window open, if you trigger AltTab, the desktop is always ready to be selected.

**Comment by lwouis** [comment]
There are multiple desktops potentially, not just one. You can have 1 desktop per monitor for instance. So when you close the last Finder window, which one gets the keyboard focus? I would need to test. So would AltTab shows all the desktops in its list?

Another thing I'm thinking about is that this ticket could be covered by #999. Today we show open apps with no window in AltTab by default. You can hide those, but AltTab can show them if you want with this preference:

![image](https://user-images.githubusercontent.com/106195/133889865-86ef396b-496b-4a44-860e-08869e6e1308.png)

In your scenario:

> With AltTab, if you trigger it in the same condition (no windows of any application open, but Messages.app is focused), nothing will happen, Messages.app will stay focused.

with #999, AltTab would show you Finder app, and releasing AltTab would focus the Finder app (instead of opening a new window, as it does today).

It sounds to me like it's probably satisfying your needs. Unless you want to be able to select specifically which desktop to focus. Because giving Finder the focus when you have multiple desktops on multiple displays, again I'm not sure which one gets the focus: the main display desktop? the desktop on the Space on which you closed the last window? Not sure.

Please let me know if #999 would cover your needs or not 👍

**Comment by Mehechiger** [comment]
Personnaly I almost always use only one monitor but I think it would be nice to be able to select which desktop to focus.

As for #999 I think the difference from what I am requesting is that I would not want apps with no window other than Finder.app (hince the desktop) to be shown (or it would be much too crowded to shown this many windows — for me)
— a possible quick fix of this could be to set a whitelist for this option (show apps with no windows)

I don't know what would be easier to implement, but either
1) #999 + whitelist for apps with no windows
or defintely
2) include all desktops
can cover my needs ;)

**Comment by Mehechiger** [comment]
Another argument supporting 2. including all desktops might be:
sometimes even when there are windows open, I might still need to focus on the desktop to do some selections — although this is not crucial and can be easily satisfied by switching to an empty Space (with no window in it) where the focus would be automatically given to the desktop (tested).

**Comment by lwouis** [comment]
I'm wondering if it's even possible to force the focus on a specific desktop. There is no API for that as far as I know

**Comment by Mehechiger** [comment]
I don't know much about Swift (if it is) but it seems that with Hammerspoon you can play with different screens. However, I'm not sure if you would want to glue them together...

**Comment by Mehechiger** [comment]
I don't know much about macOs programming but it certainly is a problem. Do you have an idea how HyperSwitch works? — though it can't really toy with multiple desktops focuses — by doing exactly like #999 ?

**Comment by lwouis** [comment]
I think HyperSwitch activates Finder, which gives focus to one of the desktop

**Comment by lwouis** [comment]
Closing this as it seems a bit too niche, and hasn't seen activity in a year.
