### ISSUE TITLE
Alt-tab to preferences window moves it to the front but does not focus it

### ISSUE THREAD

**Issue by lilyball** [lwouis/alt-tab-macos#1151]
**Describe the bug**

If I use alt-tab to select the preferences window (or Feedback window), the window is moved to the front but does not have focus. At this point it appears that no window in any app has focus (e.g. pressing ⌘W just beeps at me). Oddly, clicking the window at this point does not give it focus either. I have to click to another app and back.

If I have both Preferences and Feedback open, even clicking between them doesn't give focus (it just moves the window to the front). Interestingly, even when one of the ~~apps~~ (EDIT: windows) have focus, using Alt-tab to focus on the other doesn't visibly give it focus though it does become the first responder for events, and waiting a few seconds (and possibly touching the trackpad, this is somewhat inconsistent) will make the focus visually switch (though the text field in Send Feedback doesn't start flashing its insertion point until I interact with it).

Note that this is _not_ an issue with apps that hide their dock icon in general. In particular, I can't reproduce this using Dash or Yoink.

This was reproduced on macOS 11.6 (20G165). Alt-tab preferences are mostly vanilla (just tweaked the minimized/hidden windows settings).

**Screenshots / video**

Screen recording showing this. When the Alt-tab preferences window moves in front of the Finder window, this was me pressing the alt-tab shortcut.

https://user-images.githubusercontent.com/714/134229452-462f247c-49bd-41dc-9930-2c5562d71b3b.mov

**Steps to reproduce the bug**

1. Open the Alt-tab preferences window (or Send Feedback window)
2. Move focus to a window from any other app (either clicking, cmd-tabbing, or alt-tabbing)
3. Press your Alt-tab shortcut to move focus back to the Alt-tab preferences window
4. See preferences window move to the front without taking focus.

**Comment by lwouis** [comment]
> it does become the first responder

Are you familiar with macOS development by any chance? Some expertise would help a lot here.

AltTab has very complex interactions in that area. It has to come up on the screen, but not steal focus from where it currently was. So it should be focused but-not-really. On top of that, it should still get local shortcut events. So it should be displayed visually on top, but not steal keyboard focus from where it currently is, but it should kind of have keyboard focus though to receive the events. This is for AltTab main window. It's preferences/feedback windows are normal windows, so should get focus normally.

This was to give you an idea of what the constraints are. Now the code behind all this is quite complex because Apple's APIs are being stretched to their limits to implement what I described above.

If you know how to fix this, please give a PR a try!

Another question: I knew this issue could happen with AltTab's own windows, but you mention it can happen with other apps. That I've never seen. Could you please share a video of that scenario?

Thank you!

**Comment by notconfusing** [comment]
I notice a similiar behaviour. I will alt-tab to a different window, but occassionally it does not focus the window that is show in the alt-tab modal overlay. In the menu-bar the the previous app-name will still appear (as if no switch has happened). If I try repeatedly to make the switch, about 3x, eventually the normal app-switching behaviour will occur. I have not been able to find any more clues than that. 

I am also running magnet which manipulates windows too, so that is a possibility.

**Comment by lilyball** [comment]
> Another question: I knew this issue could happen with AltTab's own windows, but you mention it can happen with other apps. That I've never seen. Could you please share a video of that scenario?

Do you mean this bit?

> Interestingly, even when one of the apps have focus, using Alt-tab to focus on the other doesn't visibly give it focus though it does become the first responder for events

It's been a few months so I don't remember the details anymore, but I'm pretty sure I meant to write "windows" here instead of "apps".

**Comment by lwouis** [comment]
This should be fixed with https://github.com/lwouis/alt-tab-macos/issues/759. I'm closing it. Please let me know if it's not fixed 👍

**Comment by shehuawwal** [comment]
Hi @Iwouis;

I am currently encountering this issue, The Windows Focus doesnt work. I am currently running Altab Version 6.68.0 and I am running MacOS Sonoma.

Please can you investigate and issue a fix; Thanks
