### ISSUE TITLE
Show apps/windows in app dimension

### ISSUE THREAD

**Issue by chinleo** [lwouis/alt-tab-macos#1178]
**Describe the solution you'd like**
### now 
Like the picture, same app shows multi icons, because AltTab shows the window as icon, not the app

![image](https://user-images.githubusercontent.com/10843041/137883262-f5c569c0-26a6-438a-9d4a-f19c146f6664.png)

### the feature I want
AltTab add a switcher  in the setting tab of control, both of shotcut 1 & shotcht 2:  

☉ shows app as icon 
○ shows app window as icon

thx.

Lastest, my settings
![image](https://user-images.githubusercontent.com/10843041/137884815-d5ca25b2-13fc-4138-8972-582260e80838.png)

**Comment by lwouis** [comment]
Hi @chinleo

The result you want to achieve is already possible by tweaking the preferences. You even showed your preferences which should produce the result you are after.

It's already possible to accomplish what you want, so what are you looking for me to add here? A more convenient button that does it in one click? Such a button would be tricky because if it's checked, it should disable related appearance preferences for instance.
