### ISSUE TITLE
When switching to an app, its other windows occasionally also rise to the top

### ISSUE THREAD

**Issue by jasonhan-vassar** [lwouis/alt-tab-macos#1197]
**Describe the bug**

Occasionally, switching to an application's window will also bring the app's other windows to the top of the switcher stack, right behind the switched-to window. I'm honestly not sure when or how this happens, but all I know is that this was one of the main problems that made me switch off of HyperSwitch, another macOS app switcher, to AltTab, and that AltTab wasn't always like this. I'll bet this is an underlying Apple API issue.

**Diagram**

Let the list of application windows be a stack, with the head of the stack being the topmost window. There are three apps, with prefixes showing the respective app's window numbers. We have the starting state, shown below:

App_A<sub>0</sub> → App_B<sub>0</sub> → App_A<sub>1</sub> → App_C<sub>0</sub> → App_A<sub>2</sub>

We trigger a switch (between the topmost and second-topmost windows), and we get the following:

App_B<sub>0</sub> → App_A<sub>0</sub> → App_A<sub>1</sub> → App_C<sub>0</sub> → App_A<sub>2</sub>

This is working as intended. However, once we switch back, we get this:

App_A<sub>0</sub> → App_A<sub>1</sub> → App_A<sub>2</sub> → App_B<sub>0</sub> → App_C<sub>0</sub>

Every App_A window rises to the top while the other windows stay in order.

**Steps to reproduce the bug**

The most frustrating part? I'm not even sure how to reproduce this.

**System Info**
macOS 11.1
AltTab 6.26.0

**Comment by lwouis** [comment]
Without steps to reproduce, or a video showing the issue in motion, I'm not sure any progress can be made, unfortunately.

**Comment by jasonhan-vassar** [comment]
@lwouis You're right, it could be that this started happening after I updated to 11.

As for reproducing this, does this not happen to anyone else in daily use? It's not that rare and very jarring to switch to the wrong window once in a while. I'm going to try and screen record a heavy browsing session and see if I can eventually catch it.

**Comment by jasonhan-vassar** [comment]
@lwouis Wow, I found out the culprit. Turns out HyperSwitch was also on in the background somehow! This whole time I've been using both simultaneously. I'm so sorry for the trouble.

**Comment by lwouis** [comment]
I'm glad it wasn't a bug in AltTab in the end.

> uses less CPU

This is an arguable statement. What are you even comparing here? Minimum CPU, maximum CPU, average CPU? Are you measuring, or estimating with gut feelings? I would be curious to compare CPU usage over time between the 2 apps.

In addition, it's possible the issue on macOS makes AltTab consume more CPU when opening a popup specifically  because the OS makes it loop for a few seconds.

Also note that it's unfair to compare both apps since they don't even do the same things. AltTab has more sophisticated mechanisms to make sure to not miss on windows, and apps that are poorly programmed. This means that it will sometimes retry on a tight loop every few milliseconds to get info on a window, if an app is not responding, whereas Hyperswitch may just give up and show incorrect info, or not show a window for instance.

**Comment by jasonhan-vassar** [comment]
@lwouis It was more of a quick "benchmark" using Activity Monitor eyeballing CPU usage while switching around randomly — AltTab's was significantly higher. You're right to call my comment unfair, since after I wrote that I did some more comparison and found that HyperSwitch's window previews are lower quality and don't get updated nearly as often, meaning they are as good as no preview at all. Disabling window previews in AltTab significantly increases the speed and lowers CPU usage to a comparable level.

However, the pop-up slowdown is absolutely real though as stated those other GitHub issues.

In my usage of both, I actually don't recall a time where AltTab covered a window HyperSwitch missed, but I trust it's much more solid in that regard seeing how HyperSwitch suffers from the window order bug. However, I do have a reproducible instance of *both* apps missing a specific app window if you're interested in me reporting it. I haven't reported it because I noticed Mission Control also misses it, but a quick Swift script I wrote that basically just uses `CGWindowListCopyWindowInfo` catches it.

**Comment by lwouis** [comment]
> However, I do have a reproducible instance of both apps missing a specific app window if you're interested in me reporting it. I haven't reported it because I noticed Mission Control also misses it, but a quick Swift script I wrote that basically just uses CGWindowListCopyWindowInfo catches it.

What a window is is not straightforward on macOS. If Mission Control misses it then it's probably correct for HS and AT to ignore it as well. `CGWindowListCopyWindowInfo` is not the right API. It's the one I started with around 2 years ago on this project. Then I discovered many things, and moved to other APIs and many private API tricks. I've decompiled HS a little bit, and I believe they use the same advanced techniques / dark arts.

macOS is quite a mess in that regards. Apple introduced Spaces, but there is no public API to deal with it, so we are left to dark arts and retro-engineering.

**Comment by jasonhan-vassar** [comment]
@lwouis Thanks for the info! As you can probably tell, I'm quite new to Swift/macOS APIs myself. I respect how much work you and other devs put into this kind of stuff.

**Comment by mistermantas** [comment]
the #718  issue seems to be related to #1197 for me - or I'm experiencing both separately - because when I alt tab from say Word to Safari, a part of Word stays on screen on top. I'm not using Hyperswitch. It's like a very specific cut of the screenshot. Wish I could screen record but I'm always doing schoolwork when this happens (and it's pretty unpredictable). Both things only happen while using ATM
