### ISSUE TITLE
Switcher sometimes starts on the first window instead of the second

### ISSUE THREAD

**Issue by jasonhan-vassar** [lwouis/alt-tab-macos#1198]
**Describe the bug**

Sometimes, the app switcher will start on the first window instead of the second.

**Screenshots / video**

https://user-images.githubusercontent.com/34594853/139494503-805c87f9-36d4-4df5-84f7-2d421bcc51c4.mp4

**Steps to reproduce the bug**

I'm not too sure how to reproduce — I believe it's related to window pop-ups since the bug above was recorded right after a Wi-Fi pop-up appeared. I've tried a few times unsuccessfully to reproduce.

**System Info**
macOS 11.1
AltTab 6.26.0

**Comment by lwouis** [comment]
It may be related to the other ticket about popups breaking on macOS 11: #718

**Comment by khour** [comment]
I don't think it's related to popups. Can happen without them w/ default apps, see attached screencast.
It won't switch the window until I hit alt tab twice (first to bring the switcher, second to actually switch the window). After that, first alt tab invoke start to properly switch windows.
It's interesting that it doesn't happen with every app. Like in my example, if I replace activity monitor with sublime text, alt tab works properly from the get go and doesn't skip the first switch.

https://user-images.githubusercontent.com/763911/146891804-800b8bf0-f0c7-4273-a072-517de826211f.mov

**Comment by lwouis** [comment]
I was able to reproduce the issue by simply launching AltTab. On a fresh start, with existing windows, I notice that the selected thumbnail is the leftmost, when AltTab UI shows. It should be the second to the left, not the first.

It's probably a bug in the code that handle the edge-case where there is no focused window (when you click the desktop for example).

I'll look into it

**Comment by lwouis** [comment]
Ah, yes indeed it's exactly what I mentioned above.

When AltTab is opened, it asks the OS for the active app, and checks if it has an open window. If it does, then we select the second thumbnail. If it doesn't, we select the first thumbnail.

As I said, this is useful for cases like clicking the finder. In that case, you want that behavior.

The bug comes from the fact that when AltTab is brought up and asks the OS for which app is the active app, the OS will sometimes return... AltTab itself.

I need to find a new approach to detect the active app *before* AltTab is brought up

**Comment by khour** [comment]
Some updates on what I found out while using AltTab.

It's indeed a specific set of applications, which when launched, make AltTab stuck on its first entry.
Apps affected that I found: disk utility, activity monitor, system preferences, mail.
Order matters, as the issue is only present when the problematic app is launched last. For instance: launch mail, then calendar -> AltTab properly switches to the second window (i.e. to mail) from the start. But launch calendar, then mail -> AltTab is stuck on the first window (mail), and requires hitting tab again to get to calendar. After that it works properly.
All of that makes me think that there's something fishy about certain apps and their windows. As far as I see so far, it's only standard apps that are affected, but maybe I've just yet to encounter a 3rd party with the same behavior.

Sorry for the info dump. I'm getting familiar with the AltTab code for now, and kinda using this ticket a logbook in case you won't have time to handle it so that I can eventually get to it and fix it, as it's bugging me a lot.

**Comment by Willem-SN** [comment]
This happens all the time for me. Most apps will focus on itself the first time pressing alt-tab. But when going out of the window, and getting back into it, it will work properly. I've tried a lot of different settings configurations just it case, but the issue always persists.

Apps that has the bug: calculator, forklift, transmit, safari, vlc, iterm, system preferences (so most applications)
Apps that always work properly the first time: sourcetree, vscode, discord (first splash window works as well) -> can't find any others

**Comment by altfoxie** [comment]
> Apps that has the bug: calculator, forklift, transmit, safari, vlc, iterm, system preferences (so most applications)

Same happens to me

**Comment by altfoxie** [comment]
@lwouis any updates on this? This bug is very annoying

**Comment by lwouis** [comment]
@altfoxie it seems i found the root cause: https://github.com/lwouis/alt-tab-macos/issues/1198#issuecomment-998689752

so it's about working on it now. Anyone is welcome to share a PR. Me, i have very little time for this project, unfortunately (see pinned issue).

**Comment by lwouis** [comment]
I was wrong in my assessment above. When I launch AltTab on my machine, it keeps focus on the app that had focus previously, but it removes focus on the window that had it.

This is why AltTab selects the first thumbnail instead of the second there.

Now, I managed to reproduce the issue from the video from @[khour](https://github.com/khour) above. I also managed to debug and understand. Here is the root cause:

Some apps, like Activity Monitor, don't trigger a `AXApplicationActivated` after they are launched, even though they are active/activated. I don't know why this is. Maybe it's linked to this `Keep CPU windows on top`?

![image](https://user-images.githubusercontent.com/106195/167247186-5e2e51b8-1b8b-4e79-bb8a-abd9b4c1c2be.png)

In any case, this trips AltTab because during `AXApplicationActivated`, is when we check if there is a focused window for an app.

As a workaround, I added code to check for the focused window during window creation, which should ensure we don't miss the info, and the issue from this ticket is fixed.

I'll release a fix soon

**Comment by GrayedFox** [comment]
I believe this bug may have re-surfaced on `15.6.1` Mac OS Sequoia. The apps I have open are VSCode, Slack, and Chrome (with the Slack app on the hide list so it doesn't appear when using the alt-tab shortcut).

This is now consistent for me so I always need to thit `tab` twice to switch to the most recent window that is not my active window.

Edit: in my case, the bug seems to be because despite having the preference set as 'Order by most recent application' the order of the apps inside the switcher pop-up never changes.

**Comment by GrayedFox** [comment]
@lwouis add a tag here as I forgot to in the last message :)

**Comment by lwouis** [comment]
@GrayedFox there was a regression in v7.28. It was fixed in further releases. Are you on v7.30?
Thank you

**Comment by GrayedFox** [comment]
I was on v7.28! Manual check for updates and upgrading to v7.30 resolved this, thanks, been a thorn in my side since the last update 😉

**Comment by lalitkapoor** [comment]
I'm continuing to experience this with the recent releases including the latest `10.12.0`. The Arc Browser, even though it is the current window will sometimes show up first in the list when I alt-tab. I sometimes experience this with Ghostty too. It really breaks my flow when this happens.

**Comment by janosmiko** [comment]
@lwouis I also face this issue with Arc and Slack, and it happens quiet often.
