### ISSUE TITLE
main window show delay and disappear delay

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [lwouis/alt-tab-macos#1215]
**Describe the bug**

I have noticed https://github.com/lwouis/alt-tab-macos/issues/1096, same problem, It's fixed in 6.24, but my version is 6.26. 
MacOS 10.15.7.

**Screenshots / video**
![1636458803804](https://user-images.githubusercontent.com/2133400/140920262-7d158b5d-52bd-4bde-8dd6-00fb4b8fd57e.jpg)
this shows switch from Intellij to safari. It happens frequently so I can take a picture very easily.

My origin main window look like this:
![image](https://user-images.githubusercontent.com/2133400/140920858-d50cb078-f04d-4c7b-9058-f42b0615e897.png)

**Steps to reproduce the bug**

**Comment by lwouis** [comment]
This issue is part of https://github.com/lwouis/alt-tab-macos/issues/563. Could you please [try out the build here](https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-963304271) and share (in the other ticket) if that fixed it for you.

I'll close this ticket as duplicate to keep the discussion in one place (the other ticket).
