### ISSUE TITLE
Some icons are randomly smaller than others

### ISSUE THREAD

**Issue by simoheinonen** [lwouis/alt-tab-macos#1248]
**Describe the bug**

Some icons are smaller than others when doing cmd+tab. Happens pretty consistently but not all the time so not sure if this a bug or some kind of feature I don't understand. 

**Screenshots / video**

![PXL_20211123_151138679](https://user-images.githubusercontent.com/3840367/143050710-8f04fd8b-782d-457f-8f74-e7c73bd80a83.jpg)

**Steps to reproduce the bug**

macOS Monterey 12.0
AltTab 6.28.0

![Screenshot 2021-11-23 at 17 12 24](https://user-images.githubusercontent.com/3840367/143051066-34f043ed-28d4-4877-9513-f70cc71c10f9.png)
![Screenshot 2021-11-23 at 17 15 36](https://user-images.githubusercontent.com/3840367/143051081-3f636a45-849f-43ca-aea5-531bb8224f4e.png)

**Comment by lwouis** [comment]
I set my preferences to the same values you show on the screenshot, and it works correctly for me.

It seems like a bug in the layout logic. The layout logic is very complex, as you can see from the available options offered to customize. I'm noticing that you have the window titles set to 10px here, though it doesn't show, because you set the min width in row to 0% for instance.

I'm afraid I can't offer much for now. I think I approached with too much open-ness when I made the layout system. I'm hoping it can be remade to focus on the common use cases like yours (big app icons, no thumbnail, no title). Most people (rightfully) don't understand how the various parameters interact.

So short-term, please try to play with the options. Maybe some variation will be more stable / not have the issue. More long-term, proper solution will happen we we rework the appearance preferences, and the layout system.

I'll close this ticket for now as I consider it will be subsumed by tickets such as #351

**Comment by simoheinonen** [comment]
Making "Window min width in row" over 0% fixed it for me!
