### ISSUE TITLE
Make AppCenter integration opt-in

### ISSUE THREAD

**Issue by Rjevski** [lwouis/alt-tab-macos#1265]
**Describe the bug**

The application contacts `in.appcenter.ms` on first run. While I haven't examined the exact data transferred, it's most likely checking in and registering a persistent ID that it'll use for future telemetry/crash reports. This inherently includes the user's IP address and if a persistent ID is indeed used then would allow AppCenter to have a log of the user's IPs. This should be opt-in and having it phone home immediately (without any warning nor disclosure) may be a breach of the GDPR.

**Screenshots / video**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/45625150/144025766-304d3840-9dc2-4c6e-89b4-9e3417366b99.png">

**Steps to reproduce the bug**

1. Monitor network traffic
2. Open alt-tab-macos
3. See spyware phoning home

**Comment by Rjevski** [comment]
I see that there is a setting that's available once the app is configured and accessibility permissions are granted. It does do the right thing and defaults to "ask whether to send crash reports". The AppCenter registration should be delayed until the first crash is encountered and the user explicitly opts-in.

**Comment by lwouis** [comment]
*On the form of your message*

I didn't know that AppCenter was making network calls on setup. I don't know what is being exchanged. As you've seen, I've designed AltTab to be as unintrusive as possible. I don't appreciate you attributing malice on my part. I've made a strong stance with this app to have 0 telemetry, use as little CPU/memory/disk/battery/etc as possible. I've spent days optimizing images so the bundle size is small, using observers instead of polling so the battery usage is as low as possible, dealing with hundreds of poorly written tickets from people who don't know how to fill a bug report, which I could have approached by having telemetry but didn't, etc.

> breach of the GDPR

This is FOSS I do on my weekends. This is not a commercial endeavour. I benefit in no way from this. I've been refusing donations for years. I'm not a lawyer, but my opinion is that there would never be any ground for litigation here. It's like going to your local homeless shelter and criticizing the volunteers for having the "free food" sign show a picture of a burger. "The burger on the sign is not exactly the food served; it's false advertising". The allegation is quite misplaced in that context.

> See spyware phoning home

This way to categorize the appcenter network call is why I'm being offended by your attitude in the ticket. Painting me for a villain when I'm trying so hard to be ethical with this project. In every way I can. I have advanced accreditation for contributors to make the project about everyone for contribute vs just myself for instance. This app is pretty exemplary in my eyes. I'm very much against common industry practices, and trying to take a stance against those on this project. It seems the situation is not perfect, but please don't call it malice at first glance. How about being polite/civil and asking first why there is a call before talking about spyware, telemetry, and breaching GDPR?

*On the contents of your message*

I totally agree that this is undesirable. I wasn't aware that AppCenter was doing it. It's [not documented](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/macos). I use AppCenter because they provide a good library to collect crash report. I looked into all alternatives when I implemented crash reports (for the benefits of users and no other goal), and it was by far the best technical solution. They also host the crash reports on some server for free, and provide a nice UI to review them so that I can actually investigate and fix exotic bugs that would never happen on my setup.

I'll look into a way to disable the network call. However, I've done a quick check and given we just call a function called `AppCenter.start`, it's possible that Microsoft designed the framework with this call being non-optional. It may not be possible to de-couple the first call from initializing AppCenter (which we need to do as early as possible, to catch early crashes; early crashes were the main motivation to have crash reports in the first place).

Lastly, this is FOSS, so of course the best thing you could do would be to open a PR to fix the issue you found. This would benefit everyone, and serve your own desire immediately, without relying on someone else to do it.

**Comment by lwouis** [comment]
> However, I believe I have legitimate reasons for calling AppCenter spyware, both when it comes to this activity (why is it phoning home on first run before asking, especially when your intention was to default it to ask first) and considering Microsoft's pivot to user data mining since Windows 10. Even if the data collected appears benign in isolation (an IP address alone won't give you much), it can be correlated with other data Microsoft has collected (through similar unethical means) which is why I'm not happy despite the data point by itself being pretty much public and meaningless. The fact that the behavior is not documented is even worse.

I was originally thinking why you mention Microsoft, when they are simply the library author, and not a service provider here. However, I realized that you are right and it's *possible* that they abusive the situation. I haven't read the AppCenter T&A and it's possible that they have a clause like "we reserve a right to cross-reference fingerprints from your reports for our own purposes. I underestimated the fact that I use their library _and their SaaS platform_. When the library sends data to AppCenter, it's a blackbox as to what really happens to the data. I guess I also thought it's not too bad since it would happen only after the user accepts to share some info about themselves.

Anyway, I'll review your PR now, and it seems you found a way to do it, so that's just a nice win for everyone 👍
