### ISSUE TITLE
Some windows don't show in AltTab

### ISSUE THREAD

**Issue by Joilence** [lwouis/alt-tab-macos#1317]
**Describe the bug**

Not able to show all windows, only works as show windows of one app.

macOS 12.1, MBA M1 2020, AltTab Version 6.29.0.

**Screenshots / video**

Using Default settings:

<img width="686" alt="CleanShot 2022-01-09 at 18 48 34@2x" src="https://user-images.githubusercontent.com/14588641/148694080-a0a2f07a-1729-4605-8d73-521e24ba3ba8.png">

With Dash in the front, two Safari windows and AltTab in the back, only shows Dash:

![CleanShot 2022-01-09 at 19 04 26-0001](https://user-images.githubusercontent.com/14588641/148694650-6546fa32-64ce-402d-aac1-9c22831fb6c6.png)

With two Safari windows in the front, Dash and AltTab in the back, show two Safari windows:

![CleanShot 2022-01-09 at 19 04 26-0002](https://user-images.githubusercontent.com/14588641/148694719-2292a5aa-fc4a-4ef6-b288-62757cb87f50.png)

**Steps to reproduce the bug**

With the same environment, install app, run, and try the default shortcut.

**Comment by flypenguin** [comment]
i constantly do not see opened apps. if i activate mission control the windows are visible, but no icon in alttab. restarting alttab helps. this is a blocker bug in my eyes - it's the core of what alttab does, and it is *highly* annoying.

**Comment by lwouis** [comment]
@flypenguin there is no public API for this core feature. AltTab uses private APIs and SPIs, and very complex tricks to get the best it can. To my knowledge, AltTab is best in class. Yet it's not 100% reliable.

if you have concrete knowledge on how to improve, please share it.

I've been doing my best efforts for years on this app but at the end of the day i'm fighting the operating system and its internal quirks and bugs.

**Comment by Joilence** [comment]
I do appreciate your efforts and I understand the project is in the transition of looking for a new maintainer.

Only FYI, on my machine, HyperSwitch works well (only the developer stop maintaining it so it constantly pops out the beta expired window).

So there should be some way could fix it. I just wonder if my problem appears also on other people's machines.

**Comment by flypenguin** [comment]
@Joilence true, i checked with witch and contexts - they both seem to suffer the exact same fate. i really love apple, except for that part. that part sucks. alttab has become a core tool of mine, and it seems apple just canceled the whole class.

**Comment by lwouis** [comment]
@Joilence i've contacted HyperSwitch developer multiple times. I tried to find his work contact using his company registration for example. Detective work lol. I did it because i thought i could convince him to open source the app, or maybe sell me the code which i would have open sourced. He's unreachable. I also decompiled and tried to retro engineer his app to find his techniques as well as maybe private APIs he's using and i'm not. I confirmed some suspicions that way.

Overall if something seems to work better on HyperSwitch it's probably a tradeoff. The way HS updates the thumbnails for instance is poor compared to AltTab. They also have some use-cases where focusing windows fail whereas it works on AltTab. Their keyboard shortcuts won't work in Secure Input mode when AltTab does. Etc

If you want to help, i invite you to try to contact the HS author, or disassemble the app to try and get insight as i did. That would be helpful

**Comment by Joilence** [comment]
@lwouis I tried to contact the developer of HyperSwitch as well. Yes, unreachable at least for quite some time indeed.

TBH this is beyond my ability, I may not be able to help in a technical way.

**Comment by ikodev** [comment]
Same problem for me :-)

**Comment by PsyGik** [comment]
One behavior that I've observed (in Contexts as well), is that during/after entering sensitive info, like passwords, credit card etc. the the windows (in my instance Firefox), doesn't show up until I restart either Firefox or AltTab. Really frustrating experience, wish Apple provided a public API instead of good people having to hack through private undocumented APIs

**Comment by d1rewolf** [comment]
I'm having issues as well...mostly it seems that certain applications (Firefox is most noticeable) stop showing up. A restart of the app fixes it. 

@lwouis, just wanted to say thank you for all your hard work on alt-tab. It has to be a completely frustrating experience to try to reverse engineer this crap. For as much as Apple likes to be known as a developer-focused platform, they seem overtly developer-hostile. If they didn't make such wonderful hardware, I'd switch back to linux in a heartbeat ;-)

**Comment by codewise-nicolas** [comment]
The app is the best thing Ive found in a long time.

What about a "Restart App" in the tray icon options list. I know its annoying to have to restart the app to have it re-find the windows, but at least the restart app item would make it much easier/quicker when you know its happening instead of having to exit it, go find it in Applications and re-open it.

**Comment by lwouis** [comment]
@codewise-nicolas this has been suggested before, as a mitigation as you say. It's really not satisfying though because it loses window focus order. When AltTab starts, it has no idea of the order the windows were focused last. We use their z-index (order in which they are stacked on top of each order) as a proxy, but it's often not correct.

I feel a bit like giving up if we add a button. Like an app shouldn't provide an option to restart because it needs to be restarted daily of something, no? That feels wrong.

**Comment by flypenguin** [comment]
hm, honestly? if that restart-button would be actually _in_ the tab switcher, so that i could press CMD-TAB, it opens, and move the mouse to restart immediately, it would definitely suck, but it would be DOABLE. now this is a hassle which is why i am using the standard mac os tab switcher with horrible muscle memory issues. i would like a really really smooth "restart way" a lot.

**Comment by lwouis** [comment]
What I struggle to explain even when the window is missed by AltTab, there is a catch-up mechanism: if the user focuses the missing window, AltTab will add the window to its list, if the window is an actual window, and was missing.

So the fact that you guys can't focus it to list it, seems to indicate that these windows don't pass the `isActualWindow` test.

**Comment by Riezebos** [comment]
I think this has been the case a few times, but I'm not 100% sure. Next time this happens I'll be sure to thoroughly test whether focusing solves it!

**Comment by ipeluffo** [comment]
In case it helps, below there is a recording showing an issue when changing a browser (in this case Brave) to full screen:
https://streamable.com/11xefj

**Issue**: Brave browser disappear from alt-tab when changing to full screen. After restoring from full screen, the app still doesn't appear in alt-tab.

I checked and the options to full apps in fullscreen is active:
![Screenshot 2022-05-15 at 17 38 29](https://user-images.githubusercontent.com/889705/168483801-d42515c2-d622-401e-8184-99711e8fb999.png)

**Steps to reproduce the bug**
1. Open browser
2. Change to full screen (app disappears from alt-tab)
3. Change back to normal screen (app still doesn't appear in alt-tab)
4. Reopening alt-tab fixes the issue

**Comment by lwouis** [comment]
@[ipeluffo](https://github.com/ipeluffo) I downloaded Brave, and reproduced your steps. It worked fine for me.

I'm suspecting you're on macOS 12.3+ and are facing #1324

**Comment by ipeluffo** [comment]
> @[ipeluffo](https://github.com/ipeluffo) I downloaded Brave, and reproduced your steps. It worked fine for me.
> 
> I'm suspecting you're on macOS 12.3+ and are facing #1324

I can confirm I'm running macOS 12.3+. Sorry I've posted this issue here, I didn't see the other one. Feel free to delete or hide the comments. Thanks for the great work on this.

**Comment by lwouis** [comment]
I've dug into this again today, and come to the conclusion that it falls under the umbrella of #447. Indeed, the issue here is the following:

* We rely on subscribing to an app's notifications to know when it creates a new window
* When an app launches, its initial windows tend to not send such notifications. It could be a macOS bug, or it could be that technically by the windows are created right before we have a chance to subscribe to the app's notifications
* Such initial windows can be on other Spaces than the current Space
 
This happens for instance when an app is opened, and some of its windows are restored. If they were fullscreen, they will be restored on other Spaces. Sometimes macOS will then automatically focus on another Space to show the newly open window, but there is an animation to get there which could mean we don't ask for windows during it, and we don't get the window.

More importantly, sometimes macOS will not focus such initial window. For example, if the restored app had multiple windows fullscreen. Then it may focus on of those Space, but not both.

Because we get no notification, and we don't travel to all relevant Spaces, we miss those windows. Let's thus focus the discussion in #447.
