### ISSUE TITLE
AltTab does not close when I select Quit or Force Quit from Activity Monitor

### ISSUE THREAD

**Issue by imfromthenet** [lwouis/alt-tab-macos#1367]
**Describe the bug**
I have been having the unwanted behaviour of AltTab not showing some of open programs. To try to remedy this, I wanted to restart AltTab. To do that I started `Activity Monitor`, found AltTab. Selected it, pressed on `X` button and then selected `Quit`. nothing happened. then I tried `Force Quit`. The result was the same. 

I would expect that AltTab would be easy to quit.

**Screenshots / video**

https://user-images.githubusercontent.com/2662996/152783019-a0f47f58-7e32-4fa8-80c7-5365c811ca1f.mov

**Steps to reproduce the bug**

1. Go to 'Activity Monitor'
2. Click on 'AltTab'
3. Click 'X'
4. Select 'Quit'

**Comment by lwouis** [comment]
You can quit AltTab from the app icon in the menubar at the top of the screen. That's the intended way to quit it. Now of course Activity Monitor should work as well.

I tried to launch AltTab, and quit it and force-quit it through Activity Monitor, and both cases worked correctly. So I can't reproduce the issue that you show in the video. I'm not sure what's different about your setup.

Something to note in your video is that AltTab is indeed quit when you ask for it. However, it's immediately re-launched. You can see the PID on the right changing, and the CPU counter being blank for a few seconds.

I'm thinking that it could be due to the following thing:

Back in November 2021, we moved from one way to implement "Start at login", to another implementation (664c5b96284559). The new way relies on Launchd, and has this line here: https://github.com/lwouis/alt-tab-macos/commit/664c5b96284559571e80d4b38d5e9aa489b4c1a8#diff-323d91ad380ecd3f3fc161764535c247cf088a79fc2aba547e6e2f64fb146adaR50

It may be that this line being `true` makes Launchd restart the app after a force-quit? I can't explain why it would do it after a normal Quit though? Also why doesn't it happen on my machine? It could be that I manually quit and start AltTab, from which point it's now manually launched and not supervised/relaunched by Launchd if it terminates.

This [doc here](https://github.com/tjluoma/launchd-keepalive) explain the dangers of KeepAlive. However, we use it with `SuccessfulExit`, as they recommend, so it should be fine, and actually only relaunch AltTab on crashes, which is a behavior what we want for users to have a smooth experience.

**Comment by kylemart** [comment]
I'm experiencing a similar issue to OP. After updating to the macOS Monterey 12.3 beta, I started running into persistent crashes. Immediately after choosing "Don't send" or "Send", it fires back up again and immediately crashes. Tried terminating AltTab with the Activity Monitor and `kill` command, but neither worked.

**Comment by lwouis** [comment]
@kylemart regarding macOS beta please see #1351. Regarding the auto-restarts, please see my comment above

**Comment by lakshyaelite** [comment]
Just open alttab from the spotlight and click "quit" in the upper right corner of the window
