### ISSUE TITLE
Bad interaction with iTerm2's key remapping feature

### ISSUE THREAD

**Issue by gnachman** [lwouis/alt-tab-macos#1415]
I received this bug report:

https://gitlab.com/gnachman/iterm2/-/issues/10220

The user is having a problem in AltTab where my event tap remaps modifier keys. Even after modifying iTerm2 to remap keyUp as well as keyDown, the problem remains - but I don't know what AltTab is seeing that confuses it. Can you help diagnose this issue?

**Comment by lwouis** [comment]
The issue isn't super clear to me. As I understand this is the issue:

> releasing command-tab does not focus the selected window.

In other words, iTerm2 being opened breaks AltTab's release shortcut.

This probably means that AltTab is not receiving the keyboard input. I'm not sure what iTerm2 is doing here with the input, but it seems it's intercepting it, and absorbing it instead of letting it propagate through to other listeners.

I remember that there are multiple macOS APIs to listen to keyboard events. Depending on the one you're using, and the flags you pass, it will either let through or absorb.

Since it seems you're not absorbing on key down, I suggest you try to replicate that code/logic on key up.
