### ISSUE TITLE
Holding down cmd+tab switches waaaay too fast.

### ISSUE THREAD

**Issue by rasben** [lwouis/alt-tab-macos#1473]
Relying on "delay until repeat" / "key-repeat" is pretty frustrating.

I like to have my settings like this, but it causes a big issue with alt-tab.

<img width="434" alt="Screenshot 2022-04-07 at 23 27 55" src="https://user-images.githubusercontent.com/12376583/162320978-fdd4449c-d14c-4754-9933-ad1de213a44e.png">

It's super easy to hold down cmd + tab a second too long, and the switching just goes bananas.

Is there any way we can either:

- Disable auto-scroll on holding down - only triggering a switch on new click of tab?
- Set some kind of delay between switches?

**Comment by lwouis** [comment]
You set repeat to the max, and alt tab respects that and repeats quickly. Then you say it's too quick. Something confuses me here. Why not reduce the repeat speed then?

Maybe you're trying to say that alt-tab is faster than other apps like TextEdit if you hold a key there?

**Comment by rasben** [comment]
I know it's a weird issue :)

I've always had this setting, but back when I used hyperswitch, this was never an issue

**Comment by lwouis** [comment]
Probably because HS does not respect the user's preference there. It's actually a refinement i added at some point to pay attention to that preference and repeat accordingly. It was previously a hardcoded timing.

AltTab uses standard macOS preferences. This means you can customize them per-app. The standard system is pretty well designed. You could set the repeat speed and delay only in AltTab, to a slower speed.

**Comment by rasben** [comment]
Frigging awesome - Thank you!!
