### ISSUE TITLE
Minimised apps in bottom(est) row

### ISSUE THREAD

**Issue by TitanBlast** [lwouis/alt-tab-macos#1518]
Currently when an app is minimised a preview is hidden. Is it honestly, a very great feature, but I am also curious if it is possible to make it so that all minimised apps always "break into a new row". 

Example:
![CleanShot 2022-04-26 at 21 58 19](https://user-images.githubusercontent.com/54638868/165382479-e7c826fe-327f-4488-93bb-f1f095bd6495.jpeg)

That would put all minimised apps into a new row, no matter how many slots are left for "unminised" applications, making it (optionally), more intuitive. 

Let me know if this is already possible and if so how can I do it or if any further explanation is needed I am happy to contribute wherever or however I can. many thanks for building such an amazing product <3!

Best, Matic

**Comment by lwouis** [comment]
Hi Matic,

It's an interesting idea, so thanks for presenting it with a nice visual and explanations. I'm afraid this idea goes into the category of marginal benefits at the cost of more complexity and more preferences. I don't want AltTab to turn into an app with 200 preferences users can set. I'm afraid I have to close this ticket since you're the first one to ask for something like this in years, implying that there is not much of a demand for such feature. In short, it's a nice idea, but too niche and it would bloat the app.

I hope you understand the constraints I have to operate in, and why I can't include everything, however nice it is 🙇
