### ISSUE TITLE
Quitting from Activity Monitor doesn't restore the native command+tab switcher

### ISSUE THREAD

**Issue by furqan-qadri** [lwouis/alt-tab-macos#1622]
I need to take screenshots of the default app switcher for a project but even after quitting alt tab from the activity monitor, the default switcher is not loading. pressing cmd+tab does nothing. Same is the case with option+tab. I tried other keyboard shortcuts as well but none of them is working. how to get the default switcher back?

**Comment by lwouis** [comment]
Hi @furqan-qadri,

I'm sorry you ran into this issue!

At first, I was surprised, because I remember specifically adding code to restore the native app-switcher shortcuts when AltTab quits. However, you mentioned that you used Activity Monitor to quit.

I then spent hours of googling and learning about how macOS handles quit, force-quit, kill, etc, from Activity Monitor, from the Terminal, from a user UI, etc. It turns out that AltTab being a background app, the method I mentioned above where we restore command+tab on quit is not called when AltTab is quit from Activity Monitor.

I added a signal listener to `SIGTERM`, so that AltTab can properly restore the shortcut even when quit through unconventional methods like this. I'll ship a version with this fix soon.

In the meanwhile, you can fix the issue by simply launching AltTab, then quitting it normally, with the dedicated UI:

![image](https://user-images.githubusercontent.com/106195/170481341-d682a1c2-ee44-4811-801b-fd6919fb1384.png)

By the way, why did you use Activity Monitor and not quit AltTab normally here?

**Comment by furqan-qadri** [comment]
@lwouis thanks man for taking the pains. Glad I mentioned that I used the activity monitor to quit, otherwise this could have been frustrating. I don't have the menu bar icon enabled for alt-tab that's the reason I used the activity monitor to quit. 
Btw am currently writing a medium story where I recommend this app and show how much better it is,  compared to the default switcher! (that's why needed the screenshots)! I will post the link of that article here soon.thanks again
