### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by 3767jack** [lwouis/alt-tab-macos#1646]
Hi! Every single time I try to open the app it crashes immediately and then doesn't work. It worked perfectly for 15 minutes and then i think I may have messed up one of the preferences and it's never worked after that.

Any ideas or help would be great. Especially how to clear all preferences without having to actually open the app (since it keeps crashing).

**Comment by 3767jack** [comment]
Updating my Mac to MacOS 12.4 seemed to fix it. I was on 12.3 beta before.

**Comment by lwouis** [comment]
Apps these days have to be moved to the Applications folder, until then macOS will have them in "quarantine" (it's the technical language used actually). That's why i added the system to suggest users to put it in the right folder for them.

So it may be that this was your issue.

Did you send the crash reports? You can also find them in Console.app > Crashes.

Finally, to reset prefs without opening the app, you can run `defaults delete com.lwouis.alt-tab-macos`
