### ISSUE TITLE
Maintain windows order after restarting AltTab

### ISSUE THREAD

**Issue by simonhf** [lwouis/alt-tab-macos#1694]
**Is your feature suggestion related to a problem? Please describe.**

Have been using AltTab for a while and have noticed that there are relatively frequent updates... which is not necessarily a bad thing. But... after each update then AltTab forgets the list of windows and their order from before the update. If you are somebody who keeps a lot of windows open then this is frustrating :-)

**Describe the solution you'd like**

Remember the windows and their order from before the update?

**Describe alternatives you've considered**

"Workarounds" considered are 1. Delaying updates. 2. Searching for an alternative app providing the same functionality.

**Comment by lwouis** [comment]
You can tweak the update policy to your liking in preferences > policies.

Regarding remembering order, the issue is that the OS doesn't provide APIs to do this. While AltTab is restarting, you could click around and change the window focus order, and AltTab would have no way to know when it's finally ready. The best we get from the OS is the windows Z-index. That's what we use today, but it's not actually the focus order.

i'll look into improving again. Maybe we could cache the previous order and use it instead (or in combination with, somehow?) of Z-index for the windows that are still there when AltTab is back up.

**Comment by lwouis** [comment]
I can't think of a way to "remember" the order. Anything AltTab would remember before quitting could be wrong by the time it is launched again. The user can indeed click/interact with windows during AltTab's downtime. It would then be wrong and misleading to show focus-order as it used to be. So I don't see any way to deal with this in particular.

Now looking into this, I found out that at some point there was a regression, and we stopped using Z-index to estimate the focus-order, in the cases where users have only 1 Space. I'm going to fix this, and windows should have a way higher chance to be in a right-ish order at launch, for users who use only 1 Space 👍
