### ISSUE TITLE
Apps with no open windows are shown as "Window is on every Space"

### ISSUE THREAD

**Issue by LostInCompilation** [lwouis/alt-tab-macos#1700]
**Describe the bug**

When a running App has no open windows, AltTab thinks the App's window is on every Space (see screenshot). I would expect AltTab to say something like "No windows on no spaces".
Is this expected behavior or considered a bug?

**Additional info**
AltTab version: 6.43.0
macOS version: 12.4
Device: M1 MacBook Pro 16"

**Screenshots**
<img width="1493" alt="AltTab bug" src="https://user-images.githubusercontent.com/12819635/174412088-fb773287-4bcf-4fab-a666-95ae94e17a99.png">

**Comment by lwouis** [comment]
Thank you for reporting this issue! It's a bit of a complex story, so I'll try to break it down:

* The tooltip is simply wrong. At the very least it should read "App is" not "Window is".
* An app (with or without windows) can actually be assigned to a specific Space. What this does is that opening a new window (for example by clicking on the app Dock icon) will open it on that assigned Space, instead of the current Space.
* You can also assign the app to "All Desktop", which I'm not sure what it does. Maybe it moves the windows around automatically as you change Space? I'll dig deeper

I'll dig deeper and improve this~

**Comment by lwouis** [comment]
I can't find a way to get the "Assign to Space" information for apps. I looked into every API that I know, `NSProcess`, `NSRunningApplication`, private APIs, etc. I don't see a way to get that info.

I'm going to change it so apps don't show their Assigned Space:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/106195/174488468-28e973d3-1885-4f82-a369-76785f48b684.png">
