### ISSUE TITLE
Blacklist table is broken in Dark Mode

### ISSUE THREAD

**Issue by LostInCompilation** [lwouis/alt-tab-macos#1702]
**Describe the bug**

The Blacklist table in the settings window doesn't show properly with dark mode enabled. The background is white and every other item looks to be white text on white background.

**Additional info**
AltTab version: 6.43.0
macOS version: 12.4
Device: M1 MacBook Pro 16"

**Screenshot**
<img width="792" alt="bug" src="https://user-images.githubusercontent.com/12819635/174439641-9d53caba-18be-463b-8135-52007fcec504.png">

**Comment by lwouis** [comment]
Thank you for opening this issue! I could reproduce it indeed. It's surprising to see this issue since I used the [standard system property](https://developer.apple.com/documentation/appkit/nstableview/1533967-usesalternatingrowbackgroundcolo) for having zebra row colors. I would expect the OS would handle Dark Mode on its own then.

It should be easy to fix. I'll work on a fix soon~
