### ISSUE TITLE
How to show only 1 window for each application?

### ISSUE THREAD

**Issue by sekmo** [lwouis/alt-tab-macos#1823]
I have multiple Chrome windows open, and I would like to show the Chrome application only one time inside alt-tab. Is this possible?

**Comment by lwouis** [comment]
Maybe you should use the default command+tab macOS switcher if you want the latest window of a given app?

See also #337

**Comment by sekmo** [comment]
but I love this app, I'm just asking if it was possible to show only one window of the same running application 😥

**Comment by lwouis** [comment]
It's not possible at the moment. Please see the existing ticket #337 to learn about previous discussions that go more in depth and that would satisfy your use case

**Comment by hidr0** [comment]
Hey @lwouis great app! Using the default switcher is not possible, because then it does not encapsulate the apps that are on different screens/desktops. What I think @sekmo wants (at least that is what I want) is to be able to have the default functionality of Mac app switcher, but hide the Finder and hide apps from different desktops.

I would be more than happy to try to prepare a PR for this. I downloaded the code and set up XCode, but I cannot run the project. Are you available to sit down for a meeting or point me to where I can get help.

P.S I am not sharing the problem here not to pollute the thread.

**Comment by lwouis** [comment]
@hidr0 yes we can work on this together. My email is in [my github profile](https://github.com/lwouis) on the left. Please first check out the guide here to [learn how to run the project locally](https://alt-tab-macos.netlify.app/contributing).
