### ISSUE TITLE
Parallels Windows VM Apps don't show up

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#187]
Parallels Windows VM Apps don't show up in the AltTab switcher (v3.2.1).

with the default macOS App Switcher you can see the App within an Parallels Windows 10 VM.

with the AltTab Switcher I can only see the Window of the VM.

**Comment by lwouis** [comment]
Hi @mrc247-DE! Thank you for sharing this issue!

It's a bit hard for me to imagine what you are describing. Could you please share a screenshot so that it's easier to visualize?

Also, was this showing properly in the past, like in v2? I'm wondering if this is a regression or if it was never working.

**Comment by mrc247-DE** [comment]
I can't make a Screenshot from the App Switcher, so instead I make a Photo. ;-)

In v2 the Parallels Apps was also not visible.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/55986035/77530658-fb151e80-6e91-11ea-9655-4b6fdc0d7da1.png">

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/55986035/77530716-12eca280-6e92-11ea-829f-7c94addad44c.png">

with the default macOS App Switcher you can see all App running under Windows, Like Outlook, Skype, MS Teams, Firefox.

This is my Corona Home Office Setup. ;-)

please excuse my google translator English. :-)

**Comment by lwouis** [comment]
Could you show me how the missing windows look like? For example, the Firefox window?

I'm afraid it will be hard for me to reproduce this issue on my machine. I think Parallel is not free and i would also need to install Windows, get a license, etc. Mmm... not sure how to go forwards with this

**Comment by mrc247-DE** [comment]
all Icons with the Red Dashes are Apps running in an Parallels VM.

![](https://user-images.githubusercontent.com/55986035/77530658-fb151e80-6e91-11ea-9655-4b6fdc0d7da1.png)

i think this is a very special case that affects only a few users like me. But it could have been that you quickly have an idea.

**Comment by lwouis** [comment]
Can you share a screenshot of the Firefox *window*? Not the app icon, but the full window. AltTab is showing thumbnails of windows, so i would like to see how the window not shown looks like

**Comment by mrc247-DE** [comment]
<img width="2530" alt="image" src="https://user-images.githubusercontent.com/55986035/77540905-34568a00-6ea4-11ea-8437-84f2dd1e5d69.png">

**Comment by lwouis** [comment]
It looks super custom! On the top left, there are 4 round circles for example. I'll see if i can download a demo + a Linux VM to debug and see what this custom windows looks like at the technical level

**Comment by mrc247-DE** [comment]
ok, don't waste your precious time on it. It works like this too. I love your tool and have been using it with enthusiasm for weeks. I just wanted to ask if you see a possibility or indicate that the "problem" exists.

**Comment by lwouis** [comment]
Parallel has a 14 days trial, so I could test with some Ubuntu image I had. To my surprise, it is showing in AltTab:

![Screen Shot 2020-03-26 at 1 41 14](https://user-images.githubusercontent.com/106195/77562220-18360580-6f03-11ea-8edc-cae1cac4caf0.jpg)

![image](https://user-images.githubusercontent.com/106195/77562218-15d3ab80-6f03-11ea-8777-1c14afa814d0.png)

My Ubuntu window look really similar to your Windows 10 window. I also have the dedicated dock icon, and app-switcher icon:

![image](https://user-images.githubusercontent.com/106195/77562626-9a262e80-6f03-11ea-82bb-161fb3493ef2.png)

Could the issue be only happening for Windows 10?

**Comment by lwouis** [comment]
I installed a free Windows 10 VM and was finally able to understand. You are using Parallel default mode. In that mode, the Windows 10 VM has **one** window which contains your Windows 10 environment. Parallel is making nice Dock icons, and app-switcher icons for each app that exists inside the Windows 10 VM, but these are just app icons. When you click one, it just focuses the Windows 10 window, and brings that app to the foreground. There is nothing AltTab can do here because Firefox is not a separate window. AltTab only shows you the full Windows 10 window.

![Screen Shot 2020-03-26 at 2 20 05](https://user-images.githubusercontent.com/106195/77566321-d1e3a500-6f08-11ea-830b-e2a6218b05bb.jpg)

If you want to use AltTab to switch between Windows 10 windows while being on macOS, you can use Parallel Coherence feature:

![image](https://user-images.githubusercontent.com/106195/77566832-8f6e9800-6f09-11ea-9efb-0ce8ecddb03c.png)

In that mode, Parallel create 1 window for each open Windows 10 app:

![Screen Shot 2020-03-26 at 2 14 07](https://user-images.githubusercontent.com/106195/77566320-d14b0e80-6f08-11ea-8efa-cfe6653e1c8f.jpg)

In that mode, AltTab will show you every window (since these are actual windows in macOS):

![image](https://user-images.githubusercontent.com/106195/77566468-0eaf9c00-6f09-11ea-94e8-42e8c88eabc4.png)

I hope I clarified the behavior of Parallel for you :)

**Comment by lwouis** [comment]
I think I showed how it is not a bug of AltTab, but the way Parallel handles windows in general. If I missed something, please feel free to re-open this ticket! :)

**Comment by mrc247-DE** [comment]
thank you for all your work and explanations. :-)
In fact, I didn't use Paralles' Coherense mode. Thanks for pointing out that alt-tab works in Coherense mode. I just tried it and it works fine. Then I will use this mode and have to get used to the way I work. Thanks again for your help. :-)

**Comment by lwouis** [comment]
@juzijun233 could you please contact Parallels customer support. The issue is most likely on their side 👍
