### ISSUE TITLE
Freeze when alt-tabbing between two Libre Office windows

### ISSUE THREAD

**Issue by gvalmont** [lwouis/alt-tab-macos#1923]
**Describe the bug**

Alt-tabbing between two Libre Office windows causes Libre Office to freeze

**Steps to reproduce the bug**

1. Open or create a document using Libre Office (I used Writer)
2. Open or create anoter document using Libre Office (I used Writer)
3. alt-tab from one to another
4. The loading circle appears and Libre Office do not respond anymore, I had to force quit.

Note :
alt-tab between a Libre office Window and another app works flawlessly

**Comment by lwouis** [comment]
I'm pretty sure this was discussed before in a ticket. Strangely, I can't find the ticket.

Unfortunately, I don't think much can be done here. AltTab focuses windows using some private APIs and SPIs. It's a trick we have to resort to, in order to get the focus to work properly. It works fine except for maybe 2 or 3 apps. These apps have bugs that are triggered by this way of focusing I guess.

I suggest you contact the Libre Office maintainers and ask them if they can look at the issue.

**Comment by Perlence** [comment]
Here's the ticket where we discussed it #1508.

**Comment by lwouis** [comment]
@Perlence thank you very much!
