### ISSUE TITLE
CGWindowList future deprecation

### ISSUE THREAD

**Issue by brettstover** [lwouis/alt-tab-macos#1945]
At the end of "Meet ScreenCaptureKit" from WWDC 2022 [https://developer.apple.com/videos/play/wwdc2022/10156/], it's mentioned that CGWindowList will be deprecated in the future. Just wanted to post this here as a heads up and something to start thinking about.

From my own investigation, the ScreenCaptureKit API for getting window information is quite limited (and requires screen recording permission just to get the window list without actually recording anything from the screen). This will (among other things) break the check for if user is in mission control or not. Any thoughts generally about the impact of this future deprecation, workarounds, alternatives, etc? Is there other private API that can be used in place of CGWindowList (assuming that after deprecation it is gone entirely and not available as private API). Are there any alternate methods available for checking mission control status?

**Comment by lwouis** [comment]
Hi @brettstover,

Thank you for sharing this.

You can see `ScreenCaptureKit`, as well as the myriad of other APIs and tricks being discussed here: https://github.com/lwouis/alt-tab-macos/issues/447. The ticket is quite rich, so maybe start there: https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1152269901. Another interesting angle: https://github.com/lwouis/alt-tab-macos/issues/122.

Finally I'll note that an API being deprecated means nothing. AltTab makes use of Carbon APIs that have been deprecated for like 10 years, and which documentation is no longer even on Apple Website. The old APIs are very useful and very used, thus breaking them breaks apps people use. So Apple has very little incentive to break things. They may do it, but historically they haven't much. Here in concrete terms, removing this API would break all sorts of popular screen readers and other accessibility software. For what benefits? The new API is not safer or anything; the permissions work the same as the current API. So I'm not holding my breath.

The real issue is the private API `CGSAddWindowsToSpaces` being removed recently. That one, we have 0 replacement for, and it breaks AltTab's behavior on newer macOS releases.
