### ISSUE TITLE
Modified key seems to be sticky after long pressing

### ISSUE THREAD

**Issue by WinnieJiangHW** [lwouis/alt-tab-macos#1959]
**Describe the bug**

When switching the apps, the option key is sticky after long pressing, while there is no such problem when switching the apps quickly.

btw, the problem remains if I change the shortcut to ctl+tab.
Also, I test one by one and find this problem only happens after v6.7.3 (included)

**Screenshots / video**

1. I have quitted almost all apps that works with shortcuts.
2. I exchange the cmd and option keys in system preference, so I actually press the option key in the video.
3. Option + scroll refers zoom function in the app (pdf expert, as same as adobe acrobat).

https://user-images.githubusercontent.com/57868812/191312149-62342b58-0c6c-4dbb-be36-77857a7870c0.mov

**Comment by XInTheDark** [comment]
cannot reproduce.

**Comment by lwouis** [comment]
Hi @WinnieJiangHW,

Sorry for the delay. I missed this ticket 🙇 

Could you please test the latest release, v6.49.0, and let me know if the issue still happens?

Furthermore, is the issue happening with other apps than the one you demo? It seems to be called "PDF Expert"? Can you reproduce the issue with another app? I suspect it could be this app behaving poorly maybe.

> Also, I test one by one and find this problem only happens after v6.7.3 (included)

You tested every version until v6.7.3? Wow that's so many! It's cool you went through the effort, thank you. That being said, 6.7.3 is from 2 years ago. I looked at the diff between 6.7.2 and 6.7.3, but it's not helpful because I have multiple times rewrote the whole keyboard management to handle things like https://github.com/lwouis/alt-tab-macos/issues/157

**Comment by WinnieJiangHW** [comment]
Thank you for your kind response. I have just tested the new version, the problem remains. However, a thought hits me that the problem may be caused by the mouse (Logitech MX anywhere 3). So I test another brand's mouse and it works fine. As a result, it could be the bug of Logitech's driver (Logitech Options+).

I am sorry for the negligence in the previous test, and thank you again.
