### ISSUE TITLE
Option to hide menubar icon

### ISSUE THREAD

**Issue by quinncomendant** [lwouis/alt-tab-macos#1973]
Now that MacBooks have notches, menubar real estate is more valuable. Can you please add an option to hide the menubar icon? Thanks!

**Comment by lwouis** [comment]
It's already possible. Please see the options in the preferences in the dropdown.

**Comment by XInTheDark** [comment]
@quinncomendant It is the last option in the drop-down menu.

It may be hard to find because there is literally nothing there, but you have to select the last option to hide the menu bar icon.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/61100393/192202192-6e15370c-e5d5-46b7-9fdc-eec2b16841a4.png">

**Comment by quinncomendant** [comment]
@XInTheDark, thanks for pointing that out. Yeah, I wasn't able to figure it out on my own. 🙈
