### ISSUE TITLE
After Effects not detected as active

### ISSUE THREAD

**Issue by probablykasper** [lwouis/alt-tab-macos#1982]
**Describe the bug**

After Effects seems to always show up in the same spot in AltTab. If AE is in focus, it's showing far down the list. If I tab out of AE, it's still far down the list.

It's probably related to #647, though in that one AE doesn't show up at all. I'm guessing that's because they have enabled `Hide apps with no open window`.

I don't think [Contexts](https://contexts.co/) has this problem. Maybe it's solvable by detecting what app is currently focused and showing that at the top of the list.

**Screenshots / video**

![image](https://user-images.githubusercontent.com/11315492/193148854-ebfd5061-f7e5-445f-bd63-2cdcbd0f3a96.png)

**Comment by sgametrio** [comment]
I happened to see this behaviour with VSCode too!

**Comment by lwouis** [comment]
Apps with no window being at the end is normal. The issue is, I imagine, that you have open windows? So you would expect the windows to be listed higher.

If you show the thumbnails, it should make the situation clearer.

Now why the windows are not recognized is most likely due to #1324. I'm going to close this ticket for now as I don't think it's actionable. Feel free to post more information regarding the issue if you think it's not related to #1324 (e.g. activte the thumbnails, then record a video showing the various steps, as well as listing the steps with bullet points). Thank you

**Comment by probablykasper** [comment]
> Apps with no window being at the end is normal. The issue is, I imagine, that you have open windows?

Yes, when I have the After Effects window focused (see screenshot), it doesn't show up at the top. That by itself isn't really a big problem, but it prevents you from alt+tabbing out and back.

> Now why the windows are not recognized is most likely due to https://github.com/lwouis/alt-tab-macos/issues/1324

I'm not on macOS 12 yet, so I don't think that's the issue here.

### Fix suggestion

When a window-less app is in focus (For example QuickTime Player), put the app 1st in the list. When the user tabs out of the app, show the window-less app 2nd in the list. I believe this is how Contexts works.

If it's undesirable behavior for some users, there could be an option to go back to the old behavior, but keep the new behavior for specific apps. You'd want After Effects to always use the new behavior because After Effects _always_ has a window open.

**Comment by lwouis** [comment]
Please share steps to reproduce and a video

**Comment by probablykasper** [comment]
It's just what's shown in the screenshot really:
1. Open After Effects
2. Press alt+tab

**Comment by lwouis** [comment]
Unfortunately, I don't pay for AE, so I can't really try it out myself. I checked on their website, and it's pretty high commitment to just try it out.

**Comment by lwouis** [comment]
If you're before macOS 12, I really wonder why AltTab wouldn't list AE windows. That's very unexpected/uncommon.

Maybe you could open AltTab in Terminal.app, wait for the logs to settle, then open WE, and share the logs you get? I'm curious if the OS is not sending the normal events maybe? It's highly unlikely.

The other explanation would be that AE windows are not real OS windows. I made a [build which doesn't filter-out non-windows](https://github.com/lwouis/alt-tab-macos/files/9904943/AltTab.app.zip). Could you run it and tell me if it shows the AE windows?

**Comment by probablykasper** [comment]
These are the logs from opening AE:
```
"OS event" "apps launched" [(94255, Optional("com.adobe.AfterEffects"))]
"Adding app" 94255 "com.adobe.AfterEffects"
"OS event" "apps launched" [(94270, Optional("com.adobe.GPUSniffer.application"))]
"OS event" "apps quit" [(94270, Optional("com.adobe.GPUSniffer.application"))]
"Deinit app" "com.adobe.GPUSniffer.application"
"OS event" "apps launched" [(94272, Optional("com.adobe.TeamProjectsLocalHub.application"))]
"Accessibility event" "AXApplicationActivated" "iTerm2"
```

> The other explanation would be that AE windows are not real OS windows. I made a [build which doesn't filter-out non-windows](https://github.com/lwouis/alt-tab-macos/files/9904943/AltTab.app.zip). Could you run it and tell me if it shows the AE windows?

That did fix it! It shows the window, including the thumbnail

**Comment by lwouis** [comment]
> That did fix it! It shows the window, including the thumbnail

Then it means AE windows are not real windows. It's a bug on their side. You should open a ticket for them so they fix it. If it affects AltTab, it must affect other accessibility apps.

I could add a workaround like I've done in the past for a few apps, but it may then list some UI elements as windows in AltTab. Some poorly written apps will use `NSWindow` (macOS standard windows) to implement tooltips or menus. These tooltips/menus will then show in AltTab as windows (since they are instances of `NSWindow`). This is the purpose of AltTab filtering out "real and fake" windows.

Could you test out [this build](https://github.com/lwouis/alt-tab-macos/files/9905080/AltTab.app.zip)? I applied the same whitelist as I did Adobe Audition. It's a bit more restrictive than a blanket-statement whitelist, so if it works it would be better.

To insist again: this is a bug on AE side. It should be reported. Screen readers and other apps are probably broken with AE.

**Comment by probablykasper** [comment]
> To insist again: this is a bug on AE side. It should be reported. Screen readers and other apps are probably broken with AE.

Got it, will report. Shocking to see a bug in After Effects, hopefully they fix it in just a few short years

> Could you test out [this build](https://github.com/lwouis/alt-tab-macos/files/9905080/AltTab.app.zip)? I applied the same whitelist as I did Adobe Audition. It's a bit more restrictive than a blanket-statement whitelist, so if it works it would be better.

AE lets you drag different UI elements/panels out into their own separate windows. The old build showed the panels individually. The new one only shows the main window, which is great.

AE also has a preference window, and when it's open, you can't interact with the main window. The preferences window showed up separately in the old build, not only the main window shows up. I think it's good that it doesn't show them separately, but it also means that when you tab into AE, the non-interactive window is what gets focused.

Ideally it would match Mission Control: Only the main window shows up in Mission Control, but when you click it, the Preference window keeps focus (but it's also not a huge deal, I don't spend all my life preferences)

**Comment by lwouis** [comment]
Yes, all

**Comment by debuxxed** [comment]
still present issue. Adobe wouldn't listen anyways

**Comment by guillaumebaeriswyl** [comment]
i have this issue too!

**Comment by Jean-Batiste0** [comment]
This seems to be an issue again!

**Comment by sgtlighttree** [comment]
Still seems to be an issue again. It was fixed at one point but I can't tell if it was something on the app, macOS, or AE itself. I'm leaning towards it being Adobe's fault again.

**Comment by bear-ic** [comment]
I have this issue now as well with Adobe After Effects 2026
