### ISSUE TITLE
CTRL+TAB (the default way to switch tabs in chrome) doesn't work

### ISSUE THREAD

**Issue by AdityaAnand1** [lwouis/alt-tab-macos#20]
Wouldn't CMD+TAB be better for this app instead of another shortcut that may conflict with other apps?

**Comment by bartoszhernas** [comment]
I would also love to just switch to this app and replace default macos switcher, so ability to use CMD+TAB would be great :)

**Comment by lwouis** [comment]
I have a global remap of cmd<->ctrl on mac my mac. That's why it's currently using ctrl+tab

The short term fix is change the code ([2 lines here](https://news.ycombinator.com/item?id=21254933)) and rebuild (run `xcodebuild `)

The long term fix is letting users select the hotkeys with some UI (see [ticket](https://github.com/lwouis/alt-tab-macos/issues/8))

**Comment by lwouis** [comment]
**Update:** changing hotkey is now possible by [editing preferences in a JSON file](https://github.com/lwouis/alt-tab-macos/issues/8#issuecomment-542695697).

**Comment by lwouis** [comment]
@AdityaAnand1 @bartoszhernas I just released [1.6.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.6.0) which features an easy dropdown menu to select which shortcut key you want to use to trigger the app. Check it out! :)
