### ISSUE TITLE
At startup restricting shown apps to "visible spaces" does not work

### ISSUE THREAD

**Issue by mbert** [lwouis/alt-tab-macos#2015]
I have configured AltTab to show only the apps from visible spaces. This mostly works, but when starting AltTab at a time when there are already numerous apps open across various spaces, then AltTab often (not always) shows several apps on other spaces. Often the only way to resolve this is to close and open again the other apps.

**Comment by lwouis** [comment]
Could you please provide steps to reproduce, and a video demonstrating the issue? I can't reproduce it. Thank you

Also to clarify apps are not "on a Space". Apps have windows. These windows can be on specific Spaces. The apps themselves are not "on a Space".

**Comment by mbert** [comment]
> Could you please provide steps to reproduce, and a video demonstrating the issue? I can't reproduce it. Thank you

Hi, here's a [video](https://drive.google.com/file/d/19k3vXBXV7hPRQZ1L_m1OqLv3z4W1608S/view?usp=sharing).

> Also to clarify apps are not "on a Space". Apps have windows. These windows can be on specific Spaces. The apps themselves are not "on a Space".

Sure, I meant to say: apps with no windows on the respective current space.

**Comment by mbert** [comment]
> So the initial state is right after you have started your computer? In other words, AltTab is missing some apps (`Franz` for example) on a fresh start up, but then any restart after will always show it?

The initial state is actually what is shown at the end of the video. The state before that is the expected state: I cycle through all windows in the current workspace. However it looks like when AltTab is started after there are already a number of windows open on various workspaces, it will cycle through all of them regardless the workspaces where they have their windows. 

On my box, the web browsers are all on space 2. Teams and Franz is on space 1. Airmail on space 5. Hence after restarting AltTab it's pretty much a mess. 

If I now restart the apps one by one AltTab will function as expected.

**Comment by lwouis** [comment]
Here is a comparison of what AltTab shows:

Before | After
-|-
![image](https://user-images.githubusercontent.com/106195/195630655-3920d4f0-9c47-4404-8c38-f474b861bb98.png) | <img width="782" alt="image" src="https://user-images.githubusercontent.com/106195/195630631-1f289f7a-7d64-4d9d-ab58-a3d6d05477b5.png">

We can see that the only difference is 3 new apps are being shown: `Franz`, `Teams`, `Airmail`.

AltTab is showing these **apps** not their windows. This is expected behavior since as I said previously, an app is not on a specific Space. So when yo're on Space 2, AltTab should show you **all apps + windows on Space 2**.

Does that make sense?

**Comment by mbert** [comment]
> We can see that the only difference is 3 new apps are being shown: `Franz`, `Teams`, `Airmail`.
> 
> AltTab is showing these **apps** not their windows. This is expected behavior since as I said previously, an app is not on a specific Space. So when yo're on Space 2, AltTab should show you **all apps + windows on Space 2**.
> 
> Does that make sense?

Hmm, It does not really.
I am in space 2. AltTab shows me the three windows in my current space. 
I quit AltTab and start it again without switching space.
Now I get a different, much larger list of entries. 

If AltTab were to show me apps rather than windows then I should see all of them all the time, shouldn't I? 

My expectation is to see only windows from my current workspace in the cycler when I have "show windows from all apps / visible spaces" selected. Otherwise I don't see any point in this setting, because all apps are in all spaces as you correctly pointed out. 

Or have I not understood something fundamental?

**Comment by lwouis** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/106195/195635093-e40702a1-5710-4416-915d-577ac2dbfdb0.png">

This is not a window. This is a UI element representing **an app which is running but without any open window**. If you select it, it will activate that app. For a lot of apps it will then create a new window.

This is a example use-case that many users asked for: let me open a Finder window from anywhere.

These UI elements are global. It doesn't matter which Space you are on, if you suddenly want to open a new window from Finder. This is why the preference you shared above applies to windows, since they exist in a specific Space, but not to apps-with-no-open-window. These are global.

Is that part more clear?

The fact that you get a before and after that's different seems to indicate a bug in the **before** picture to me. For some reason, AltTab is failing to show you 3 open apps with no open window. It shows you Finder for instance, which is correct, but not Franz. I'm not sure what's causing this issue.

**Comment by mbert** [comment]
Thank you for clarifying this. 

So there is an inconsistency, this seems confirmed. 

Having understood all this, it seems to (mostly) turn out as a feature request: Being able to completely filter out anything that is not an open window in the current space would be useful. It would resemble the standard switcher on Option+Tab as in MacOS. Since we can assign 2 shortcuts with different settings one could have both - the complete (standard) list and a list drastically reduced to the open windows. How about this?

**Comment by lwouis** [comment]
What you're describing is already possible. You can hide apps-with-no-open-window in Preferences > Appearance. This way you'll only see windows of the active Space

**Comment by mbert** [comment]
> What you're describing is already possible. You can hide apps-with-no-open-window in Preferences > Appearance. This way you'll only see windows of the active Space

Thank you. That really helps a lot. Maybe nevertheless worthwhile making this a setting that can be bound to one of the two possible key combinations. But still this already got me much closer to what I need. Thank you again for your support!
