### ISSUE TITLE
Window skipped after active active app becomes windowless

### ISSUE THREAD

**Issue by probablykasper** [lwouis/alt-tab-macos#2065]
**Describe the bug**

When alt+tabbing after a window becomes windowless, the first item in the list is skipped over

**Screenshots / video**

https://user-images.githubusercontent.com/11315492/199083928-42a2f791-8fc1-46b4-b6a1-f86e7a3ca4e4.mp4

**Video explanation:**
1. QuickTime Player is launched with no windows. Alt+tabbing correctly selects the 1st item
2. A window is opened in QuickTime Player. Alt+tabbing correctly selects the 2nd item
3. The window is closed, but QuickTime Player is still focused. <ins>Alt+tabbing incorrectly selects the 2nd item</ins>

**Steps to reproduce the bug**

1. Open a file in QuickTime Player
4. Close the window, but keep QuickTime Player in focus
5. Alt+tab

**Comment by lwouis** [comment]
Thank you for sharing this issue @probablykasper!

I was able to reproduce the issue. I must say I was surprised because I remember taking care of this scenario a while ago (in f4d3db79). It turns out that I had only tested various other scenarios, but not that exact one. I added some logic to handle closed windows. It works correctly for me. Could you test [this build](https://github.com/lwouis/alt-tab-macos/files/9904890/AltTab.app.zip)?

Thank you

**Comment by probablykasper** [comment]
Yep, the build works beautifully! :D
