### ISSUE TITLE
Allow removing the ellipsis... truncation symbol

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#2075]
**Is your feature suggestion related to a problem? Please describe.**
The `...` truncation symbol takes valuable space in packed AltTab lists with many apps/windows opened (especially when used without thumbnails, so text is the only thing you rely on)

**Describe the solution you'd like**
Please add an option showing __no truncation symbol__, I'm generally already aware that the full name doesn't fit, expect it and wouldn't worry if I see
`/ApplicatTab.app` instead of
`/Applic...ab.app`

**Describe alternatives you've considered**
You could maybe use another truncation indicator at the top/bottom of the text that wouldn't cut into the text length itself, but that's more complicated

**Comment by lwouis** [comment]
Hi,

I don't think this proposal goes in the right direction.

Your example will not happen, because if your example `...` takes more space than what it replaces, which can't happen. So a better example would be to say:

`/ApplicatTa` (text is clipped to the right) instead of `/Applic...ab.app`.

Furthermore, you're only losing the space of `...` total. It's not much content you would save if you would clip the text abruptly instead.

A better solution, I think, for people like you who don't care about thumbnails, and focus on text, is to do what others apps like Contexts and Which are doing. You can already set AltTab to do this by tweaking the preferences in the Appearance tab. Look at the OP in this ticket to see what I mean: https://github.com/lwouis/alt-tab-macos/issues/2026

Through #351, I hope that we establish "pre-sets" so that you can turn AltTab, in one click in the preferences, from the default experience (same as Windows alt-tab), to something similar as the native macOS app-switcher (app-icons only), or to something similar to Contexts (vertical rows of text).

**Comment by eugenesvk** [comment]
> Your example will not happen, because if your example ... takes more space than what it replaces, which can't happen. So a better example would be to say:

How so? Both words are 16 characters. I understand that many letters are wider than a period, so it won't always be that `...` is replaced with 3 regular chars, but maybe 2 like in this TextEdit screenshot
<img width="374" alt="at" src="https://user-images.githubusercontent.com/12956286/199597405-e8d510ef-5bef-4c81-b69e-276fbcbefdc2.png">

but still `...` doesn't take more space than the replacing 3 chars in my example


So I'm a bit confused by your example:
>/ApplicatTa (text is clipped to the right) instead of 
>/Applic...ab.app

where did the `.app` go? Why is the replacement of 16 chars with `...` only 11 chars without?


> A better solution, I think, for people like you who don't care about thumbnails, and focus on text, is to do what others apps like Contexts and Which are doing. You can already set AltTab to do this by tweaking the preferences in the Appearance tab. Look at the OP in this ticket to see what I mean: https://github.com/lwouis/alt-tab-macos/issues/2026

Thanks for the suggestion, but I don't want to have just one column, that's also suboptimal — most window titles aren't long enough (as you can see on the video as well) to justify taking the whole line with just one item! And when I do it more dense with several columns, the `...` issue reappears

> It's not much content you would save if you would clip the text abruptly instead.

Yep, just ~10-20% characters

**Comment by lwouis** [comment]
> ![image](https://user-images.githubusercontent.com/106195/199610648-f6f90f28-6bb3-44bd-bea1-d5e94dd7ac66.png)

In this example you shared, there are 2 possible options:

* Either `/Applicatab.app` fits in the available space, in which case AltTab will show that text without truncation
* Or `/Applicatab.app` doesn't fit in the available space, in which case AltTab has to decide how to deal with the overflow

The case you imagine where we could just show the missing letter doesn't exist. If we can show it, we do. If we don't, it's thus that we couldn't physically fit it. We then need a strategy. There are many strategies here:

* Clipping abruptly to the right or to the left
* Using an ellipsis to remove part of the title, to the right, left, of middle
* Reducing the size of the font as the text gets longer
* Probably others

I went with the ellipsis. I think it's an elegant choice, and I like the flexibility of being able to pick the sides or the middle. Which clipping doesn't allow for instance.

**Comment by eugenesvk** [comment]
> ... 2 possible options:
> * Either `/Applicatab.app` **fits** in the available space, in which case AltTab will **show that text without truncation**

These aren't the options since there is no Applicatab.app, the path is the regular path to AltTab.app in the /Applications folder, which doesn't fit and gets truncated in the middle to those examples

> The case you imagine where we could just show the missing letter doesn't exist

Except it does exist, it's a simple case of replacing 3 characters `...` with the actual truncated characters (however many fit, 2 or 3 depending on the character width). So the strategy is more like
  - Using a customizable symbol to remove part of the title, to the right, left, of middle

> and I like the flexibility of being able to pick the sides or the middle.

So do I, thanks for that option, I usually pick to trim the middle if there is an option since it's usually less valuable (especially when you have various `(1)` and `(2)` in the end of file names or for paths etc.)

>Which clipping doesn't allow for instance

Why not? The only thing that changes is the truncation symbol —
  - `...` in your case and
  - `` in mine or maybe a 
  - `⋮` compromise or a more advanced solution which places some kind of 
  - ⎀ marker at the top (so it doesn't interfere with how much text you can fit in the main line)
  - or something

all the other text trimming options can remain as is — you can clip in the middle/beginning or the end with either of those custom truncation symbols

**Comment by lwouis** [comment]
> Except it does exist, it's a simple case of replacing 3 characters ... with the actual truncated characters (however many fit, 2 or 3 depending on the character width).

Again, if we could replace the ellipsis with the actual characters, we would just display them. The reason we display ellipsis is because the width of the ellipsis is smaller than that of whatever it replaces.

> >Which clipping doesn't allow for instance
>
>Why not? The only thing that changes is the truncation symbol —

That's not clipping. Clipping refers to cutting the pixels abruptly like with a pair of scissors.

I prefer an ellipsis because yes it's 3 dots wider, but it explains that there was a cut, and where it is. Clipping is rough. It can look like a visual bug, and confuse people. If it doesn't cut in the middle of a letter, then it may even confuse people as they have no way to know that the full name of the window is not shown. It's not aesthetically pleasing. Finally, you can clip in the middle because then it's impossible to tell that a piece was removed.

I'll stop discussing this I think. Ellipsis is reasonable. It's a convention people understand. It's widely used in macOS (e.g. in the Finder). It's built-in, whereas anything more custom would require lots of hard work. I don't know if you've ever worked on pixel-perfect text layout algorithm but this stuff is PHD-level to support all languages. Like good luck implementing it correctly for Arabic and Chinese.

Your request may work for you because you know what you want and are willing to push the limits. 99% of users will be fine with the current ellipsis. We probably actually already provide too many preferences to customize the experience (see #351)

**Comment by eugenesvk** [comment]
> Again, if we could replace the ellipsis with the actual characters, we would just display them. The reason we display ellipsis is because the width of the ellipsis is smaller than that of whatever it replaces.

No you wouldn't! They wouldn't ALL fit, the whole point of the ellipsis is to indicate that. Let's try another example, don't understand where the confusion lies (let's assume fixed-width fonts for simplicity):
- we have a space of 14 chars in the AltTab layout
- `/Aplications/AltTab.app` is 23 chars, so obvioulsy doesn't fit in this space of 14 chars
- `/Aplic...b.app` is the above string truncated in the middle with 3 `...` chars added to indicate the truncation, 14 chars in total
- `/Aplicatab.app` is the above string truncated in the middle without any of the extra 3 `...` chars added to indicate the truncation, 14 chars in total, but now with 3 more content chars instead of the 3 truncation chars

>That's not clipping. Clipping refers to cutting the pixels abruptly like with a pair of scissors.

Yes, can't you cut the pixels with a pair of scissors in the middle of a word and glue that word back toghether?

>I prefer an ellipsis because yes it's 3 dots wider, but it explains that there was a cut, and where it is. Clipping is rough.

Ok, so you'll continue using the ellipsis. I'd be fine without those explanations or with those explanations conveyed with a shorter indicator

>It can look like a visual bug, and confuse people.

No it can't because those confused people will simply continue to use the ellipsis. I won't be confused, as I mentioned in my original post

>It's not aesthetically pleasing

Which is fine, I'd take more content for less pleasure

>   Finally, you can clip in the middle because then it's impossible to tell that a piece was removed.

It's not impossible, it's just harder, which is also fine for me


>It's built-in, whereas anything more custom would require lots of hard work.

Ok, that's a major roadblock. But do you mean that even pixel clipping in the middle is also too hard?

>We probably actually already provide too many preferences to customize the experience (see #351

Thas has simple solutions to separate average advanced users, for example, the one I mentioned https://github.com/lwouis/alt-tab-macos/issues/351#issuecomment-1301043430. Or you could use an extra "advanced flag" that shows more tabs with options but only for advanced users
