### ISSUE TITLE
AltTab should intercept command+shift+tab if command+tab is bound

### ISSUE THREAD

**Issue by Swandog** [lwouis/alt-tab-macos#2080]
**Describe the bug**

I have Alt-Tab configured with Command+Tab as the shortcut. This works great, and has been for some time. With the latest release, though, there seems to be a problem with using Command+Shift+Tab to cycle backwards through windows. When I hit Command+Shift+Tab, it does cycle windows in Alt-Tab; but it also raises the default MacOS application switcher as well. Then I have to close/escape out of that one after I've finished selecting a window in Alt-Tab.

I'm pretty sure this issue wasn't happening in the version prior to this one.

**Screenshots / video**

<img width="3001" alt="Screen Shot 2022-11-04 at 10 25 34 AM" src="https://user-images.githubusercontent.com/863307/200014672-b8071cae-524f-4a1e-9df6-58c605ba0d1d.png">

**Steps to reproduce the bug**

1. Set up Alt-Tab with a shortcut of "Hold ⌘" and press "⇥" (this is what comes up for Command-Tab for me)
2. Use Command-Tab to bring up the Alt-Tab switcher
3. Use Command-Shift-Tab to cycle backwards in Alt-Tab

Notes: I tried resetting my preferences, that did not help. Command+Tab does not bring up the default switcher; only Command+Shift+Tab does.

**Comment by lwouis** [comment]
Hi @Swandog,

I just tried to reproduce but couldn't. I tried with these preferences:

>  <img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/200044064-cd2f5cbc-0d65-4bb1-85b5-59a52f0765a0.png">

Could you please share your preferences?

**Comment by adityakaulagi** [comment]
@Swandog I was able to reproduce the bug you mentioned. I think you're experiencing this because AltTab has a different approach to shortcut compared to the native app switcher for going to previous window/app.

1. In the native app switcher, cmd+tab is used to bring up the app switcher. To select the next app, you press tab while holding cmd. To select the previous app, you press tab while holding cmd and shift.

2. For AltTab, the shortcut you've assigned will bring up AltTab's app switcher. Let's assume this is cmd+tab. Then, to select next window, you need to hold cmd and press tab. To go to previous window, you should hold cmd and press shift, which is different than holding both cmd and shift and pressing tab that you do for native app switcher.

So by holding cmd+shift and pressing tab, you're bringing up the native app switcher.

**Comment by lwouis** [comment]
Oh, I see.

I thought I should only disable the native `command+shift+tab` if the exact shortcut is bound in AltTab, but I guess it's confusing that `command+tab` would be disabled (replaced with AltTab) but `command+shift+tab` not be.

I think I'll add a special case that if `command+tab` is bound, then both native `command+tab` and `command+shift+tab` should be disabled. I think it will help for most people. It will still not work if people press `command+shift+tab` as the `tab` key will go forward and the `shift` key will go backward, so depending on the order they are pressed it will mess up in a different way. But that can't be helped. People hopefully learn that it's only shift that's use to cycle backwards.

**Comment by Swandog** [comment]
Ah yes--this is exactly the case! Somehow I didn't trigger this before. But now, testing it out, I see that `command+shift` works exactly as described by @lwouis  and @adityakaulagi . I was used to the default switcher's command keys, and that was what was tripping me up.

Now that I know how it works, I can figure it out. Though it would still be helpful to me if `command+shift+tab` was disabled.

Thanks!

**Comment by puntium** [comment]
Came here to chime in on the same issue. My muscle memory from 20 years using windows causes me to hit "cmd + shift + tab" after i've already summoned the alt-tab switcher with a cmd-tab shortcut. This causes the native app switcther to appear in addition to the alt-tab window switcher which is very confusing.

repro steps:
1. create a command + tab short cut in AltTab
2. hit AltTab to bring up window switcher
3. without letting go of command, also press shift + tab
4. see now native app switcher appear on top of AltTab switcher

expected behavior: Shift+tab would cause a previous item in the AltTab switcher to be selected.

**Comment by lwouis** [comment]
Next release will have the mitigation to avoid this issue

**Comment by Swandog** [comment]
FWIW--I got the update today and it fixes the issue perfectly! Thanks!
