### ISSUE TITLE
Louis Pontoise background items keep being notified

### ISSUE THREAD

**Issue by jmoritz** [lwouis/alt-tab-macos#2097]
In MacOs Venture, I deleted the AltTab app but I keep seeing a "Louis Pontoise" background items notification popup, I cannot find how to make it disappear so would appreciate some help there

**Comment by t1noo7** [comment]
> Please update AltTab. It will fix this issue. See [#2069](https://github.com/lwouis/alt-tab-macos/issues/2069)

Excuse me! I do not clearly understand your answer. You mean it has to be installed again and update it right after that?

**Comment by lwouis** [comment]
Hi,
The issue was fixed 3 years ago. That means that any version since then doesn't have the issue. If you update your AltTab to the latest version, you'll not have the issue. If somehow you still have it, then a full uninstall may be required. Then install the latest and there won't be any issue
Thank you
