### ISSUE TITLE
Firefox hints are identified as windows

### ISSUE THREAD

**Issue by Perlence** [lwouis/alt-tab-macos#2110]
Hello, I'm using AltTab 6.49.0 on macOS 13.0. I've noticed that AltTab identifies the Firefox hints as windows. I believe, you don't really want to switch to them.

https://user-images.githubusercontent.com/1044300/201291764-965262eb-46e3-4ad9-99ff-f3a70b58f5d2.mp4

**Comment by lwouis** [comment]
AltTab shows instances of NSWindow. Now why Firefox decided to use NSWindow instances to draw their tooltip is beyond me.

This is a bug with Firefox. Please open a ticket to them.

i'll see if i can add another workaround, but really it's an issue on their side.

**Comment by Perlence** [comment]
Thanks for taking a look! What class do the regular apps, such as Finder, use to display the hints?

![image](https://user-images.githubusercontent.com/1044300/201494340-fc75f29e-d7a8-4e97-9c26-d900b22df3ac.png)

**Comment by lwouis** [comment]
> What class do the regular apps, such as Finder, use to display the hints?

It depends. There are multiple tooltips in macOS. You can checkout the general [`NSView.tooltip`](https://developer.apple.com/documentation/appkit/nsview/1483541-tooltip). On your screenshot specifically, it's [`headerToolTip`](https://developer.apple.com/documentation/appkit/nstablecolumn/1524685-headertooltip). There are many other APIs.

In general, you specify the tooltip's value as a string, and the OS takes care of how the tooltip should look, behave, how long until it's shown, etc. You might be able to override some methods to customize things further, but I've never done it, so I'm not sure. That being said, you could create a custom tooltip based on `NSPopover` maybe, or definitely based on `NSPanel` or even `NSWindow`. But you should definitely for the last 2 cases define the right attributes on that window so it's clear to the OS and Accessibility apps that this is not something the user would consider a window.

**Comment by Perlence** [comment]
Awesome, thanks!

**Comment by lwouis** [comment]
I looked into it further. It's actually the previous workaround I added to support fullscreen windows from Firefox (these are not normal/native fullscreen windows) (see https://github.com/lwouis/alt-tab-macos/issues/558 and related tickets).

To show these fullscreen windows in AltTab, I added an exception to let windows with role `AXUnknown` show, even though they shouldn't be shown normally to users. The issue here is that that rules lets us show fullscreen windows, but also as a side-effect shows tooltips which are also implemented as `AXUnknown` windows.

I'll add another layer of workaround to show `AXUnknown` only if the app is Firefox (already the case) + if their height is taller than 400px. That way it should show fullscreen windows, and not tooltips.
