### ISSUE TITLE
AltTab Hot Corner

### ISSUE THREAD

**Issue by Maghsad** [lwouis/alt-tab-macos#2119]
To me, AltTab offers a more reasonable solution than Mission Control and Stage Manager, especially since it can be used to close Windows. It would be great if AltTab could be used as a Hot Corner.

**Comment by lwouis** [comment]
Hi,

There are dozens of possible triggers for an app to act. A mouse gesture, phone bluetooth losing connection, a ping from an ethernet cable, etc. I think it's reasonable for AltTab to focus only on the main ones: keyboard and mouse/trackpad.

In order to enable other triggers, please you an app like BetterTouchTool. It will allow you to bind any trigger to anything else. For example you can bind a hot corner to a keyboard shortcut, thus enabling the hot corner workflow you want in AltTab.

Good luck~
