### ISSUE TITLE
Default value for "Apparition delay"

### ISSUE THREAD

**Issue by ElhemEnohpi** [lwouis/alt-tab-macos#2128]
**Is your feature suggestion related to a problem? Please describe.**
Brief flashing of the thumbnails when quickly switching between the two most recent windows is a bit irritating, and unexpected if the user is used to the built-in app switcher. The user can fix it in Preferences, but better to have it work smoothly from the start.

**Describe the solution you'd like**
I suggest making a default value for "Apparition delay" of around 100 ms or so, to match the way the built-in app switcher works, "out of the box" or after resetting preferences.

**Comment by lwouis** [comment]
It's always a though choice between following established conventions, and going with what you think is an improvement over status-quo.

I prefer snappy UI. I worked really hard on AltTab's performance, and it takes only a few frames to show and hide, under good circumstances. I prefer that snappiness over aesthetics.

Similarly, I learned the backwards cycling shortcut `alt+shift` from HyperSwitch. I thought it was way better ergonomics for the hand (just look at your hand when doing `alt+shift+tab` like on Windows).

These are the 2 places, out of *many* places, where I've decided that the default would be bold and daring, instead of going with status-quo. Maybe I'm wrong. That's what I went with. Maybe I'll change default in the future. Maybe someone will take over after me (#1179) and do it. Time will tell. For now, these are the few choices were I'm standing my grown for what I believe are improvements over the status-quo.

**Comment by ElhemEnohpi** [comment]
The majority of the time, I'm hitting alt-tab (actually alt-backtick) to rapidly switch between the two recently used windows, so for me, it actually seems less snappy - and looks kind of glitchy. But anyway, it's easily fixed in the preferences I guess. I definitely agree that shift on its own to go back is a big improvement over the built-in app switcher's command-shift-tab, which has always annoyed me.
