### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by marcpops** [lwouis/alt-tab-macos#2155]
Hi, since AltTab takes images of the windows, these images can potentially show critical informations.
Could you please tell me how they are managed, stored and  when they are erased ?
Thanks
Marc

**Comment by lwouis** [comment]
This question has been answered many times, so please look at the [more in-depth answers in the existing tickets](https://github.com/lwouis/alt-tab-macos/issues/970#issuecomment-848403678).

In short, AltTab gets the screenshots from the OS, and uses them in RAM. It never gets stored on disk at any point. When the app is quit, all data is gone. While the app is alive, you would need extremely advanced memory take over to read those. At this point you would rather target Chrome and read its tabs.

AltTab is a safe as it can be. Furthermore, you don't have to take my word for it, since the whole source-code is nicely shared here in the open on Github, so you can see for yourself.

Beyond that, as I wrote on the website:

> **Privacy and respecting the user**
> * AltTab doesn’t send or receive any data without explicit user consent. It may ask the user to send a crash report after a crash for example, but it will never spy on the user.
> * AltTab tries to use as few resources as it can: CPU, memory, disk, etc. All images are compressed, AltTab is optimized to be as light as possible on the user resources.
