### ISSUE TITLE
Hovering name-tag doesn't disappear

### ISSUE THREAD

**Issue by honeySleepr** [lwouis/alt-tab-macos#2190]
**Describe the bug**

Minor issue here.
While using alt-tab, a name-tag appears when you hover over an Icon for a few seconds.
The problem is that the name-tag will remain on the screen even after `Cmd+Tab` is released.
Clicking on the screen doesn't make it disappear; it goes away only when I press `Cmd+Tab` again.

**Screenshots / video**

- My mouse is located at the red circle, on the Between App. You can see the grey little name tag has appeared right next to it showing the app name "Between"

![2E4F5659-A93F-40C3-9317-DBCFBAAFC546](https://user-images.githubusercontent.com/92678400/206180937-9f727092-df2e-47ae-9a0d-8adaa854205d.png)

- After I let go of `Cmd+Tab`, the name-tag remains on the spot. Clicking the mouse or typing doesn't make it go away.

![3404E9E7-B06D-48B7-9723-803A77038A12](https://user-images.githubusercontent.com/92678400/206182266-513fc2bb-3820-4f9b-8ba8-7297c7dbed28.png)

**Steps to reproduce the bug**

1. Press down on `Cmd+Tab` to show alt-tab interface 
2. Keep your mouse hovering on an Icon for about 2 seconds
3. The little grey name-tag will appear
4. Let go of `Cmd+Tab` without actually clicking the icon.
5. The name-tag will still be there
6. **Press `Cmd+Tab` again to make the name-tag disappear**

**Your environment**

* AltTab version:  6.51.0
* macOS version: Ventura 13.0.1

Thank you for this great app : )

**Comment by XInTheDark** [comment]
Reproducible; this bug happens for me too. It's quite troublesome since I sometimes hover over the icon by accident, and it takes another key press to make the nametag disappear. 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/61100393/206405508-eb96c7c2-8334-4681-9372-e709cda7a950.png">

_As shown in the photo, the nametag remains after the window switcher is closed._

**Comment by lwouis** [comment]
I wonder if this is not a bug in AppKit. AltTab has hidden its window. Why would the tooltip still show? We use standard tooltips which is just setting a string on the hovered view. Everything else is up to Apple/AppKit.

**Comment by XInTheDark** [comment]
I'm not sure if this issue occurs in other Mac apps as well. AFAIK, this doesn't occur in Safari.

**Comment by lwouis** [comment]
I think i've had it happen with other apps. Definitely with IntelliJ, but i doubt they are using native tooltips since their products use Java UI frameworks

**Comment by decodism** [comment]
It would be better to understand why this happens but here's a workaround:

```swift
NSApp.perform(NSSelectorFromString("abortAllToolTips"))
```

**Comment by XInTheDark** [comment]
> It would be better to understand why this happens but here's a workaround:
> 
> ```swift
> NSApp.perform(NSSelectorFromString("abortAllToolTips"))
> ```

I don't know Swift, but this seems like it forces the deletion/cancellation of all active tooltips. Is this a good idea, though? Wouldn't it be better to cancel this specific tooltip instead of every one? I don't have a specific scenario in mind but cancelling every tooltip might result in some unexpected glitches. 

After doing some searches, I found a method `NSView.cancelToolTip()` which seems to do what we're looking for.

**Comment by lwouis** [comment]
@decodism this snippet seems like it would be a very simple workaround for the issue. However, I'm a bit hesitant to add this line given that it doesn't seem to be documented anywhere? From [what I can tell](https://github.com/w0lfschild/macOS_headers/blob/master/macOS/Frameworks/AppKit/1643.10.101/NSApplication.h#L106) it's a private API.

Could you please share a bit more on how you came up with this, and if you think it's safe to use, on all macOS versions from 10.12 to current, and on Intel and Apple Silicon, without known side-effects?

**Comment by XInTheDark** [comment]
> can you please share a link to its documentation? I can't seem to find information about this method.

I was mistaken, apparently. There isn't any official documentation introducing that method; I will try to find if there is a way to cancel a specific tooltip.

**Comment by XInTheDark** [comment]
There does seem to be the [`removeToolTip()`](https://developer.apple.com/documentation/appkit/nsview/1483522-removetooltip) method to remove a tooltip, and [`removeAllToolTips()`](https://developer.apple.com/documentation/appkit/nsview/1483801-removealltooltips) to remove all tooltips.

**Comment by decodism** [comment]
@lwouis Yes, it is a private API. That's why it's called dynamically.

I found it while digging in AppKit and tested it on macOS 13. For macOS 10.12, I just checked and it is present in a header dump I found on the internet. You can always check that it exists with :

```swift
let selector = NSSelectorFromString("abortAllToolTips")
if NSApp.responds(to: selector) {
    NSApp.perform(selector)
}
```

**Comment by lwouis** [comment]
I tested the snippet above, and it fixes the issue. I'll implement this in the next release. Thanks a lot @decodism for sharing this trick 👍

@XInTheDark these APIs do more than hidding the tooltips. They unset them. Meaning in order to bring them back next time, we would need to go on each view, and re-set to the exact value for that view. I'll go with the `abortAllToolTips` private API. It seems to work and it's a simple OFF toggle for all tooltips 👍
