### ISSUE TITLE
Ability to filter out windows from appearing based on data

### ISSUE THREAD

**Issue by parssak** [lwouis/alt-tab-macos#2207]
**Is your feature suggestion related to a problem? Please describe.**
I get frustrated when certain unfavourable windows appear in AltTab, such as invisible windows that Arc may spawn, or small over windows like the Messenger

**Describe the solution you'd like**
I'd like a way to filter out certain windows from appearing
"filter out windows from app X that have Y"
things such as the title of the window is "ABC"
or the dimensions of the window are smaller than "X,Y"

**Comment by lwouis** [comment]
You can already filter some of these in the Blacklist section of the preferences. Filtering in more finer grain would be too niche to add to the app, i'm afraid. You opened another ticket for Arc. The root cause here is that this app has issue. Once fixed, it will make the need less strong to filter things
