### ISSUE TITLE
Scaling external monitor

### ISSUE THREAD

**Issue by hda42** [lwouis/alt-tab-macos#2210]
I use a Macbook Air M1 and a 32" 4k Monitor with MacOs Ventura. If Im on the go I just use the internal Macbook display.

The Monitor is scaled to 3008x1692
The MacBook is scaled to 1440x900

If I use the Macbook with my Monitor I use the MacBooks display as a mirror for the 32" Monitor, so the macbook display is also scaled to  3008x1692 like the big monitor. (I tried it also as an external Monitor but nothing changed)

The problem is, that Alt-Tab looks with default settings on the Macbook great but when I plugged it in to my big monitor Alt-Tab was way to big. If I adjust the size of Alt-Tab on my monitor to a normal looking size Alt-Tab is way to small if I unplug the Macbook. The Alt-tab icon preview is even bigger on the macbook display when the macbook is connected to the monitor and this although everything else is much too small on the macbook display because  it serves as a mirror. When I unplug my macbook from the monitor everything on the macbook display gets bigger and scaled correctly except Alt-Tap gets way smaller.

I love your support for the app.

Greetings from Germany

**Comment by lwouis** [comment]
Hi @hda42,

Could you please share a picture or two of what this all looks like in practice?

Thank you

**Comment by hda42** [comment]
Here are a few pictures. You can see the alt-tab settings.

from my external Monitor (how it should be):
![monitor-normal](https://user-images.githubusercontent.com/118397088/208170737-224f0710-16be-4cc1-a3d2-cc512965d48a.png)

the macbook display when plugged in to the monitor (macbook display is scaled to 3008x1692). even scaled the preview is bigger compared to unplugged:
![mirror-mac](https://user-images.githubusercontent.com/118397088/208172805-5093bab9-42b2-4cb4-ad7e-5ee6dcb35561.jpeg)

after unplugged the macbook from the monitor:
![macbook-unplugged](https://user-images.githubusercontent.com/118397088/208170887-0eea5edb-b782-43d6-8488-becc076ec8b8.png)

if I set the alt-tab settings for the macbook internal display (different settings)
<img width="1440" alt="macbook-normal" src="https://user-images.githubusercontent.com/118397088/208171001-1d2be05f-b9a4-4ebd-a5b4-b501951fc55b.png">

same settings as above. Macbook plugged in to the external monitor:
![monitor-macbook-settings](https://user-images.githubusercontent.com/118397088/208171186-2a8b949c-7d9c-4ac4-a2d1-61471eff70aa.png)

**Comment by lwouis** [comment]
Watching all these screenshots, I'm really not sure what you would expect from AltTab. AltTab is respecting your setting, and the OS scaling correctly.

It seems you would prefer having 2 sets of settings, depending on the monitor, because you prefer (from your own taste) different ratios on the 2 monitors. This was discussed before by people with a vertical monitor and a horizontal monitor. In that case, it makes sense that the same settings won't work.

To support that, we would need to add full support to multiple monitors. That would mean some kind of list of monitors, remembering all that the macbook got plugged into at some point, being able to select them, and set settings for them, etc. It's doable but a big feature, and would add a lot of complexity to the app UI and the codebase.

I'm afraid this is a bit too niche at the moment. If enough people have the need, it may happen in the future. Just sharing this also so you have the full context: #1179

**Comment by lwouis** [comment]
> Is the app just use the percentage of the screen size?

Yes, there are sliders on your screenshots showing that percentage.

> A solution could be that you can set a specific pixel-size.
> So if I just set a custom width not using a percentage but pixel i guess the problem would be solved for me.

Yes, this was suggested before. I think there is already a ticket for that, but I can't find it right now. It may be an easy solution to get it workable for some setups.

> can I compile the app without Xcode?

You need to install XCode to build any macOS, iOS, tvOS, watchOS, app. You need to install it. After that you don't need to open it to compile the code into the app. You can use the command line `xcodebuild -workspace alt-tab-macos.xcworkspace -scheme Release -derivedDataPath DerivedData`. Anyway, I [documented the steps here](https://alt-tab-macos.netlify.app/contributing). It's very simple actually to compile this app. 2 steps.
