### ISSUE TITLE
Please add faint shadow behind thumbnails in GUI

### ISSUE THREAD

**Issue by eshashoua** [lwouis/alt-tab-macos#2279]
I like the functionality of Alt-Tab, but it lacks a tiny bit of the design polish of MacOS. Could you include an option to turn on slight shadows behind windows in the switcher GUI? HyperSwitch did that before they seemed to fizzle out years ago. 

Thank you for an amazing app! It's immediately a go-to for me.

**Comment by lwouis** [comment]
Hello @eshashoua,

There are already slight shadows behind the app icon, window name, and window thumbnails. They are not as pronounced as HyperSwitch though.

I think it's usable enough as it is, and people tend to struggle more with knowing which window is currently selected, rather than distinguishing individual windows.

That being said, there is probably an argument to increase the shadows on app icons and thumbnails to match the aesthetics of the native app-switcher.

**Comment by lwouis** [comment]
Oh sorry, I got tricked by the shadows on new app icons on Ventura. Actually the native app switcher doesn't have any shadows at all. Neither on the label, nor on the app icon. Some app icons from Ventura have their own white square with shadows, but the switcher itself renders things flatly.

So I'll close this ticket, as I don't see why we would add more noticeable shadows, and diverge from the macOS aesthetics.

**Comment by lwouis** [comment]
I'll also add that the shadows look differently in the native app-switcher (the shadows built into the Ventura app icons, that is; again, the switcher itself adds no shadows) and in HyperSwitch, because both use a light background whereas AltTab uses a dark background.

If I increase the shadows which exist today, with color gray, the difference is barely noticeable. We would need to change their color if we wanted to make them more visible.
