### ISSUE TITLE
Release shortcut should trigger even when other modifiers are pressed

### ISSUE THREAD

**Issue by ialiendeg** [lwouis/alt-tab-macos#230]
When cmd+shift+tab is pressed, and then cmd key is released before shift, the selected app is not activated and selection window cannot be closed, even pressing esc key. Otherwise, If shift key is released before cmd key, the selected app is activated and the selection window closed normally.

Once the problem is triggered and while the selection window cannot be closed, using cmd+tab or cmd+shift+tab makes the app working normal again (of course, if using shift, releasing cmd in wrong order triggers the problem again).

**Comment by lwouis** [comment]
I keep being amazed by how complex keyboard shortcuts can be. [See when I discussed with the ShortcutRecorder main maintainer](https://github.com/Kentzo/ShortcutRecorder/issues/117).

I'll look into this. It's important to keep in mind that in your case it's `cmd-shift-tab` but someone else can add more modifiers for the `hold` shortcut, and add different ones for the `previous-window` shortcut, for example `cmd+ctrl` for `hold` and `shift-alt-tab` for previous window. In which case, the behavior becomes even trickier on how the keys should be released and what different things can/should happen upon release of each key

**Comment by ialiendeg** [comment]
I see how tricky is keyboard handling, at least it's not a critical issue.

Meanwhile I discovered that, when the issue is triggered, I can press and release cmd key so the selection window is closed and the active window is selected correctly.

**Comment by lwouis** [comment]
ShortcutRecorder only support exact matching, not "shortcut contains these keys". Note that this issue only applies because our shortcut is modifiers-only. I made a workaround in AltTab to support this use-case, as it would be a lot longer and more involved to ask ShortcutRecorder to incorporate this feature. I asked last time, but the maintainer was limited on time, and was already generous enough to implement the exact matching for modifiers-only, which made adoption possible for AltTab!

Anyway, I tested locally, and the workaround seems to work. Please let me know if that fixes it for you. I hope it doesn't break shortcuts on non-US keyboard layouts, or other corner cases, as some shortcut matching is now done by AltTab instead of ShortcutRecorder.

**Comment by ialiendeg** [comment]
Yes, it's fixed for me too. Alt-tab is getting better every day :)
