### ISSUE TITLE
Mouse hover selection index wrong in 2.53.*

### ISSUE THREAD

**Issue by jediwade** [lwouis/alt-tab-macos#2326]
Starting with 6.53.0, there seems to be a disconnect between the thumbnail you AltTab to vs what app window gets activated when using mouse hover to select app window and then releasing CMD key to activate selection. Using the mouse to hover selection and then clicking to activate the app window works as expected.

Running macOS Ventura 13.1. MacBook Pro 13", Intel, 2 external displays (4k + 1080p).

I don't know Swift, but I wanted to take a guess at where the error is to try and help. In src/logic/Windows.swift on line 117, you have:

`let index = fromMouse ? hoveredWindowIndex! : focusedWindowIndex`

Is the exclamation point at the end of `hoveredWindowIndex` correct?

**Comment by lwouis** [comment]
Hi @jediwade,

The issue was fixed with v6.53.1. However, there is indeed a change in behavior, very much intentional. If you check the "Select windows also with: mouse hover" in the Preferences > Controls, it will sync keyboard and mouse-hover selection. If you don't, which is the default for new users/installs, there will be 2 different UI for keyboard and mouse-hover, with different semantics. The goal is to mimic the way Windows 10 does. Please see the videos I recorded back at the design stage here: https://github.com/lwouis/alt-tab-macos/issues/2078#issuecomment-1303983097

Thank you
