### ISSUE TITLE
Preferences window and panel positions get messed up when switching between tabs

### ISSUE THREAD

**Issue by DaVince** [lwouis/alt-tab-macos#233]
This issue is a little difficult to describe in a single sentence. Let me demonstrate it instead:

https://youtu.be/YmGSY0lGJXY

Basically, a few things seem to happen:
* When switching between the tabs, the wrong window size is sometimes used, possibly from switching too quickly between tabs and it using the previous window size instead.
* The Updates and About tabs tend to be empty when I click them. Sometimes they will pop in after a second or so.
* When switching from Updates to Appearance, sometimes the Appearance panel will be entirely empty, and sometimes the window size stays at the old size.
* The contents of the panel sometimes get displaced.

I use Mojave 10.14.6 on a retina display with AltTab 3.7.3.

One easy solution to at least one of the problems, I think, is to always keep the window the same size on all of the tabs.

**Comment by lwouis** [comment]
Hi @DaVince! Thanks for sharing this crazy behavior with us! That's pretty wild stuff.

On my machine is switches correctly, and importantly without any fading animation. I thought it wouldn't animate for anyone since it didnt for me

This panel is a complete mess. I mentioned in another ticket how this preference panel is actually pretty complex and non-intuitive at the code level. I think i'll replace with some preferences panel from cocoapods i saw a few months ago

**Comment by gitgetgot** [comment]
Hi, just want to say, I have exactly the same issues w/ AltTab 3.7.3 and Mojave 10.14.6 (18G4032)

**Comment by lwouis** [comment]
@DaVince @gitgetgot I just released a new version that uses the Preferences cocoapod (see [previous discussion about integrating this pod)](https://github.com/lwouis/alt-tab-macos/issues/179#issuecomment-599487607). Hopefully the new version works properly on Mojave.

Could you guys update and share here if it's fixed for you now? 👍

![image](https://user-images.githubusercontent.com/106195/79683748-11cb4d00-8267-11ea-9430-8987556d29ee.png)

**Comment by DaVince** [comment]
The new preferences code works beautifully, thanks so much!

**Comment by gitgetgot** [comment]
Works like a charm now. Thank you!
