### ISSUE TITLE
MacOS theme with border and shadow

### ISSUE THREAD

**Issue by maciej-skurznica** [lwouis/alt-tab-macos#2340]
I would love to see a border around the switcher be the same as all other windows borders within macOS. When I am on a dark background it is hard to distinguish the switcher from the rest.
See pictures:
[https://drive.google.com/file/d/1CjHp-jxQGn92Lc39v-XJfrlG-R8w2qUY/view?usp=share_link](https://drive.google.com/file/d/1CjHp-jxQGn92Lc39v-XJfrlG-R8w2qUY/view?usp=share_link) [https://drive.google.com/file/d/1brT5hHyWAU_K6c4OkhtbQBCtZTocMKRE/view?usp=share_link](https://drive.google.com/file/d/1brT5hHyWAU_K6c4OkhtbQBCtZTocMKRE/view?usp=share_link) [https://drive.google.com/file/d/10Lm4MtLlGmUiDw8Fpv1HjmN2_FC5meXr/view?usp=share_link](https://drive.google.com/file/d/10Lm4MtLlGmUiDw8Fpv1HjmN2_FC5meXr/view?usp=share_link)

The best scenario solution will be to have another theme from the themes dropdown which will be exactly the same as the current macOS but with border and shadow.

Alternatively, just a border will be just fine.

**Comment by lwouis** [comment]
AltTab is matching the looks of the native app switcher. It doesn't have a border or a shadow.

In the last release, we've added a white border around thumbnails. Does that not make it clear for you to see, with the high contrast? If you don't have it activated, you can do so in `Preferences > Controls > Select windows also with: Mouse hover`

**Comment by bbbush** [comment]
Just .02 -- Native app switcher has a wide margin which makes the active icon apparent. Native app switcher also does not show thumbnail. Alt-tab has a narrow margin. The thumbnail in Alt-tab blends so well with the application displayed in the background, because they are the same color and style. Without the margin and the contrast between the highlighted icon and background, it is a usability problem. It is difficult to find where things start and where the active icon is. Thanks!
