### ISSUE TITLE
Close window with cmd+q on hover

### ISSUE THREAD

**Issue by ChristianMichelsen** [lwouis/alt-tab-macos#235]
Hi, 

First of all, I wanna say thank you very much for building this great tool! 

I was wondering if it was possible to implement the ability to close a windows with cmd+q when hovering over that window with a cmd+tab? Like cmd+tab+tab+q to close the second window open and so on, similar to how it is implemented in the "normal" cmd+tab from Apple. 

Cheers,
Christian

**Comment by lwouis** [comment]
Hi @ChristianMichelsen! We have already a ticket for that (and more!): #9. Note that the original ticket mentions `cmd+w` to close windows and `cmd+q` to close the window's app. However, since then, we have integrated custom shortcuts, so you will be able to map closing window to `cmd+w` with ease.

Please follow the other ticket. I think it will be released within a month 👍

**Comment by ChristianMichelsen** [comment]
Thanks a lot, thought I had looked through the open issues but apparently not thoroughly enough. Thanks a lot for the quick response!
