### ISSUE TITLE
No Finder thumbnail even if `Hide apps with no open windows` is turned off

### ISSUE THREAD

**Issue by ris58h** [lwouis/alt-tab-macos#2361]
**Describe the bug**

I have `Hide apps with no open windows` setting turned off and I expect Finder thumbnail to be in the list but it's missing.

**Steps to reproduce the bug**

1. Turn off `Hide apps with no open windows`.
2. Close all Finder windows.
3. Activate AltTab's UI.

**Your environment**

* AltTab version: 6.54
* macOS version: Ventura 13.2.1

**Comment by lwouis** [comment]
Hi,

Most users don't want to see the Finder when there are no open windows, because that's most of the time.

In order to get this good experience, but also let power-users see Finder if they prefer, we have used the Blacklist preferences, and added Finder by default there:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/106195/220674879-5f1a43d8-7d48-4987-8a86-15978dd92e14.png">

Please customize the blacklist to your liking. You may want to remove that row for instance

Thank you
