### ISSUE TITLE
Update from 3.2.1 to 3.7.3 => App does not start

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#240]
today I update from 3.2.1 to 3.7.3 but now the app doesn't start at all... :-(

I delete the App and all associated files with the app AppCleaner and install AltTab 3.7.3 fresh, but that didn't help either, the app doesn't start for me anymore. :-(

**Crash Report:**

Process:               AltTab [13993]
Path:                  /Applications/AltTab.app/Contents/MacOS/AltTab
Identifier:            com.lwouis.alt-tab-macos
Version:               3.7.3 (3.7.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           AltTab [13993]
User ID:               501

Date/Time:             2020-04-14 14:41:18.854 +0200
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:       ######################

Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [13993]

Dispatch Thread Soft Limit Reached: 64 (too many dispatch threads blocked in synchronous operations)

Application Specific Information:
Performing @selector(callClosureWithSender:) from sender AltTab.UnclearableRecorderControl 0x7fe689c140d0

**Comment by mrc247-DE** [comment]
same problem as the last update attempt. The settings were the problem. After deleting, see below, the app starts again.

**defaults read com.lwouis.alt-tab-macos**
{
    "NSStatusItem Preferred Position Item-0" = "443.2734";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-14 13:03:32 +0000";
    cancelShortcut = "\\U238b";
    holdShortcut = "";
    nextWindowShortcut = "\\U21e5";
    preferencesVersion = "3.7.3";
    previousWindowShortcut = "\\U21e7\\U21e5";
}

**defaults delete com.lwouis.alt-tab-macos**

**defaults read com.lwouis.alt-tab-macos**
{
    "NSStatusItem Preferred Position Item-0" = "442.3008";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-14 13:17:07 +0000";
    arrowKeysEnabled = true;
    cancelShortcut = "\\U238b";
    hideSpaceNumberLabels = true;
    holdShortcut = "\\U2318";
    nextWindowShortcut = "\\U21e5";
    preferencesVersion = "3.7.3";
    previousWindowShortcut = "\\U21e7\\U21e5";
}

**Comment by lwouis** [comment]
I see you had this preference: `holdShortcut = ""`

There was a bug introduced in 3.6.0 (5b0341539c3e12fe7726de18104e871276c85c98) which would let the user clear the main hold shortcut. You could click on the shortcut to customize it, and press `delete` which would empty the shortcut. That would later trigger crashes on boot since the shortcut shouldn't be null.

I noticed this the day after releasing 3.6.0, and released 3.6.2 which doesn't let the user press the `delete` key anymore to clear the main shortcut; only the individual shortcuts like "Select next window".

It seems that you downloaded 3.6.0 during that 25h period before 3.6.2 was out, and cleared the shortcut. As you mentioned, deleted the preferences resets them to valid values and fixes the issue.

Sorry about the bug! I'll close the ticket as the issue was fixed in 1158a321265fbbc2174a96cf922a58c3231caae8
