### ISSUE TITLE
Preview option can create screen flickering when switching windows

### ISSUE THREAD

**Issue by OoguroxRyuuya** [lwouis/alt-tab-macos#2432]
**Describe the bug**

Flickering screen when switching windows

**Screenshots / video**

https://user-images.githubusercontent.com/61595521/227412201-8728ef4a-7e02-48ad-8df7-41396ab3c090.mp4

**Steps to reproduce the bug**

1. CMD + TAB

**Your environment**

* AltTab version: 6.56.0
* macOS version: 13.2.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

![CleanShot 2023-03-24 at 10 53 43](https://user-images.githubusercontent.com/61595521/227412294-19d9e36e-a6c6-4e57-af24-3652e47c3824.png)

***Preview selected window ticked.***

**Comment by lwouis** [comment]
I downloaded the video and looked frame-by-frame to understand. This happens because the preview, which is an image of the target window, is first removed, then the real window is focused.

If we want to avoid this, I think we would need to first bring up the real window, and *then* remove the image that should now be behind it.

It's probably possible, but seems complex to me, because when we ask the OS to focus the real window, it may take a few seconds to do so, so we would need to keep the preview window for that long. But what if the user re-opens AltTab and does other things in the meanwhile? And the window may block user interaction on screen as well.

@decodism do you think there is a way to reduce the visual flickering here? I just checked how it goes in HyperSwitch, and somehow they made it really smooth every time :o
