### ISSUE TITLE
Show preview: Add delay

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#2456]
Possibly add a delay to the "show preview of window" option. In Windows 10, there is a ~1s delay before showing the live preview, where the cursor has to stay focused on the window thumbnail. The same feature could be implemented.

**Comment by lwouis** [comment]
Hi @XInTheDark,

I like the idea, but I think it's yet another preference slider. There are already too many (see #351).

Do you see a way to handle this without having another slider in the preferences?

Thank you

**Comment by XInTheDark** [comment]
Hmm, the best method I've considered so far is only showing a slider/text box when the option is checked. Would that be neat enough to make it into the preferences pane?

**Comment by lwouis** [comment]
It's better for sure. My worry is that we can always add more sliders and niche preferences. It's way harder to cut them out, and decide what is worth having as a preference, and what is probably best hardcoded and be satisfying for 99.9% of users.

**Comment by daybreaker** [comment]
I like the idea of copying the VSCode settings.json for advanced options.

Would it be too much of a cop out to just have some basic options that most people will need in Controls/Appearance, and then an expandable/collapsible "Advanced Settings" section at the bottom of each one?

**Comment by lwouis** [comment]
Hidding some "advanced" settings somewhere where only serious users would dig for it is a legitimate approach to serve both casual and serious users. An issue though, is that is doesn't reduce the complexity of *supporting* all the various settings and their combinatory explosion.

Take a look at the [various scenarios that AltTab is engaged in](https://alt-tab-macos.netlify.app/contributing#list-of-use-cases). It's really easy to forget interactions between the numerous part of the operating system, and AltTab, and other apps, and Mission Control, and the Dock, and accessibility features, and login/logout, etc.

So yes, advanced settings have been considered, but I would like overall to reduce the amount of settings, because settings are complex to maintain at *every* level, including making sure they don't break over time with the new macOS releases, other code changes, new features of macOS, etc.

See the rich discussions in #351

**Comment by daybreaker** [comment]
Thanks for the reply! I'll check that issue out. 

I just found this app and its fixed the biggest "minor annoyance" I've had on MacOS. So thanks for all the hard work you've put in on it!

**Comment by angusjoshi1** [comment]
+1 on this issue. I just installed alt-tab today for the first time and thought this as well immediately.
