### ISSUE TITLE
Can't get "show standard tabs as windows" to work

### ISSUE THREAD

**Issue by nathanielvirgo** [lwouis/alt-tab-macos#2511]
**Describe the bug**

I can't get tabs to show up as windows in Chrome, Safari or preview.

This is with "show standard tabs as windows" enabled in the preferences under appearance. I'm assuming that with this enabled I should see a separate thumbnail for each tab. (But maybe this option does something else? If so I guess this is a UX bug.)

**Steps to reproduce the bug**

1. Go to 'Appearance' in the preferences menu
2. Ensure "Show standard tabs as windows" is enabled
3. Open a bunch of tabs in any app, in the same window. (I've tried Safari, Chrome, Preview.)
4. Hit option-tab.

My expectation is that I will see thumbnails for each of the tabs in the window, but in fact I only see the frontmost tab.

**Your environment**

* AltTab version: 6.55.0
* macOS version: 12.6.1

**Comment by lwouis** [comment]
Hi,

The preferences says "Show **standard** tabs as windows". A standard tab is when the app uses standard macOS technology to draw a tab. That's what Finder or Terminal do for example.

Web browsers draw custom tabs. They do it for security reasons (1 tab = 1 process), aesthetics (tab is very compact), and other reasons. As a result, AltTab and other accessibility apps can't interact with these custom tabs.

For Preview, I'm not sure if the app uses custom tabs, or if you're facing this issue: #1324 

Thank you

**Comment by nathanielvirgo** [comment]
Ok, fair enough. I don't think the term "standard tabs" is very clear from a user perspective but don't have a better suggestion.

Witch can show tabs as windows for Safari and Chrome, so I guess it's not completely impossible to interact with them. I've no idea how it does it though.

**Comment by lwouis** [comment]
> Ok, fair enough. I don't think the term "standard tabs" is very clear from a user perspective but don't have a better suggestion.

The UX could definitely be improve. Many users don't notice the word "standard" and even if they did, no-one could reasonably guess what's behind it. It could definitely be improve. However: #1179 

> Witch can show tabs as windows for Safari and Chrome, so I guess it's not completely impossible to interact with them. I've no idea how it does it though.

We can use the accessibility API to do custom parsing and try to grab the tabs for web browsers. However, it would mean custom code/support for each app we do that for. It's initial effort + maintaining the custom code through UI changes of these apps. Furthermore, there are some things that are technically impossible. If I remember correctly, for example, Chrome doesn't render its tabs when there are not active. This means that there would be no way for AltTab to draw these tabs thumbnails. The best we could do is remember them after the user has made them active once. I just downloaded Witch and tested, and indeed it's full of issues with these. Can't show thumbnails of some tabs, even some windows (e.g. minimized).

I've been working on AltTab for 3 years, and I can guaranty you that it has the best support of any app on the market, free or commercial, regarding these kind of things. And it's not perfect, nor can it be, because macOS doesn't have public APIs for us to do the features, so we use private APIs, SPIs, and clever tricks. But when the apps are making custom tabs (i.e. pixels that are tabs to the user, but that are not built using standard macOS window APIs), there is nothing we can do in some aspects. There are also the practicality of having no-one here with time to implement custom code for every non-standard app out there. A commercial company could justify doing that. It's harder for us because we have very few contributors. It's basically me, and some nice but rare contributions by 2 people, over the years.
