### ISSUE TITLE
Why do you use kCGHeadInsertEventTap?

### ISSUE THREAD

**Issue by gnachman** [lwouis/alt-tab-macos#2537]
Hi,
I'm the developer for iTerm2. I'm trying to fix a bad interaction between iTerm2's modifier remapping feature and AltTab.

A user reported that when he swaps option and command in iTerm2, AltTab will show its UI but not hide it upon releasing the modifier.

https://gitlab.com/gnachman/iterm2/-/issues/10220

I don’t know whether iTerm2 should change to register at the head or if it would make more sense for AltTab to add itself at the tail. I know it's been a few years but do you recall the motivation for using `kCGHeadInsertEventTap` in the call to `CGEventTapCreate`?

**Comment by lwouis** [comment]
Hi @gnachman,

I don't think the solution to the issue lies with the point of insertion of the event tap. Users can always launch their apps in various orders, thus the order of the taps can't be guaranteed. It's especially true of apps that are launched at login. These are launched in parallel, so it's random which one is going to run first.

It seems to me here that the root cause is that iTerm2 event listening is disruptive. Global keyboard listeners can really mess with the user experience. They are trying to hit a local shortcut in an app, and another app which is globally listening may intercept the input and mess things up. Thus apps which listen to global events should be careful not to alter events which are not targetted at them.

In the scenario described in the iTerm2 ticket, it doesn't look like iTerm2 has any reason to intercept the keyUp event. I'm an iTerm2 user, so maybe I'm missing an interaction here? I tried to reproduce the issue, but I can't follow the step-by-step from the gitlab ticket. I don't understand where I need to go in the preferences to do these steps:

> Configure iTerm2 to:
> 
> 1. swap the `command` and `option` keys
> 2. set `Do Not Rempap Modifiers` for command-tab

Could you help me understand: why does iTerm2 alter keyboard events in the scenario? It seems to me that if the user is not trying to interact with iTerm2, then iTerm2 shouldn't alter globel events, no?

**Comment by gnachman** [comment]
Thanks for the thoughtful response and I'm sorry for the delay in getting back to you.

The reason iTerm2 uses event taps is so that certain keystrokes can be rebound *while iTerm2 is active*. For example, if the user swaps cmd and option, that should affect keystrokes like cmd-tab. The reason for intercepting keyUp (as well as FlagsChanged) is to provide consistency to any other app that's receiving the keystrokes. If another app sees cmd-x down and opt-x up, it'll be confused.

I don't believe that AltTab itself will ever be the active app in normal use since it enables LSUIElement in its Info.plist.

The settings in question are here:

<img width="897" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/427546/3ee605f6-8bbb-4171-bf91-d3f572a8c9f9">

<img width="1023" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/427546/0addeec8-08ee-4757-97af-d04a7d5d2720">

I don't know why I haven't been able to reproduce this locally, but the logs don't lie and the reason makes sense to me.

I think you're right that registration order ends up being random when the user logs in. If I were really confident that I wanted to be first I could re-register for the event tap each time iTerm2 is activated. The downside is breaking who-knows-what.

**Comment by lwouis** [comment]
I'll close the ticket for now. I think I've helped what I could. Good luck with this issue. Don't hesitate to ask more questions if you still have some 👍
