### ISSUE TITLE
Right click on app icon not working

### ISSUE THREAD

**Issue by ftorelli165** [lwouis/alt-tab-macos#2546]
Right click is now blocked by the preview window. It looks like it's attempting to open, stutters, but can't get it to open.

**Steps to reproduce the bug**

1. Right click on open app

**Your environment**

* AltTab version: 2.8
* macOS version: 13.2.1

**Comment by lwouis** [comment]
Hi,

I'm not exactly sure what you mean. This is what I understand from your message:

* You have activiated the Preview feature in Preferences > Appearance (last checkbox at the bottom)
* You hit alt+tab to bring AltTab on screen
* The previous window is now previewed on top of any other window
* While still holding alt, you attempt to right click on this previewed window
* You expect here that the right click is received by the window, but instead nothing happens (since the preview is an image)

If I understood correctly, then this is a technically limitation. You could solve your issue by doing one of those things:

* Disable the Preview feature
* Focus the window, *then* right click it

Closing the issue as this behavior is both a technically limitation, as well as pretty niche behavior/need.

**Comment by ftorelli165** [comment]
Sorry, I'm referencing DockAltTab, not AltTab. In DockAltTab in this latest 2.8 update when I right click on a dock icon of an open application that have a DockAltTab preview the system menu of app options that includes quitting the application will not show. It appears that the DockAltTab window preview is blocking this system menu from opening.
