### ISSUE TITLE
The app breaks full-screen windows

### ISSUE THREAD

**Issue by Venegrad** [lwouis/alt-tab-macos#2559]
The app breaks full-screen windows. For example games, if you take the game Dota2, and when it's in full screen mode it grabs the cursor, if you alt-tab, the cursor stops being grabbed by the application until you restart it.

* AltTab version: 6.58.0
* macOS version: 13.4 Ventura

https://github.com/lwouis/alt-tab-macos/assets/9676703/8e71b285-3811-4aeb-9a37-d13fc870d9b2

**Comment by lwouis** [comment]
This looks like a bug with Dota 2. Is there any other app that does this for you? On my computer, no app has this issue. It's the first time someone brings this up in 3 years, so I'm assuming the issue lies with the macOS Dota 2 client implementation. If only Dota 2 has the issue, could you please contact their customer support?

Thank you 🙇

**Comment by lwouis** [comment]
The default option+tab switches to an app, not a window. So there are differences for sure. AltTab could switch to the app and there would be no issue. But we have to focus a window, and that's really hard. Today we use a private API and private SPI to achieve that. It's really lots of effort over the years from other project and this one to retro-engineer macOS, and manage to do it. The public API don't let us do it, actually.

Potential new tricks we could pull are discussed in this big ticket: [#focuswindow](https://github.com/lwouis/alt-tab-macos/issues/447)
