### ISSUE TITLE
DockMate

### ISSUE THREAD

**Issue by jimmysmits** [lwouis/alt-tab-macos#2569]
**Description**

I am using DockMate (https://www.macenhance.com/dockmate) in combination with AltTab macOS. DockMate shows a preview of an open app by hovering over the dock. AltTab macOS shows this preview (LargePreview) as an additional screen in the overview of active screens, effectively duplicating an application (it is always the last shown preview). For now I've added this in the Blacklist manually, but maybe worthwhile to look if this can be fixed or maybe include it in the default list (com.macenhance.dockmate). If you think it is not worthwhile you may close this ticket 😄 

<img width="584" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/61211859/0fe90ab4-1a90-4e7e-9f45-51b9f36c55ae">

**Screenshots / video**

See attached image (blurred out some private details)
![SCR-20230606-koe](https://github.com/lwouis/alt-tab-macos/assets/61211859/aa8205cc-475e-41e4-b701-dca06ea732e3)

**Your environment**

* AltTab version: Version 6.59.0
* macOS version: 13.4

**Comment by lwouis** [comment]
Thank you for sharing this issue.

AltTab shows you these windows because they are coded as windows by DockMate. The correct fix, I believe, is that DockMate fixes this. These previews should be popovers or HUDs, not standard windows.

This probably affects other apps and things like Mission Control. DockMate should fix their implementation. I advise contacting their customer support 👍
