### ISSUE TITLE
Custom arrangement of apps, or renaming for alphabetical sort

### ISSUE THREAD

**Issue by eshoyfer** [lwouis/alt-tab-macos#2688]
Requesting a way for custom arrangement of apps, or a filter for renaming how apps are internally treated within AltTab for alphabetical sort. 

While this is useful for its own sake (allowing the user that level of flexibility — a dock-like permanence of structure), this feature request is directly intended to resolve a bug or issue that arises with some programs. In particular, Adobe has made a slight mistake when packaging its software for Mac, and the internal representations are some apps are inconsistent. While Photoshop and Illustrator are sorted by the names "Adobe Photoshop 2023" and "Adobe Illustrator 2023", respectively, InDesign is known simply as "InDesign". It's frustrating since clearly the intent for alphabetical order is to facilitate a breezy headspace where all Adobe apps are in their own cluster. Instead, they are segmented for no reason, and there's no way to force them together. Instead of necessitating a hack at the OS-level, it would be much more comfortable for AltTab to allow custom internal aliasing or, even better, an order override or custom order mode. 

<img width="1049" alt="Screenshot 2023-07-23 at 9 27 37 AM" src="https://github.com/lwouis/alt-tab-macos/assets/5425118/78318578-a6f9-4047-ab07-69235a936fe9">
<img width="1043" alt="Screenshot 2023-07-23 at 9 28 04 AM" src="https://github.com/lwouis/alt-tab-macos/assets/5425118/fb836850-6f18-4c22-bdee-5e6a48152d2b">

**Comment by lwouis** [comment]
I'm afraid this type of workflow is too niche: too few users would use this regularly.

Another issue is that Windows are volatile. We can't "remember a window" since nothing about it is unique. 2 windows can have the same parent app, the same title, the same dimensions, etc. When windows are created, they get assigned a random ID, and if closed then re-opened, the ID is different.

I think your main issue here is with Adobe suite not being consistently named. I think this lies with Adobe to fix. I suggest contacting their Customer Support 👍 

Thank you
