### ISSUE TITLE
Add an option to switch between windows of current stage in stage manager

### ISSUE THREAD

**Issue by shahzaibkhalid** [lwouis/alt-tab-macos#2696]
**Is your feature suggestion related to a problem? Please describe.**
While using Stage Manager, with Alt-tab,  there is no way to tab-through windows of current screen as `visible spaces` option doesn't consider just the windows in the current stage of stage manager.

<img width="590" alt="Screenshot 2023-07-25 at 4 22 55 PM" src="https://github.com/lwouis/alt-tab-macos/assets/18225515/b2cc395c-6329-4c73-b7ac-f11f517ec42e">

**Describe the solution you'd like**
 I wonder if `Visible spaces` or any similar option would only allow to switch between windows of current stage?

**Describe alternatives you've considered**
I know we can do that using `cmd +`` but its rather convoluted and doesn't show an app switcher.

**Comment by lwouis** [comment]
Stage Manager is not supported. There are no APIs to support it we could use. It also break AltTab basic functionality of showing thumbnails since they get skewed when Stage Manager is enabled. Again, nothing we can do technically about it.

AltTab let's you narrow down windows of a given Space or given Screen. It can't narrow down to windows of a given Space Manager "stack", as I said above. There are no APIs for us to implement that. There is not a single Stage Manager API available to us to interact with this new system.
