### ISSUE TITLE
How did you add your app into System Settings -> Privacy and Security -> Accessibility ?

### ISSUE THREAD

**Issue by ukushu** [lwouis/alt-tab-macos#2714]
I have tried to read your code ( SystemPermissions.swift ), but didn't found any code that is related to add AltTab into Accessibility apps list?

Can you help me to find solution inside your code?

PS: I have updated ukrainian localisation, please include it into your next release

**Comment by lwouis** [comment]
Hi @ukushu,

I believe `AXIsProcessTrustedWithOptions` triggers 2 things:

* It adds the app to the list of apps but the toggle is off
* Prompts the user to authorize the app, which switches the toggle on if accepted

The localization will be shipped in the next release 👍 

Thank you

**Comment by ukushu** [comment]
Problem is I'm already using AXIsProcessTrustedWithOptions for a year time period and it does not add app to the list, just check that accessibility is granted =(

**Comment by lwouis** [comment]
@ukushu this is the API to do it. If it doesn't do it, it may be because of another concern.

* It could be that your app is not signed, so between builds in XCode, the permission doesn't persist, since technically you're building a new app everytime.
* It could be a bug with macOS or XCode
* It could be because of some other environment factor

Try to Google it. There are many people like you having exotic issues. You may find someone finding the solution to the same issue as you 👍

**Comment by lwouis** [comment]
Try to bring your codebase to another machine, and it will work, most likely. It's likely some bug in your current environment. I suggest playing with resetting permissions via the command line, and signing your app if it's not already signed.

**Comment by ukushu** [comment]
Found the reason of issue, but still have no ideas how to fix it.

The reason why it does nothing is: Sandbox enabled. 

In my case it just do nothing instead display of request popup.  ( This one: https://i.stack.imgur.com/0SOHU.png )

How did you get ability to work `AXIsProcessTrustedWithOptions` when sandbox enabled?

**Comment by LZhenHong** [comment]
I run into the same issue.

Fix this by [Remove Sandbox][https://stackoverflow.com/a/59752583/5350993].

Just in case if someone else finds this discussion like me, they can try this solution.
