### ISSUE TITLE
Hide apps with no open window doesn't work

### ISSUE THREAD

**Issue by lukejames1111** [lwouis/alt-tab-macos#2767]
As the title suggests. Enabling "Hide apps with no open window" doesn't do anything. I still get Finder in CMD + tab even though this option is selected. Tried updated, restarting, etc, nothing works.

MacOS version: 13.4
AltTab version: 6.61.0

**Comment by lwouis** [comment]
Could you please share a screenshot of the preferences and another screenshot of the windows you see in AltTab?

Thank you

**Comment by jrogov** [comment]
I'll add my 2 cents if noone minds.

I've just upgraded from 6.31.0 to 6.61.0 (via homebrew) to use new "Window Order" feature.

And it seems that something broke, perhaps because of the addition of "Hide apps with no open window" (also, how should it be different from "Show window from: Visible Spaces"?).

I have two shortcuts: Alt for global (all spaces) and Cmd for local (visible spaces), and they behaved similarly until I toggled "Hide apps with no open window" (which is not desirable, since I can't have global shortcut anymore).

And funnily enough, as I was trying to screenshot the behaviour, it fixed itself. Now I'm able to use it as I intended to (all and visible spaces shortcuts).

Perhaps some bad config migration..? Just guessing, I'm not aware of internals at all.

I'll post screenshots or additional info if I encounter it one more time.

**Comment by lukejames1111** [comment]
All it does is show that "Hide apps with no open window" is ticked, and that it still displays in CMD+tab.

![image](https://github.com/lwouis/alt-tab-macos/assets/66020346/e4ab82ab-0932-409b-aa07-c38e5b6e636e)

**Comment by lwouis** [comment]
@lukejames1111 

Could you please share a screenshot of what AltTab displays when you summon it? You can use the Screenshot.app built-in app and set a 5s timer for example, to screenshot AltTab being opened.

@jrogov 

> And it seems that something broke, perhaps because of the addition of "Hide apps with no open window" (also, how should it be different from "Show window from: Visible Spaces"?).

I think you're mistaking what "Hide apps with no open window" does. It hides the app icons when you have an app open but it has no open window. For example launch Safari, then close its window. It will still be running (e.g. dot under the icon in the Dock) but doesn't have any open window. At this point, AltTab will show "Safari" and the Safari icon, in the list. If you don't want to display that, you can check the preference "Hide apps with no open window".

You mention having issues with Spaces. There is a high chance you're seeing symptoms of #1324.

**Comment by lukejames1111** [comment]
@lwouis I've fixed it. The shortcut was set to option + tab, not CMD + tab!
