### ISSUE TITLE
Thumbnails have unnecessary padding at the bottom

### ISSUE THREAD

**Issue by linkot** [lwouis/alt-tab-macos#277]
![2020-04-25_16-00-21](https://cdn.jsdelivr.net/gh/linkot/image/img/2020-04-25_16-00-21.jpg)

**Comment by linkot** [comment]
![2020-04-25_16-05-47](https://user-images.githubusercontent.com/59691364/80274666-b4c01300-870e-11ea-8400-ee96f9b41781.jpg)
😕

**Comment by lwouis** [comment]
Hi @linkot! I gather from your question marks that you think there is an issue with the layout of the UI.

First, I think it is important for the discussion that you understand the [current layout logic](https://github.com/lwouis/alt-tab-macos/issues/256#issuecomment-616763733). The current layout logic has fixed height for the thumbnails, so that users can expect them to be at a certain position constantly.

If you would prefer a different logic for layout, could you please elaborate it here in a nice detailed fashion, so that it's possible for us to discuss its benefits over the current approach, and importantly, so that someone can work on implementing it, if it is indeed an overall more appealing proposition

**Comment by linkot** [comment]
> Hi @linkot! I gather from your question marks that you think there is an issue with the layout of the UI.
> 
> First, I think it is important for the discussion that you understand the [current layout logic](https://github.com/lwouis/alt-tab-macos/issues/256#issuecomment-616763733). The current layout logic has fixed height for the thumbnails, so that users can expect them to be at a certain position constantly.
> 
> If you would prefer a different logic for layout, could you please elaborate it here in a nice detailed fashion, so that it's possible for us to discuss its benefits over the current approach, and importantly, so that someone can work on implementing it, if it is indeed an overall more appealing proposition

I don't speak English, I use Google Translate.
I think the height of each thumbnail should be the same, just like a window computer.
There shouldn't be a large area under the thumbnail.
Maybe it can be centered?
![2020-04-25_21-50-15](https://user-images.githubusercontent.com/59691364/80281617-084a5500-873f-11ea-9878-5bb848714b67.jpg)

**Comment by lwouis** [comment]
Hey @linkot, did you read the explanations by following the link I provided? 😅

It explains why the UI is the way it is.

The logic is different from Windows 10. In Windows 10, the thumbnails get smaller as more rows are displayed.

With AltTab, the thumbnails have a fixed height, so that the user can locate them easily.

You can customize the sliders in the preferences, if you want to get rid of the the extra padding.

**Comment by linkot** [comment]
@lwouis Thank you,Solved my confusion

**Comment by lwouis** [comment]
@linkot if you are satisfied with this, could you please close the ticket?

If you think the thumbnails layout could be improved, then we would need a detailed description on what the new design would look like, what the logic would be, and why it is better than the current solution.

**Comment by linkot** [comment]
@lwouis  
Just like this, the thumbnails are centered. Instead of leaving blank at the bottom. It is more visually comfortable around.
This question can be closed, thank you.
![2020-04-26_18-12-56](https://user-images.githubusercontent.com/59691364/80304699-4781b000-87ea-11ea-8c68-17029cfed075.jpg)

**Comment by mfn** [comment]
>  I think the height of each thumbnail should be the same, just like a window computer.

I also struggle with this, eventually accepting it because I've no idea how to bring this up properly.

Windows 10 or HyperSwitch (more important here to me 😄 ) work that way, thumbnails are the same height.

Using same width / different height as AltTab creates a kind of "visual noise" to me, I look at the screen and it feels "disorganized" because every thumb is slightly different: Like my room is not clean up but in chaos and my mother yells at me to fix this. But there's nothing to fix, it's by design. Makes me cry 😄 

AltTab has no clear grid to me, hence the "noise" I'm seeing. There's only "rows" which match, but there are no columns.

I look at HyperSwitch, it's so much cleaner: there is a clear grid, every thing is perfectly squished into a regular grid of rows and column. This is "organized" to me and _much much_ easier to "locate stuff with my eyes" (the **primary** reason for me to use such a tool).

But what to do with the feedback? Too much options create complexity and I certainly don't want to see a flag in AltTab providing different layouts, that would be a hell to maintain (especially for a single person, I can imagine).

(sorry I resized the screenshot to mask my private stuff)

Screenshot HyperSwitch aka "neatly organized"
![Snip20200427_24](https://user-images.githubusercontent.com/87493/80415008-2c8a6b00-88d2-11ea-9f30-c27438ba46fe.png)

Screenshot AltTab aka … 
![Snip20200427_20](https://user-images.githubusercontent.com/87493/80414935-12e92380-88d2-11ea-9b5e-e69e5182d668.png)

I get the pro arguments for the AltTab rendering: they're more details, better match the shape.

In all my years (probably totally biased and trained and thus simply used to) it's just not an issue.

To quickly locate information, I need it organized ("grid"), not uneven shapes in rows 🤷‍♀️

(ps: this is not a rant: I primarily use AltTab because I absolutely value it and your outstanding fantastic work on this, you know that!)

**Comment by lwouis** [comment]
@mfn actually on the complexity of maintaining an alternate layout, it could be reasonable. I can imagine 2 functions/classes to contain the variations and make it clear for readers. It would introduce yet another preference though. Recently i've been thinking about reducing the amount of preferences actually, which is way harder than adding more of them, since to reduce and make macro preferences, you need usage statistics to know which ones people are using, with with values. Making statistical clusters. However, out of libre-software spirit, i refuse to add any kind of telemetry to the app, so that data is not available.

On the design side of things, this project was born as a port of Windows 10 alt-tab UX. There are differences today, but on the layout, i copied their non-uniform grid. My thought process was that the people at Microsoft probably poured a bunch of R&D and user studies into their decisions, and that when in doubt I would better copy their approach.

It's really hard to work without data. Both without actual usage data, but also without user studies because everyone could be using sub-optimal settings and think it's efficient, as people are often wrong about things. Also i suspect most people use defaults settings so ideally we make those the best ergonomic choice, but then again how do we know what is without user studies.

Tricky problem

**Comment by mfn** [comment]
> Tricky problem

Absolutely :-)

Oh, forgot one thing: I've never seen a scrollbar on HyperSwitch. I think it rather scales down the thumbnails and just displayes more rows/columns.

AltTab "hides" stuff behind the scrollbar, i.e. least recently used windows fall off the visible grid.

I think this is a killer feature because, if you use such a an application, to me the _primary goal_ is to "see everything".

In practice though even I was not hit by that often (hardly notice the scrollbar because I switch so quickly) because the common case is to switch between recently windows.

**Comment by lwouis** [comment]
@mfn actually there is a lot that happened on that front already. Let me share.

HyperSwitch doesn't support lots of windows. It's UI just crops and goes offscreen. It's a pretty bad UX. Try it. Spawn a bunch of Finder windows and see how it looks. Windows 10 has a pretty poor UI as well were it kind of "paginate". It's a bad UX I think cause it's hard to see, is keyboard-only, etc.

You say scaling down is the best UI because it shows everything at once. [I thought that too](https://github.com/lwouis/alt-tab-macos/issues/69#issuecomment-548196293) (see the visuals and my summary here), so I implemented scale-down-to-fit a few versions ago. Then a [user who actually is the kind of person always having 50 windows open at all times](https://github.com/lwouis/alt-tab-macos/issues/128) (a friend of mine has 200 chrome tabs at all tabs and was offended I suggested closing some). For that user, scaling down means basically the app is unusable because everything is small and hard to recognize. They actually suggested a scrolling UX, which I ended up implementing after much thoughts.

**Comment by mfn** [comment]
I guess I never had that much windows open with HyperSwitch to ever notice. And it's usually not the use-case to select the "oldest recently used" windows, that's why the scrollbar equally "Works" because a low number actually needs to use it (I never did so far, I hardly notice there's even one present).

Nevertheless, the non-existent of a grid kills my "perceptability" to choose windows :)
