### ISSUE TITLE
Security development

### ISSUE THREAD

**Issue by aina-kamarul-chan** [lwouis/alt-tab-macos#2774]
Hello, I was just wondering what is the security process for all of these as I want to reduce possible security risk before installing the application

I have few questions in regards to this application.

1. How do you evaluate the security of this application, it is based on secure coding and have protection against OWASP top 10?
2. Hypothetically, if I found vulnerability in the codebase and is valid, can I know what would be the process?
3. If there is identified vulnerability, where do you report it?
4. From what I read on the main page, there is no data collected which means that there is no log unless we consent to send the crash report, is that right?

I look forward to your response.

**Comment by lwouis** [comment]
Hi @aina-kamarul-chan,

Security is an open question. What kind of threats are you worried about? This is a desktop app. It's not on the internet. It operates offline.

1. OWASP top 10 are web vulnerabilities. Like an SQL injection. We don't have to worry about having a client-server system on this projet. It's a desktop app.
2. There is no process currently because it's unlikely to happen. Someone came to me once, in the past 3 years. I asked them to email me the issues privately. They shared a list of vulnerabilities. None of them were actually a problem.
3. Please email me.
4. The app doesn't do any networking without explicit user consent. It can only do 3 things: (1) a crash report, if the app crashed, and the user clicks to send the report when asked, and (2) a feedback report, if the user fills the built-in form and clicks to send it, and (3) checking/downloading an update, if the user opts-in to do it.

Overall this app is as secure as it gets, in my opinion. It's also an offline desktop app, so security in that context is typically not a big deal. I think for a desktop apps, more relevant topics is Trust. Do you trust people who wrote the app? Do you trust the place you download it? Is the build/CI pipeline secure so that no-one inject malware during the build, or changes the link on the website to download something else.

To make a comparison, it's like asking if Photoshop is secure. Personally, I trust that Adobe is making a safe image editing app. I also trust that their IT team has secured the CI and the website where I can download the tool, so that I'm downloading the correct app. But asking if Photoshop itself is secure... what does it mean?

I hope that was helpful 👍

**Comment by aina-kamarul-chan** [comment]
Thank you for your prompt response. The threats that I am worrying about, since this application is open source, I was wondering if people could push malicious code/ code can be exploited (e.g:outdated library) into the github repository and may potentially result in hacker accessing  the screen recording as permission has given in order to use it.

Just wondering, do you use security tools such as snyk or gitguardian to monitor it to scan the overall code?

**Comment by lwouis** [comment]
There is little code not written by me in this repo. Maybe less than 5%. And for that code, i thoroughly reviewed it manually when people submitted their PRs. So i'm aware of every line of code in the codebase.

This is not a large project where a lot of PRs are merged and some code could get merged without enough attention paid to it. It all goes through me and i review everything thoroughly.

I don't use the tools you mentioned. I don't see the need for a tool like this.

**Comment by aina-kamarul-chan** [comment]
Understood. I am assuming when you sending the crash report / feedback form, the connection is based on the WiFi/mobile. For networking protocol, do you use SSL or TLS?

**Comment by lwouis** [comment]
@aina-kamarul-chan you seem to not understand what this project is about. Have you used the app?

It's a desktop app for macOS. I can't run on mobile.

For crash reports, we use [this library from Microsoft](https://learn.microsoft.com/en-us/appcenter/sdk/crashes/ios)

**Comment by lwouis** [comment]
I imagine microsoft is using standard HTTPS calls to their backend to store crash reports.

it should be very easy to confirm with Wireshark.

Are you a security researcher perhaps?

**Comment by aina-kamarul-chan** [comment]
I am interested to be. =) . How do I track feedback form, I would like to suggest to have colour options so that my eye can immediately set it apart.
