### ISSUE TITLE
AltTab offers to switch to windows behind modal windows

### ISSUE THREAD

**Issue by jahabrewer** [lwouis/alt-tab-macos#2787]
**Describe the bug**

Windows that can't be switched to (i.e., a main window that has popped up a modal) are in the list of windows. In the video, you can see I've popped up the new branch modal in intellij. I can't click on the main window to go back to it because the modal is open, but AltTab tries to switch to the main window anyway.

AltTab should not list modals like this in its window list? Maybe I'm missing some nuance or option?

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/857884/81407f6f-7b8d-43d4-8644-8ad95e4bce45
<img width="576" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/857884/e5a45e5c-5657-46fe-a51d-165c455ae108">

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Open a modal
2. See that you can't click to focus the window that spawned the modal
3. Activate AltTab
4. See that it tries to switch back to the main window, which can't be done

**Your environment**

* AltTab version: 6.61.0
* macOS version: 13.5.2
* Other relevant info: I use a slew of apps like BetterWindow, BetterTouchTool, Karabiner

**Comment by lwouis** [comment]
Hi @jahabrewer,

The issue is on Jetbrains side. They have implemented the window as a standard window, thus AltTab displays it. It's typical of ported apps like Jetbrains products to improperly map their components to native elements on macOS/Windows/Linux.

Please contact their customer support in order to get the issue resolved.

Thank you

**Comment by jahabrewer** [comment]
I see, makes sense. Thank you!

**Comment by jahabrewer** [comment]
Filed https://youtrack.jetbrains.com/issue/IDEA-332158

**Comment by JB-Dmitry** [comment]
Hello @lwouis,
JetBrains developer here.
The problem seem to be related to Java AWT/Swing implementation in general, not just our IDEs, as it's reproducible also for a sample Java app. I don't know whether it will be easy to fix, now I just want to understand the problem better. 
You've mentioned that the problem is caused by the incorrect mapping to native macOS elements. Could you please elaborate on that more? What exactly do you expect from an app in that regard?
I've just experimented with showing a modal window using [runModalForWindow:](https://developer.apple.com/documentation/appkit/nsapplication/1428436-runmodalforwindow?language=objc) AppKit call, and such a window is also treated by AltTab as a 'normal' window. That's not the call AWT uses now to show the modal dialog, that's just what I've tried while looking for 'proper' API.

**Comment by lwouis** [comment]
Hi @JB-Dmitry,

You can find here the [checks we do to decide to show or not the windows](https://github.com/lwouis/alt-tab-macos/blob/1561f2631aa2dbe8f5ce27cea2c76075c95bdd4a/src/api-wrappers/AXUIElement.swift#L86). There is a [hardcoded extra rule to block some known IntelliJ windows](https://github.com/lwouis/alt-tab-macos/blob/1561f2631aa2dbe8f5ce27cea2c76075c95bdd4a/src/api-wrappers/AXUIElement.swift#L119) as well.

AltTab displays some modales. I'm not knowledgeable enough in the AppKit API to tell you directly what's wrong in your case. Some dialogs are presented on top of the main window, and the background gets dimmed. This is the case for most `Save` or `Open` dialogs. I think you probably want to use that type of dialog in the OP case. In the OP video, it seems like it's just another window, but it's actually blocking interaction with the main window. Yet, it appears independant visually. 

I think if you play around a bit more with the Alert and Sheet APIs, you can find a better match. It should provide a better UX for your users, and apps like AltTab will only show the main window, and focusing it will only focus the alert/sheet.

Thank you 🙇

**Comment by JB-Dmitry** [comment]
If I'm not mistaken, Alert API is intended to represent simple content only (text/icon/buttons), and Sheet API only allows to show window-modal (document-modal), not app-modal dialogs. Even though this might change in future, right now we mostly use app-modal dialogs. So, there doesn't seem to be a straightforward way to achieve the goal, and some more delicate hacking would be required.
The conditions you use for detecting 'actual' windows mostly take into account window sub-role and level. While 'Dialog' sub-role is considered 'normal', there's likely not much hope here. The remaining thing is window level, and it probably can be adjusted for AWT modal dialogs, cause it is already adjusted by AWT for some windows/popups. This only needs to be done carefully, with resetting the level to normal when the app loses focus, for modal dialogs not to be displayed above other apps' windows. We can look at it at some point, but this might not get high priority immediately.
