### ISSUE TITLE
Native macOS app switcher showing (instead of alttab) when focus of the cursor is inside login forms of various apps

### ISSUE THREAD

**Issue by philipreichen** [lwouis/alt-tab-macos#280]
(this is a bug, but i can't tag it with a label. no idea why)

*What's wrong?*
The native macOS app switcher shows, instead of the alttab window switcher, when cursor if focused on textbox of login screen (of the master password) of 1Password app.
This only happens when the focused window is the login screen of 1Password app. If it's not the focused window, then alttab functions properly.

*When does it happen*
When cursor is focused inside a textbox of a login form. Confirmed cases:
- 1Password master password login form
- Chrome with this webpage's login form https://www.banorte.com/wps/portal/banorte

*How to reproduce*
Two cases:
1. Open 1Password app, focus cursor inside the textbox where master password is typed in, do cmd+tab
2. Open chrome, go to https://www.banorte.com/wps/portal/banorte, focus cursor inside textbox where username goes, do cmd+tab

**Comment by lwouis** [comment]
I already noticed such behavior, and investigated this in #17. I'll close this ticket as a duplicate.

Please refer to #17 latest comments for the full picture, but basically it's a security feature of macOS that an app should not be able to capture keyboard input of another app, if the focus is on a secure text field. Otherwise you can have an app, like AltTab, keylogging all your passwords.

There are technical workarounds, not even using private APIs, but simply using the old deprecated, yet still publicly available, carbon API. This would allow us to capture the keys on such secure text fields. I have an ethical opposition to that though. I want to honor macOS security intention.

It is a tad annoying to not be able to switch from a password field, but I think the alternative is less desirable

**Comment by philipreichen** [comment]
Thanks a lot for...
- ... working through my issue so quickly
- ... explaining it so thoroughly
- ... and _finally_ creating a really nice looking, and great working alt-tab app for macOS!

I see why you wouldn't want to work around it and agree on both terms with you: it's a bit annoying for it not to work on password fields but I do definitely see why you (and Apple) want to enforce the current behavior.
