### ISSUE TITLE
AltTab UX Design suggestion

### ISSUE THREAD

**Issue by kutawhat** [lwouis/alt-tab-macos#2858]
I really like this app, but as for me the UX design could be slightly improved. That's why I'm proposing my solution. I'll attach warframes and a link to the figma file below.

### Win11 style
<img width="3024" alt="Win11 Light" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/3c05dbfa-52de-4e74-ba35-d14e7d96073a">
<img width="3024" alt="Win11 Dark" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/e1eaf420-06ab-4866-a63e-29cd8541c9a0">

### MacOS style v1
<img width="3024" alt="MacOS 1 Light" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/65200761-1c94-448f-be37-5fb425f66553">
<img width="3024" alt="MacOS 1 Dark" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/ccbabfb4-51b4-4a1c-878c-40523865cfc6">

### MacOS style v2
<img width="3024" alt="MacOS 2 Light" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/a3d7d75b-7ae5-4af2-877e-75ca73701546">
<img width="3024" alt="MacOS 2 Dark" src="https://github.com/lwouis/alt-tab-macos/assets/64655969/e4fa82b1-d787-4f4e-8b48-59d279d9e661">

### Figma file link
[https://www.figma.com/file/hXoN1Q7zzKFVubgVGkStWL/AltTab?type=design&node-id=0%3A1&mode=design&t=KNr7uA5SxkGguMGC-1](url)

**Comment by lwouis** [comment]
Hi @kutawhat,

Thank you for sharing these design mockups!

The current design for AltTab is trying to get as close as possible to the built-in app-switcher (i.e. the one triggered by `command+tab`). I don't think we would like to stray away from it, even if there was a design with better UX. People seem to really want a native look and integration. It makes sense to try and present the switcher in a way that ressembles what Apple would have done.

Regarding the Window theme, we also tried to look like Windows 10, so that people who like that look can enjoy it on macOS.

I would have advised to make your themes alternative themes that the user could opt into from the preferences. However, in the context of #351, we are looking at removing themes altogether. Very few people probably use these, so it's probably best to remove themes.

If we were to try and improve the UI, I think we would try to get the complex text effect used by the native app-switcher, as [detailed here](https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-577480530).

I'll close this ticket for now since I don't see actionable tasks here. I'm sorry.

Thank you 🙇

**Comment by kutawhat** [comment]
@lwouis I understand! I too tried to make the redesign as close to Apple as possible (not considering Win11 theme), even used their design system. It's a bit unfortunate that my suggestions don't match your vision, but thank you anyway for the extensive reply and clarification on this issue!
