### ISSUE TITLE
Qtake application not showing in Alt-Tab menu

### ISSUE THREAD

**Issue by Gh0stBustr** [lwouis/alt-tab-macos#2864]
An application called Qtake, which we use on set on big movies is not showing up on Alt-tab.

I have attached screenshots of my settings as well as the application itself so you can replicate and fix this issue.

Repro steps:
- Download Qtake from this URL (download expires in 7 day, 16th October):   https://we.tl/t-QkmOqW4wio
- Open Qtake (No need for online registration just create a local user and a project)
- press "H" to hide Qtake
- use Alt-tab (or with my settings it is Cmd+tab)
- >>> Qtake is not showing amongst the open apps on Alt-tab

**Your environment**

* AltTab version: 6.61.0
* macOS version: 13.6
* Other relevant info: 5K Retina iMac screen + 2 external 4K monitors via Thunderbolt.
<img width="586" alt="Screenshot 2023-10-05 at 09 45 01" src="https://github.com/lwouis/alt-tab-macos/assets/74185358/cfa632f3-a87d-45c9-b683-25adba7d8b27">
<img width="583" alt="Screenshot 2023-10-05 at 09 44 55" src="https://github.com/lwouis/alt-tab-macos/assets/74185358/6dd9a12f-7ad7-4d03-bf21-2266eb7a20f3">

**Comment by lwouis** [comment]
Hi @Gh0stBustr,

I'm sorry, I can't install software on my machine if it was shared by strangers on the Internet.

That being said, I don't even need to install it to diagnoze the issue: the issue is that Qtake has not correctly implemented their app. Windows not showing are a sign that the windows are not correctly implemented. AltTab shows normal windows. If a particular app is not showing their windows, it's because these look like windows, but at the technical level, they are not implemented correctly.

Please contact QTake customer support so they can fix the app, and it will show in AltTab with every other app 👍 

Thank you

**Comment by Gh0stBustr** [comment]
Wow most unprofessional response I got from a dev in my career.. guess that's what you get for free software huh.
Lack of care and a classic "our app is flawless" attitude.

You can download Qtake from the official store then: https://shop.qtakehd.com

We have been investigating on Qtake side, obviously that was the first try, haven't found an issue there.

There is no "window" it is not showing up at all, there is not even a tile for it in Alt-Tab.

**Comment by lwouis** [comment]
Hi,

This project is volonteer work. Let me compare your behavior to another situation with volonteer, so maybe you see yourself in a different light.

Volonteers open a soup kitchen for the poor. You come to the kitchen after getting their soup for free for a while, without contributing anything personnaly. You start complaining that your tupperware is tainted by the soup. A volonteer (me) tells you that it's likely an issue with your tupperware. All other tupperware brands are fine with the soup. You reply:

> Wow most unprofessional response I got from a cook in my career.. guess that's what you get for free food huh.
> Lack of care and a classic "our soup is flawless" attitude.

I've spent thousands of hours on this free software. I give it away for free. I share the source code. I've read, triage, discussed 2500 tickets, over the years. I get nothing from this, except a sense of being useful to others.

Your reply is the most unpleasant I've read since this project started. I suggest you look at what you have written. I don't think you would have behaved like this in a real-life interaction. See my comparison with an in-person volonteer project. Being anonymous on the Internet doesn't make bad behavior acceptable.

I don't know you. We've exchanged 1 message each, and you started throwing a fit. This is not acceptable behavior, especially when I've given you thousands of hours worth of work for free, and you've given me nothing so far.

Also "hello" and "thank you" are missing from both your messages. Please treat people with respect.

Thank you
