### ISSUE TITLE
No Application preview for KeepassXC

### ISSUE THREAD

**Issue by huyhoang8398** [lwouis/alt-tab-macos#2884]
**Describe the bug**

No Application preview for KeepassXC

**Screenshots / video**
<img width="1432" alt="Screenshot 2023-10-14 at 01 25 18" src="https://github.com/lwouis/alt-tab-macos/assets/25379882/7755e68f-5cf7-4226-b15d-b715f8c3f8ab">

**Steps to reproduce the bug**

1. Open KeepassXC application
2. Press atl+tab

**Your environment**

* AltTab version: Version 6.62.0
* macOS version:  MacOS Sonoma

**Comment by lwouis** [comment]
Hi @huyhoang8398,

I was able to reproduce the issue. The screenshot API call (i.e. `CGSHWCaptureWindowList`) returns nothing (i.e. `nil`). It's the first time I see this in like 3 years of seeing various weird app behave differently because they are not native macOS apps.

All I can suggest is to contact KeepassXC maintainers / customer support, and ask them to look into this. Every single other app works. The issue must lies with their implementation. The window looks like a gnome/kde port, so there may be some arcane tech converting things, and making the window image not available.

Thank you

**Comment by huyhoang8398** [comment]
thanks, i forwared. to KeepassXC maintainers. [this](https://github.com/keepassxreboot/keepassxc/issues/9934) if you interest

**Comment by droidmonkey** [comment]
Howdy, you guys need to display some generic window when the screenshot call returns nil. We block screenshots at the OS level on macOS, that is why it returns nil.

**Comment by lwouis** [comment]
Hi @droidmonkey,

I understand now. You hide these windows **on purpose**, because they contain sensitive data. That explains why I've never seen this issue in years of user reports.

I think our current behavior is good then. We show app icon, window title, badges, status indicator, Space number, etc. Everything we know about the window.

An improvement, perhaps, would be that KeepassXC shows a screenshot explaining what's going on, instead of nothing. It could be a UI showing a lock, with some text. I believe 1Password does this kind of thing: as soon as you unfocus their window, a giant lock appears on top of the window, making it impossible to read its content. I think this would be more transparent to the users perhaps. We've seen with this report that the user didn't know that KeepassXC was hidding data on purpose. They thought AltTab was malfunctionning.

Thanks everyone for clarifying the situation. I'll let KeepassXC decide if they want to take action for this UX. On AltTab's side, there is nothing more we can do to improve the UX.

Thank you

**Comment by lwouis** [comment]
Hi @droidmonkey,

Please remember that AltTab is just an accessibility app amongst many. I don't think it's the best approach to have all accessibility apps all handle this use-case, each in their own way. I think it makes more sense for the app hidding window content to find a way to better communicate their intent. I gave the example of 1Password, doing this.

It makes sense that the app hidding knows why they are hidding, and try to communicate this to their users. If AltTab shows a generic image here, and for another app who doesn't show a screenshot for a different reason, it seems less good that if you show a lock or other imagery, and the other app shows "no stream content" if it's a streaming app let's say.

I imagine Keepass has similar "lock my vault after 5min of inactivity" feature? What do you show the user in the UI when these types of locks happen? I suggest showing the same thing here for third-party apps dealing with the screenshot of accessibility APIs.

Thank you

**Comment by droidmonkey** [comment]
I think we are talking past each other or I don't understand what your app actually does. I'll just leave this alone for now, we aren't going to do anything for now.

**Comment by MasterGroosha** [comment]
There is a new bug in 10.12.0. By default, it shows "empty" preview for KeePassXC (which is okay for me), but after some time it starts skipping the app entirely. However, if you restart AltTab, the missing preview (empty again) re-appears.

Also I'd suggest showing app icon instead of empty preview for KeePassXC, or add a setting to control this behavior for any app.
