### ISSUE TITLE
Unidentified Window Created Every Time I Switch Language in Browser

### ISSUE THREAD

**Issue by dvirginz** [lwouis/alt-tab-macos#2936]
**Describe the bug**

This is a bug where one image better explains it than a thousand words.

<img width="647" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/31047807/8cbfee1a-b698-4b94-b9fb-164c753b7762">

As you can see in the image, I have "ghost" tabs that are completely empty/transparent. This happens every time I switch languages.

**Your environment**

* AltTab version: 6.64.0
* macOS version:  14.0

**Comment by lwouis** [comment]
Hi,

How do you "change language in browser"? This sounds specific to Microsoft Edge. If so, could you please contact their customer support? It's most likely a bug on their side. AltTab never creates extra windows. It only reports existing windows. Here, Edge has extra windows for some reason. I imagine they use those invisible windows to implement some language switching UI.

Thank you

**Comment by dvirginz** [comment]
Thank you for the prompt response. Unfortunately, I don't think so. As you can see, it happens in Slack as well. When I use the Mac hotkey to switch language, a blue shift icon appears. Usually, this is what causes the "blank" window to be created, depending on where I switched languages.

**Comment by lwouis** [comment]
I see. It must be a macOS bug. The capslock on your screenshot is similar and has been confirmed to be a macOS Sonoma bug that AltTab can't do anything about. macOS spawns a window in the app that has the active input field with capslock. AltTab only shows that window. It does exist. The OS spawns it. I imagine this language switching issue is the same root cause.

In any case, AltTab only report existing windows. It hasn't been untrue for more than 2 years I would say.

**Comment by dvirginz** [comment]
I definitely understand and agree it is not an alttab bug. I wanted a)
other people to be aware because it is very annoying and b) share as you
may have a workaround

בתאריך יום א׳, 29 באוק׳ 2023 ב-1:08 מאת lwouis ***@***.***>:
