### ISSUE TITLE
Zoom meeting window doesn't show in alt-tab under specific circumstance

### ISSUE THREAD

**Issue by MatthewScholefield** [lwouis/alt-tab-macos#2951]
**Describe the bug**

When the below conditions are true, the primary Zoom meeting window doesn't show up in the alt-tab switcher. Conditions:

1. Zoom app is initially closed (and meeting is opened from a link)
2. Zoom meeting shows the preview window before joining the meeting

Other observations:
 - No windows are maximized / full screened and this is all on a single space
 - Re-opening alt-tab fixes it
 - Switching between spaces and moving the window between spaces doesn't fix the problem

**Screenshots / video**

In this video I demonstrate this behavior and then I disable the video preview and show that it fixes the problem.

https://github.com/lwouis/alt-tab-macos/assets/5875019/f82ea048-e30d-47ec-a66d-b62e301458b6

**Steps to reproduce the bug**

1. Make sure you get a zoom video preview before joining a meeting (Enable "Always show video preview dialog when joining" within "Video" settings, Disable "Stop my video when joining" within "Video" settings)
2. Close zoom application
3. Open a zoom meeting directly from a link in the browser

You should now observe that when opening the alt-tab switcher the primary meeting window is missing from the list.

**Your environment**

* AltTab version: 6.64.0
* macOS version: 13.5.2
* Other relevant info: No external monitor, no multiple spaces

**Comment by lwouis** [comment]
Hi,

I updated to the latest Zoom. I'm on the latest macOS and AltTab.

I can't reproduce this issue. It shows windows correctly:

https://github.com/lwouis/alt-tab-macos/assets/106195/05b22b1f-3877-4f40-b16f-9b8249ce112c

**Comment by MatthewScholefield** [comment]
Can you try:
1. Completely close the zoom application and leave it closed when you open the meeting.
2. Use a real meeting link (I've created one you can use [here](https://us05web.zoom.us/j/7423349615?pwd=cERlQzZ4YUQ0TEpzMFNiYVRnZ3BIZz09)). It looks like the test meeting has a different popup which could affect reproduction.

**Comment by lwouis** [comment]
Thank you for the help.

Unfortunately, following your steps, I still can't reproduce the issue:

https://github.com/lwouis/alt-tab-macos/assets/106195/f83d707f-c1c1-434f-a90a-6a0d75ca4965

**Comment by MatthewScholefield** [comment]
Thanks for trying to reproduce. I think there's one more thing missing: we need the pre-meeting video screen to show up which I didn't see in the video you shared.

Could you by chance double check that these settings are enabled in the zoom app settings?:
> Enable "Always show video preview dialog when joining" within "Video" settings.
> Disable "Stop my video when joining" within "Video" settings

**Comment by lwouis** [comment]
I'm afraid that these settings are already set for me exactly as you mentioned:

<img width="846" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/62590a02-f777-4cc9-9d58-d730256b97b9">

**Comment by GLobyNew** [comment]
I think I was able to reproduce this issue. But not where OP showed. 
There are several scenarios where Zoom has an extra window, but which is not shown in Alt-Tab. 

For example, when you run Zoom for the first time, it shows that an update is available in a separate window
However, Alt-Tab does not see this window:
![SCR-20231126-mnyo](https://github.com/lwouis/alt-tab-macos/assets/32239128/94123339-c792-416f-9c5f-6ff675b850df)
![SCR-20231126-mnzs](https://github.com/lwouis/alt-tab-macos/assets/32239128/fddcdee9-0dfd-4ea0-bc1f-ff2af42b6c80)

Also, when starting a Zoom conference, a separate window asks for access to the camera. However, this window itself does not appear in Alt-Tab:


https://github.com/lwouis/alt-tab-macos/assets/32239128/b55f4e09-c52c-4145-8356-742880f5a147





I suspect this is not an Alt-Tab problem per se, but a problem with how Zoom handles windows.

**Comment by lonsdaleite** [comment]
I have exactly the same issue. Restarting AltTab helps to make Zoom call show up in AltTab.

**Comment by porridgewithraisins** [comment]
I have the same issue as well

**Comment by Brog33** [comment]
i have this issue too. the zoom window doesn't appear in alttab.

**Comment by gubbin** [comment]
Confirmed that:
- A long-running AltTab instance does not see Zoom meeting windows.
- If I restart AltTab while a meeting window is present, it will see the Zoom meeting window.
- If I close and then start a new meeting, AltTab still sees it.  Same if I quit and restart Zoom.

I'm going see how long before my current AltTab instance stops seeing Zoom meeting windows.

**Comment by lwouis** [comment]
Hi,

To clarify the situation of this ticket:

* I wasn't able to reproduce the issue on my machine. Zooms shows correcty.
* It seems inconsistent, and different people have reported different issues

AltTab is working fine for 99% of apps. The 1% that have issues are because something is not properly coded with these apps.

I'm going to close this ticket. Please open tickets with Zoom, so they fix their app. It will show better in AltTab, and also in other Accessibility apps like AltTab, after they fix their implementation.

Thank you 🙇

**Comment by gubbin** [comment]
> I'm going to close this ticket. Please open tickets with Zoom, so they fix their app. It will show better in AltTab, and also in other Accessibility apps like AltTab, after they fix their implementation.

I'm sorry to hear this, it seems to be a problem with long-running AltTab instances which makes reproduction difficult and slow.  I'm going to see if I can repro anyway.

**Comment by Brog33** [comment]
It sounds like it could be the same issue with VICE GTK (C64 emulator). 
The vice maintainer commented this:

_What VICE does different (probably) is, that the actual rendered image (the emulated screen) is rendered with a custom GL overlay (because GTK can't do this properly). If that is the problem.... no idea if/how it can be fixed._

Do you think this could be the case @lwouis ?

**Comment by BaronAWC95014** [comment]
I was able to get this same bug, but I was also able to fix it be restarting AltTab.
I joined a webinar through a link, and the Zoom window didn't show up in the list.

**Comment by xstephen95x** [comment]
> I was able to get this same bug, but I was also able to fix it be restarting AltTab.
I joined a webinar through a link, and the Zoom window didn't show up in the list.


Same here.

**Comment by ylibrach** [comment]
This is definitely a problem that happens when starting a Zoom call while AltTab is already open. Restarting AltTab works, but it's not a real solution especially for people that start many Zoom meetings throughout the day (for example, for work). @lwouis is it possible to reopen this issue?

**Comment by obtuse-whoosh** [comment]
Also experiencing this issue. Would love a workaround that doesn't include restarting AltTab!

**Comment by ab** [comment]
I also am seeing this.

It seems to happen mostly when launching Zoom by clicking on a meeting URL, when the Zoom app is started after AltTab is already open. Restarting AltTab does fix it for that window.

@lwouis Do you have a theory for what the cause is, whether it's ultimately Zoom's fault or not?

**Comment by mchenryc** [comment]
I see this consistently as well. It happens when the "preview" dialog (showing the camera view) is shown before joining a call. Disabling the preview (in the preview screen itself, or in preferences) solves it for the next call.

The dialog window is modal, but the resulting meeting is not. Alt-Tab ignores modal dialogs, yes?
* Could they be re-configuring the dialog window as non-modal to show the meeting? If so, is this "wrong" or could alt-tab watch for this kind of repurposing?
* Could they be opening the meeting window as a child of the modal-dialog? If so, could this be circumventing standard window creation events used by alt-tab?

@lwouis is this like the [Chrome bug](https://github.com/lwouis/alt-tab-macos/issues/3834) where you were able to see what the offending application (Zoom here) was doing wrong? Perhaps if we can tell Zoom what they're doing wrong, they'll be able to fix it quickly as well.

**Comment by lwouis** [comment]
Hi @mchenryc,

Yes, AltTab ignores modals. On window creation, on only then, it looks the window role/subrole, and [decides if it's an actual window](https://github.com/lwouis/alt-tab-macos/blob/820b6ea3aae62cd76ccc0e95c6b0614641acc615/src/api-wrappers/AXUIElement.swift#L233).

Once a window is discarded, it will never be shown. We don't observe discarded window, in case they change. I'm not sure if windows can change after creation. Perhaps? In any case, it's likely not a good pattern since no other app is doing it. Also, we would take the user ressources if we started using CPU to follow the state of all modals and UI elements, in case they morph into windows. There is no observation API for this, so it would require polling which is very resource intensive. AltTab today polls nothing. We use efficient observation APIs, so the footprint is very small.

Zoom should fix their app. If AltTab is not detecting this window, it's most likely that other accessibility apps aren't.

Thank you

**Comment by radaczynski** [comment]
@mchenryc : thank you so much. Indeed for me this was the reason I was seeing the bahaviour. I am not expecting zoom to fix their app unfortunately, so at least I have a workaround now. I don't mind having the video auto-on when I join a meeting so this works for me.

**Comment by eeshugerman** [comment]
This is unfortunate -- "Always show preview when joining" is a great feature and it seems unlikely Zoom will "fix" their app.

**Comment by ADTC** [comment]
@eeshugerman @mchenryc I have discovered a workaround which lets you enable (turn on) "Always show preview when joining".

1. Before joining a meeting, launch the Zoom app first.
2. Close the Zoom Workplace window by clicking the red circle on top left (in the traffic lights).
3. Launch and join the meeting from the meeting link.
4. Confirm the preview and join the meeting.
5. Tada! 🎉 The meeting window is in the AltTab list.

**Note:** I don't know if "Add Zoom Workplace to MacOS menu bar" needs to be enabled, but closing all windows in macOS typically still keeps the app running.

**Tip:** If you attend a lot of Zoom meetings, just keep the app running all the time, but with the Workplace window closed (not minimized). You can even add it to the Login Items.

---

@lwouis How far along did you get with investigating the issue on the AltTab side?

> Please open tickets with Zoom, so they fix their app.

The problem is, we don't even know what they need to fix. How would we explain to the massive company that runs Zoom that a little third party utility app that less than 0.1% of its users use is having trouble switching windows? And why would they even care?

**Comment by DereC4** [comment]
I have this issue too.

**Comment by Delayed-Gitification** [comment]
yes same issue, can fix by restarting alttab

**Comment by yutotakano** [comment]
I don't think this'd be fixed by the Zoom side.

What could be useful on the alt-tab side is potentially a menu bar drop-down option that "refreshes" or re-initializes AltTab with the currently open windows, treating all windows as freshly created. It'll be a wee bit quicker than quitting and restarting AltTab entirely and useful for debugging issues like this.

**Comment by lwouis** [comment]
In recent AltTab releases, there is a "manual refresh" happening every time you press alt+tab

**Comment by DereC4** [comment]
Alas

**Comment by lwouis** [comment]
Could you please try out [this local build](https://github.com/user-attachments/files/24265844/AltTab.app.zip), and let me know?

In that build, I've removed the filtering of windows which are higher level than the normal level. That is, windows that float on top of others. Normally, we remove them from the list. I actually wonder if this is good these days. So if you see more windows you consider windows, and and no new windows you would consider popups/HUDs, then I'll release this change 👍 

It also contains my work-in-progress for video thumbnails, so please ignore that part

Thank you

**Comment by DereC4** [comment]
Ah I don't have my mac on me because I drove down for winter break, but hopefully someone with a mac can check

**Comment by yutotakano** [comment]
@lwouis I can verify that Zoom meetings (launched from a URL, with video preview before joining) now correctly show up as a window! 🎉  

Double checked that it doesn't show up with the 7.38.1 release, so it's definitely a fix.

I also didn't notice any other popups/HUDs showing up on Alt Tab. I was worried that maybe the Zoom "overlay" that shows while sharing your screen might appear in the list, but that still (correctly?) remains filtered out.

**Comment by murray** [comment]
> Could you please try out [this local build](https://github.com/user-attachments/files/24265844/AltTab.app.zip), and let me know?
> 
> In that build, I've removed the filtering of windows which are higher level than the normal level. That is, windows that float on top of others. Normally, we remove them from the list. I actually wonder if this is good these days. So if you see more windows you consider windows, and and no new windows you would consider popups/HUDs, then I'll release this change 👍
> 
> It also contains my work-in-progress for video thumbnails, so please ignore that part
> 
> Thank you

Has this fix been included in a newer version?

Still can't switch to zoom calls on version 8.0.0.

Thanks
