### ISSUE TITLE
"Show on" should be always "on all screens"

### ISSUE THREAD

**Issue by dims12** [lwouis/alt-tab-macos#3037]
**Is your feature suggestion related to a problem? Please describe.**
There is no well defined and visible concept of "active screen" in MacOS. There is also no well defined cocept of "screen with menu bar". Finally, mouse is very small and should not define anything. So, the option

![image](https://github.com/lwouis/alt-tab-macos/assets/5513817/31343183-6022-44b6-b1b1-668bc9c3486d)

is effectively useless. Effectively, during everyday work, window switching UI is appearing randomly on any monitor, especially in the cases when you switched to the wrong window.

**Describe the solution you'd like**
Window switcher should be displayed on all displays. Either always or by default.

**Describe alternatives you've considered**
None

**Comment by lwouis** [comment]
Hi,

The current options are useful to many people. I suggest you don't discard them so quickly.

* MacOS has a clear concept of screen with menubar. You can select that in System Settings > Display. It's well defined and stable. It's been there since the beginning.
* The concept of Active screen is not as well defined, I agree.
* Screen with the mouse is very clear as well, and lots of people like that one

We have a ticket to offer a 4th option to show on all screens: https://github.com/lwouis/alt-tab-macos/issues/535 Please follow that ticket to keep up to date 👍 

Thank you 🙇
