### ISSUE TITLE
Partially missing window previews with Stage Manager and specific screen arrangement

### ISSUE THREAD

**Issue by ypekka** [lwouis/alt-tab-macos#3079]
**The bug**

When the Stage Manager is active and there is a screen west (left) of main screen only those window's previews are captured that are on Stage Manager's recent list. All other windows do not have previews visible. If Stage Manager is deactivated the issue resolves.

If screen arrangement is modified so that the screen in the west is moved more towards WNW or WSW and screens overlaps less than about 50% then again the issue resolves.

Screen on the west can be either physical or virtual (like BetterDisplay) and resolution or orientation doesn't seem to affect the issue.

**Environment**

* AltTab version:  6.64.0
* macOS version:  14.2.1

**Comment by lwouis** [comment]
Could you please share a video of the issue? It's hard for me to understand the issue from your description.

Thank you 🙇

**Comment by lwouis** [comment]
Thank you for sharing some visuals.

If I understand correctly, you're saying that some previews are missing when, and only when:

* Stage Manager is enabled
* There is a screen left of the main screen, overlapping vertically at least 50% of the main screen height

And in that case, only the previews from that leftmost screen are missing. Is that correct?

I'm wondering if this could be caused by the pinned issue #1324 which stems from the OS not sharing windows from other Spaces.

Have you checked `Displays have separate Spaces` in System Settings here?

<img width="488" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/4bbb7d61-8c3b-48cb-ae18-afb11efd85a6">

Thank you

**Comment by lwouis** [comment]
This issue is quite complex, so I'll try rephrasing you, to make sure if I understand correctly.

You're saying that this case exists:

* All windows are on the main screen, and no other screen has a window
* Stage Mananger is ON
* You alt-tab, and while all windows are shown, the ones not present in Stage Manager UI don't have screenshots, as such:  
  ![image](https://github.com/lwouis/alt-tab-macos/assets/106195/60040d46-7ce5-40dc-b040-2ec209ada304)

Is that correct?

I'm trying to get to a single use-case that demonstrate the issue with minimal amount of complexity.

**Comment by lwouis** [comment]
I looked into this issue. I think it's unrelated to screen position. I think it's purely related to what fits on Stage Manager.

I did a test with something like 40 Finder windows. When I switch to another app, let's say Chrome, I see all those Finder windows going into Stage Manager. However, Stage Manager only show a stack with 3 windows. The other 37 windows are not visible.

When summoning AltTab, I see the 3 windows from Stage Manager. The others are shown, but with no preview.

This is the way macOS is doing it: when you minimize a window for instance, the **actual window** is shrunk, and put on the Dock. Same thing with Stage Manager. The actual windows are shrunk or hidden. It seems like Stage Manager doesn't render more than 3 window per app, and the other don't keep their buffer, thus when AltTab asks macOS, it gets no image to display.

Nothing we can do about this. The same way we can't do anything about the thumbnails being skewed and low-resolution when Stage Manager is enabled. In general, Stage Manager breaks AltTab, and there is nothing we can do about it :/

**Comment by skylerreeves** [comment]
@lwouis 

> but for 99% of users, we should advise not to use Stage Manager in combination with AltTab

Just started my trial about 30 min ago. Been looking for a better app switcher. Glad I found this comment sooner rather than later haha. I'm a near constant user of Stage Manager.
