### ISSUE TITLE
Customize windows order

### ISSUE THREAD

**Issue by jiangtann** [lwouis/alt-tab-macos#3154]
There are lots of issues and pull requests about manual windows order:

https://github.com/lwouis/alt-tab-macos/issues/515
https://github.com/lwouis/alt-tab-macos/issues/2688
https://github.com/lwouis/alt-tab-macos/pull/2583

As for me, I want to always have VSCode and Chrome in the first and second positions, respectively, because I use these two applications the most frequently. If VSCode and Chrome are always in the first two positions, I wouldn't need to scan through Alt-Tab to find the position of a specific application.

I believe a considerable number of people need manual windows order or application aliases which support indirectly manually sort windows through alphabetical order.

**Comment by lwouis** [comment]
Hi,

As I explained in the tickets, this is niche. Few people want this.

Furthermore, no one has yet explained the details of how a manual ordering would work.

* A Window is volatile. After it's closed, it's gone forever. You can spawn a similar window, but the ID will be different. This means that it's not possible to remember the position of a window between restarts for example. Since all windows get destroyed, then clones get created, with new IDs. So at best, the user could manually order, and it would last as long as the windows are opened. On every reboot, the order would have to be re-set.
* What would the UI be to change the order? Drag-and-drop? How exactly? It may seem trivial, but it's actually really tricky. Some windows are not shown, but they may be in higher positions. For example, you hide windows which are minimized, but there is a recent minimized window. Then you order manually a window to the left-most. Now you un-minimize the window. Where should it be, in the order? On the left or on the right of the manually-ordered window?

Overall it's niche, and too complex, so I can't imagine it would be added, at the moment at least.

I hope this rationale makes sense. I'm sorry 🙇 

Thank you

**Comment by sincethestudy** [comment]
I really want this man
=
