### ISSUE TITLE
XML External Entity (XXE) Injection Vulnerability in fonttools (CVE-2024)

### ISSUE THREAD

**Issue by SandeepVashishtha** [lwouis/alt-tab-macos#3164]
**Describe the bug**

A security vulnerability has been identified in the fonttools library, specifically related to XML External Entity (XXE) Injection via the OT-SVG parser in the svg.py file. This vulnerability could potentially allow an attacker to exploit the OT-SVG parser to perform various attacks, including reading sensitive data, executing remote commands, or causing denial of service.

**Affected Versions:**

- Vulnerable: fonttools versions up to and including 4.8.1
- Fixed: fonttools version 4.43.0

**Remediation:**
Upgrade fonttools to version 4.43.0 or later to mitigate the vulnerability.

**Security Information:**

- Snyk CVSS Score: 7.5 - High Severity
- NVD CVSS Score: 7.5 - High Severity

**Comment by lwouis** [comment]
Hi,

This vulnerability exists on a python library used for offline preparation of some AltTab assets. I use it years ago to generate the fonts that AltTab uses internally for icons.

This vulnerability is not exploitable by any means. I'm well aware that some automated tools flag it as a vulnerability. It is not correct. I'm stopped the Github security bot trigger for instance, because it kept showing such false positives.

Thank you
