### ISSUE TITLE
Alt-Tab Displays Two Instances for Rhino 8 (CommandLine and Main Window)

### ISSUE THREAD

**Issue by regiulien** [lwouis/alt-tab-macos#3218]
https://github.com/lwouis/alt-tab-macos/assets/162313450/ea3961c0-4b9d-4cc9-961d-3d271f6e1228

Environment:
Affected Application: Rhino 8
Operating System: macOS 14.3.1

Description:
While using Alt-Tab on macOS with Rhino 8, Alt-Tab displays two separate instances for Rhino 8: one for the main software window and another for the command line interface. Typically, the command line should not appear as a distinct window in the Alt-Tab switcher.

Steps to Reproduce:

1. Open Rhino 8 on macOS.
2. Use the Alt-Tab shortcut to switch between applications.
3. Notice two separate instances for Rhino 8: the main window and the command line.

Expected Behavior:
The Alt-Tab application should only display the main window of Rhino 8, not the command line interface.

Actual Behavior:
Alt-Tab shows both the main window and the command line interface as distinct entries.

Additional Information:

- The Rhino 8 command line shares the same application name as the main software, making it impossible to add only the command line to the Alt-Tab blacklist.
- Adding Rhino 8 to the Alt-Tab blacklist removes both the command line and the main software window from the Alt-Tab view, which is not a desirable solution.

Attachment: video.

**Comment by lwouis** [comment]
Hi,

This issue lies with this particular app. AltTab reports open windows. Rhino 8 seems to be using an actual window to implement what looks like a tooltip.

It's a common issue with app ported from other platforms and/or using cross-platform UI libraries (e.g. Steam, Adobe suite, etc).

Nothing AltTab can do about it. We provide the Blacklists feature already but as you noted it's on/off entirely for that problem app. We can't fine-tune more than this. It's on Rhino's side to fix this issue. Other accessibility apps than AltTab will also see 2 windows.

Thank you 🙇‍♂️

**Comment by regiulien** [comment]
Hi! Just to let you know.
Guys from McNeeel solved this problem with the new release: Rhino 8.5 :)
