### ISSUE TITLE
Adobe Media Encoder not showing on Alt Tab when using both AfterEffects and AME

### ISSUE THREAD

**Issue by noidwasavailable** [lwouis/alt-tab-macos#3235]
**Describe the bug**

When using both Adobe After Effects and Adobe Media Encoder, Media Encoder does not show up on Alt-Tab.

**Screenshots / video**

Couldn't directly upload the video because the file was too large.

https://youtu.be/EG3duo5Q5bE

You can see on the video that the Media Encoder window is definitely open. It is captured by the Raycast window switcher but not AltTab.

**Steps to reproduce the bug**

1. Open AfterEffects
2. Open Media Encoder.
3. Open the AltTab window switcher via shortcut.

**Your environment**

* AltTab version: 6.66.0
* macOS version: M1 Pro Sonoma 14.2 (23C64)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

This issue is most likely on Media Encoder side. AltTab reports windows if they are standard windows. Adobe software is often ported to mac. It's often ported or cross-platform software. This type of software often poorly integrates into macOS. Steam is another example of such software.

If AltTab doesn't report the window, it's because it's not a standard windows. Other accessibility apps may have similar issues.

Please contact Adobe's support so they get it fixed. Nothing we can do on our side.

Thank you
