### ISSUE TITLE
Alt-Tab app broke application switcher on my mac?

### ISSUE THREAD

**Issue by ironhak** [lwouis/alt-tab-macos#3248]
Since when I installed alt-tab my mac does not focus appliations anymore. 
Here's an example using alt-tab: [Video](https://imgur.com/EVJ1M2a)

Now, the same example with alt-tab application closed: [Video](https://imgur.com/zH5IjfW)

Searching in google I found a possible remedy for this bug is making sure "When switching to an application, switch to a Space with open windows for the application" is enabled, I showed the behaviour with it enabled and disabled. 

Everything worked perfectly prior to alt-tab installation on my mac. After I installed alt-tab it worked for a couple of weeks and now this problem is emerged. I'm 99.9% sure the problem is related to alt-tab because I did not installed other applications in the mean time. 

**Your environment**

* AltTab version: 6.66.0
* macOS version: Sonoma 14.2

**Comment by lwouis** [comment]
Hi,

I'm sorry to hear you're having this issue.

AltTab interact with the built-in app-switcher in one way, and one way only, to my knowledge. This is if the user changes the AltTab shortcut to be `command+tab` instead of `alt+tab`. In that case, AltTab disables to built-in app switcher, so that it can display instead of it. When you quit AltTab, or when it crashes, or when you change the shortcut back to anything except `command+tab`, the built-in app switcher is re-enabled.

As we see on your video, the built-in app switcher shows up. So there is no issue here. I can't imagine how AltTab would interact with the built-in app switcher without being opened. I don't know of any other interaction than the one I described.

I'm afraid the most likely cause is some setting, or some other app on your system. It's the first time this issue is reported, so no one else has ever seen this behavior in the 5 years this project has been used by people.

I'm afraid I can't help you beyond sharing this information. I can't reproduce it on my machine, and I can't picture how it could possibly interact after being quit here.

Thank you 🙇
