### ISSUE TITLE
Norwegian translations cleanup

### ISSUE THREAD

**Issue by snomos** [lwouis/alt-tab-macos#3260]
"Norwegian" is actually two written languages (ISO codes in parenthesis):

- Norwegian nynorsk (nn)
- Norwegian bokmål (nb)

"Norwegian (no)" (unspecified) is merely the spoken language, and should be interpreted as indifferent to Nynorsk or Bokmål. Apple (and others) has sinned in this regard for many years, using "Norwegian (no)" as if it meant "Norwegian bokmål (nb)". It does not.

I have added a Norwegian nynorsk translation, and completed the Norwegian bokmål translation, and uploaded it under the new locale "Norwegian bokmål (nb)" in POEdit.

That is, there is presently **three** Norwegian locales for AltTab in POEdit:

- Norwegian nynorsk (nn) - 100 % done
- Norwegian bokmål (nb) - 100 % done
- Norwegian (no) - ca 86 % done

I suggest you remove the "Norwegian (no)" project, and use the two complete localisations instead.

One possible negative consequence: Norwegian users with only Apple's default settings might have to explicitly add Norwegian Bokmål as a preferred language after this change, to see the Bokmål localisation of AltTab.

**Comment by lwouis** [comment]
Hi @snomos,

Thank you for being so diligent about localizing the app in Norwegian. Thank you for all your work!

If I understand correctly, the situation seems complicated. I've googled the issue, and found that it seems to be an [unresolved situation](https://linguistics.stackexchange.com/questions/36784/norwegian-translation-codes-no-nn-nb-which-to-use-on-a-website), with different possible solutions being used in the wild.

I've tested launching AltTab with the 3 iso codes: `no`, `nn`, `nb`. My chose was always respected; it worked great. I then tried to remove the `no` localization. I assumed that when launching the app asking for `no`, it would fall back to `nn` or `nb`. It seems that it fell back on `en` instead. I think that's the negative consequence you were talking about:

> One possible negative consequence: Norwegian users with only Apple's default settings might have to explicitly add Norwegian Bokmål as a preferred language after this change, to see the Bokmål localisation of AltTab.

However, my tests were pretty synthetic. I launched the app like this `AltTab -AppleLanguages "(no)"`. I'm not sure this is similar to a Norwegian user having not changed any setting on their default mac setup, launching the app.

Maybe you could help me here? This is a [local build](https://github.com/lwouis/alt-tab-macos/files/14742549/AltTab.zip) which has only `nb` and `nn`; `no` was removed. How does it behave when you open it on your machine? Which language is shown to you?

If default users see English, indeed I think it's not ideal since 80-99% of users will use defaults. If it's the case, I think we could either keep the `no` localization and manually maintain it to mirror `nb`, or maybe at the code level I could force the app to serve `nb` instead of `en` if the user is asking for `no`. I'm not sure it's possible but I assume it should be.

What do you think?

Thank you 🙇‍♂️

**Comment by snomos** [comment]
> Hi @snomos,
> 
> Thank you for being so diligent about localizing the app in Norwegian. Thank you for all your work!

Thank you for all the good work in making alt-tab-macos!

> If I understand correctly, the situation seems complicated. I've googled the issue, and found that it seems to be an [unresolved situation](https://linguistics.stackexchange.com/questions/36784/norwegian-translation-codes-no-nn-nb-which-to-use-on-a-website), with different possible solutions being used in the wild.

On the surface, it seems complicated, but in reality it isn't, and it isn't unresolved either. As it is said in the second comment to the post you link to, the general rule of avoiding macrocodes apply, and should always be followed. This is also according to BCP-47, which builds upon the ISO 639 series of language codes (and other standards). I happen to know the Norwegian representative in ISO, the one that initially suggested the three codes `no`, `nn`, `nb`, and his intention is very clear:

- `no` is for spoken modalities, and other contexts where written language is secondary
- `nn`, `nb` should always be used for the written languages, never `no`, since it is a macrocode, and thus unfit for the purpose

That is, on a standardisation level there is no question and no confusion, and no unresolved situations.

But it is true that quite many people are ignorant about this, and out of laziness ignores the linguistic diversity of Norway, and just uses `no` as a short-hand for `nb`, since it is the dominating variant. That does not make it correct, and it is this misuse that creates the impression of an unresolved situation.

> I've tested launching AltTab with the 3 iso codes: `no`, `nn`, `nb`. My chose was always respected; it worked great. I then tried to remove the `no` localization. I assumed that when launching the app asking for `no`, it would fall back to `nn` or `nb`. It seems that it fell back on `en` instead. I think that's the negative consequence you were talking about:
> 
> > One possible negative consequence: Norwegian users with only Apple's default settings might have to explicitly add Norwegian Bokmål as a preferred language after this change, to see the Bokmål localisation of AltTab.

Yes, this was what I had I mind. But it seems to me that Apple has corrected its language selection options, at least in the latest version(s):

> However, my tests were pretty synthetic. I launched the app like this `AltTab -AppleLanguages "(no)"`. I'm not sure this is similar to a Norwegian user having not changed any setting on their default mac setup, launching the app.
> 
> Maybe you could help me here? This is a [local build](https://github.com/lwouis/alt-tab-macos/files/14742549/AltTab.zip) which has only `nb` and `nn`; `no` was removed. How does it behave when you open it on your machine? Which language is shown to you?

Thanks for providing this special build 🙂 

What I found was:

- there are only two Norwegian languages selectable in macOS these days:
    - Norwegian Bokmål
    - Norwegian Nynorsk
    - "Norwegian" is gone
- when I set the interface languages to *Norwegian Bokmål* and *English* (using system preferences), I get the bokmål version of the app
- when I set the interface languages to *Norwegian Nynorsk* and *English* (using system preferences), I get the nynorsk version of the app

In no cases do I end up with English.

It might be an issue on older versions of macOS, but that I can't test that now. And I don't think that user population is very large. And for those that are on older systems, it should be easy to fix by adding Norwegian Bokmål explicitly.

> If default users see English, indeed I think it's not ideal since 80-99% of users will use defaults. If it's the case, I think we could either keep the `no` localization and manually maintain it to mirror `nb`, or maybe at the code level I could force the app to serve `nb` instead of `en` if the user is asking for `no`. I'm not sure it's possible but I assume it should be.
> 
> What do you think?

I think Apple has solved this for us, so that it is safe to remove the `no` locale, and only keep the `nb` and `nn` ones going forward 🙂 

> Thank you 🙇‍♂️

Thank you for the very swift and clear response to my issue, and for making this very cool tool and everyday improvement to macOS 🙂

**Comment by lwouis** [comment]
Thank you for your message.

I also noticed that in XCode, even though there were 3 ISO codes, only Norwegian Bokmål and Norwegian Nynorsk were listed. With your explanation that they removed it as a selectable language, it makes sense.

In conclusion, I'll remove `no` from poeditor, and from the app. This will happen in the next release.

Thank you for your help 🙇‍♂️
