### ISSUE TITLE
Unlocalisable strings

### ISSUE THREAD

**Issue by snomos** [lwouis/alt-tab-macos#3261]
**Describe the bug**

There are a couple of strings that I can't find in the POEditor interface. They  are either in English, or (in my case) Norwegian Bokmål, but I am unable to find them anywhere in the localisation interface.

**Screenshots / video**

![image](https://github.com/lwouis/alt-tab-macos/assets/1255285/bb4cb4a6-9bb3-471e-9285-71204c7d4262)

The first line is in Norwegian Bokmål, the second in English, and the button is in Norw. Bokmål again. None of these strings can be found in PO Editor.

The dialog pops up when trying to look for updates, but there was an error during the process.

![image](https://github.com/lwouis/alt-tab-macos/assets/1255285/3fa3bc93-7f35-4803-a5b3-9e88727fc6f0)

In the Acknowledgments section of the preferences, the headings and short descriptions are candidates for localisation, but are presently not localisable as far as I can tell.

**Steps to reproduce the bug**

First case:
1. Go to 'Settings > Policies'
2. Click on 'Look for updates now' with e.g. no network connection
3. See untranslated strings

Second case:
1. Go to 'Settings > Acknowledgements'
2. See untranslated strings

**Your environment**

* AltTab version: latest as of 25.3.3034
* macOS version: Sonoma 14.4
* Other relevant info:
    - external keyboard: yes
    - multiple monitors: yes

**Comment by lwouis** [comment]
Hey @snomos,

Indeed, both those experiences have special treatment:

* Updates are done through the wonderful [Sparkle project](https://sparkle-project.org/). It's a FLOSS library that we use to get all the great updating functionality. They have their own localizations. [Norwegian was added with those PRs I think](https://github.com/sparkle-project/Sparkle/pulls?q=is%3Apr+norwegian+is%3Aclosed). ~~I think you could contribute improvements there. Those would benefit AltTab and also every other app using Sparkle, which is most popular apps out there, in my experience.~~ **Update:** I think the `nb` localization [may be up to date](https://github.com/sparkle-project/Sparkle/blob/2.x/Sparkle/nb.lproj/Sparkle.strings#L23). A caveat here: AltTab is on an old version of Sparkle, and migrating would be a big undertaking, so I'm afraid that until we bite the bullet and go for the big upgrade, improvements from the Sparkle project wouldn't reflect in AltTab.
* The "Thank you" section is reusing the [same markdown file](https://github.com/lwouis/alt-tab-macos/blob/master/docs/Contributors.md) as [the website](https://alt-tab-macos.netlify.app/thanks). It's a markdown file which is filled by a shell script, it's then used to display the list on the website and on the app. The website is only in English. there is no tech foundation to serve it in multiple languages. I had [wanted to do it years ago](https://github.com/lwouis/alt-tab-macos/issues/211) but it never happened. I used a special trick for release notes, since those are pretty impactful for users: I call Google Translate automatically based on the locale. People have reported that it's pretty decent. It seems better than showing English to everyone, even though the app itself is in their language. The changelog is derived from git commits, so again, no technical foundation to have it in multiple languages. Furthermore, this one has a component of timeliness with it: by the time people have volonteered localizations for the latest lines in the changelog, most users have been offered the list and a prompt to update. So these hand-crafted translations would only benefit a few late adopters.

I'm sorry that both the sections you shared don't have an easy path to getting a proper localization at the moment. I regret it. Unfortunately, I can't afford to spend lots of time addressing it: https://github.com/lwouis/alt-tab-macos/issues/1179

I'll close this ticket for now since it's not actionable

Thank you 🙇‍♂️

**Comment by snomos** [comment]
Thank you @lwouis for the explanation, I fully understand. I will see whether I can contribute to the Sparkle project. That would improve the user experience for Norwegians in many apps, so I guess that is useful even if you won't upgrade to the newest Sparkle in a long while.

Thanks again for your nice work and welcoming support of a stranger.
