### ISSUE TITLE
Windows-ify: Use secondary shortcut keys as primary in other Shortcuts 

### ISSUE THREAD

**Issue by buck-0x** [lwouis/alt-tab-macos#3302]
**Is your feature suggestion related to a problem? Please describe.**

1. I have `Shortcut 1` and `Shortcut 2` as default
2. When alt-tabbing thru all applications, I would like to used the back-tick for `Select previous window` (like Windows)
3. I can't use the back-tick for `Select previous window` because it is being used in Shortcut 2 for `Select next window` but in a different context

**Describe the solution you'd like**

I would like to be able to use `While open` hotkeys in one shortcut, as the main hotkey in other shortcuts without conflict. Basically, what I'm used to from Windows.

**Describe alternatives you've considered**

I have been trying to get used to using Shift or other keys to select the previous window but when I do it messes me up when I'm back on my Windows machine.

**Comment by lwouis** [comment]
Hi,

It seems like a nice flexibility to have. It would be quite tricky to implement though, given our current design which is quite complex and very involved to QA.

Thank you

**Comment by lwouis** [comment]
A while ago, we changed how shortcuts work. On recent versions, you can switch shortcuts on-the-fly. For example, you can start with alt+tab to show all windows. Then without release alt, you can hit ``` ` ``` to only show windows from the active app.

This flexibility is nice as people can change their mind, and switch from the 5 shortcuts fluidly.

Unfortunately, it means that we can't move forward with the idea in this ticket. This is because if the user presses a shortcut which is both a trigger-shortcut, and a while-open shortcut, we have to pick. Today we pick the trigger-shortcut.

It's also confusing what would happen if we let users set ``` ` ``` for both trigger-shortcut to move forward, and as a while-open to move backwards. Let's say you press it once -> trigger-shortcut triggers. Then you press it twice -> should we could this as a while-open trigger, and move backwards? But the user may expect to go forward by pressing it again.

I'll close this ticket for now. Please let me know if you see another approach which would conciliate all the constraints and requirements.

Thank you 🙇
