### ISSUE TITLE
Allow users to immediately switch to next available window without pressing `tab` twice

### ISSUE THREAD

**Issue by GrayedFox** [lwouis/alt-tab-macos#3359]
**Describe the bug**

Pressing alt-tab shortcut doesn't switch to the next tab, the tab key must be pressed twice.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/6493307/7cb91ab3-27ac-4985-9b25-3779985fb12e

**Steps to reproduce the bug**

1. ensure AltTab is running
2. open up two different applications
3. use the default alt+tab shortcut by pressing and holding `alt`, then pressing the `tab` key one time
4. notice that the application doesn't switch, the original/currently open application remains focused

**Your environment**

* AltTab version: Version 6.69.0
* macOS version: 14.4.1 (23E224)
* Other relevant info: I do have the 'Show on: screen including mouse' setting set as well as the 'Window order: alphabetical' setting set, not sure if relevant

**Expected behaviour**

I would expect that pressing `alt+tab` switches between my open applications, or if this is a breaking change, I would expect to be able to configure this behaviour in my settings, so that I can opt-in to having certain shortcuts **immediately** switch windows/applications without having to press tab twice.

This could perhaps be via checking a boolean/checkbox under the Controls > Shorcut N (Tab) that reads "switch to next window immediately upon shortcut activation" or something similar.

Keep up the great work!

**Comment by lwouis** [comment]
Hi,

This is happening because you set `Window order: alphabetical`. Indeed, if you keep the default order: `Recently Focused`, AltTab behaves as most users expect. If you switch to any of the less used orders, AltTab will display with the last focused window pre-selected.

This is because when using another sort order, the user may not necessarily want to cycle to the right when showing AltTab. In your case, with the alphabetical sort, you may want to show AltTab, then decide to cycle left toward a particular window. There is no way to tell if going right or left is useful. It's different with `Recently Focused` since the user will most likely want to go back to a previous window. So we anticipate that and cycle right. Can't anticipate that with alphabetical sorting, and the other sorting.

I hope this explains things for you.

Thank you 🙇

**Comment by GrayedFox** [comment]
That all makes sense! True indeed. I think there's an argument to assume that a user that's opted into alphabetical sorting may also want to opt into alphabetical focus switching, that is, in the order from left to right the windows are ordered in (ascending alphabetical, descending alphabetical). But I see now that it's not as simple as a preference box as there's too many outliers.

I just switched back to most recent window for now which I'm happy with 👍🏽

**Comment by khanakia** [comment]
I am looking also for something when arranged in alphabetical ordering. It should switch to the next available window
