### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by danielbascunan** [lwouis/alt-tab-macos#3364]
can we write a gnome and kde version of this app?

**Comment by lwouis** [comment]
Hi,

Do you mean if I could do it, as in, you'd like for me to do it? Or do you mean if it's ok if you port the app yourself, as in, asking permission?

I have no plan on implementing this app on Linux since I'm only using a mac these days. I would encourage anyone porting it on linux though. There already exist implementation though. Also, this app is very macOS specific. Lots of OS behaviors would differ on Linux. Also lots of OS APIs would be different. It's not portable by any mean. It would be a rewrite for a completely different environment. Very little code could be reused.

Thank you 🙇
