### ISSUE TITLE
Start "max width in a row" slider scale from 0%

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#3412]
Would avoid visual glitches like this - where you move the min width slider and the max width slider also moves despite the fat that its number doesn't change (or have a smaller % be located more to the right than a larger %)

https://github.com/lwouis/alt-tab-macos/assets/12956286/84628638-b499-40d6-b3e4-22f37d354691

Instead max width slider scale should start from 0 like all other sliders, but you should be just unable to move the slider below "min width"

**Comment by lwouis** [comment]
Thank you for reporting this issue.

The sliders in general are part of a bigger problem: 80% of users don't understand, or take time to understand, that tab. It's a lot of sliders and values. It's powerful because of lot of the layout system is exposer. On the other hand, it's not usable/used by many users, because it's too much, and the UX is generally bad.

If I take time to work on such issues, I'll tackle #351, which revamps the whole tab, which something much nicer.

Thank you 🙇
