### ISSUE TITLE
Allow user to "pin" certain apps 

### ISSUE THREAD

**Issue by JerkyTreats** [lwouis/alt-tab-macos#3425]
Being able to pin say, Iterm2, slack, etc. to always be first in the list would be pretty useful.

**Comment by lwouis** [comment]
Hi,

This topic was discussed in https://github.com/lwouis/alt-tab-macos/issues/515 and I think #337 as well.

The bottomline is that it's too niche. Too few people would use it. In addition, the UX would be questionable.

You can't really pin windows since they are created and deleted constantly. A new window is not the old window back. It's a new one. So as soon as the window would be closed, you would lose it being pinned. You would need to re-pin the next one after it's opened/created.

Let's say we pin apps instead. You pin Slack then Safari. So every new Slack window is leftmost in AltTab now, then Safari windows, then the rest of the window, in most-recently-use-to-least-recently-used order? So now you press AltTab. Let's say you're now in position 5 or 6. You would need to cycle Backwards 4 or 5 times to get to the Slack windows. It's perhaps easier to locate visually, since it's pinned, but it's inconvenient to navigate to since the current selected window would be to the right.

I'm afraid this is too niche, asked by too few people, to be implemented. Sorry about it!

Thank you 🙇

**Comment by xzbdmw** [comment]
I searched the "pin" keyword to find this issue, but with another idea similar to https://github.com/lwouis/alt-tab-macos/issues/210. One popular category of plugin in neovim is [harpoon](https://github.com/ThePrimeagen/harpoon) or [arrow](https://github.com/otavioschwanck/arrow.nvim), in short, they allow you to pin a buffer with a number, and navigate among them with leader key + number, and I wander alt-tab could extend this to OS level.

The imaginary flow is that, I have 3 windows open in chrome, two windows open in excel, and I constantly switch between the 5 windows, the current design requires me to tab 1-4 times to identify the window I want to open each time.

To improve this, how about introducing a concept of pinned space, with a different keybinding, say <control-;>. You press the key, brings up all and only pinned windows, then press 's', save the current window to the list, the number associated with the window growths in order, let's say 3. Next time when you want to go back to this window, press <control-;> + 3, without thinking, you are done.

- the UI could stay unchanged except a number along with the title
- remove the pinned item if the window is closed
- if current window is already in list, press 's' remove it from the list
- control-j/shift-down and control-k/shift-up to reorder items
- the item order is freeze unless you add/reorder/delete it
- in normal alt-tab use case, we can still show a number hint to those who are pined before

> The bottomline is that it's too niche

Maybe you are right, anyway, share my thoughts here 😄

**Comment by lwouis** [comment]
Thank you @xzbdmw. I linked this very interesting concept here: https://github.com/lwouis/alt-tab-macos/issues/210

**Comment by truhanen** [comment]
> It's perhaps easier to locate visually, since it's pinned, but it's inconvenient to navigate to since the current selected window would be to the right.

@lwouis, I think It's not inconvenient to navigate when using "Select windows on mouse hover". With that setting on, showing pinned apps in a static location would improve usability.

Another way of achieving a similar feature would be an "Order windows by" setting like "most focused first".
