### ISSUE TITLE
iterm2 exclude from dock and alt-tab

### ISSUE THREAD

**Issue by huyhoang8398** [lwouis/alt-tab-macos#3426]
**Describe the bug**

Im using iterm2 as a dropdown terminal and in iterm2, there is an option to exclude this application from showing in alt-tab and dock

**Screenshots / video**
![image](https://github.com/lwouis/alt-tab-macos/assets/25379882/0f1879ac-2739-4310-8c35-7232eb33e669)

<img width="2048" alt="Screenshot 2024-06-11 at 23 15 34" src="https://github.com/lwouis/alt-tab-macos/assets/25379882/66b2face-3d93-4b2e-bdce-caef82b7049e">

It work with default macOS application switcher but not alt-tab application

**Steps to reproduce the bug**

1. Go to iTerm2
2. Enable exclude from task switch
3. Test

**Your environment**

* AltTab version: Version 6.70.1
* macOS version: 14.3.1 (23D60)

**Comment by huyhoang8398** [comment]
My solution for now is exclude iterm2 directly from the alt-tab application

**Comment by lwouis** [comment]
Hi,

Excluding from the App Switcher probably means that they don't show an app there. The App Switcher shows apps, not windows. I'm not very familiar with iTerm2. I assume if you check that box, they don't create a secondary app, or simply hide the main app.

AltTab also hides its app icon from the App Switcher and the Dock. Again, it has nothing to do with windows. It's about hiding apps.

AltTab shows windows. If iTerm2 generates windows, they will be shown in AltTab. I see you used the Blacklist feature to exclude those.

Let's close the ticket since there is no action to take 👍 

Thank you 🙇
