### ISSUE TITLE
macOS 15 Stuck on video recording permission

### ISSUE THREAD

**Issue by Xytronix** [lwouis/alt-tab-macos#3427]
**Describe the bug**

Alttab requests permission for video recording, although it does have the permission. The application can't be closed as a new window appears when trying to close the application.
I had to kill dozens of Alttab processes and restart the app manually to be able to use it. It opened up a dozen ones.

**Steps to reproduce the bug**

 Open Alttab after installing macOS 15

**Your environment**

* AltTab version: 6.68.0
* macOS version: 15

**Comment by flexlixrup** [comment]
I think this is related to the daily(!) popup I get if the App is still allowed to record my screen. But I guess thats a bug that it occurs that often.

**Comment by Xytronix** [comment]
Weirdly enough that happened with other apps too, so I guess that might be related to accessibility tweaks in macos 15

**Comment by lwouis** [comment]
Hi,
Thank you for reporting this issue. Apple has bugs every single new macOS release. I always wait for the beta to be out, and sometimes the next weeks with the hotfixes. After that, bugs are typically fixed on Apple's side.
Closing this ticket since it's most likely a macOS bugs, since it happens with other apps.
Thank you

**Comment by lwouis** [comment]
Hi,
Thank you for reporting this issue. Apple has bugs every single new macOS release. I always wait for the beta to be out, and sometimes the next weeks with the hotfixes. After that, bugs are typically fixed on Apple's side.
Closing this ticket since it's most likely a macOS bugs, since it happens with other apps.
Thank you

**Comment by Xytronix** [comment]
@lwouis 
> This is not due to a bug in macOS 15, this is due to the following per Apple's documentation and enterprise support recommendations:
> 
> > Applications utilizing deprecated APIs for content capture such as CGDisplayStream & CGWindowListCreateImage can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to ScreenCaptureKit and SCContentSharingPicker. (120910350)
> 
> https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#Deprecations
> 
> This was announced in 2022 with Sonoma beta, and the experience was so poor Apple removed the notifications in favor of the next OS (now 15, Sequoia)



> Looks like it's this line:
> 
> https://github.com/jordanbaird/Ice/blob/79a833ee963b0d99a2798dbe10bd782f263569c8/Ice/Bridging/Bridging.swift#L221
