### ISSUE TITLE
Thumbnails should be vertically centered

### ISSUE THREAD

**Issue by alinalihassan** [lwouis/alt-tab-macos#343]
**Describe the bug**

Upon pressing Option+Tab, the windows do not appear to be centered vertically.

**Screenshots / video**

![AltTab](https://user-images.githubusercontent.com/4151505/82371362-5c80e600-9a1a-11ea-8a85-edc797143a21.gif)

**Steps to reproduce the bug**

1. Install the latest version of AltTab
2. Press Option+Tab and see for yourself

**Comment by lwouis** [comment]
Hi @hassanalinali! Thanks for taking the time to share this feedback!

The vertical alignment is intentionally top-aligned instead of center-aligned. This is the first time someone seem to have an issue with top-aligned. I was intrigued, and checked other apps:

* HyperSwitch: bottom-aligned
* WindowsSwitcher: center-aligned
* Windows 10 alt-tab: top-aligned

I started this project as a clone of Windows 10 alt-tab, which I love. That's why the thumbnails are top-aligned today. As often with UX choices, my thinking was that Microsoft has done UX research and user studies to decide these things, and copying it is the safe option when in doubt.

What would be the benefits of center-aligned over top-aligned?

Right now it seems to me like it could be yet another preference. I don't know how to handle the growing number of preferences though. The preferences panel UX is becoming bad for casual users.

**Comment by hassanalinali** [comment]
Hey @lwouis, I understand now what you mean. I honestly thought for a second that it is a bug since the built-in Application Switcher and HyperSwitch (from which I just switched to AltTab) are both centered vertically. If it is on purpose and there's no plan to offer an option in the preferences, then I assume we can close this issue. I could also consider making a PR with this enhancement if you would consider it appropriate.

**Comment by hassanalinali** [comment]
This might be off-topic, but I forked the repository and was looking for some other possible improvements, like making the window padding a preference and things like that, while trying to keep the preference list at a decent minimum. Would you like some collaborators and if so, what would be the next steps for Alt-Tab where I could contribute?

**Comment by lwouis** [comment]
Hey @hassanalinali! Collaboration is very welcomed on this project!

There is no clear roadmap at the moment. Feel free to tackle any open issue. As the app is getting more robust and mature, there are only a few bugs remaining. I had in mind to prioritize these 2, as they have the most conversation happening:

* https://github.com/lwouis/alt-tab-macos/issues/239
* https://github.com/lwouis/alt-tab-macos/issues/157

That being said, they may be quite challenging for a newcomer to the project. Some other tickets would be much easier for sure. As I said, feel free to pick any ticket you have personal interest in.

Regarding this current ticket, and the you mentioning adding another preference for window padding: I'm read complaints from people that the current preferences are too overwhelming. Imagine you open it the first time, you see 20 sliders and checkboxes, and just close it immediately.

I think I'll open a ticket soon to discuss how this can be improved. It's very challenging to keep the app flexible, while keeping its preferences reasonable. One way to do it is to have "normal" and "expert" modes. Normal mode would be macro preferences wherein each choice corresponds to a set of preferences (e.g. "macOS theme" = no borders, black background, rounded corners, etc). You could then switch to "expert" mode, and all the details would be exposed for maximum flexibility. It's quite a lot of work though, and I'm not a fan of these modes in general.

What I was more appealed by would be to introduce a richer UI for preferences where the preferences are communicated in a more visual manner. Let's say we split the preferences tabs more, and within the "layout" tab, you have a diagram representing AltTab main window, and if you move a slider like window padding or number of windows, you see the diagram update in real time, illustrating the change. It is quite a lot of work though, which is why I haven't done it yet.

Let me know if you decide to work on something, that way we avoid working on the same thing at the same time 👍

**Comment by LazarLazarov** [comment]
Hello, I also find the top-alignment to be more jarring than both center or bottom aligning. Ideally having a drop-down to choose the alignment would best, but I do also understand the issue of being overwhelmed with options. Would maybe adding an "Advanced options" checkbox that reveals such settings be a possible solution?
