### ISSUE TITLE
Simplifying the preferences UI

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#351]
I was responding on #337, and realized it's been a theme recently, and I feel the need to take some time to steer this project. Here is the situation as I see it. This is a copy/paste of my answer of the ticket I just mentioned:

AltTab is a port of Windows 10. As such, it shows windows in chronological order. While I believe it to be the best general approach for productivity, I'm open to introducing other workflows to the app. People have suggested direct access for instance (#210).

The issue however with adding more workflows into the same tool, is the explosion of preferences. The tool already has a large number of preferences because I find myself wanting to let people have it their way, and be empowered. The downside of that is that the tool is becoming unwelcoming/overwhelming, especially to new and more casual users.

Let's imagine we add a new preference to group the windows by app. That's yet one more preference. Now in your example (Pic 5), you say that the windows for each app could be ordered based on the screen they are on. Some people may prefer that they be in chronological order, instead of based on which screen. Actually if you have multiple windows of the same app on the same screen, you need to sort them anyway, and chronological seems the way to go. My point being that we are already talking about adding 2 new preferences here.

Another issue is that I decided our of principles to have 0 telemetry in the app, website, etc. This means that I have 0 statistics on users preferences, usage pattern, etc, outside of the active people like you who take the time to discuss on the Issues here. I think everyone would agree that adding a preference to accommodate 1 person is not the best idea. Preferences should be useful to a bunch of people. However as I said there is no way to know even if current preferences in the app are of any use.

Really, I'm not sure how to pilot this project forwards without data. I all falls down to my judgment in the end since I'm the main contributor. It's not necessarily a bad thing btw to not follow data. Data is why fast food in the US is so big. They optimize demand and human feedback for caloric-rich food, and now they have a terrible obesity problem. I rather like the idea of not always optimizing for real-world usage as people's habits may not be the direction we should reinforce.

I'm inviting everyone to feel welcome to share here their vision on where the project should go, in terms of features, flexibility, UX of the preferences, richness vs complexity, etc.

**Comment by borna761** [comment]
I really appreciate you taking the time to think this through before just going ahead and implementing all the suggestions and ideas that people come up with.

My suggestion would be to perhaps have a toggle of a simple/advanced mode? The simple mode could have the current functionality (or perhaps even some of it removed to make it even simpler?), and the advanced mode could have the extra functionality that has been asked for.

Mind you, I'm not a UI/UX expert, so I don't know how good of an idea this is in terms of usability, but it's an idea that would allow you to respond to the community's requests while maintaining the original simplicity of the application.

**Comment by mfn** [comment]
For me the "project direction" would be to replace HS (HyperSwitch).

I still have to in fact use both, primary reason is that AltTab does not support per-app window switching at all; which IMHO is _the_ killer feature. Don't remember the exact reason, but I think AFAIR it was that AltTab mimics Windows behaviour which doesn't feature this at all. Obviously to me a big disappointment because, as mentioned, per-app windows switching is the absolute killer feature which learned to massively loved after 20+ years of Windows and then coming to OSX half a decade ago.

**Comment by lwouis** [comment]
@ribrob A survey is an interesting option. I'm not sure if enough people would take it though. In many ways, there is already data in the shape of issues, and activity on issues. There are around 30 tickets open right now, and almost all of them are suggestions for enhancements that people made. While I would love to include all these, I feel it would bloat the app, and make it less usable. This is why I opened this very ticket, to discuss how we can have more features, without overwhelming the users. Maybe split the app in multiple apps, many have normal/advanced preferences, etc. Also, which feature get implemented next as you said.

@borna761 modes are a good candidate to allow simple/advanced users to use the same app. An issue with modes is that for the advanced mode we still need to maintain the long list of preferences, meaning code complexity is not tamed. Also I've seen a few apps for which I personally think the modes are terrible. An example that comes to mind right now is VLC. The advanced mode is really complex, and the relationship between simple and advanced is not clear. In our case, would we have bridges? By that I mean let's say in simple mode we have a preference for how big the UI is: small, normal, large. Each of these would be a "macro-preference" that affects multiple preferences in the advanced mode, such as: "max size on screen, max windows per rows, rows of windows, etc". They could also be distinct, so that setting in one mode doesn't interfere in the other mode. Not sure, but whichever decision, there is a bunch of work required. Also modes don't have to be global like VLC. It could be that some preference tabs have a switch to get simple/advanced preferences. Keyboard shortcuts for instance don't seem like they would need any modes.

**Comment by lwouis** [comment]
I thought about this issue of the preferences being unwieldy.

What I want to do, is *illustrate* more. Instead of showing text and more text, having illustration of a preference impact.

This issue is mainly about the Appearance tab. It contains a lot of sliders which I think people don't understand clearly by their wording.

I would like to have section like "main window layout" where there would be a simplified drawing of AltTab main window, and as you move cursor for fewer and more rows, you see the distribution change on the "preview" drawing. That way you get a sense of how the preferences impact layout.

Another about "thumbnail layout" where there would be a simplified drawing of one thumbnail, and you can see all the UI elements you can disable/enable on it.

With this visualized UIs, there can be even direct manipulation of preferences. For example you could click directly on the 3 colored circles on the drawing to disable/enable it. It would then show at half-opacity if disabled. Another option is to have a line going from the visual to the traditional label + checkbox.

I want to do these, but it's really hard to do this kind of UI work, so I don't know when I'll get to it.

If you're interested in contributing here, please let me know! 👍

**Comment by lwouis** [comment]
Previously, I described "simplified drawings". These could dynamic drawings that are done on-the-fly depending on the preferences. The later is hard to implement obviously, and we would need a way to let the user preview how it would behave with more/fewer windows. That's complex.

An alternative would be to somehow screenshot the full screen, and compose on top of it a screenshot of what AltTab would show if summoned right now. We would put that "preview" on the preferences panel on the right, and simply refresh the screenshot if the user changes a preference. It's "simple" to implement, and would show actual windows from the user, helping them customize for their actual situation, monitor size, etc.

Another way I thought about, maybe in addition to the above, would be to make static images to illustrate each preference. They could be shown upon hovering each preference label, or a question mark icon next to it. That way we illustrate situations that the wouldn't manifest in the preview (e.g. the user doesn't have enough windows to get a scrollbar in AltTab's UI).

**Comment by lwouis** [comment]
Following up on recent discussion, I think we should have "presets" to simplify things. That is, instead of exposing every possible tweak and slider, we group things in use-cases. For instance, I like the approach of first asking the user which general UX they want:

* Thumbnail focused (as currently done)
* App icon focused (big app icons, like the built-in switcher)
* Text focused (vertical list of window titles)

Then depending on their choice, we would offer different sub-preferences. We could reduce options here are as well like instead of letting users pick how many rows, and width and height, etc; we could ask them: "small", "medium", "large", a bit like what macOS does for display scaling:

![image](https://user-images.githubusercontent.com/106195/171148945-7f6706bb-72a6-400f-ba98-433295410d97.png)

@metacodes if you're interested in this, could you draft some mock designs? Like pen and paper or even ascii art where you would sketch how the new UI would look like? I think it's important we agree on the target before any effort is put into the implementation.

**Comment by metacodes** [comment]
> if you're interested in this, could you draft some mock designs? Like pen and paper or even ascii art where you would sketch how the new UI would look like? I think it's important we agree on the target before any effort is put into the implementation.

OK, I will try it.

**Comment by metacodes** [comment]
@lwouis This is the current design for the `Thumbnail focused` theme. I referenced the design of HyperSwith's configuration options. I'm not a professional UI designer, I just learned sketch, there are still a lot of shortcomings, please forgive me.
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/3339872/173170747-09b8d885-5c74-4cf8-adfe-e5c0e5fdab3f.png">
I extracted some common options of the three themes and put them at the top, the bottom will show different configuration items according to different themes.

The remaining two themes `App icon focused` and `Text focused` configuration items I have not yet considered clearly, do you have any ideas?

**Comment by eugenesvk** [comment]
> The tool already has a large number of preferences because I find myself wanting to let people have it their way, and be empowered. The downside of that is that the tool is becoming unwelcoming/overwhelming, especially to new and more casual users.

Can you hide some advanced preferences in the text config files? Then the casual users would see their acceptable amount of **10 preferences** in the GUI and the more advanced users can open the config in a text editor and tweak the **other 90** (numbers are just for illustration)?

**Comment by ElhemEnohpi** [comment]
Regarding the idea of simplified presets:

I've used Firefox's "control-tab" switcher for many years. I'd like AltTab to look as much like that as possible, just because that's where my eyes go, and what my brain is used to... I've come pretty close with the Appearance settings - a single row with (almost) max screen width, and max seven thumbnails (though I would actually like more customizing - title below the thumbnail, thumbnails window centred vertically, icon in the bottom right, etc., but that's another story.) So if you're making presets, it would be nice to have one something like this, or at least, to not lose the ability to get it as close as I have it now. Or, as the comment above mentioned, maybe some kind of text file or style sheet option for more detailed customizing.

**Comment by lwouis** [comment]
Today I was inspired to work on this ticket, after the [discussions here](https://github.com/lwouis/alt-tab-macos/issues/1025#issuecomment-1317368854) with @ElhemEnohpi. I took some time to consolidate my thoughts about where this ticket should go. I draw some UI sketches, and recorded a [video to explain the current situation, and my idea of the future](https://youtu.be/0fNLSPNrYng).

Please feel free to share feedback. It's a first draft. There is clarification required between the first part (Layout) and the second part (Preview). I think we should first show the user the Layout choice, and when they pick one, it would show them the Preview choice. And they could customize by adding back some removed features for example. And if they would go back to the Layout, it would reset that process. That's one way. More thought is needed there.

To be honest, I probably won't have the time to go through and implement this. See #1179. I can discuss the UX and help with implementation, but I know for a fact that it would be quite a lot of work to implement, so I'm looking for someone motivated.

**Comment by muescha** [comment]
for the other settings you described in your video -> it would also nice to have a preview of this settings. maybe if i hoover over a setting with the mouse an overlay (maybe below the settings dialog) should be visible with the current state and then if a user tweak the values it should show it direct.

just now i can change a value, need to activate it with option-tab to see the change (if i not understand what i am changing i have to find out what changed exactly - at first glimpse its difficult to see) and then i need to restart the alt-tab app because they is closed when i alt tab away from it.

**Comment by mindyourlifeguide** [comment]
@lwouis  You can try to be inspired by the main menu example, as in [kde](https://www.debugpoint.com/configure-task-switcher-kde/).

[This option](https://www.debugpoint.com/wp-content/uploads/2022/02/Compact-Task-Switcher.jpg) vertical menu with the preview window selected is the most convenient, as for me

**Comment by towerofnix** [comment]
It can be tricky to figure out a good approach for simplifying an existing UX without knowledge of where users currently struggle! Have you considered, if it's at all within your reach, performing some "playtests" where you share your app with individuals, give them a goal like "explore the preferences pane and configure AltTab to work how you want it to," and casually observe what they do to reach that goal? Generally, no providing guidance, just watching how they figure it out on your own. It really helps to identify "pain points" and discover some users' own experiences of the app! Watching how others interact with the thing you've spent dozens of hours poring over really helps show you it in a different, outside perspective, and can reveal problems and potential solutions you missed before.

(The way I usually do this is by showing my project to family or friends and being physically near them or on a screen-sharing voice call as they explore it, usually for the first time. I totally understand if it's not an approach you have access to, just thought I'd recommend it since it's been very helpful for me in the past!)

<hr>

Personally, I feel visual explanations for behavior-altering options is extremely useful. The older animations in the Trackpad section are a big inspiration to me. [This video from MacMost shows them off.](https://www.youtube.com/watch?v=n8FISXr-Ocg) Those gif/recording embeds are great for trackpad gestures since they're very animated, over-time/transitionary movements, and that doesn't translate directly to AltTab. But they have another advantage: Since they're recordings, they have an advantage of having an "ideal" setup.

For example, the "Show windows from: Visible Spaces" option is challenging to explain because some users don't know what Spaces are, and many only work on one Space. So if you use a "live preview" of the AltTab switcher, then there will be no difference between "Visible Spaces" and "All Spaces", because there is only one Space. A recording has the advantage of showing what the option actually does in an environment where there *are* multiple Spaces. Or an environment where there are multiple monitors, each of which has its own Spaces.

They're basically bite-sized tutorials for each option, shown in a simple way which demonstrates the usage in a way which is easy to digest and consistently demonstrative because it's a recording. They also add some visual flare to the preferences pane and make you not feel like you're "left alone" to attempt to understand the label and dropdown in front of you, which goes a long way to make a complicated settings screen with many options feel more friendly.

There are some other smaller ideas I have but I'd like to think about them more and stick them in separate comments, and share this relatively complete idea (and the suggestion about playtesting) sooner.

**Comment by afefer** [comment]
> Can you hide some advanced preferences in the text config files? Then the casual users would see their acceptable amount of 10 preferences in the GUI and the more advanced users can open the config in a text editor and tweak the other 90 (numbers are just for illustration)?

I love this idea - Visual Studio Code, for example, does a great job of allowing for an "explosion of preferences" (as you put it, @lwouis) by allowing virtually infinite customization through a settings.json file. The actual preferences window with a UI simply writes to the same settings.json behind the scenes.

I suspect that most users of AltTab who care about the more esoteric settings are technically savvy users anyway, and shouldn't have a problem working with a json file or something similar. I think this approach is a great "best of both worlds" in that you can have virtually unlimited preferences/tweaks (which lots of people are asking for), while also achieving your goal of a simple, user-friendly preferences UI for casual users.

**Comment by joshuakaufman** [comment]
Adding my feedback to request AltTab Appearance preferences that allow me to:

1. Remove "Window title" completely
2. Show all app icons on a single row 

This will enable AltTab to emulate how the default macOS switcher works with improved functionality, which is what I imagine many users, including myself, are seeking. Thanks!

**Comment by lwouis** [comment]
Hi everyone following this thread,

@Allsochen has be working hard for months now on a big Revamp of the Preferences!

He has redone **a lot** of the preferences UI. It's now much simpler, full of visual illustrations, and should provide a much better experience for users.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/271c1ea0-60d7-45a7-ab27-a3fdc9fa4b6b">

<img width="672" alt="image" src="https://github.com/user-attachments/assets/328d5fa4-ae66-4cec-82bf-a1b5c946638d">

<img width="672" alt="image" src="https://github.com/user-attachments/assets/d96e9a46-8117-4a9c-a722-4d20961810cc">

<img width="672" alt="image" src="https://github.com/user-attachments/assets/8e60d586-9e2b-4c3b-8938-7f14219b99c1">

If you're interested, could you please try out [this local build](https://drive.google.com/file/d/11C7DqHiRwDa_VbFj6EBn7BcpW-8xfpNy/view?usp=sharing), and share your feedback here? Especially if you find issues with the build?

Thank you!

**Comment by sizhky** [comment]
It's exactly as I wanted and expected. I'm trying the app for the first time and didn't like the choice of preferences initially. Luckily found this thread and installed the build. All the settings are really well organized!

**Comment by knoajp** [comment]
The local build looks better!! 🤗
Especially when I activate it on my sub-monitor, which is 20" 1600x1200, much smaller than my main monitor 40" 3840x2160. (It was hard to customize to look good on both monitors with public build)

I want the window thumbnails should be all in the same rectangle area, rather than changing the width of the size depending on its window aspect ratio. The window layout looks so ugly when one of the windows has a short-and-fat aspect ratio. Also, if a window has a tall-and-thin aspect ratio, I don't want the area of the thumbnail to be squished, but the thumbnail to be shown with gaps on both the left and right sides. "Even spaces for each thumbnail" gives me a better glance.

**Comment by sebastianvitterso** [comment]
Hey! Loved the new preferences-UI, looks really good, and the previews are magical!

One gripe I have, though, is that on my work machine I generally always have 6 windows open (chrome, vscode, slack, teams, outlook and terminal). Before, I had my setting set to "width=6" (or whatever it was called) and it fit my screen perfectly in one row when I had 6 windows open. 
Now it only fits five full-screen apps in medium size, and in small it fits seven. Would it be possible to have a way to have an "advanced setting" for this, to allow me to more finely tune the size of the windows? So I could have "small point five" as my setting 😄 .

**Comment by Allsochen** [comment]
> Hey! Loved the new preferences-UI, looks really good, and the previews are magical!
> 
> One gripe I have, though, is that on my work machine I generally always have 6 windows open (chrome, vscode, slack, teams, outlook and terminal). Before, I had my setting set to "width=6" (or whatever it was called) and it fit my screen perfectly in one row when I had 6 windows open. Now it only fits five full-screen apps in medium size, and in small it fits seven. Would it be possible to have a way to have an "advanced setting" for this, to allow me to more finely tune the size of the windows? So I could have "small point five" as my setting 😄 .

I understand that you have this requirement, but maintaining the original custom resize will become very complicated, which is why this reconstruction is done. I hope you can understand it. I hope that after using it for a period of time, you will like the new version. 😄

**Comment by knoajp** [comment]
After using the local build, 6.73.0 was pretty good at showing thumbnails at even spaces.
Now 7.0.2 shows thumbnails with each window's aspect ratios again. 🙃

> I want the window thumbnails should be all in the same rectangle area, rather than changing the width of the size depending on its window aspect ratio. The window layout looks so ugly when one of the windows has a short-and-fat aspect ratio. Also, if a window has a tall-and-thin aspect ratio, I don't want the area of the thumbnail to be squished, but the thumbnail to be shown with gaps on both the left and right sides. "Even spaces for each thumbnail" gives me a better glance.

**Comment by sebastianvitterso** [comment]
It looks particularly bonkers when you're copying a file
![image](https://github.com/user-attachments/assets/962c6baa-2190-469e-96d5-43071ddfc734)

**Comment by lwouis** [comment]
Indeed, there were 2 changes with v7.0.0:

* The maximum width was increased from 30% to 90%. This creates these huge tiles.
* The minimum width was reduced from 15% to 0%. The tile can be as thin as the thumbnails

You can see both extremes here:

<img width="1247" alt="Screenshot 2024-10-18 at 00 34 14" src="https://github.com/user-attachments/assets/9c23af3a-a962-4a54-be57-ec889b27b461">

The wide item is too wide and takes too much space compared to the others
The tall item is too narrow and we can't see any of its title

@Allsochen  We should probably go back to previous values (15-30%) for better usability

**Comment by Allsochen** [comment]
> Indeed, there were 2 changes with v7.0.0:
> 
> * The maximum width was increased from 30% to 90%. This creates these huge tiles.
> * The minimum width was reduced from 15% to 0%. The tile can be as thin as the thumbnails
> 
> You can see both extremes here:
> 
> <img alt="Screenshot 2024-10-18 at 00 34 14" width="1247" src="https://private-user-images.githubusercontent.com/106195/377652416-9c23af3a-a962-4a54-be57-ec889b27b461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQ1OTMsIm5iZiI6MTcyOTI0NDI5MywicGF0aCI6Ii8xMDYxOTUvMzc3NjUyNDE2LTljMjNhZjNhLWE5NjItNGE1NC1iZTU3LWVjODg5YjI3YjQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwOTM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODU4YzFjZjcwOTk5ZGU3NTRiOTQ2Yjk0OTdhODk5MTQzZmRlYmNiZTY3MjIxOGI4YmFhNjRjYzg0MDUyNjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vwE73NqgNM2DA5O2p8Wxb3Kxh-oBAjHgbjC-iYycVks">
> * The wide item is too wide and takes too much space compared to the others
> * The tall item is too narrow and we can't see any of its title
> 
> @Allsochen We should probably go back to previous values (15-30%) for better usability

The root cause is this code change. I have remove the minimum width to adapt the gap between two thunbnail
https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/main-window/ThumbnailView.swift#L564
https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/main-window/ThumbnailView.swift#L368
