### ISSUE TITLE
SentinelOne is blocking AltTab

### ISSUE THREAD

**Issue by ppatel-gh** [lwouis/alt-tab-macos#3527]
**Describe the bug**

I have a MacBook Pro provided by my company that has SenitnelOne software on it for malware protection and today suddenly AltTab stopped working for me, I get the following message when trying to run it.

"You can’t open the application “AltTab.app” because it may be damaged or incomplete."

so I uninstalled the app and downloaded the latest version from the website but when I try to install it I get the same error. I'm posting this here to see if others are facing this issue or not, if not then it's just likely my company's security policy changed and I might need to get in touch with IT.

I saw this closed issue that's also related to SentinelOne just a slightly different error message from mine - https://github.com/lwouis/alt-tab-macos/issues/2725

**Your environment**

* AltTab version: AltTab-6.72.0
* macOS version: Sonoma 14.5
* Other relevant info: e.g. I am using external keyboard connected via Bluetooth, and I have the MacBook connected to a monitors using a doc

**Comment by lwouis** [comment]
Hi @ppatel-gh,

I've re-read #2725. I think we've looked at every aspect of this issue on that thread. I conclude again that there is nothing AltTab can do to improve this. It's all about how this software is configured by each IT team.

AltTab itself does nothing shady. It is also signed and notarized by Apple. I pay 100 dollars every year just to have our users get a smooth experience downloading and opening the app. Some other FLOSS apps don't do that, and you have to jump some hoops to launch the app since it's not notarized.

If SentinelOne detects AltTab as a bad agent, it's definitely a mistake on their side. The app does nothing harmful.

Thank you 🙇
