### ISSUE TITLE
Little Snitch window not shown when "hide apps with no windows" is on

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#3535]
**Describe the bug**

Little Snitch is not shown in AltTAb when "hide apps with no windows" is on even though Little Snitch has its settings window opened

**Screenshots / video**

shows that LS is running/has a window opened, but not visible in AltTab

<img width="821" alt="Alttab LS" src="https://github.com/user-attachments/assets/1560369a-97a0-42d5-80ff-99b4bf6200a3">

**Steps to reproduce the bug**

1. Open Little Snitch
2. Enable "hide apps with no windows" in AltTab
3. Press Cmd-Tab

**Your environment**

* AltTab version: Version 6.72.0
* macOS version: Ventura 13.4.1 (22F82)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

If a window is not appearing in AltTab, it's most likely because it's not considered to be shown. This happens for HUD and other "not really a window we should show".

I suspect that this LittleSnitch window is not implemented as a standard window. You can confirm this using the Accessibility tool from XCode. You can also contact their customer support to confirm this and ask them to address the issue.

If AltTab is not considering this a window, it's most likely that other accessibility apps don't.

Closing this ticket as there is no action we can take on our side

Thank you 🙇

**Comment by eugenesvk** [comment]
Could you add an exception list of apps to the "hide apps with no windows" rule? Or have a "whitelist" in addition to the already existing "blacklist"? (this app never exists without a window)

**Comment by lwouis** [comment]
Unfortunately, this would be too niche. I suggest asking their customer support to address the issue. It must be affecting other accessibility apps in addition to AltTab. They should probably fix this issue

**Comment by eugenesvk** [comment]
Looked a bit more into this: this limitation is an intentional security config in LS since being accessible means other apps can change the firewall rules

Meanwhile I'll see if disabling this global option and adding apps in the blacklist could work (or require too many exceptions) if you think the blacklist mirror is too niche

(by the way, think this global option "hide apps with no windows" should be in the blacklist instead of appearances as it's about the same thing unless there is some subtle difference)

**Comment by starptr** [comment]
@eugenesvk fyi there is a (perhaps new) option in LS to expose its windows to other applications, including alt-tab. See https://github.com/lwouis/alt-tab-macos/issues/3591#issuecomment-2339337261

**Comment by eugenesvk** [comment]
Thanks, my last comment is about this option
