### ISSUE TITLE
Always show option for new finder window

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#354]
alt-tab-macos is great software - loving the enthusiasm and care to detail lwouis brings to the table. Hope it will be around for a long time 🙌

**Problem**
I much prefer alt-tab-macos over the default macOS app-switcher and assigned alt-tab to use the default app switcher keyboard shortcut ⌘Tab.
The issue now is, with all finder windows closed there is no way to invoke a new finder window from alt-tab using the keyboard. The default app-switcher always shows finder, even when no finder window is open.

**Describe the solution you'd like**
A possible solution could be, to always have the finder with "new window" option in alt-tab so when toggling app-switcher there would always be an option to create a new finder window via alt-tab without having to leave the keyboard.

**Describe alternatives you've considered**
I understand this might be a very niche use-case and not in the scope of what mac-tab is trying to solve. So no hard feeling if this gets closed.
As a workaround I try to keep at least one finder window open and minimized so it is out of the way when not needed. But old habits are hard to change and I keep finding myself with all finder windows closed, forcing me to leave the keyboard, and with the mouse opening the hidden dock and then click the finder icon there to get back to a new finder window.

**Comment by lwouis** [comment]
Hi @foss-! Thank you for the encouraging words!

Regarding the issue you describe, it's quite a tricky situation. Here are some observations:

* What about the same issue with other apps. Let's say I close all windows from Terminal.app. Terminal is still open, so the same situation happens. I just tested and many Apple apps close when you close the last window, but some don't like Terminal, Preview, and Finder or course. For Terminal, launching it again opens a new window, so you could use Spotlight or Launchpad to open a new window that way and stay on the keyboard. It doesn't work for Finder though.

* Your proposal is interesting. I don't like the idea of a special window, but Finder is quite a special app I guess. Where do we put the special window in the list? At the end of the list? If you have lots of windows, it will be kind of hidden after the scroll. How big would the window be? What would it represent visually?

* I think such a feature crosses the line between managing the existing windows, and initiating new windows/apps. How do you launch your Terminal for instance? AltTab is not launching apps, so you have to resort to a launcher. Either a built-in solution like Launchpad (which I use, for speed) or Spotlight, or a third-party one. It would seem logical to me that that launcher also handle opening new Finder windows. The built-in don't do it, but I'm pretty sure the third-party ones like Alfred or Silverlight can be customized to do so. My point here is that you need app launchers anyway if you don't want to use the mouse, so you may want to consider having these apps handle that use-case, as it's about new content, rather than navigating existing content which is AltTab focus currently.

**Comment by foss-** [comment]
Missed the most obvious way to invoke a new finder window. I never used Spotlight or LaunchBar to "start" Finder and now feel stupid 😬

Closing this issue and excuse for the noise.

> For Terminal, launching it again opens a new window, so you could launch it to open a new window that way and stay on the keyboard. It doesn't work for Finder though, through Spotlight/Launchpad.
Is that so? For me opening LaunchBar, entering "fin" and pressing enter does launch a new finder window, as does doing the same in Spotlight.

> Where do we put the special window in the list though?
Although obsolete, the idea was analog behavior to what the macOS default app switcher does, which is most recent from left to right.

Tapping into app launcher or window manage territory are interesting thoughts, although beware the feature creep and time needed to maintain things running smoothly. Although no objections to a nice open source window manager for macOS.

**Comment by lwouis** [comment]
I'd like to keep this issue open actually as a place to discuss/draft this idea in case it eventually goes into the app 👍

**Comment by lwouis** [comment]
Subsumed by #397
