### ISSUE TITLE
Adobe Bridge 2024 doesn't show up in AltTab

### ISSUE THREAD

**Issue by lawand** [lwouis/alt-tab-macos#3540]
**Describe the bug**

When I have Adobe Bridge 2024 running, and has one window, the app's window isn't listed in AltTab

**Screenshots / video**

In the current space, I have two Firefox windows and one Adobe Bridge 2024 window open and in focus. Only the Firefox windows are listed:

<img width="1280" alt="Screenshot 2024-08-07 at 18 54 31" src="https://github.com/user-attachments/assets/c526531f-ea06-4f3c-8e18-cac49031c4b4">

**Steps to reproduce the bug**

1. Run Adobe Bridge 2024
2. Open AltTab

**Your environment**

* AltTab version: 6.70.1
* macOS version: 14.5

**Comment by lwouis** [comment]
Hi,

This happens sometimes when an app is not correctly implemented. They implement windows using the wrong macOS building-blocks, and these are not technically windows, even though they may look like a window from the user's perspective. It happens often when they use cross-platform tech. Adobe does this for most of their apps, since they are often ported to macOS from Windows.

Could you please contact their support? There is nothing we can do on AltTab's side.

Thank you 🙇

**Comment by lawand** [comment]
@lwouis Ok I understand, thanks for the quick reply.
