### ISSUE TITLE
UX issue - "AltTab is capturing your screen"

### ISSUE THREAD

**Issue by Knocks** [lwouis/alt-tab-macos#3572]
For AltTab users, MacOs will regularly show a purple icon in the menu bar, and the message is "AltTab is capturing your screen."  This is both distracting and disruptive.  That area is reserved for important (or at the minimum, useful) messages, and users' eyes are trained to glance at that area to check if something important is happening.  You can't be showing a bright purple icon every time the app is capturing a new thumbnail.  That message is unhelpful and unneeded.

I've seen a few other issues over the last 2 years.  Some of them were closed because "This is a MacOS issue, deal with it."  This is not  a Mac issue.  It's an issue with the design of this app.  

As it stands now, the distracting notification is taking away any benefit I was gaining from being able to alt-tab between opened windows, and I will probably uninstall it in favor of the MacOS-native command-tab (even though it has inferior UI).

* AltTab version: 6.72
* macOS version: Sonoma 14.6.1
* Other relevant info: e.g. using external Logitech keyboard

**Comment by lwouis** [comment]
Hi,

This is indeed related to https://github.com/lwouis/alt-tab-macos/issues/3477.

As is discussed in this issue, this UI is under Apple's control. There is nothing we can do. We have to call APIs to get the thumbnails. When we call those APIs, the OS shows a warning to the user. If there was a way to hide it from our app, then we would be malware. The system is telling the users that we screenshot the windows. Which we do, in order to show the thumbnails.

There are potential solutions discussed in the other tickets, such as #1082 or changing to another API.

Please note that on Sonoma's release, the purple UI was showing way more. Apple has since patched it many times. It's now showing once in a while. There is a buffering approach now: it will show maybe once, then not show for a while. Then it will show again to remind the user.

Apple is changing that approach again in the next Beta. They have changed it a lot between the few Beta waves. Who knows what will be their final design.

Thank you 🙇

**Comment by Knocks** [comment]
Again, this is not an Apple issue. This is this app's issue. If the app behaves like malware, fix the behavior or redesign the app.  Hijacking the operating system's notification area is not an option from a UX perspective.

**Comment by lwouis** [comment]
Please suggest how we could improve things. Simply pointing out your frustration doesn't provide a way forward. Ways forward have been discussed in the ticket I linked. You seem to think we can fix this. Please share how **in details**.

Thank you

**Comment by Knocks** [comment]
The way to fix it is to get rid of screen recording, since Apple considers it sketchy behavior, unless you can engineer your way out of it some other way.

I am not expressing my frustration.  I am pointing out that it's categorically wrong to have a flashing icon in the notification area, because it's an indicator of a broken app and goes against all UI/UX conventions.

**Comment by lwouis** [comment]
> The way to fix it is to get rid of screen recording

Screen recording is necessary to achieve what the app offers: thumbnails and titles of the users open windows.

Are you proposing we remove thumbnails and titles? If so, this approach is discussed in #1082 as i've pointed out.

Are you proposing there is a way to keep thumbnails and titles without screen recording? If so, which way is that?

Thank you

**Comment by Knocks** [comment]
I am not an engineer and don't have the knowledge of all available APIs in MacOS. You have an usual approach of asking users who report critical issues to devise a solution.  Usually, users report issues and developers devise solutions.

I do know what's acceptable from a UX perspective and what's not, and the current way is not.  I have read #1082 in its entirety and saw users bickering with developers for 3 years, with nothing being implemented in the end.

Yes, getting rid of thumbnails/tiles, using another API, or coming up with another way are all possible solutions.  For now, I have disabled this app because the flashing icon was disruptive, and switched to Contexts.

**Comment by lwouis** [comment]
> I do know what's acceptable

I find the idea of "acceptable" here very rude. You come here and download a free app. I've poured thousands of hours of my free time crafting this. I decided to share it for free so other people can benefit from it as well. I don't ask anything of you. I pay 100 euros a year to Apple to get the app signed so users get a good install experience. What have you done for me? There is an imbalance here.

If you don'f like this app, no need to use it. No need to come here and demand a better experience.

You wouldn't come to a volunteer project like a dog shelter, and start complaining to the volunteer that the way they do things is not great for visitors. That they should really improve things. It's not acceptable this way. How rude is this attitude?

If you don't like something people are working on on their free time and sharing with others for free, you should either silently leave, or offer to help. Maybe after you've shown good behavior, you could start lightly raising issues. Once you've gained good-will with people in the community. It's very rude to start conversing with strangers and right away criticize their work. This is not a shop. You're not a customer.

Anyway i'm at a loss when i witness such attitude. Thankfully it's very rare. Most people are polite. The rate of such rude encounter is around once a year.

I think Contexts will suite you better. It's a commercial app. There is a customer support for you there. You are definitely welcome to explain to them what's acceptable to you. They may listen to you after you've paid them. Paying them contributes to improving their lives so it gives you some degree of rights to ask that they care about your desires.

**Comment by Knocks** [comment]
If you find it offensive that users provide valuable (and **indisputably valid**) feedback, you're best taking your product off GitHub, because apparently you have limited understanding of this platform.  The platform is set up for users to report issues.  You insist on serving a broken product and hide behind a volunteer.  No one gives a flying kite about whether you're paid or not.  You are still a developer who provides a product, which means you will hear feedback about it.  I provide several free products to hundreds of thousands of people, and when something is broken, I fix it, or at least acknowledge the issue.  Being a volunteer doesn't entitle you to talk down to users.  My feedback is valid, and if you surveyed 1000 industry professionals, they would tell you the same thing.  Thanks for helping me realize that this product is not for me.

**Comment by lwouis** [comment]
> GitHub, because apparently you have limited understanding of this platform.

> I provide several free products to hundreds of thousands of people

On Github, you have no repository. Where are these free products you talk about? Where are the github issues that you selflessly fix regardless of how people demand they be fixed?

Please show me your work on Github. I'd like to see how you do think and get inspired. Right now i'm confused because i open your profile and see no content and no engagement with the community which makes no sense to me after you told me you know Github better than me. Do you have multiple accounts? Where are your Github projects?

**Comment by Knocks** [comment]
I run a company that provides both free and paid products, and as already mentioned, we don't cry when people report issues. We say thank you. If you release something, you owe a responsibility to users, at the minimum that the product is not broken. Your dog shelter analogy is misinformed. Not charging end users for software does not make a you a volunteer.  You are a full-fledged publisher who uses a non-commercial license to release products. You also have a thin skin and can't take critical feedback, so GitHub is not the right platform for this product. Either shit or get off the pot.

**Comment by lwouis** [comment]
Please share a link to your company, so I can see your products and how you handle feedback.

**Comment by Knocks** [comment]
What else would you like, my home address, ATM PIN, social security number?  If I wanted to sell things on GitHub, I would have put a link in the bio.  In the discussion you linked earlier, you also attack other users for reporting issues.  Perhaps you should take a look in the mirror.

**Comment by lwouis** [comment]
I'm asking a link to your product website which you claim is free and has amazing support. I'd like to take a look for myself and learn.

This has nothing to do with your home address. You have full access to the product i'm offering here and 4000 tickets with users discussing it.

You're very confident about how right your position is. Please show everyone some concrete things now. Otherwise it's just words. My work is here in the open. I'm not hiding behind anything.

**Comment by Knocks** [comment]
You want users to doxx themselves because you are inept, entitled, and condescending?  Try again.
