### ISSUE TITLE
Windows-style top right X button?

### ISSUE THREAD

**Issue by TheHarmonicRealm** [lwouis/alt-tab-macos#3581]
I like this app a lot and there are many good customization options. One thing I do miss sometimes from Windows when using it is the top right "X" button to close windows that shows up when you hover the mouse over a window in the switcher, which turns red when the mouse is over it (screenshot is Windows 11; 10 had a similar feature):

![image](https://github.com/user-attachments/assets/ed6a3a15-7e87-4576-849f-f7f9e1556128)
![image](https://github.com/user-attachments/assets/bde66fcf-51ec-4c8c-9d5b-b30a94810642)

I know the app already has an option to show the Mac-style colored circles in the top left of but these are less natural to use as someone with a lot of Windows muscle memory. An option to show a similar X in the same place when the mouse is moved to the top right would be awesome (and additionally an option to also show buttons equivalent to the colored circles to the left of it or at least to minimize would be helpful!).

Thanks for making this! (I hit a shortcut and accidentally posted this before finishing writing it lol)

**Comment by lwouis** [comment]
Hi,

AltTab is attempting to look and feel as native as possible on macOS. That's why we stick with the same exact icons, and put them on the top-left.

I'm afraid we can't make it more like Windows like you suggest.

A workaround I can offer is that you can middle-click the windows to close them, in the AltTab switcher. Then you don't even need to reach for any icon 👍 

Thank you 🙇
