### ISSUE TITLE
Does not detect Little Snitch's open windows

### ISSUE THREAD

**Issue by starptr** [lwouis/alt-tab-macos#3591]
**Describe the bug**

I'm using the [Little Snitch and Little Snitch Network Monitor](https://www.obdev.at/products/littlesnitch/index.html) applications. For both applications, instances of its windows do not appear in alt-tab.

**Screenshots / video**

See below:
- Ignore CleanShot X; that appeared only for a few milliseconds to take the screenshot
- TextEdit correctly appears as an available window
- Neither Little Snitch nor Little Snitch Network Monitor appears as an available window

![CleanShot 2024-09-07 at 15 54 00@2x](https://github.com/user-attachments/assets/ab413865-4428-41f1-b6f8-c0da7b2a37c7)

**Steps to reproduce the bug**

1. Start the Little Snitch Network Monitor and Little Snitch applications
2. Open alt-tab

**Your environment**

* AltTab version: 6.72.0
* macOS version: 14.2.1
* Other relevant info: NA

**Comment by lwouis** [comment]
Hi,

I installed Little Snitch and tested things out.

I can confirm that this issue comes from Little Snitch. It has non-standard window management. Processes like the Network Manager are spawn only when you display the window. I think it's good to avoid using resources on the machine unless the user is activitely looking at the window. However, they must have made mistake implementing this.

When the window is open, the app declares having no window. Specifically, when AltTab does its call to the macOS Accessibility API, it returns `nil`. Nothing we can do about this.

Could you please open an issue with Little Snitch support, so they can investigate and fix this issue? Feel free to link to this ticket here with my analysis. I'll be glad to help them if they have questions.

Thank you 🙇

**Comment by lwouis** [comment]
Oh, I forgot that this has been discussed before!

Here is an explanation on what is going on: https://github.com/lwouis/alt-tab-macos/issues/3535#issuecomment-2268829773

**Comment by starptr** [comment]
Thanks for the thorough response! Sorry for the dupe issue; somehow missed that one. I sent them a message; let's see how things go.

**Comment by starptr** [comment]
This isn't too relevant to alt-tab, but very helpful info for Little Snitch users for posterity: there is an option in the settings to expose the windows to other applications including alt-tab! This worked for me.

![CleanShot 2024-09-09 at 16 39 54@2x](https://github.com/user-attachments/assets/968d48b2-3a09-4bd3-980c-df494db710e6)
