### ISSUE TITLE
7.0 window picker UI size too big

### ISSUE THREAD

**Issue by magdogg** [lwouis/alt-tab-macos#3658]
Hello, great app!

Since 7.0 the total area of the UI is too big for my taste, the picker takes up most of my screen and I don't see a way to resize it. I suggest going back to the size of 6.X or making it optional.

**Comment by Allsochen** [comment]
Hi, can you take a screenshot of the size you expect? The current thumbnail mode refers to the design on Windows, and the AppIcons mode refers to the design on macOS.

**Comment by lwouis** [comment]
@Allsochen [this other ticket](https://github.com/lwouis/alt-tab-macos/issues/3655) is interesting. This user's issue is that they have a very wide screen. On such screen, the picker will be very elongated.

I think we could study this, and maybe come up a UX improvement. I think for instance, that like a book, there should probably be a max width, so that the lines/rows are not too long.

I don't have such a wide screen. It would be interesting to test how Windows handles such screens, and how the built-in macOS switcher does it, and third-party apps as well.

**Comment by lwouis** [comment]
@Allsochen [another ticket](https://github.com/lwouis/alt-tab-macos/issues/3661) about this issue. In this other ticket, there seems to be an issue with vertical monitors in the Titles Style. I don't own a vertical monitor to test it, unfortunately.

**Comment by magdogg** [comment]
> @Allsochen [this other ticket](https://github.com/lwouis/alt-tab-macos/issues/3655) is interesting. This user's issue is that they have a very wide screen. On such screen, the picker will be very elongated.
> 
> I think we could study this, and maybe come up a UX improvement. I think for instance, that like a book, there should probably be a max width, so that the lines/rows are not too long.
> 
> I don't have such a wide screen. It would be interesting to test how Windows handles such screens, and how the built-in macOS switcher does it, and third-party apps as well.

Yes this is correct. Allthough I have a regular 32" 16:9 display and the picker is covering about 80-85% of the width. I think it's just too big in general. An option to scale the whole UI would be nice.

**Comment by simoheinonen** [comment]
I'd also prefer like 50% smaller icons. 43" monitor

![jee-min](https://github.com/user-attachments/assets/8cf4e6e7-d954-420c-8bda-45668fe0d91b)

**Comment by lwouis** [comment]
Hi @simoheinonen,
Could you please a screenshot of what the default command+tab switcher looks like on such a big display? That way we can have a reference point of how Apple handles this situation.
Thank you 🙇

**Comment by simoheinonen** [comment]
Here's the default. A little bit smaller than AltTab but still not small enough for my liking.

![jeenormal-min](https://github.com/user-attachments/assets/a58ade27-e00f-4519-85ad-372ac7732c4e)

**Comment by lwouis** [comment]
@simoheinonen what's been discussed above is that on a large monitor, it's uncomfortable to move the head laterally if the switcher UI is wide.

You mention you would like smaller icons. Are you sure that it is your issue here? How would you like it if we capped the width of the picker UI, so it started to form a second row. This way you would keep the UI in the center of the screen.

Thank you 🙇

**Comment by lwouis** [comment]
Let's keep discussions centered in this ticket: https://github.com/lwouis/alt-tab-macos/issues/3770 👍
