### ISSUE TITLE
With Thumbnails style, setting "Show titles" to "Application name" not working

### ISSUE THREAD

**Issue by aheckler** [lwouis/alt-tab-macos#3667]
**Describe the bug**

Setting the "Show titles" option to "Application name" is not working when using the Thumbnails style. It still shows the window title in the AltTab interface.

**Screenshots / video**

Recorded my screen showing the bug: https://cln.sh/L74KJZnXGy42bZSdMnC6

**Steps to reproduce the bug**

1. Open AltTab.
2. Go to **Appearance** tab.
3. Set the **Thumbnails** style.
4. Click the **Customize Thumbnails style...** button.
5. Click the **Advanced** tab.
6. Set the _Show titles_ option to "Application name".
7. Use your configured trigger shortcut to engage AltTab.
8. Notice that the window title is still used.

**Your environment**

* AltTab version: 7.0.0
* macOS version: Sequoia 15.0.1
* Other relevant info: N/A

**Comment by lwouis** [comment]
Hi,

Thank you for sharing this issue.

I was able to reproduce it. @Allsochen this may be the first logic-error bug after release. I imagine it should be an easy fix. Sorry I missed that during QA! 🙇 

Thank you

**Comment by lwouis** [comment]
<img width="695" alt="image" src="https://github.com/user-attachments/assets/c28dbeb7-ebfd-4370-b82b-89807dd7e68f">

We excluded that scenario in Thumbnails Style. I think perhaps we discussed not to include that setting for Thumbnails Style? Maybe that changed later, since it's available in all 3 modes currently. But we forgot to remove the `Preferences.appearanceStyle != .thumbnails`?
