### ISSUE TITLE
After upgrading to the latest version, I cannot customize the length, width, and height of alttab's interface at will.

### ISSUE THREAD

**Issue by Tinyu-Zhao** [lwouis/alt-tab-macos#3770]
**Is your feature suggestion related to a problem? Please describe.**
In the old version, I can customize the overall length, width and height of this window.
![WechatIMG1162](https://github.com/user-attachments/assets/5f3ec907-3522-4841-ab45-1b115556c369)

But in the new version I only have these three options
<img width="561" alt="image" src="https://github.com/user-attachments/assets/aa1953e5-f629-48e6-afbc-a6e6503ba37c">

**Describe the solution you'd like**
I want to customize the length, width and height of this window

**Describe alternatives you've considered**

**Comment by lwouis** [comment]
Hi,

We don't want to bring back all the sliders from v6. They are too confusing for 99% of users. I understand users here are the 1% power-users, so it's not a good feeling to feel power loss with v7.

We'd like to reach a middle ground. We don't bring back the full set of sliders and settings to configure things to the max. However, we improve on the current design by carefully adding: smart adaptations, and perhaps a few settings.

This thread showcases various use-cases linked to the layour of the switcher:

* Vertical screens (e.g. better layout for this aspect ratio?)
* Very large screens (e.g. make it confortable for the neck somehow? scale UI down based on resolution+DPI?)
* Titles Style (e.g. remove empty spaces in that Style? max width to avoid very long lines?)
* Small/Large Sizes may not be enough (e.g. introduce XS/XL?)

Thank you

**Comment by J-Siu** [comment]
For myself, regarding the "Tiles" style, one extra option for "Auto Width" will be good.
- If content width is less than max width, then use content width
- If content width is larger than max width, then use max width
- I think currently max width is certain % of screen width, no need to change

**Comment by Tinyu-Zhao** [comment]
When I connect an external monitor (32 inches), the width of the ALTTAB window reaches almost 90% of the screen width. I think at least the width can be adjusted to display the content in the middle as much as possible.

**Comment by guillaumebrunerie** [comment]
Hey! For me the issue I have with the new preferences is that the style I was using seems to have been completely removed. I had icons together with the title of each window, like this: (the screenshot is from a few years ago, but it still looked similar)

<img width="1169" alt="17302344820015039178358346178279" src="https://github.com/user-attachments/assets/cf0438cf-8307-474c-9e5a-14ec379f3089">

But now neither of the available options give this style. I particular I find screenshots hard to read compared to icons, icons only doesn't work well when I have several windows of the same app open, and the "Titles" option has way too small icons even in Large. Would it be possible to add a fourth option like the screenshot above?

**Comment by ntcho** [comment]
> scale UI down based on resolution+DPI?

Would love to see this. Font size of AltTab is way too big compared to all other applications with my current DPI settings.

I expected the ability to customize in the `Customize Thumbnails style...` menu — would it be too complex to add a `Advanced...` menu?

**Comment by lwouis** [comment]
@ntcho could you please show how AltTab looks on your setup?
Thank you

**Comment by Pederytter** [comment]
For widescreen users it's definitely a worse experience. 

You have to look further to the sides, which takes longer and takes more effort to find the right window.

I hope you find some kind of solution which support custom window sizes. Did the last configuration option confuse some people, since they were removed?

**Comment by Tinyu-Zhao** [comment]
> For widescreen users it's definitely a worse experience.
> 
> You have to look further to the sides, which takes longer and takes more effort to find the right window.
> 
> I hope you find some kind of solution which support custom window sizes. Did the last configuration option confuse some people, since they were removed?

I totally agree, not everyone only uses their laptop screen.

**Comment by lwouis** [comment]
@Pederytter @Tinyu-Zhao could you please show your setups? Perhaps show how you had it setup with v6 and the custom size?

Thank you 🙇

**Comment by Pederytter** [comment]
@lwouis That was a bit tricky. I have no idea how you take a screenshot while doing alt + tab but I did find a solution

V7
![image](https://github.com/user-attachments/assets/ea95ec0d-6347-4889-bd83-d49830db748b)

V6
![image](https://github.com/user-attachments/assets/30eac471-55bb-4065-9abb-8313fb36aabe)

**Comment by hicaicai** [comment]
@staneta I agree with most of what he said.
I need to add a few things, I think instead of being able to set the width and height, it might be more appropriate to be able to set the maximum number of apps that can be displayed in a row, and of course we could default to only displaying one row, and you could switch to other rows with a shortcut key. Here's my idea.
Now it works like this, one line is too much app, I don't need multiple lines to display.
![Snipaste_2024-11-04_13-37-58](https://github.com/user-attachments/assets/c47d397e-7d58-4a72-b614-ead8435b0bdd)

**Comment by mwpardue** [comment]
The new version is, quite frankly, terrible from a customization standpoint. You really should never remove options, especially options that so many used. A better middle ground would be to put all those options under an advanced menu. If it's too complicated for a user, they have no business in the advanced menu anyway.

**Comment by lwouis** [comment]
Power users is a spectrum. Even amongst AltTab users, some features are used by a few percents of users.

You can install any previous versions. They are all hosted here in the Releases section of the project 👍

**Comment by ynouri** [comment]
Thanks @lwouis for the wonderful work you made with Alt-Tab! I do agree with the comments above, and it's unfortunate to auto-upgrade and see the Alt-Tab design completely change. It really threw me off. I had to downgrade to 6.73 too.

The issue for me is not to be able to have an Icon + Title layout, like showed by @guillaumebrunerie above. Titles are extremely important to navigate multiple windows of the same application. I don't think it's a power user feature. Unclear if there's a way to achieve this version 7.x?

<img width="1353" alt="image" src="https://github.com/user-attachments/assets/4803d13c-c25d-43e8-b131-c555e0ca8d35">

**Comment by lwouis** [comment]
Hi @ynouri,

Currently, you can't get this exact layout. That's part of #351. We knew some layouts would be lost. The benefits is a simpler experience. An analogy is tshirt sizes vs custom tailoring.

There are approximations you can get, with the current release:
* Use AppIcons Style. It has app icon and title. However, you won't see all titles at once, like the native app switcher.  
* Use Titles Style. It has app icon and title. However, the icon is smaller, and the flow is vertical not in a grid.
* Use Thumbnails Style. It has app icon and title. However, it also has the thumbnail. You can remove the Screen Recording permissions and use the checkbox to use AltTab without. In that mode, you'll have big app icons instead of thumbnails.

We are in the process of gathering such feedback to decide what to do next 👍 

Thank you

**Comment by guillaumebrunerie** [comment]
> * Use Thumbnails Style. It has app icon and title. However, it also has the thumbnail. You can remove the Screen Recording permissions and use the checkbox to use AltTab without. In that mode, you'll have big app icons instead of thumbnails.

I'm not sure if I'm doing something wrong, but without this permission none of the styles work at all. I can open the preferences and change style, but the Alt-Tab pop-up never shows. I tried a few times and checked the checkbox but I couldn't get it to work.

**Comment by mwpardue** [comment]
> Power users is a spectrum. Even amongst AltTab users, some features are used by a few percents of users.
> 
> You can install any previous versions. They are all hosted here in the Releases section of the project 👍

I apologize if I was too harsh in my last response, and I do appreciate the work you've done on this application. 

That being said, "you can install any previous versions" is a disappointing response if that's your suggestion for those unhappy with the removal of a very large subset of features. The customizability is the draw of AltTab. I and clearly many others are very disappointed with the decision to remove features when the only reason for doing so is that it's too complicated for some users. Just put those options behind an advanced menu. If you're really concerned that people will get in over their heads then you can always make the barrier to accessing those options something that only a power user is likely to do, like a preference that has to be changed at the command line. Eventually 6.73 will no longer be compatible with the latest MacOS. Knowing Apple, that day is probably not too far off.

**Comment by lwouis** [comment]
@guillaumebrunerie it seems you're experiencing https://github.com/lwouis/alt-tab-macos/issues/3819

**Comment by guillaumebrunerie** [comment]
> * Use Thumbnails Style. It has app icon and title. However, it also has the thumbnail. You can remove the Screen Recording permissions and use the checkbox to use AltTab without. In that mode, you'll have big app icons instead of thumbnails.

Now that #3819 is fixed, this is indeed the closest to the previous style I used. It doesn’t look as good, though, (in particular the icon is too large and the title too small) and it also feels weird that I need to remove a permission in order to get a different style that isn’t available otherwise.
