### ISSUE TITLE
Thumbnails can be too wide

### ISSUE THREAD

**Issue by arekk** [lwouis/alt-tab-macos#3791]
**Describe the bug**

I use the Lazarus application, which uses many separate windows. Some of them are horizontal windows, the width of the entire screen. These types of windows take up a lot of space on the preview,  what looks unsightly.

**Screenshots / video**

![IMG_20241031_104044_A](https://github.com/user-attachments/assets/d4f75b05-d707-4f9f-995b-eec683518f45)
![IMG_20241031_104054_B](https://github.com/user-attachments/assets/82a0d1dc-60b9-464f-8713-fc06aded3a91)

**Steps to reproduce the bug**

1. Run Lazarus IDE: https://www.lazarus-ide.org/
2. Use alt-tab

**Your environment**

* AltTab version: 7.0.2
* macOS version: Sequoia 15.0.1 (24A348)

**Comment by lwouis** [comment]
Hi,

This issue has been [noticed here](https://github.com/lwouis/alt-tab-macos/issues/351#issuecomment-2420787325). It will likely be fixed in the next release 👍 

Thank you 🙇

**Comment by lwouis** [comment]
I checked how Windows 11 handles wide and tall windows. Usually we look up to what Windows does. In this case, I must say I'm very surprised at how wide the windows can get:

![image](https://github.com/user-attachments/assets/43d6f468-deb5-4f6c-b6a4-ff81f7d1d655)

**Comment by lwouis** [comment]
This is AltTab since v7:

![Screenshot 2024-10-31 at 19 22 01](https://github.com/user-attachments/assets/0ecd4da2-9226-4414-a606-d5f0685759e6)

I checked how Windows 11 handles wide and tall windows. Usually we look up to what Windows does. In this case, I must say I'm very surprised at how wide the windows can get:

![image](https://github.com/user-attachments/assets/c78771e3-b33d-47e7-90e9-1a4fe43456f3)

I think it's reasonable that a thumbnail can be 50% wider than another, at most. This way we garanty that the switcher remains compact.

I wonder how we should align the windows:

| top-center (AltTab < v7 was like this) | center-center | top-left |
|-|-|-|
| ![Screenshot 2024-10-31 at 19 14 12](https://github.com/user-attachments/assets/0c9fe4ac-5686-4954-a39d-c625ee816f3d) | ![Screenshot 2024-10-31 at 19 13 28](https://github.com/user-attachments/assets/6ad02c43-e9e2-4f90-84c8-82fa5d660cb5) | ![Screenshot 2024-10-31 at 19 18 36](https://github.com/user-attachments/assets/485f98c0-0ef3-4eca-9901-3a836f7ba8a3) |

We can also consider if the backgrounds go all the way up or not:

![Screenshot 2024-10-31 at 19 29 21](https://github.com/user-attachments/assets/9ac00fb1-d8e3-42fe-8a49-3b8c3ce98f86)

**Comment by lwouis** [comment]
Here's a [local build with the fix](https://github.com/user-attachments/files/17593926/AltTab.zip). Could you please try it out?
