### ISSUE TITLE
More compact design/view like the Contexts one

### ISSUE THREAD

**Issue by valentinocossar** [lwouis/alt-tab-macos#384]
**Is your feature suggestion related to a problem? Please describe.**
When you have a lot of windows opened, it's difficult to detect the right window to select, maybe you have more windows opened for the same app and the current design/view it's not helpful.

**Describe the solution you'd like**
Thinking about a more compact design/view, more focused on the window's title, and not on its content could be a good solution. The window switcher will work vertically instead of horizontally. So for each window, there will be more space to print the title and to make it fully readable by the user.

**Describe alternatives you've considered**
Contexts app provide this feature by default, look at [its website](https://contexts.co). Also Contexts it's no more actively maintained and with this feature, a lot of people could potentially switch from Contexts to Alt Tab.

**Comment by lwouis** [comment]
Hi @valentinocossar! Thank you for sharing this suggestion!

There has been previous tickets asking for features from Contexts to be added to AltTab: #338 #210. For instance, here is what I said regarding a thumbnail-less UI with direct shortcuts to windows:

> Overall, I would say that what you describe is a big departure from the current AltTab. Such a departure that I feel it could be a separate app at this point. AltTab is all about: visual memory/recognition of the windows, and chronological navigation. Both of these defining features are absent in your proposed UX, and are replaced with: memory mapping of windows to numbers, and direct navigation.

Since Contexts exists, and provides the experience you are looking for today, I would say the priority of this to me is not urgent. That being said, I'm open the the idea, as I know first hand how insanely complex monitoring windows using macOS private APIs is. So capitalizing on AltTab and potentially build a better, open-source, Contexts, is something i'm open to. I would merge a PR without a doubt for instance.

There also needs to be a discussion about how this alternative UI would be represented in the preference UI.

**Comment by andylima** [comment]
The proposed feature would also be very useful to me. 👍

…But since it's not a priority for now, what about having the ellipsis for the window title (i.e.: the truncation) in the middle (instead of at the end) so that we can see the last part of the title?

This is very useful, for example, to discern Finder windows…

Here's an illustration — Presently, in the AltTab list, all windows of Google Drive folders have the same title: "/users/andy/Google Drive..."

…This tells you very little.

…With my proposed change, the titles would be something like:
"/users/andy/Google.../notes"
"/users/andy/Goo.../articles"

…See what a difference this makes? I hope you do. 😉

(I do not mean to hijack this issue… If it is better for me to open a new issue, please let me know. Thank you. 👍)

**Comment by lwouis** [comment]
Regarding having the ellipsis in the middle, I'm afraid it doesn't work as smoothly as you illustrated. Because the space is very limited above thumbnails, I think the middle ellipsis works worse than the right ellipsis. The reason being that with such short length, you can't really make up neither the beginning nor the end of the line.

Here is a build I made locally that has middle ellipsis. Could you please try it out? [AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/4817273/AltTab.app.zip)

Please share here what you think. Personally I think it would be a UX downgrade as it makes the titles pretty unreadable. There is not enough space most of the time for a single word to be readable on either side.

**Comment by andylima** [comment]
@lwouis Thank you so much! I really like this version! 🙂 But, you know why?… It's because I already had the window title font size set to 11px. 😀

Maybe the middle-ellipsis could be used when the window title font size is lower than 13x?

I'm using this version for now… — it that OK? 🙂

It makes such a big difference… Not only on Finder… But on Sublime Text too, as the project name is at the end of the window title.

**Comment by andylima** [comment]
…Just checked on Sound Studio… — Working great too! Because the initial and last parts of the filename (basename) are both shown. 👍

**Comment by valentinocossar** [comment]
@lwouis Thank you for the answer. I'll wait for this new "breaking" feature, sooner or later. 😄

**Comment by lwouis** [comment]
For the truncation part, I think we could add yet another preference for it. I'm reluctant because these have become a bit out-of-hand, but at the same time they empower users to set up a workflow customized for them, so I guess it's a good thing.

For the alternate UI with titles only, no thumbnails, vertical orientation, as I said, since this is already done by another app, there is no rush in my mind. I'm open to merging a PR of course. If you're interested in contributing, please let me know so we coordinate further.

**Comment by andylima** [comment]
> (...) they empower users to set up a workflow customized for them, so I guess it's a good thing.

I agree that it is generally a good thing, yes. 🙂 You probably know this but… here goes: In the future, if you need to avoid visual clutter you can always turn some settings into "hidden" ones — Example of a hidden setting in Alfred:

> Execute the following command in Terminal:
> defaults write com.macility.typinator2 expandInAlfred 1

**Comment by andylima** [comment]
Hi again @lwouis — I'd love to be able to update to the latest version so that I can hide AltTab's menubar icon…

…My menubar is getting too long for my 13" screen. 😉

…But if I update, I lose my current customized version where you implemented that "truncation in the middle for the window title" feature…

Do you think you could add that feature, toggled by a hidden setting?… So no work needed to change the Preferences UI?…

I hope I can update my AltTab soon without losing that "middle truncation" functionality you so kindly added… Thank you so much. 🙏

**Comment by lwouis** [comment]
@andylima I added it, with a preferences UI as well. I figured other users may benefit from it, and I re-read my past-self and convinced my present-self to do it lol (emphasis mine):

> For the truncation part, I think we could add yet another preference for it. I'm reluctant because these have become a bit out-of-hand, but **at the same time they empower users to set up a workflow customized for them**, so I guess it's a good thing.

It will be out with the next release, which I hoped to be in a few minutes, but github is having technical issues, and the PR are bugged (Netlify and TravisCI fail to see the PR, because of issues with Github at the moment)

**Comment by andylima** [comment]
> It will be out with the next release (...)

@lwouis Updated and using it — Working great. 🙂 Thank you! 🐬

**Comment by lwouis** [comment]
Hey everyone! I have implemented this ticket. There is now a preference to disable thumbnails, and have that Contexts-like experience, with vertical layout showing window titles, without thumbnails.

Please [check out this video demo](https://www.loom.com/share/5eb4a0a3aec6409abc46081b6de98d11), and let me know your feedback! 👍

**Comment by lwouis** [comment]
Here is a [build that should work now](https://github.com/lwouis/alt-tab-macos/files/5163336/AltTab.app.zip). Please let me know about the feature in this ticket, and also #397 if you're interested.

Please share feedback before I release the next version 👍

**Comment by andylima** [comment]
> There is now a preference to disable thumbnails, and have that Contexts-like experience, with vertical layout showing window titles, without thumbnails.

Already using it & Lovin' it. 😍 🤗

Also the demo video was very enlightening. Really great to see how the "Window title list" feature was made possible in an organic way, with small incremental changes over time. ☀️

…Soo impressive to see AltTab's evolution overall. 🙂

Regarding your question (in the demo video), what I've been learning from others lately is: Test it. Test it in the real world — Ship the smallest change that makes sense and check for users' feedback.

…To be more specific (and maybe more helpful!), if enough users ask: "How do I get a vertical window title list?" Maybe instead of building up and having an alternative / parallel UI, you can point those users to a short tutorial (on the website) showing them how to config things that way. And probably link to it on the site's front page.

These days I avoid lots of work for small results. I've been calling this "following the law of least effort". 😂 In Portuguese the expression ends up being very funny ("Eu sigo a lei do menor esforço.") because our parents / grandparents would always admonish us, when we were kids, to work hard and not follow the easy way. 😉

**Comment by valentinocossar** [comment]
Super feature! Thank you so much! 🚀

**Comment by fregs7** [comment]
Thanks a looot for this feature!

I know it's not the typical use case for AltTab but it is just perfect for me as I never cared about the thumbnails but I do care about the responsiveness (and of course about AltTab's other options too to customize its UI), and now it is super fast. (Also, it was a bit annoying that when the system was a bit lagging because of some other process it was impossible to use AltTab as it was trying to generate thumbnails — not anymore! 🥳)
