### ISSUE TITLE
wrong alphabetical order since newest google chrome update

### ISSUE THREAD

**Issue by enfgjoooja** [lwouis/alt-tab-macos#3857]
wrong alphabetical order since newest google chrome update

**Comment by lwouis** [comment]
Hi,

Could you please share a screenshot and steps to reproduce?

Thank you

**Comment by enfgjoooja** [comment]
> Hi,
> 
> Could you please share a screenshot and steps to reproduce?
> 
> Thank you

before it was focusing on name of the window..  which you can set manually in chrome, 
now its focusing on the name of the tab
which obviously changes  when you hit different  tabs in chrome

**Comment by lwouis** [comment]
We report the name of the window. Chrome sets it. We can't decide what they set, sorry

**Comment by enfgjoooja** [comment]
bettertouchtool captures names perfectly somethings wrong with the app not chrome

**Comment by lwouis** [comment]
AltTab is getting the `kAXTitleAttribute` of the window. Chrome is responding with the value of the tab.

I think BTT may be using `CGWindowListCopyWindowInfo` to get the title. That API returns the custom window name.

AltTab uses the Accessibility APIs to grab info about windows, such as their title. This is the correct and most robust way to do so, which is why we moved to doing it that way.

Chrome should fix their app so that accessibility apps like AltTab get the custom title with calls to get `kAXTitleAttribute`. It's definitely a bug on their side.

Thank you
