### ISSUE TITLE
Poor performance when using multiple desktops

### ISSUE THREAD

**Issue by rway7** [lwouis/alt-tab-macos#393]
When I have about 9 desktops, and several windows on each, there's a noticeable delay for AltTab to response.

I've already configured to show only the windows in "Active Space", but I suspect it's still caching all thumbnail images for windows from all spaces. So it might be related to the caching mechanism.

**Comment by lwouis** [comment]
Hi @rway7! Thanks a lot for sharing this issue!

I double-checked, and indeed we refresh all thumbnails, whether it is shown to the user or not. I'll push a fix for that. Hopefully it solves your performance issue.

Note that as of now, the *only* significant performance bottleneck is indeed getting the thumbnails. It is unfortunately a though issue. The only thing that we could do really is to show previous thumbnails when the UI is summoned, and asynchronously update them over a few seconds. I have made a POC for that in #171. My issue with this approach is that it's actually an inferior experience in cases where the user is only shown a few thumbnails. Let's say less than 20, depending on the screen resolution (i.e. a big 4k displays means heavy thumbnails, so worse performance).

The new version should be available in less than an hour. Could you please let me know if that mitigated the issue for you? 👍

**Comment by rway7** [comment]
Thanks @lwouis!

Now it feels much better. And I would like to describe further about my needs, which might help you making decisions.

To me, the thumbnail image is actually inconsequential. I only use "window switcher" as a quick way to bring back recently used windows. And I have never tried using it to switch to windows that are not in the top five list, because Mission Control does a better job on that purpose.

I use Mission Control for further overview and management, paired with Mission Control Plus—a third-party software that adds shortcut support.

I have also tried Contexts, and the "list mode" does it just fine, except sometimes the windows are not sorted correctly. AltTab doesn't have that issue.

**Comment by lwouis** [comment]
It's the first time I hear about Mission Control Plus. I thought I knew all the apps in that space! That's pretty cool. I can't imagine the hacks they must go through to enable such a feature-set 🙉

You said you don't care about thumbnails, and you like the Contexts flow. From that I gather that if given the preference, you would like to disable thumbnails in AltTab? Such a preference and alternate layout is already being discussed in #384.

For me, thumbnails are an essential part of the workflow, because I want 1 workflow to go back to one of the last 5 windows, as you said, but I want to same workflow to enable me to find windows from 2h ago, in the bottom 20. That being said, having an alternate UI with no thumbnails, and vertical list of window titles, would be quite easy. Let me know if you would be interested to raise a PR for that ;)

**Comment by rway7** [comment]
Yes, a vertical list would be perfect. And I'm interested to be involved.😀

I would like to talk more about my multiple desktop usage as well.

In fact, I have 25 desktops, arranged in 5x5 grid, all the time. The arrangement is static. Desktop 17 is dedicated for this AltTab discussion. Everything about AltTab is on this desktop, which includes this issue, related issues, PRs, and the Xcode project, or even some Google search. The grid view is achieved using [TotalSpaces2](https://totalspaces.binaryage.com)—also an essential tool for me.

When I have to do something else, for example, watching WWDC, I simply switch to Desktop 4, without mixing all these windows together. And when I switch back, everything is still the same.

**Comment by lwouis** [comment]
> I'm interested to be involved.😀

Could you please PM me by email, or on the [Discord](https://discord.com/invite/mHvmcqT)? Here is more info on [how to start contributing](https://alt-tab-macos.netlify.app/contributing).
