### ISSUE TITLE
Add window thumbnails to Dock and built-in app switcher

### ISSUE THREAD

**Issue by ans87gh** [lwouis/alt-tab-macos#396]
**Is your feature suggestion related to a problem? Please describe.**
App works perfectly. Has great functionality added with keyboard shortcuts and previews are high resolution and refresh regularly.

**Describe the solution you'd like**
What I'd like is an expansion of the previews to other areas of the system.
ie preview windows from the dock by hovering over the app icon.
ie preview windows when moving through app switcher (⌘ ⇥)

**Describe alternatives you've considered**
Other places where the preview can be manifested.
Similar to what is done in HyperDock and HyperSwitch. Both great apps but want to trim the functionality to just window management at its best.

**Comment by lwouis** [comment]
To illustrate a bit more, using screenshots from Hyperdock and HyperSwitch:

![image](https://user-images.githubusercontent.com/106195/86559247-778dc200-bf96-11ea-87e7-8322db687dee.png)
![image](https://user-images.githubusercontent.com/106195/86559258-7c527600-bf96-11ea-9fe9-9ca230990db2.png)

**Comment by ans87gh** [comment]
Thank you for the examples. Spot on. They have since evolved in look to be consistent with the current macOS design language.

**Comment by koekeishiya** [comment]
HyperSwitch appears to be doing this by using the accessibility API to track when the Dock creates the window-switcher. It also track focus changes and by doing so it can draw images of windows belonging to the selected applications below the image of the application itself.

**Comment by lwouis** [comment]
Thanks for sharing this @koekeishiya! I noticed this general approach also when checking their code

**Comment by lwouis** [comment]
I thought about it, and I think such "add-ons" will be janky, by nature of being unsupported mods of the base OS:

* They may not work between previous and future versions of the OS
* They will most likely perform poorly with lag, jank, due to us trying to follow the state of the native system
* They limit us on what we can do (e.g. we can't change the size of the `command-tab` app icons)

I've decided to close this ticket in favor of bringing similar functionality through #337. Instead of plugin onto macOS app-switcher, we will draw our own app switcher, and have this functionality on top of that. That way we have an integrated, cohesive experience.

Regarding the Dock popovers, I don't think this will happen. If we go that route, we may also as well consider creating a whole new Dock / bar, such as what [uBar](https://brawersoftware.com/products/ubar) is doing. I've been thinking about that for a while now. Basically always-on UI, as opposed to on-demand UI which AltTab provides today. Actually I'll create a ticket for that
