### ISSUE TITLE
Virus alert on official website

### ISSUE THREAD

**Issue by SaJavlaBaddy** [lwouis/alt-tab-macos#3981]
The official website linked to in README, and that also opens on automatic updates renders a Virus Alert an Avast Security! Apparently the URL seems to be blacklisted.

![image](https://github.com/user-attachments/assets/460525c0-7d09-4701-a2bb-293a23fa899c)

![image](https://github.com/user-attachments/assets/3701f62e-bd5f-420b-a26f-3f5f25dd2a9e)

**Your environment**

* AltTab version: 7.10.0 
* macOS version: Sequoia 15.1.1
* Chrome 131.0.6778.140
* Avast Security 15.9.2

**Comment by lwouis** [comment]
Hi,

Thank you for sharing. I [reported here](https://www.avast.com/report-false-positive#mac). I didn't have any Alert ID though. Could you please report it as well on your side?

I wonder if the reason we got in this blacklist is because of https://github.com/lwouis/alt-tab-macos/issues/3933

Thank you 🙇
