### ISSUE TITLE
Make it possible to require double tapping Q to quit an application

### ISSUE THREAD

**Issue by joachimbulow** [lwouis/alt-tab-macos#4001]
**Is your feature suggestion related to a problem? Please describe.**
I have oftentimes accidentally closed my code editor pressing `cmd+q`. Frustrating when running expensive processes

**Describe the solution you'd like**
Would like to make my editor application require an extra tap of Q to close. Chrome already does this, so maybe there is a way? Maybe even at the OS level. 

**Describe alternatives you've considered**
Figuring out how to block it at the OS level

**Comment by lwouis** [comment]
Hi,

This seems unrelated to AltTab? Look into other tools to implement this perhaps.

If you mean "when AltTab is open" then there is already something implemented like that. A single Q will Quit. If the app is stuck, a second Q will Force-Quit.

Thank you

**Comment by joachimbulow** [comment]
You have a setting to specify which button you want to close programs with, so it would seem to me it is related?

**Comment by joachimbulow** [comment]
At least you could make it possible, and that would be sweet

**Comment by lwouis** [comment]
By unrelated, i meant: your message reads like you want command+Q to act differently, when you use it in macOS, without having AltTab opened. Like Chrome does. You can focus an app and press command+W.

That is out of scope for AltTab. The app is not dealing with shortcut remappings. Tools like BTT or Karabiner may help you here.

Regarding supporting it while AltTab switcher is open, as i mentioned it's not possible because we already make use of double command+Q. We force-quit. That logic is useful to many people. We can change it like this

Thank you

**Comment by joachimbulow** [comment]
Yea sorry for misspeaking - i see what you mean, the chrome example is not related to alttab. 

I just meant, in the exact same way chrome does it, we could add it as an option for AltTap. 

I think their approach is nice, and allows you to protect important processes from mistakes
