### ISSUE TITLE
Localization Contribution and Question(mostly in Chinese)

### ISSUE THREAD

**Issue by hshsilver** [lwouis/alt-tab-macos#4013]
First of all, love this app!

have been using this for long and today got some time to improve the Chinese (zh-cn, simplified chinese) localization.

I reviewed the whole catalog from beginning to end and unified the string according to apple's official terminology.

you can find the update from poeditor.com

but still, i need more info and context for these strings:

1. Space
Here you mean the white space or the zone that holding the windows? 

2. Show & Hide
where is this string? a title? or a toggle/ options? a screenshot will be better

3. Theme
highly recommend replacing this string with "appearance" to align with apple's official terminology. 

4. Use the app without this permission. Thumbnails won’t show.
is the first period a typo? or say this whole paragraph should be 
"If you use the app without this permission, thumbnails won't show."
------------------------------------------ ^-----------------------
or
"Use the app without this permission and  thumbnails won't show."
-------------------------------------- ^---------------------------
?

**Comment by lwouis** [comment]
Hi @hshsilver,

Thank you for your work!

> Space

This is a string from a previous version of the App. Your question motivated me to finally do proper labeling on the project, through automation. I've now tagged every single string in poeditor, based on the first and latest version that it was featured in. We can see that `Space` was introduced in `v6.60.0`, and removed in `v6.73.0`:

![image](https://github.com/user-attachments/assets/b5e7c55a-fc5b-4abf-a9a2-d70eff670b8f)

There is no need to translate older strings. The effort is not worth it.

> Show & Hide

It's in Appearance > Customize... > name of the first tab

> Theme

We thought a lot about it with the release of the v7 revamp. We offer 3 different "styles" we call them "Appearance". Thus for the dark vs light, we went with "Theme". I think it's not very important because users understand which picture to click, and what Dark/Light refers to 👍 

> Use the app without this permission. Thumbnails won’t show.

I think this is correct. This style of short, clear sentences is recommended in https://www.amazon.com/Elements-Style-Fourth-William-Strunk/dp/020530902X
