### ISSUE TITLE
Render Behavior with Stage Manager

### ISSUE THREAD

**Issue by kaitpw** [lwouis/alt-tab-macos#4015]
**Describe the bug**
I almost exclusively use stage manager to manage my windows, I've found that its just more ergonomic for me. The videos attached shows what this looks like. I have two minor points of feedback:

1) windows that are stage managed/minimized render blurry. I'm assuming that this is because alttab downscales the screen capture or something like that.

2) The fact that alttab screen captures to get the window causes another slightly annoying behavior with stage manager as you can see in the vid 1. Mainly what I'm referring to it the re-rendering of the window from the unminimized to minimized and vice versa which causes a shift after alttab opens (in specific scenarios). I actually really like the 3D tile look of the minimized stage manager window, and I'd choose for every window to look like this if it was up to me, but the re-rendering I'm not a fan of. This seems probably unfixable, but with some of the options from alttab v6 back this wouldn't b a problem for me.

In v6, I had my app icons roughly the same size as the window they were attached to so neither of these were an issue for me (see vid 2, where I switched back to alttab v6). I'll probably stay on v6 for now for this reason.

Thanks for the amazing app! Alttab has been indispensable for me since I found out about it.

**Screenshots / video**
https://github.com/user-attachments/assets/5a3a8c19-e0b0-4bb6-9696-c27d350789ae
https://github.com/user-attachments/assets/84576609-0eea-4ef5-8125-7accc200b243

**Comment by kaitpw** [comment]
Here's my alttab v6 prefs too:
![CleanShot 2024-12-24 at 13 34 54@2x](https://github.com/user-attachments/assets/3e381796-5241-4466-b1f5-7bfdc06025d7)

**Comment by lwouis** [comment]
Hi,

Stage Manager is a problem paused to AltTab, for which we have no solution. Apple doesn't provide any API to deal with it. The thumbnails are skewed, and there is nothing we can do about it, because the actual windows are actually skewed. There is no way to un-skew them. Please see https://github.com/lwouis/alt-tab-macos/issues/1731

Re-rendering is also normal. AltTab updates thumbnails when it notices changes in a window. If the size changes, if it gets minimized, etc. So the user has the latest version / most up-to-date.

Finally, regarding your v6 setup, given your goals and the constraints, I would suggest you try out the AppIcons Style in v7. You lose the thumbnails, but you get big nice app icons. That's the best I can think of. There is also https://github.com/lwouis/alt-tab-macos/issues/3882 where a few people are requesting another Style, or a way to customize existing Styles.

Thank you

**Comment by kaitpw** [comment]
Ya sounds good, I expected an answer like this. I would switch to the app icons in v7 but the problem is differentiating between multiple windows of the same app, it’s difficult for me to differentiate with titles, so seeing the state of each one super helps
