### ISSUE TITLE
Separate horizontal/vertical swipes in Gesture tab

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#4020]
![image](https://github.com/user-attachments/assets/e43d19fd-4764-4dd6-9125-af8bdf9094a7)

Should we have 5 options here?
* Disabled
* Horizontal Swipe with 3 Fingers
* Vertical Swipe with 3 Fingers
* Horizontal Swipe with 4 Fingers
* Vertical Swipe with 4 Fingers

_Originally posted by @lwouis in https://github.com/lwouis/alt-tab-macos/issues/4012#issuecomment-2560959110_

**Comment by chalda** [comment]
Hey actually was gonna make a separate enhancement post but might as well piggy back from my big #4027 and see if we can use gestures as hotkeys

So i use the swipe as a defacto Mission Control replacement with on release disabled. This presents a challenge tho because 
- the mouse follows focus is global setting and not per hotkey config
- selecting a window is easy enough with space but backing out of the alttab requires reaching all the way to escape
- there is a option in the menu bar dropdown to just open alttab (which would just be equivalent to 4 fingers up for Mission Control) but afaik there isn’t a hot key binding for it
