### ISSUE TITLE
Allow changing keybinds :enhancement:

### ISSUE THREAD

**Issue by jfdhuiz** [lwouis/alt-tab-macos#42]
Could you allow a way to modify https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/resources/preferences.json within a text editor, say in ~/Application Support/Library/AltTab/preferences.json? That would the user to change the keybind.

In Hyperdock (combined with Karabiner Elements / Hammerspoon) I use Cmd+Space to "alt tab" and Meta+Cmd+Space to "alt tab within application". It allows to keep Ctrl+Tab intact, as it is also used in e.g. Firefox, iTerm, ...

In this example, I would like to change

> "metaKey": 59,

to

> "metaKey": 55,

as per [1]

[1] https://eastmanreference.com/complete-list-of-applescript-key-codes

**Comment by lwouis** [comment]
What you describe is [possible starting from 1.1.0](https://github.com/lwouis/alt-tab-macos/issues/8#issuecomment-542695697) :)

I hope to release some Preferences UI soon so that the text approach is less needed. However actually I just realized the json file should still be documented because it makes it scriptable and portable, whereas the UI is convenient and friendlier. Both should be documented!

**Comment by lwouis** [comment]
@jfdhuiz I just released [1.6.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.6.0) which features an easy dropdown menu to select which shortcut key you want to use to trigger the app. Check it out! :)
