### ISSUE TITLE
Allow to disable thumbnails

### ISSUE THREAD

**Issue by oshatrk** [lwouis/alt-tab-macos#432]
**Is your feature suggestion related to a problem? Please describe.**
In the switcher window I prefer to see app icons and titles only, without thumbnails. 

**Describe the solution you'd like**
Add a preference to disable thumbnails.

**Comment by oshatrk** [comment]
I suppose that the background thumbnailer can also be turned off with this switch. So it will help to recognize the type of a reported problem (is it a usual problem with the thumbnail generation or just a doomsday).

**Comment by lwouis** [comment]
Hi @oshatrk! Thanks for the suggestion!

Turns out we already have a ticket for this UX without thumbnails: #384. The ticket goes into more depth: having the thumbnail-less UI be vertical instead of horizontal, to show the full titles. Basically anything Contexts is doing can be inspiration for that alternative UX.

> I suppose that the background thumbnailer can also be turned off with this switch. So it will help to recognize the type of a reported problem (is it a usual problem with the thumbnail generation or just a doomsday).

I'm not sure I understood what you wrote. I think you meant that if we don't show the thumbnails, we can stop computing them? Yes for sure. Thumbnails have not been an issue so far. The code works well and is stable. It is however, the biggest performance bottleneck for responsiveness (i.e. how fast AltTab appears after you trigger the shortcut).
