### ISSUE TITLE
Dr. Betotte Software not shown in alt-tab

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#455]
When Dr. Betotte software is open and alt-tab is used, it is not showing up in alt-tab.

Dr. Betotte is a metronome for macOS: http://www.ssworkssoftware.com/drbetotte/drbetotte.html

**Comment by lwouis** [comment]
Hey @foss-! Thanks for sharing this issue!

The app is reporting incorrect accessibility `subrole`. I'll add an exception to that app.

I've added 3 exceptions for buggy apps in the last 2 days. I really don't know how to avoid having to hardcode exceptions. The risk is that we would display objects which are not windows. You can imagine for example that some apps will have a fullscreen transparent window to draw overlays on top of existing windows, or such creative tricks. AltTab uses the accessibility API, and only lists windows that declare themselves as standard windows or dialog windows.

If we only keep these, we miss out on the buggy windows like Dr Betotte which identifies as `AXUnknown`. On the flip-side, if we remove that restriction, we risk listing non-windows in the app.

Some ideas I had to mitigate that:

* Add a whitelist preference where you can add apps `bundleId` and that will force AltTab to display all their "windows". The issue here is that it's not a good out-of-the-box experience since people need to know a lot to realize the issue, understand how to fix it (how to get the `bundleId` is non-trivial for most users). Another issue is that for these faulty apps, some of them actually have non-windows... This is the case for Steam for instance. So that whitelist approach wouldn't work here as you can blanket-approve all "windows" from Steam. You have to distinguish *within* the `AXUnknown` windows, which one is the Steam main window, and which ones are buggy dropdown menus being coded as windows.

* Better heuristic to discriminate real windows from non-window. Maybe checking the size of them, and making sure it's at least 200x200 or something like that. That would avoid showing small UI pieces coded as windows. That's not enough though, as I gave the example earlier of the fullscreen transparent window trick. We would also need to check for opacity (not sure if possible).

Overall I'm going to keep hardcoding for now, but I really wish someone would share a better way of approaching this issue that doesn't involve me hardcoding things. Many users will not open an issue when they don't see the window listed, so they have a bad experience and we never know about it. There must be a way to improve our approach
