### ISSUE TITLE
Allow completely different shortcuts in the preferences tabs

### ISSUE THREAD

**Issue by rxhfcy** [lwouis/alt-tab-macos#463]
Thank you for (almost) fixing #237 (for me).

My particular obscure preference would be to be able to switch between all windows with cmd+tab, and between windows of the 
current program with alt+tab...

So if the new vertical tab thingies (in "General") would also allow me to change "Hold (desired-key-here) and press:", I would be able to use a different "hold key" for switching between all windows (cmd) and windows of the current application (alt).

Maybe the attached picture explains better what I mean? Does this make sense to you?

![Untitled](https://user-images.githubusercontent.com/42669366/88200512-e9306600-cc4e-11ea-8ede-8ab495f00c97.png)

**Comment by rxhfcy** [comment]
So in my particular case:
"tab number 1" (the first picture) would have cmd+tab switching between all windows, and 
"tab number 2" (this second picture) would have alt+tab switching between the active app's windows

![Untitled](https://user-images.githubusercontent.com/42669366/88201823-a079ac80-cc50-11ea-9345-854b24621ea1.png)

**Comment by lwouis** [comment]
Hey @rxhfcy! That's a totally valid point!

I thought extremely deeply about this, as you may be able to tell by the flexibility of the current tabs UI. While thinking about the problem space, I thought about this too. I decided to not do this extra flexibility because I thought nobody would need it. I was wrong ;p

I'll combine this ticket with #458 which goes even further and provides a whole new *mode* of interacting with AltTab.

**Comment by fortu42** [comment]
Hi, I would also like to have cmd-tab and alt-tab options to distinguish between all apps and window apps. For me, those two shortcuts are the more natural ones.
Thank you and keep up the great work.
