### ISSUE TITLE
Always-on UI (i.e. bar or dock)

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#529]
I've been thinking about alternatives such as HyperDock and uBar. They provide always-on UIs:

![image](https://user-images.githubusercontent.com/106195/90106168-00f89700-dd82-11ea-85e3-aad910dc5d28.png)

![image](https://user-images.githubusercontent.com/106195/90106198-09e96880-dd82-11ea-9879-b454a92f72b1.png)

This type of bar / Dock is something I miss from Windows and Linux. By virtue of being always-on, they allow users to get a spacial sense of where windows are, as time goes by. AltTab currently shows chronological order of focus. An always-on display can display something very interesting: chronological order of creation. Windows stack into the bar as they are created, but then stay in place when interacted with. It's a different UX which allows user to get spacial awareness by seeing windows being added in the bar, and remembering the place. Later when they want to switch they can simply click that area of the bar.

I think it's a cool UX direction to explore. I think it could be a separate app, or a feature of AltTab. Please share feedback if you have some! :)

**Comment by rxhfcy** [comment]
I'm pretty sure at least these kinds of potential different "customers" exist:
- people who want an exact bug-for-bug copy of the Windows 10 UX
- people who want an uBar clone
- people who want a HyperDock clone

I haven't used HyperDock or uBar so I don't have an informed opinion on them. My own personal take is that since there are **lots** of current and former Windows users, maybe make something that's familiar to them?

I have a feeling it's impossible to make everybody completely happy, so you could just start by implementing what *you* personally want and iterate from there.

PS. I have no idea what the preferences window would look like for AltTab with this kind of functionality included (confusing?), so maybe a separate app, at least in the beginning?

**Comment by j0nnala** [comment]
Integrating with native dock will be super cool. There is no app currently in the market that can do that.

I know it easier said than done. It would be like having additional triggering point on mouse over on bar icon with the option of "show same following windows" to "Mouse over dock app"

**Comment by lix0x7** [comment]
This is really cool and what I am looking for. There are no alternative apps like this except for uBar. I used to be a uBar user, but there are lots of bug which I don't know why they exist. The company seems like that they have abandoned the uBar project. The uBar even couldn't show most of running apps normally. From my perspective, the uBar seems like that it cannot deal with multi-tab apps well, which leads to endless bugs. 
The windows-like bar is a more straight and efficient UI that the native dock. It could save lots of mouse or keyboard operation. I just want to develop this feature based on your amazing alt-tab project. But I am a back-end developer and not familiar with macOS developing.
Looking forward to your new release! :)

**Comment by lwouis** [comment]
@lix0x7 the reason uBar has these bugs and way it doesn't handle tabs well is because macOS has no public APIs to do this. AltTab and other similar apps use private APIs, private SPIs, and a lot of workarounds to try and do a decent job at the task. Sometimes there are bugs (see the bugs label on this project) that we literally can't do anything about.

AltTab is the most obscure piece of software i've written in my life, and i've done very diverse work. See the QA docs for examples of what the app has to deal with

**Comment by lwouis** [comment]
I think this feature request is quite niche, so I'll close this ticket for now. Please upvote if you're interested in this feature. Enough upvotes and I'll reopen the ticket 👍

**Comment by mfmayer** [comment]
> I think this feature request is quite niche, so I'll close this ticket for now. Please upvote if you're interested in this feature. Enough upvotes and I'll reopen the ticket 👍

👍 this would be super cool. Actually I was spending lots of time finding a cool taskbar for mac, but there is just none that works well. Maybe there are more people like me out there, but they just haven't found this issue (I also only found it by accident after writing my feature request ;-)). Having this described as part of alt-tab, I could imagine, more would really love that feature and with alt-tab you have a really good base for making this real. So you have my upvote ;-).

**Comment by SPavuna** [comment]
I have used Alt-tab ever since my first MacOS use (about a year or so ago) after being (and still being) a lifelong Windows user. I just can't live without a good windows management tool.

I have recently installed ubar to see how it works with the dock replacement effects, but it seems like using both disables Alt-Tab functionality? They can't both work at the same time it seems.

So I fully endorse your idea, if you ever come around to do it :)

**Comment by lwouis** [comment]
@SPavuna have you tried using a different shortcut for AltTab? I would be surprised if both apps couldn't co-exist, if they are set to different shortcuts.

**Comment by SPavuna** [comment]
@lwouis I actually got both of them to work together now, not really sure what was the problem. I've restarted both and they coexist (for now) :) I just assumed that they were fighting for some of the same thing, but doesn't seem like it's the case.

While you're here, just another thank you for this app! I love it and not sure if I'd be able to use MacOS without it :)

**Comment by coder-virjay** [comment]
Does anyone know of an application that can replace the dock but only displays the applications of the current space?

**Comment by w93163red** [comment]
Is there some guidance to make it come true? I would like to help but did not have any experience on MacOS app development

**Comment by w93163red** [comment]
<img width="1440" height="48" alt="Image" src="https://github.com/user-attachments/assets/112867d6-1fe7-4d6b-b24e-91454e2040ef" />

<img width="540" height="464" alt="Image" src="https://github.com/user-attachments/assets/9e77c0a8-27ee-408f-a53e-6d19645a05c2" />

<img width="621" height="244" alt="Image" src="https://github.com/user-attachments/assets/5dd94b43-4e67-4316-a96c-db1505204636" />

It's been a long time. 

Thanks for LLM, I am able to do some trials at least: https://github.com/w93163red/alt-tab-macos

It supports auto-scaling the full-screen app so that it does not block the taskbar (even if you try to maximize the app), and also the preview window in the taskbar.
