### ISSUE TITLE
Separate command for "Previous window of current application" (Command+Shift+<)

### ISSUE THREAD

**Issue by Rabattkarte** [lwouis/alt-tab-macos#541]
**Is your feature suggestion related to a problem? Please describe.**

Regarding #512 & #510 I figured out, that I can bind Shift+Tab to "Previous window".

My wanted configuration, though, is as follows (copying Gnome3's default behaviour) :

**Shortcut 1 / all applications**
* Command+Tab: next application
* After Command+Tab. Holding Command, Shift+Tab: previous application.

**Shortcut 2 / current application**
* Command+^: next window of current application
* After Command+^. Holding Command, Shift+^: previous window of current application.

This is not possible as "Previous window" is a global keybind. So either Shift+Tab **or** Shift+^.

Please [watch this video](https://drive.google.com/file/d/1zwAaP9ELa3R6cJMEjj1XPtt0Kdy07PhC/view?usp=sharing) as another explaination.

**Describe the solution you'd like**

I want a separate configuration for both Shortcuts.

**Describe alternatives you've considered**

For my case there is no alternative, only using one of the two shortcuts. This feels wrong, though.

**Comment by lwouis** [comment]
Hi @Rabattkarte! Thanks for sharing this feedback!

The default shortcut, which as you noted is universal, is simply `shift`. You could could use it in both scenario you describe (all apps / active app). I think it's pretty nice actually that you have 2 trigger shortcuts for different scopes, but then all further shortcuts are universal since they don't need to know the current scope to function. I'm not sure why you would want more complexity here? Why not simply use `shift` for both? It's simpler and also more ergonomic. Maybe you have long habits that you don't want to change? I can understand that

You mentioned the 2 tickets about having the backwards-cycling shortcuts become trigger shortcuts, but then in your 2 scenarios you describe backwards-cycling as a secondary shortcut. I would say that if you are also in favor of having the option to make these shortcuts trigger the app, then having them not be universal becomes a requirement that was forgotten in these tickets.

I will close this ticket as duplicate, and reference it there as it is something that everyone missed in the UI discussion
