### ISSUE TITLE
YouTube fullscreen windows in Firefox Developer Edition don't show in AltTab

### ISSUE THREAD

**Issue by mindfulsource** [lwouis/alt-tab-macos#558]
**Describe the bug**

As in title.

**Screenshots / video**

Not needed, easy to reproduce. (I reproduced in a new macOS user.)

**Steps to reproduce the bug**

1. Install [Firefox Developer](https://www.mozilla.org/en-US/firefox/developer/) and simply go a a YouTube video and make it full-screen.
2. Now toggle AltTab. Notice that (current) window is missing. Means you can't alt-tab back to it again either. If I alt-tab away my only way to get back to the window is to find it in Mission Control.

I think it's a buggy behaviour in Firefox Developer, and normal Firefox doesn't do the same thing, but whatever it is maybe other apps could produce the same scenario so it's worth finding a way to work with such anomaly. I work with a multitude of browsers concurrently.

**Comment by lwouis** [comment]
Hey @mindfulsource, thanks for sharing this issue!

I'm pretty sure I know what the issue is already. I made a fix for Firefox previously in #360. That fix whitelists Firefox `bundleIdentifier` and allows its fullscreen windows to show up. I'm guessing that Firefox Developer has a different `bundleIdentifier`.

I can whitelist this app too. These workarounds are a pain. I opened #456 to discuss a better way to handle things, but it needs a breakthrough idea. Nobody has found a better approach that the current one so far, unfortunately

**Comment by lwouis** [comment]
I made a fix. It will ship in the next release. If you want to help with the big picture, please look into #456

**Comment by mindfulsource** [comment]
I've found another app not showing up in AltTab: Adobe Audition 2020. Should there be a single Issue for people to report apps in or you're OK if I update this one with other finds?

**Comment by lwouis** [comment]
Please open a new issue for this other app. Let's try to keep ticket focused. Also that way you can use the issue template to provide all the useful information to move forward with the issue 👍
