### ISSUE TITLE
Ability to vertically align alt-tab dialog on the screen?

### ISSUE THREAD

**Issue by winteriscariot** [lwouis/alt-tab-macos#585]
**Is your feature suggestion related to a problem? Please describe.**
I would like the ability to align the dialog on the screen, vertically. Currently, the alt-tab dialog appears on the upper portion of my screen, not centered:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49098280/92482132-e2cd5d80-f1ac-11ea-97fd-ddcaba68ebe4.png">

Here's the default MacOS switcher:

![image](https://user-images.githubusercontent.com/49098280/92482638-73a43900-f1ad-11ea-8c7c-c2e8a77e0cdb.png)

**Describe the solution you'd like**
I'm basically trying to emulate the exact visual appearance of the default MacOS alt-tab switcher, with the added customization available via alt-tab-macos. I can get most of the way there, but there's no option for me to bring the dialog down to where it is by default. Would this be difficult to add?

**Comment by lwouis** [comment]
Hi @winteriscariot! Thank you for sharing this feedback!

This would be very easy to implement; as easy as [flipping a switch here](https://github.com/lwouis/alt-tab-macos/blob/355225badb4ac0391f56d47c9ed1e212a2c60793/src/logic/Screen.swift#L43).

I'm a bit concerned about adding another preference though. The preferences window is out of control. It would be a great time to work on #351

**Comment by Madd0g** [comment]
>This would be very easy to implement

I also find it very jarring to not have it in the middle vertically, coming from other switchers

When I sort by 👍 this is the top issue, so it's both easy and popular, seems like a no-brainer :)

---

Until the UI redesign, maybe just drop it under the "Align windows" dropdown?

* Align Windows
  * Left
  * Center & Top (like now)
  * Center & Middle (centered vertically and horizontally)

I understand that dropdown it's not really for this, but as a temp fix, maybe just dropping that option there is not too terrible?

**Comment by lwouis** [comment]
The `Align Windows` preference is for something unrelated. If we would go with a temp fix, it could be to add a theme like `macOS - center` in the list of themes, maybe.

I take the issue of having too many options in the preferences seriously. I try to weight the cost/benefit in these situation. I understand this ticket is popular, yet it's only 5 people. For now, it's parked until we can find a strategy for the preferences that takes into accounts their bloating, and how it cripples many users experience. I receive emails/tickets every week from people who ask to implement a feature, and it's already there but they didn't find it because the preferences are too intense for most people already

**Comment by lwouis** [comment]
@kayc7 to reply to your question in the duplicate ticket:

> why is the app switcher even centered near the top as a default?

I have a background in typography and layout. Books for instance don't usually vertically center their title. Instead they put it a bit higher. It looks better than at 50%. It was an aesthetically choice to replicate that for AltTab. It's also part of the UI guidelines from macOS. See for instance [how the method to center a window on screen](https://developer.apple.com/documentation/appkit/nswindow/1419090-center) does it. From the docs:

> The window is placed exactly in the center horizontally and somewhat above center vertically. Such a placement carries a certain visual immediacy and importance.

**Comment by kayc7** [comment]
> @kayc7 to reply to your question in the duplicate ticket #1059:
> 
> > why is the app switcher even centered near the top as a default?
> 
> I have a background in typography and layout. Books for instance don't usually vertically center their title. Instead they put it [a bit higher](https://m.media-amazon.com/images/I/21tMuSOgpcL.jpg). It looks better than at 50%. It was an aesthetically choice to replicate that for AltTab. It's also part of the UI guidelines from macOS. See for instance [how the method to center a window on screen](https://developer.apple.com/documentation/appkit/nswindow/1419090-center) does it. From the docs:
> 
> > The window is placed exactly in the center horizontally and somewhat above center vertically. Such a placement carries a certain visual immediacy and importance.
 
Thank you for the explanation. While I agree that being centered vertically towards the top does look nice for most things to me personally, and I have no doubt there are studies confirming the average person does see this, I believe that this visual change may be conflicting too heavily with my personal expected visual design language of an app switcher. I've found that unconsciously, whenever I hit the alt-tab key combination, I draw my eyes to the center of the screen because of years of alt-tabbing and looking at the center of the screen to see where I switch from Windows. Because of this, I find myself having to move my eyes upwards on the screen after initially looking at the center, which feels like it adds a sort of an invisible step to the process of using the switcher. 

I think this should be added as a setting to the Appearance menu, and I have a possible solution for the information overload. I feel as though the current major information overload is definitely in the Appearance section of the menu. However, I believe that's just because of the large amount of checkboxes and words all at once. I believe a smaller tab-system within the Appearance section could solve that (similar to the Shortcut 1 and Shortcut 2 tabs in the Controls section). Maybe label the everything beginning in Window to a Window tab, and all the checkboxes to an Etc tab.

**Comment by hicaicai** [comment]
I agree that it is really beautiful to put on top, but I use a 27-inch imac computer, my height is not very high, so my line of sight is usually in the middle of the screen, so every time I need to move the line of sight up, so that I feel a little tired, I hope it will be a little down, not necessarily the middle of the screen, just a little down, this may be related to each computer and the use of habits, some people use the macbook, some people use the imac, eye line of sight may not be, so I hope it can be freely adjusted, like alfred can move at will

**Comment by khour** [comment]
> This would be very easy to implement; as easy as [flipping a switch here](https://github.com/lwouis/alt-tab-macos/blob/355225badb4ac0391f56d47c9ed1e212a2c60793/src/logic/Screen.swift#L43).
> 
> I'm a bit concerned about adding another preference though. The preferences window is out of control. It would be a great time to work on #351

With respect to concern about preferences window, could there maybe be a middleground solution? The easiest one is probably to read the alignment value from user defaults, and if it's missing then go for appleCentered value. As it would be missing for most instances, this would preserve the current designed behavior (and UI) while also also leaving the option to set the desired alignent for those who's not happy with 0.75.

**Comment by lwouis** [comment]
I'm not a fan of such "hidden" preferences (preferences tweakable through `defaults` but without any UI for casual users. I would prefer that, if we spend time/energy improving, we improve it the right way.

That being said, i understand the bug redesign may not come soon, so i understand the practicality of what you suggest.

**Comment by franco-ruggeri** [comment]
Hi, is there any progress on this? I personally would prefer to keep the default MacOS style (I am using this utility for features such as switching among apps only in the current space).

**Comment by TomEstelrich** [comment]
Agree with @franco-ruggeri. I'm using Alt-Tab daily on all my computers and I would love to see this option being implemented as well! +1

**Comment by tenitski** [comment]
I can't use Alt-Tab specifically because of this... Hurts my eyes too much.

**Comment by jacklolidk** [comment]
+1

**Comment by afefer** [comment]
Another +1 from me. Considering that both Windows 11 and MacOS vertically center the alt-tab UI, it feels a bit strange for this to adopt a different design philosophy.

**Comment by tejasraman** [comment]
+1. Pretty much every other switcher I've used puts it in the center. This would make it look much better..l

**Comment by afefer** [comment]
@lwouis perhaps I'm opening a can of worms here, but if you don't want to expand the preferences window, would you be open to making vertical centering the default setting?

I know in your previous comment you had a preference for the "book title" style, but it sounds like there's a not-insignificant number of users (myself included) who find this jarring (and on a large monitor, tiring).

**Comment by afefer** [comment]
@lwouis if there's no appetite to expand the preferences window, any chance you're open to revisiting this design decision and just make vertically centered the default? 

It's particularly problematic on large external monitors, and just looking through the comments I suspect most favor a centered layout.

**Comment by mrAnomalyy** [comment]
+1. Pretty interested in this. On big screens, that looks ridiculous and really hurts UX - you have to look at the top of the screen

**Comment by phzh24** [comment]
I also want the thumbnails centered! It's quite unnatural to dart one's eyes to the top of the screen. 

With this figure included, the app would be perfect!

**Comment by kocho1984** [comment]
No need to add additional option to settings.  I think it should be done when user sets macOS theme because original macOS app switcher is centered.

**Comment by lwouis** [comment]
Please see [my original motivations listed above](https://github.com/lwouis/alt-tab-macos/issues/585#issuecomment-889237067).

Please keep in my that this thread has around 15 participants asking to change the design.  AltTab is used by probably between 50K and 100K people. All thing considered, it may not be a majority opinion to change the way it is. I'm still open to the idea though. As you can see I've kept this ticket open since 2020 as a potential change.

So far, I haven't seen either: (a) enough people asking for it that it's obvious it should happen, or (b) a proposal to integrate the preference in a way that is not adding to the clutter (see #351 for potential complete reworks of the preferences where it could be done).

**Comment by kocho1984** [comment]
> @kayc7 to reply to your question in the duplicate ticket #1059:
> 
> > why is the app switcher even centered near the top as a default?
> 
> I have a background in typography and layout. Books for instance don't usually vertically center their title. Instead they put it [a bit higher](https://m.media-amazon.com/images/I/21tMuSOgpcL.jpg). It looks better than at 50%. It was an aesthetically choice to replicate that for AltTab. It's also part of the UI guidelines from macOS. 

If so, than Apple implemented app switcher against their own guidelines.

**Comment by ocreturner** [comment]
id like to first apologize for commenting about this since its been so long but since its still **open** id like to bring my vote for it. ive done my very best to try to ignore the need for this feature but i just cannot anymore . 

please consider adding the ability to vertically align this beauty. Having Alfred, command switcher, spotlight, raycast in a different position to alt-tab is truly disheartening 😕

**Comment by ocreturner** [comment]
if there is any consideration to adding the ability to move it with a mouse grab with a modifier that would be a great way to do it i think

**Comment by tejasraman** [comment]
> if there is any consideration to adding the ability to move it with a mouse grab with a modifier that would be a great way to do it i think

This is similar behavior to Raycast and the default Spotlight search (i think this is a good idea)

**Comment by lwouis** [comment]
@sapoepsilon thank you for working on this. Don't hesitate to share some draft, even on paper, with me. I have years of experience, and feedback from thousands of users, each with their intriguing use-cases. It could save you time and avoid going in the wrong direction to run some ideas by me before implementing them. It's just a suggestion of course. Don't hesitate to ask for my help 👍

**Comment by sapoepsilon** [comment]
> @sapoepsilon thank you for working on this. Don't hesitate to share some draft, even on paper, with me. I have years of experience, and feedback from thousands of users, each with their intriguing use-cases. It could save you time and avoid going in the wrong direction to run some ideas by me before implementing them. It's just a suggestion of course. Don't hesitate to ask for my help 👍

Sounds good, thank you. I am still getting used to, and exploring the codebase. I will create a draft PR once I have done anything shareable.

**Comment by sapoepsilon** [comment]
@lwouis  I created a draft PR #2697  where I somewhat implemented the MacOs theme. Also, I made a dummy Figma prototype with the new appearance tab per your video [here](https://github.com/lwouis/alt-tab-macos/issues/351#issuecomment-1317633417).  I would appreciate some guidance on how the appearance tab should look like.

**Comment by qizidog** [comment]
request vertically align

**Comment by sapoepsilon** [comment]
> request vertically align

I am working on it on my branch. I actually have implemented it already, you could build [alt-tab](https://github.com/lwouis/alt-tab-macos/pull/2697) from my branch. It still has many bugs, and I am implementing complete design overhaul. So, it will take long time until I am completely done with the design overhaul

**Comment by tejasraman** [comment]
> > request vertically align
> 
> I am working on it on my branch. I actually have implemented it already, you could build [alt-tab](https://github.com/lwouis/alt-tab-macos/pull/2697) from my branch. It still has many bugs, and I am implementing complete design overhaul. So, it will take long time until I am completely done with the design overhaul

your branch works, tysm!

**Comment by darkguy2008** [comment]
For everyone arriving here through a Google or GitHub issues search like I did, here's a branch I made as of date with the proper alignment of the alt-tab dialog, with atomic commits (just 3 so far) to make it work with XCode 15:

https://github.com/darkguy2008/alt-tab-macos

I just found this app today and love the developer's work so far. The only downside I see is that there's no preference setting to change the vertical position which left me puzzled looking for that option in the preferences window.

Comparing books to computers is just like comparing apples to oranges... UI/UX for both are too different to even compare, so when it comes to digital UI/IX, even though I don't have a degree in anything, it's basic common sense (and it's been shown here by other commenters) to expect a replacement switcher to be **in the same location as the one being replaced**, or heck, at least a small setting to configure it... Quite interesting considering the liberty taken to still have a backwards switch hotkey toggle in the preferences.

There may be tens of thousands of users using this app, but I don't think that the fact that there's just "15" participants asking for a feature that's definitely useful and expected in an app like this, should make their opinion less important or less valuable to not even consider their opinion as such.

Kepe up the great work though!

**Comment by aramca27** [comment]
> For everyone arriving here through a Google or GitHub issues search like I did, here's a branch I made as of date with the proper alignment of the alt-tab dialog, with atomic commits (just 3 so far) to make it work with XCode 15:
> 
> https://github.com/darkguy2008/alt-tab-macos
> 
> I just found this app today and love the developer's work so far. The only downside I see is that there's no preference setting to change the vertical position which left me puzzled looking for that option in the preferences window.
> 
> Comparing books to computers is just like comparing apples to oranges... UI/UX for both are too different to even compare, so when it comes to digital UI/IX, even though I don't have a degree in anything, it's basic common sense (and it's been shown here by other commenters) to expect a replacement switcher to be **in the same location as the one being replaced**, or heck, at least a small setting to configure it... Quite interesting considering the liberty taken to still have a backwards switch hotkey toggle in the preferences. Sometimes you don't need a degree to notice something is off :)
> 
> There may be tens of thousands of users using this app, but I don't think that the fact that there's just "15" participants asking for a feature that's definitely useful and expected in an app like this, should make their opinion less important or less valuable to not even consider their opinion as such.
> 
> Kepe up the great work though!

Hi! I want to run this fix, but I have absolutely no experience with this kind of mods. Can you explain me how can I use this branch so I can center the position of altab? Thanks!!!

**Comment by darkguy2008** [comment]
> > For everyone arriving here through a Google or GitHub issues search like I did, here's a branch I made as of date with the proper alignment of the alt-tab dialog, with atomic commits (just 3 so far) to make it work with XCode 15:
> > https://github.com/darkguy2008/alt-tab-macos
> > I just found this app today and love the developer's work so far. The only downside I see is that there's no preference setting to change the vertical position which left me puzzled looking for that option in the preferences window.
> > Comparing books to computers is just like comparing apples to oranges... UI/UX for both are too different to even compare, so when it comes to digital UI/IX, even though I don't have a degree in anything, it's basic common sense (and it's been shown here by other commenters) to expect a replacement switcher to be **in the same location as the one being replaced**, or heck, at least a small setting to configure it... Quite interesting considering the liberty taken to still have a backwards switch hotkey toggle in the preferences. Sometimes you don't need a degree to notice something is off :)
> > There may be tens of thousands of users using this app, but I don't think that the fact that there's just "15" participants asking for a feature that's definitely useful and expected in an app like this, should make their opinion less important or less valuable to not even consider their opinion as such.
> > Kepe up the great work though!
> 
> Hi! I want to run this fix, but I have absolutely no experience with this kind of mods. Can you explain me how can I use this branch so I can center the position of altab? Thanks!!!

Just use the instructions in the original repo (this) for building/compiling. You need XCode and all that. Instead of cloning this repo, you'd clone mine (which is a fork). Let's not pollute the original repo issue with support for mine though :) I'm no expert anyways.

**Comment by alexaldearroyo** [comment]
Still no improvement? I like how the app works, but the switcher not being centered is baffling. Looks amateurish?

@darkguy2008 Thank you for your efforts. Is it not possible to make it installable? Having to install XCode to be able to use your fork seems a little bit overboard.

**Comment by afefer** [comment]
It's been nearly 4 years since this ticket was originally opened - as a temporary stopgap while the new preferences are being worked on, can we just add an additional option to the existing preferences to vertically center the dialog?

My sense is that the number of people who will complain about an additional checkbox in the preferences (how often do people look in there, anyway?) is vastly smaller than the number of people who are currently annoyed by the lack of vertical centering (which impacts constant, day-to-day usage).

**Comment by kocho1984** [comment]
I have used many operating systems: Windows, macOS, Linux and all of them have that dialog vertically centered. That means that users got used to centered dialog. Their eyes are looking for that dialog at the center, not at the top. Why not to follow all those operating systems?

**Comment by lwouis** [comment]
Hi everyone,

Please keep in mind that there are maybe 150K people using the app, and 21 people complaining about the position in this thread.

While you may feel that the current behavior is obviously wrong, I'm not sure it is. I'm not sure my initial choice of having it a bit higher like titles in a book is the right one either. I view this as a coin toss. I don't have enough data to judge which design is best.

I don't even know which data could be gathered to decide this. How fast people find the right thumbnail? Misclicks outside the UI? Self-survey of people saying if they like one or the other? People could say they prefer something, while that design is measurably making it harder to find stuff and navigate, by the way.

It's a tricky topic. A bit like saying that the Coca-Cola logo shouldn't be red because it's a violent color. Maybe? Maybe not? Who can really say if they wouldn't have even more market share with a blue logo? I don't think there is necessarily one truth to things, especially when the userbase is large, and especially over time as culture can shift. See how rounded vs straight keeps coming in and out of fashion with OS look and feel over time. See how clothes fashion is basically randomly rotating.

**Here's a compromise we could go for**: let's have this centered switcher as a theme. There is already a theme dropdown, so it doesn't add yet another preference. It could be something like "macOS centered". If someone here shares a PR, I'll merge it.

Thank you 🙇

**Comment by eugenesvk** [comment]
> I'm not sure my initial choice of having it a bit higher like titles in a book is the right one either. I view this as a coin toss. I don't have enough data to judge which design is best.
> 
> I don't even know which data could be gathered to decide this.

User customization is the solution to such issues, and it'll be also easier to do than conducting a proper study on UI effectiveness of such minor things (and implementing good telemetry is practically impossible and will also take orders of magnitude more time on building and reviewing user journeys to see where they fail). Tangentially, that's also the reason why simplifying-by-removing from 351 isn't a good approach

But I sympathize with the lack of actual code contributions

**Comment by ocreturner** [comment]
I can honestly say that I have only opened the settings section of the app 4-6 times since I downloaded
it in 2023.

After I configured everything, I just kept using it. It wasn't until recently that I gave up on the centered
version of the app and stopped using it for a while.

Basically, what I am saying is that sometimes building an app can make us think the end user is
constantly adjusting settings every other week. That is why I truly believe that making the ability to
center it will not hinder it whatsoever.

Just another viewpoint

**Comment by afefer** [comment]
Thanks @lwouis, appreciate being open to adding this! I've just submitted a PR that adds vertically centered versions of both the MacOS and Windows themes.

**Comment by Allsochen** [comment]
> Hi everyone,
> 
> Please keep in mind that there are maybe 150K people using the app, and 21 people complaining about the position in this thread.
> 
> While you may feel that the current behavior is obviously wrong, I'm not sure it is. I'm not sure my initial choice of having it a bit higher like titles in a book is the right one either. I view this as a coin toss. I don't have enough data to judge which design is best.
> 
> I don't even know which data could be gathered to decide this. How fast people find the right thumbnail? Misclicks outside the UI? Self-survey of people saying if they like one or the other? People could say they prefer something, while that design is measurably making it harder to find stuff and navigate, by the way.
> 
> It's a tricky topic. A bit like saying that the Coca-Cola logo shouldn't be red because it's a violent color. Maybe? Maybe not? Who can really say if they wouldn't have even more market share with a blue logo? I don't think there is necessarily one truth to things, especially when the userbase is large, and especially over time as culture can shift. See how rounded vs straight keeps coming in and out of fashion with OS look and feel over time. See how clothes fashion is basically randomly rotating.
> 
> Also please keep in mind that no-one has contacted me regarding #1179. I've replied to 3000 tickets on this open-source repo. No one helps me triage tickets. I've gotten impressively little help over the years with actual contributions. Lots of tickets, lots of ideas and criticisms. Very few people actually chipping in and helping concretely. #351 could have been done a long time ago, if anyone had done it, or even contributed a piece of it.
> 
> **Here's a compromise we could go for**: let's have this centered switcher as a theme. There is already a theme dropdown, so it doesn't add yet another preference. It could be something like "macOS centered". If someone here shares a PR, I'll merge it.
> 
> Thank you 🙇

I think incorporating this functionality into the theme is not a good choice. It should be designed as an option, related to color schemes rather than display positioning. If we feel there are too many options, we can take inspiration from iTerm2 and categorize the options into tabs. Provide simple choices for regular users and offer more personalized configuration options for advanced users.

<img width="785" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/242f3819-4096-4fe8-9cfb-e99e356cf53f">

**Comment by Jack-Works** [comment]
maybe it's OT, I clone and compile this app on my machine to get unmerged feature #2355 and vertically centered dialog. It's a little bit inconvenient but acceptable.

**Comment by afefer** [comment]
> I think incorporating this functionality into the theme is not a good choice. It should be designed as an option, related to color schemes rather than display positioning. If we feel there are too many options, we can take inspiration from iTerm2 and categorize the options into tabs. Provide simple choices for regular users and offer more personalized configuration options for advanced users.

I agree, but we've been going in circles on this for 4 years and this is the only compromise we've been able to arrive at that will get this functionality into the app. I'd rather have it now in a less-than-ideal place (the theme) rather than chase perfection for another 4 years. One day this can be refactored with the new settings work in #351.

**Comment by afefer** [comment]
> Please keep in mind that there are maybe 150K people using the app, and 21 people complaining about the position in this thread.

On that topic - given that this is an end-user application (as opposed to something like a developer tool), it's safe to assume the vast majority of users aren't active on GitHub. Looking at absolute numbers and comparing that against the overall userbase isn't a good way to assume how many people aren't happy with a particular design decision.

Interestingly though, if you look at all 3,105 GitHub issues, if you filter out bugs this is the second highest upvoted feature request of all time for this project.

<img width="1234" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/3399494/04144fdb-7ff2-4236-bc4c-d7f19e892035">

**Comment by lwouis** [comment]
> On that topic - given that this is an end-user application (as opposed to something like a developer tool), it's safe to assume the vast majority of users aren't active on GitHub. I'm not sure that looking at absolute numbers and comparing that against the overall userbase is an ideal way to assume how many people aren't happy with a particular design decision.

There is a "Share feedback" button in the app, both in the menubar icon and in the preferences. People use it quite a lot to share their ideas or bug reports. Reporting there opens a github issue. This is feedback in github, by non github users. They don't come here to check it most of the time, so the same ideas/bugs are being shared by many people. This is another source of feedback I consider to get a sense of what's niche and what's mainstream.

**Comment by YarAllex** [comment]
https://github.com/lwouis/alt-tab-macos/pull/3435
?

**Comment by vardecab** [comment]
Has this been dropped? It's been a while since the change was committed in https://github.com/lwouis/alt-tab-macos/pull/3435 but it doesn't look like the merge happened 😞

**Comment by lwouis** [comment]
This change will happen with https://github.com/lwouis/alt-tab-macos/pull/3468, which is progressing quickly.

AltTab will be centered at 1/2 height, with no option to change it back to the current 2/3 centering.

**Comment by hicaicai** [comment]
> This change will happen with #3468, which is progressing quickly.
> 
> AltTab will be centered at 1/2 height, with no option to change it back to the current 2/3 centering.
When's the update?

**Comment by tejasraman** [comment]
> This change will happen with #3468, which is progressing quickly.
> 
> AltTab will be centered at 1/2 height, with no option to change it back to the current 2/3 centering.

finally we're done with 2/3 centering

**Comment by SupremeRubisco** [comment]
> This change will happen with #3468, which is progressing quickly.
> 
> AltTab will be centered at 1/2 height, with no option to change it back to the current 2/3 centering.

Any recent updates on this merge? Looks like no one has looked at it yet.

**Comment by lwouis** [comment]
Hi,
It's almost done 👍

**Comment by lwouis** [comment]
v7.0.0 was released today, with this change. Closing this ticket 👍

**Comment by alexaldearroyo** [comment]
@lwouis Thank you so much for adding this feature. Now it looks like charm. Kudos for your work.
