### ISSUE TITLE
Drag and Drop screenshots of apps while holding Cmd+Tab

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#624]
This seems like a niche feature, but being able to drag a window and have alt-tab take a screenshot and copy it to the clipboard and then paste it into the text-box would be nice. If this is too niche and issue, it might just be good to close it. Let me know if this is easily achievable or not.

**Comment by lwouis** [comment]
> being able to drag a window and have alt-tab take a screenshot and copy it to the clipboard

Could you please clarify the interaction?

* The user mouse hovers one of the open window listed in AltTab UI
* They press the mouse to start dragging the open window
* ????
* They release the mouse somewhere. Where?
* The window is now in the clipboard

It sounds like it would be simpler to add a shortcut to screenshot the window, like minimize/close/etc. For example, press `c` and it screenshots it.

That being said, I don't think there is a place for screenshots in AltTab. This is already served very well by the built-in Screenshot.app, as well as a flurry of third-party apps, all more sophisticated than the other. If I add screenshot capabilities to AltTab, then it will be subpar because I don't want to pollute the UI and preferences UI with things like screenshot format, size, compression, with-or-without shadows, etc. And If I don't add these things then it's a very bare-bone experience and what's the point over other dedicated apps.

I'll close the ticket for now, but feel free to discuss it more. If other people are interested, we can re-open the ticket of course. As it stands it seems a bit too fringe of a value-proposition

**Comment by SoPat712** [comment]
I need screenshots of windows pretty often. One way, of course, is to us MacOS' screenshot app, but I was thinking that if Alt Tab could do that work, that it would make my workflow easier, but you're right. It does seem like a niche issue, and something that's not really useful for Alt-tab.
