### ISSUE TITLE
Reeder app does not show window and always at the bottom

### ISSUE THREAD

**Issue by ngocphamm** [lwouis/alt-tab-macos#628]
**Describe the bug**

The Reeder app (RSS reader) does not have thumbnail on AltTab, and it's always at the bottom of the list.

Too bad the app is not free, and it's only on Mac App Store so I know it's gonna be hard to test/reproduce. Please let me know if I can help in some way.

**Screenshots / video**

<img width="279" alt="2020-09-25 at 9 24 AM" src="https://user-images.githubusercontent.com/395123/94479990-9d94be00-01a3-11eb-9360-6854d8611e3a.png">

**Steps to reproduce the bug**

1. Get Reeder app (https://www.reederapp.com/4/)
2. Open it
3. Trigger AltTab
4. The Reeder app does not have thumbnail and is always the last one to show

**Comment by lwouis** [comment]
This is most likely due to Reeder not coding their windows as windows. I would suggest talking to them. Have you opened a support ticket with them? I would start there

I could hardcode the app so that it shows in AltTab anyway, but for that first i would need to run the app locally. It there any way to demo this? Maybe ask the devs for a test license for me so i can work on it.

Again most likely other accessibility apps will have a problem with this app if AltTab does, so it would propably be best to open a support ticket to let them know it's broken.

**Comment by ngocphamm** [comment]
Thanks @lwouis. I will try to open a ticket with them, and if that isn't going anywhere I will try asking for a test license for you!

**Comment by lwouis** [comment]
@ngocphamm any update?

**Comment by ngocphamm** [comment]
Sorry I haven't contacted Reeder developer. Please disregard this issue for now. I will re-open it whenever I have the info from the other developer. Thank you!

**Comment by ngocphamm** [comment]
Just FYI @lwouis Reeder 5, the latest version, doesn't seem to have the problem so I guess you were right that it's something from the app. Working great here! Thank you for making this beautiful piece of software!

**Comment by lwouis** [comment]
That's good news. Thanks for sharing this info with everyone 👍
