### ISSUE TITLE
Android emulator not in the alt-tab list

### ISSUE THREAD

**Issue by chronvas** [lwouis/alt-tab-macos#653]
**Describe the bug**

Android emulator not in the alt-tab list
This looks like a regression reading this #444 and #376 and possibly others

**Steps to reproduce the bug**

Using alt-tab version 6.7.3
Android studio 4.1
MacOS 10.15.4

- I understand that android studio is quite special, and I have a question regarding this:
If a similar "special" application window exists, can this be added to the alt-tab list with using a default icon for it's view instead of ommited completely?

Thank you for your awesome work

**Comment by lwouis** [comment]
Hi @chronvas! Thanks for sharing this issue!

It's most likely a regression *from Android Studio*. The Android Emulator is a cross-platform app. Its windows are improperly exposed as accessibility elements. A screen reader for instance would not be able to help a blind person understand it, for example. The emulator also has the weird characteristic of having no `bundleIdentifier` (every app has one, like TextEdit would be `com.apple.TextEdit`).

You can see here [the hoops I added to workaround their poor accessibility interface](https://github.com/lwouis/alt-tab-macos/blob/08581f50c34faa72921cdd19358712edd85e088a/src/api-wrappers/AXUIElement.swift#L146), and make it usable with AltTab.

If it stopped working, I'm not sure what they changed. I'll need to download the whole thing and try it locally to investigate.

> If a similar "special" application window exists, can this be added to the alt-tab list with using a default icon for it's view instead of ommited completely?

From that question, I think that you think that the issue is the visual, like showing the window contents. It's not the issue. The issue is recognizing what a "window" is. If we just showed everything that's supposed to be a window, AltTab would be full of UI elements that a user wouldn't consider windows. Steam for example, has dropdown menus that are coded as "windows", so you would see these menus listed in AltTab, because technically they are windows. Except end-users (rightly) don't recognize them as windows.

The long-term improvement of the heuristic that discriminate a "real window" from "technically a window" is discussed in https://github.com/lwouis/alt-tab-macos/issues/456. This ticket needs someone to come up with a breakthrough.

**Comment by lwouis** [comment]
I could reproduce the issue locally. It turns out it was in fact a regression from AltTab, not from the emulator. I didn't change the window heuristic recently, but I changed the [process heuristic recently](https://github.com/lwouis/alt-tab-macos/blob/08581f50c34faa72921cdd19358712edd85e088a/src/logic/Applications.swift#L105), to better exclude XPC processes from being watched by AltTab. In the process, this removed Android Emulator from being observed.

Note that Android Emulator has an incorrect `activationPolicy`: `.prohibited`. Apple docs state that such a policy means:

> The application doesn’t appear in the Dock and may not create windows or be activated.

This is why the emulator is not listed in AltTab, because its process declares it will not create windows, thus we ignore it. But then it does create a window.

I'll push a workaround for this in the next release 👍
