### ISSUE TITLE
When you change the shortcut key to command+->, it conflicts with cheatsheet

### ISSUE THREAD

**Issue by l54808821** [lwouis/alt-tab-macos#658]
When you change the shortcut key to command+->, it conflicts with cheatsheet

**Comment by lwouis** [comment]
Hi @l54808821,

You flagged this as a bug, but I'm not sure it is. Shortcut conflicts are outside of the scope of this project. Any app can add shortcuts that conflict with other apps, or with the OS shortcuts.

AltTab has an exception for `cmd+tab` since it's a command use-case people want. In that case we disable the built-in app switcher so AltTab can replace it. For other shortcuts, it's up to the users to avoid conflicting shortcut. There is no API to have one app change the priority of shortcuts. AltTab couldn't decide to get the shortcut before the OS for instance.

I'm not sure what you mean by "cheatsheet". Which app is this? Can you share more context?

In any case I would suggest to either remap/disable this cheatsheet shortcut, so AltTab can have it, or change it in AltTab, so there is no conflict
