### ISSUE TITLE
"Select previous window" cannot be set depending on the shortcut

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#670]
**Describe the bug**

I pondered whether I would consider this a feature or bug, but eventually went for "bug" as it broke my user expectations (but feel free to just change it 😅).

I use two different shortcuts
1. for "All apps" => <kbd>cmd-tab</kbd>
  and
2. "Active app" => <kbd>cmd-`</kbd> (the one before the numeric <kbd>1</kbd>)

I realized I could switch "forward" to the next window and not to the previous so I set the
- "Select previous window" to <kbd>shift-tab</kbd>

Since it didn't work for "Active app" I changed it to <kbd>shift-`</kbd> but failed to realize that this is not related to the "Shortcut 1" and "Shortcut 2" distinction 💥 and I thought it was a bug.

I'm wiser now, but basically: I cannot define "mirror matching" keys to navigate to the previous window _depending_ on which shortcut I chose to open "all" or the "active" windows.

My end goal would be to have:
1. for "All apps"
  - Select next window: <kbd>cmd-tab</kbd>
  - Select previous window: <kbd>shift-tab</kbd> (while holding <kbd>cmd</kbd>)
  and
2. "Active app"
  - Select next window: <kbd>cmd-`</kbd>
  - Select previous window: <kbd>shift-`</kbd> (while holding <kbd>cmd</kbd>)

Aka I would expect when I have different shortcuts for "Select next window" I would also have different ones for "Select previous window", but this currently isn't possible:
![image](https://user-images.githubusercontent.com/87493/97601617-a67ae880-1a0a-11eb-8049-b3585001899f.png)

Thanks!

**Comment by lwouis** [comment]
It's indeed not a bug, as in: the app is not malfunctioning. It would be a change in functionality to enable a workflow you would like. Let's call that an enhancement.

The same idea could be generalized to all shortcuts in the "While open, press:" section. Minimizing windows could have specific shortcuts depending on the initial activation shortcut. I would suggest that this is an increase in complexity for no practical benefits.

The idea of having 2 *trigger* shortcuts is to present the UI under 2 sets of preferences. For example, `All apps` vs `Active app`. Once the UI is triggered, all actions are the same, regardless of which shortcut brought the UI. The idea of doubling the shortcuts seems to me like doubling the shortcuts to remember, the app complexity, to no benefit.

You could for instance keep the default shortcut of `shift`, which is a great ergonomics improvement I borrowed from HyperSwitch. You can use it for both initial shortcuts. It's easier on your fingers, simpler to remember. Basically no downsides only upsides.

In my experience people don't like to hear suggestions about changing their habits (#510), or reconsidering their position on how things should be. I hope you take a moment to consider my arguments.

As a very interesting aside, I had the realization this week (not sure why it took so long, but I guess it's not *that* obvious), that every single preference in the app could be set *per shortcut*. I mean be mirrored for each shortcut, the way you mentioned in this ticket. The size of the UI could be per shortcut. The number of rows of windows could be per shortcut. Etc. The reason for the current split in what is global, and what is per shortcut, is just people asking to enable these workflows. I thought about having every single preference per shortcut, and then realize it would be a burden for users who actually want their preference changes to be global and not have to set them twice every time. Then I thought I could add some UI to set a shortcut globally or per shortcut. Then I stopped myself and realized there is no way the end UI would be as simple as it is currently. It's already quite complex due to the flexibility. That reflection made me think that I should be careful with which flow is per shortcut, as it is increasing the burden on the user when setting their preferences. They have more work/thinking to do. Of course a specific user who want more flexibility will ask for a global to be split, but we should measure the added cost of doing that. In the case of this ticket, I don't see clear benefits.

**Comment by mfn** [comment]
> You could for instance keep the default shortcut of `shift`

That will do, smart idea, thank you 🙇‍♀️!
