### ISSUE TITLE
Add Gnome theme

### ISSUE THREAD

**Issue by mjog** [lwouis/alt-tab-macos#702]
In the same way there are MacOS and Windows presets, it would be great to be able to emulate GNOME 3's alt window switcher (the default is similar to MacOS's), as shown in this screenshot:

![Screenshot from 2020-11-19 11-37-49](https://user-images.githubusercontent.com/3745088/99605696-51a41e00-2a5c-11eb-8ddc-c1dd2412adc7.png)

Note the window title appears at the bottom, only for the selected window, and the app icon overlaid in the bottom corner. This makes the switcher a lot less noisy and easier to scan.

**Comment by lwouis** [comment]
Hi @mjog! Thank you for suggesting this addition

The Windows and macOS themes are quite similar, so it's about setting a few colors and borders differently. The changes to enable a Gnome theme would involve deeper refactors. For instance having the app icon inside the thumbnail instead of above it has many implications like what happens when the app icon size is set bigger than the thumbnail, or the thumbnail is turned off. I think adding this theme would be significant work and QA. Unfortunately i'm basically the only contributor these days so with ~60 other tickers in the backlog, I can tell you that this ticket will probably not move quickly.

Or course anyone is interested in contributing this change, i would gladly help and support it 👍

> This makes the switcher a lot less noisy and easier to scan

I disagree, but that's my opinion of course 😌

**Comment by SoPat712** [comment]
I can take a look at this, but keep in mind I'm extremely lazy. I'll get back to you in a year or two with a pull request haha.

**Comment by mjog** [comment]
Unfortunately I don't have OSX dev experience and my spare time is devoted to maintaining Geary, so apologies but I won't be able to contribute the feature.

**Comment by lwouis** [comment]
I'm afraid this is too niche and nobody will do it, so closing this for now
