### ISSUE TITLE
Multi-select windows?

### ISSUE THREAD

**Issue by avivo** [lwouis/alt-tab-macos#709]
**Is your feature suggestion related to a problem? Please describe.**
It can be very useful to take an action on several windows at once, for example, bringing several windows to the front (or [combining with other approaches](https://forum.keyboardmaestro.com/t/move-frontmost-window-to-a-different-space/10512/5) to move several windows to a new space). I particularly would like this for rapidly moving several applications to a new space for fast context switching.

**Describe the solution you'd like**
Be able to select windows which will be brought to the front after alt-tab session ends.

**Describe alternatives you've considered**
Other alternatives include (1) bringing a window to the front with a keyboard shortcut without dismissing alt-tab (such that it moves in the list to the front, and perhaps the window ordering changes behind alt-tab, but there is no explicit selection, or (2) running some specified applescript that takes as input a list of selected windows and allows the execution of any command. (These might actually be better than the original approach, but also more complex...)

**Comment by lwouis** [comment]
Hi @avivo! That's an interesting idea.

My immediate thought is about the UX. Could you please provide a detailed description of how the use would interact to go about this workflow? The solution should take into account:

* existing shortcuts
* existing mouse interactions
* the fact that any shortcut can be re-mapped to any key combination
* existing interactions (e.g. drag-and-drop of files onto thumbnails, etc)
* the fact that for most people the alt key (can be changed) has to be held at all times when inspecting thumbnails. Note that there is a preference which makes it not focus on release, but on pressing another dedicated focus shortcut

For instance if you would say "i can hold another modifier like shift and then click on windows to multi-select, then i would tell you that shift is already the default for backwards cycling selection. Also what happens if you multi select 3 thumbnails then release alt? Etc. There are many things to consider, so a first step would be to flesh out the details of how this feature would work 👍

**Comment by lwouis** [comment]
I discovered the other day that the native macOS app-switcher lets the user press `shift`, and then the user can press `q`, and instead of quitting that app then hiding the app-switcher UI, it quits the app and keeps the UI open so the user can quit more apps. It's ideal when you want to close multiple apps in quick succession.

I think it's a bit similar to what this ticket is about.

An issue though is that AltTab lets the user remap all shortcuts. So we can't just assume the shift key is available and not even the single key that keeps AltTab UI open (i.e. the user set the shortcut to open AltTab to `shift+tab`).

**Comment by lwouis** [comment]
I think it would be quite clunky to support multiple focus actions since after each it would re-order the thumbnails which would make it hard to move on to the next one.

That being said, the workflow of sending multiple windows to another Space makes sense to me. It wouldn't jump around and it's a common workflow for people.

This workflow is already discussed in #1088 so closing this
