### ISSUE TITLE
AltTab not starting on macos 10.15

### ISSUE THREAD

**Issue by OranShuster** [lwouis/alt-tab-macos#71]
AltTab is not working for me for several versions now
tried to run it from source and got the following exception

`"Error loading preferences" Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "cellPadding", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
`

**Comment by lwouis** [comment]
Quick-fix: please remove your preference file and restart the app. It will work again

Improvements to do: open a ticket to better handle preferences migration

1. If the json parsing fails, we can:
* show the user there was a problem
* possibly send that to some stats server for telemetry but this is a controversial topic in the OSS community
* remove the existing file and use the defaut from the current app

2. Better handle when parsing works
* remove the version key/value and instead do some smart merging of old prefs and new defaults

**Comment by OranShuster** [comment]
Breaking changes will happen with configuration files so the parsers should be versioned and kept along side. each parser should ideally have an "upgrade" method for the next consecutive version (and then the parsers can be run one after another untill the latest version)

**Comment by lwouis** [comment]
You describe an advanced retrocompatibility story. That's certainly a nice thing for the user but there is a tradeoff to maintain all these code paths.

Because we have other bigger projects at the moment we may want to implement a quick and dirty solution like what i describe. Later when the app is more mature we may decide to invest in retrocompat

Of course this is OSS so if anyone thinks retrocompat is their priority #1, they can open a PR and get it done now ;p

**Comment by OranShuster** [comment]
ofcourse :]
