### ISSUE TITLE
ATM breaks certain rename functionality in PyCharm 2020.3

### ISSUE THREAD

**Issue by akx** [lwouis/alt-tab-macos#716]
## Describe the bug

This is a weird one...

When ATM is enabled, using the `Ctrl+T, Enter` shortcut in the PyCharm 2020.3 IDE to rename an identifier doesn't work correctly anymore. Where you should be able to edit text using multiple carets, only arrows and delete/backspace work anymore, so you can't quite rename identifiers (unless you like very short identifiers). Only clicking in the editor restores normal functionality.

I initially thought this was a JetBrains problem/regression and raised an issue on their tracker: https://youtrack.jetbrains.com/issue/PY-45867

## Screenshots / video

I overlaid my keypresses on top of the gif to make things hopefully a little clearer.

### Broken (when ATM is active)

![rename_fail_keys](https://user-images.githubusercontent.com/58669/101362060-4d735f80-38a8-11eb-9bfe-6914566dbb92.gif)

### Working (ATM not active)

This was tried a couple hours later, hence the code isn't the same.

![rename_work_keys](https://user-images.githubusercontent.com/58669/101362074-4fd5b980-38a8-11eb-84b1-1105c9ff5f82.gif)

## Steps to reproduce the bug

1. Have ATM running.
2. Open PyCharm 2020.3 (Professional in my case).
3. Set up a document where you can attempt to rename an identifier.
4. Hit Ctrl+T to open the Refactor This popover, then hit enter to use "Rename".
5. Attempt to modify text. It doesn't work correctly.

## Workarounds

* If I use the context menu -> Refactor -> Rename option, this doesn't occur
* If I use shift+f6 instead of ctrl+t and enter, this doesn't occur

**Comment by lwouis** [comment]
Hi @akx! It's been a while, thanks for the nice quality ticket!

Which exact version are you using? There have been many issues in the past with the EAP branch: #660 #652 #562

**Comment by akx** [comment]
Heya 😄 

I've downgraded to PyCharm 2020.2.x for the time being because I need both Alt+Tab and working renames. The version that did exhibit this is `PyCharm (build #PY-203.5981.165, 07 Dec 2020 16:09)` according to the log. Running MacOS 10.15.6, fwiw.

**Comment by lwouis** [comment]
If downgrading fixes it for you then it seems to be an issue from JetBrain's side. They currently have, in the EAP, this strangeness that if AltTab subscribes to a specific Accessibility Event, it breaks their behavior: https://github.com/lwouis/alt-tab-macos/blob/5f9caed280a60496f39d229c20993fe474bcd4d6/src/logic/Application.swift#L29

It should be possible that an app break another app by observing its event. The only thing I could imagine is that they rely on their own accessibility events internally, and AltTab listening to it somehow affects it. It could also be a macOS bug that only surfaces because the IDE is Java + large codebase and brings out exotic scenarios.

**Comment by ibrahimabdo** [comment]
I think the above regex is failing because the current version of JetBrains products are not in the early access program anymore, therefore they don't have EAP inside their name and bundle identifier.

**Comment by akx** [comment]
@lwouis Yeah, indeed 2020.3 is no longer EAP – what functionality is degraded if we don't subscribe to that event at all for any Jetbrains app?

**Comment by lwouis** [comment]
I didn't understand what you guys were talking about until I went into the Jetbrain Toolbox app, and observed that indeed they have stopped the EAP program on almost all their apps. Some still have it, but most don't. I wasn't aware they stopped doing EAP.

Fun side-note: my AppCode license I've used for the past year to develop AltTab has expired this month. I asked them for a new one, through their OSS program. I hope they don't shut that one down ;p

@akx here is the ticket that this regex fixed: https://github.com/lwouis/alt-tab-macos/issues/652. Notice how similar the issue is.

> what functionality is degraded if we don't subscribe to that event at all for any Jetbrains app?

The exception prevents us from shaking standard tabs. Jetbrains products don't use AppKit standard tabs, so I think it would be easy to change the regex to match `com.jetbrains.` and fix this issue
