### ISSUE TITLE
Support file drag & drop into the Switcher

### ISSUE THREAD

**Issue by gingerr** [lwouis/alt-tab-macos#74]
Suggestion is to implement the same behaviour as in the native switcher:
- the user drags a file
- opens AltTab
- moves with the mouse (dragged file) into the UI
- hovers for a specified time over a thumbnail
- the selected thumbnail container begins to blink after 1 second (optional)
  - and stops if the user moves away from the thumbnail
- the selected thumbnail application gets focused after 2 seconds total and the UI gets closed

@lwouis what you think?

references #9

**Comment by lwouis** [comment]
I think there are 2 avenues here:

1. Dropping on thumbnails like you can drop on app icons with `command`+`tab`
2. What you described: another way to focus thumbnails
  * Existing ways: release meta key, or click with mouse
  * New way: drag a file on tab of a thumbnail and wait a little

**Comment by lwouis** [comment]
I've started implementing this, and here are some observations:

* The built-in app switcher has confusing signalization when you drag stuff on top of apps:
  * When dragging text over an app that can't act on it, it should show 
![image](https://user-images.githubusercontent.com/106195/74124994-7939a080-4c17-11ea-8450-da423a575c3e.png) but instead it shows the normal pointer.
  * There is a subtle difference between hovering an app icon, and it becomes darker vs it doesn't. I think it should make behavior clearer by showing the barred-circle pointer above if the app can't act on it.
  * I think the above behavior exists because you can *always* drag stuff on top of an app icon, and wait for it to focus, then you *may* be able to drag it somewhere

* There are various things macOS lets you drag and drop: files, text snippets, images, URLs.
  * For alt-tab, I think only URLs are doable when dragged on the thumbnails. I don't think there are APIs for us to send other types of things to the other apps.
  * Even though the user drags on a specific window, dragging a file(s) or a URL will result in the the window's app opening the file(s) or URL. It is at the app level, not window specific. I think it's correct, but worth noting.

**Comment by lwouis** [comment]
I just discovered today another use-case: you can drag and drop **tabs** (not windows) on top of the thumbnails. I think it's intended for added a tab to an existing window. The UI changes: the dragged tab goes from being a thumbnail to being a tab bar. When you drop, it doesn't interact with alt-tab currently (v3 branch). I think we should either not react at all to the dragging in that scenario, or we should support tab drag-and-drop correctly on drop
