### ISSUE TITLE
Add single-row / single-column display option

### ISSUE THREAD

**Issue by flypenguin** [lwouis/alt-tab-macos#751]
**Is your feature suggestion related to a problem? Please describe.**
My eye gets confused by the multiple-row layout of altTab. It has disadvantages, too:
* with a single-row/-column layout the "least recently used" windows are at the right or at the bottom
* with a multi-row/-column layout the current window has TWO neighbors: 
  * a very UN-recently used one below
  * the most-recently used one to the right
  * I think this hinders an easy "eye flow"

**Describe the solution you'd like**
Please add an option to have a Mac OS like "single row" and/or "single-column display" experience.

**Describe alternatives you've considered**
None

**Comment by mknapper1** [comment]
You can accomplish this by setting both `Window min width in row:` and `Window max width in row` to 100%

<img width="468" alt="image" src="https://user-images.githubusercontent.com/8890070/103364123-f289ee00-4a8a-11eb-9892-f64b12b362ba.png">

**Comment by lwouis** [comment]
Indeed, a single-column layout is possible today, by tweaking the various preferences sliders. Having a simpler "one-stop button" has been discussed extensively in other tickets as well (please do a search to find these discussions; they are very rich).

Now for single-row, this raises many questions. For instance, how do we deal with UI when the list because large? The macOS application switcher for example, makes the icon smaller and smaller as space becomes limited. Alternatively, we could use the same approach we use for vertical constraint currently on AltTab: make it scrollable.

So overall, for a one-stop UI to switch to a 1-column layout, please check existing tickets. For a 1-row layout, I think we need more clarity on what that would look like, and how to handle some use-cases like many windows, given into account we need to support *all the existing preferences* that can affect layout such as text side, icon size, disabling thumbnails, etc.

**Comment by flypenguin** [comment]
ha, works just fine for me. closing! :)
