### ISSUE TITLE
Alt-tab spewing errors in system console

### ISSUE THREAD

**Issue by hpl002** [lwouis/alt-tab-macos#754]
**Describe the bug**

Alt-tab is spewing out a lot of errors on every invocation.
All errors read:
`#Critical SRKeyCodeNone has no representation in Carbon`

**Screenshots / video**
![Screenshot 2020-12-30 at 20 08 20](https://user-images.githubusercontent.com/25330262/103375554-cb5b0d00-4ada-11eb-8df1-800cdd51daae.png)

**Steps to reproduce the bug**

Any invocation at all. I have replaced the regular app switcher with alt-tab. Alt-tab is triggered via `cmd-tab`

Downloaded latest release from homebrew. Current version listed in [formula is 6.12](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/alt-tab.rb)
Running on osx 10.15.6(Catalina)

Similar log observed in issue #543

The app is fully functional, but the logging is a bit concerning..

Thoughts on this? 

Thanks!

Herman

**Comment by lwouis** [comment]
Hi @hpl002! Thanks for sharing this concern.

This error log is made by [the library we use for shortcut recording, shortcut UI, etc](https://github.com/Kentzo/ShortcutRecorder). In the version of that library used by AltTab, they have this code:

```objc
- (UInt32)carbonKeyCode
{
    if (self.keyCode == SRKeyCodeNone)
        os_trace_error("#Critical SRKeyCodeNone has no representation in Carbon");

    return self.keyCode;
}

- (UInt32)carbonModifierFlags
{
    switch (self.carbonKeyCode)
    {
        case SRKeyCodeF1:
        case SRKeyCodeF2:
        case SRKeyCodeF3:
```

I'm putting only this excerpt here to illustrate. I think their approach is wrong. When requesting the modifier flags, they check which key code is pressed, to handled the edge-case of the Function keys. When that happens, and the key code is null, they log an error.

AltTab checks modifier flags for different purposes. Sometimes it does it on events where there is a null key code. This triggers the error log I think.

This log isn't the symptom of an actual error. You can simply ignore it. It's possible that recent versions of the library have fixed that issue. I know that the maintainer was changing that area of code when we discussed another issue.

There is a lot of risk, and work needed to either upgrade to a new version, or add guard code around usage of the modifierFlags method in AltTab's code, to avoid this error log. Since it's harmless, I think we can all simply ignore it for the time being.
