### ISSUE TITLE
An option to hide application with no window such as com.apple.finder

### ISSUE THREAD

**Issue by Matts966** [lwouis/alt-tab-macos#763]
Thank you for this great project. I always enjoy tasks with this.

**Is your feature suggestion related to a problem? Please describe.**
I'm always frustrated when the `com.apple.finder` is there and selecting `com.apple.finder` creates a new window.

**Describe the solution you'd like**
It would be very nice to add another option that filters specified applications if they don't have any window.

**Describe alternatives you've considered**
It would be also nice to hide `com.apple.finder` without window by default.

**Comment by MuhammedZakir** [comment]
https://github.com/lwouis/alt-tab-macos/issues/708#issuecomment-748746213:
> > Also, I'm not sure if I'm missing if it exists, but I can't easily tell how to hide the finder icon in the alt tab when there are no finder windows open
> 
> Preferences > Appearance, then:
> 
> ![image](https://user-images.githubusercontent.com/106195/102738586-eb2d5b00-438d-11eb-8f46-14cab48a4fa7.png)

**Comment by lwouis** [comment]
Hey @Matts966! Thanks for the suggestion!

@MuhammedZakir showed you how to disable all window-less apps. It seems you want to only remove Finder, since it's always there, and is kind of a unique app on macOS.

I think we could enable that by changing the Blocklist preference UI. Today it looks like:

![image](https://user-images.githubusercontent.com/106195/103657810-b59f8900-4fad-11eb-8d24-a2ac26f13c0e.png)

We could replace the first list with a table UI, and have a dropdown on the right of the bundleID which says gives 3 options:

* Hide all windows
* Hide open windows
* Hide when no open window

`Hide all windows` would be the default selection

**Comment by MuhammedZakir** [comment]
That will be great!

What will be the difference between `Hide all windows` and `Hide open windows`?

**Comment by lwouis** [comment]
It's hard to explain with words I noticed.

* You have `Open windows` which are your apps open windows.
* Then you have the "window"/icon that AltTab shows when an app is running, but it has no open window.

You may want to hide one, the other, or both, thus you need 3 options. We could name `Hide all windows` -> `Hide everything` maybe

**Comment by MuhammedZakir** [comment]
> Then you have the "window"/icon that AltTab shows when an app is running, but it has no open window.

Isn't this what `Hide when no open window` is for? I'm confused! :grimacing:

**Comment by Matts966** [comment]
Sorry for not noticing the option. With that option, my frustration almost disappears. Great project again :)

However, sometimes I want to kill applications with no window via this project. In that case, I feel [the suggestion](https://github.com/lwouis/alt-tab-macos/issues/763#issuecomment-754672277) is great.

The change would be also nice in that we can unify the settings related to hiding applications.

**Comment by lwouis** [comment]
@MuhammedZakir `Hide when no open window` is a global flag. You turn these kind of things globally on or off in AltTab. Some people may want to see apps with no open windows, so they can quit them, or switch to them. But maybe they don't want to see Finder since it's always running, not like other apps. With my proposal above we would have _per-app_ control over what is shown in AltTab, compare to _global_ control.

**Comment by MuhammedZakir** [comment]
@lwouis: Sorry for not making it clear! I was talking about `Hide when no open window` option. You mentioned there would be 3 options -

* Hide all windows
* Hide open windows
* Hide when no open window

Then, you explained `Hide open windows` is for running apps with no windows. But isn't that what the option `Hide when no open window` do? That's what I am confused about. In other words, what is the difference between `Hide open windows` and `Hide when no open window`?

**Comment by lwouis** [comment]
Sorry I was referring to:

![image](https://user-images.githubusercontent.com/106195/103742945-e7146500-503e-11eb-8479-1c39313d18e3.png)

When I said `Hide when no open window` earlier.

* The **current checkbox** on the screenshot above is a global flag to hide all apps with no window.
* The proposed option, which is part of 3 possible options, called `Hide when no open window `, is a flag to hide the specific app that matches the bundleID listed when it has no window

**Comment by MuhammedZakir** [comment]
😅 Sorry again! This is what I want to know:

1. what is the difference between `Hide open windows` **option** and `Hide when no open window` **option**?

Again, sorry if it's a bother! Feel free to ignore this if you're busy!

**Comment by lwouis** [comment]
An app can be in 3 states:

1. Not open
2. Open, but no window is open for that app
3. Open, and N windows are open for that app

I suggested 3 options:

1. Hide all windows
2. Hide open windows
3. Hide when no open window

Option 1: nothing from that app is show in AltTab
Option 2: we don't show that app's windows.  If it has no open window, then we show that app in AltTab so people can quit it for example
Option 3: we show that app's windows. If it has no open window, then we don't show that app in AltTab

**Comment by MuhammedZakir** [comment]
Thanks! Now, it's clear! 😁 👍

**Comment by MuhammedZakir** [comment]
A suggestion: I think "Show if no open window" is clearer than "Hide open windows".

**Comment by Matts966** [comment]
IMHO, in my experience, it's enough to add a simple dropdown menu with 3 options.

1. Show all active apps as it is now.
2. An option to hide all apps without any window as we already have now.
3. Only hide Finder if there is no Finder window.

As I don't know other apps that can't be killed. (It's a special case, as far as I know.)

Still, the complete option is more extensible.

**Comment by lwouis** [comment]
> As I don't know other apps that can't be killed

The use-case is beyond that. Finder is annoying some people, so that's one use-case, but other people have mentioned in other tickets that they use some app, and they keep it open because it has a long startup time, so they close all its windows and keep the process running. In that case, they complained that AltTab keeps showing the app to them. Doing per-app preference solves all of those use-cases at once.

**Comment by Matts966** [comment]
I see it's important now.

Then a problem is the priority issue. The existing `Hide applications without a window` conflicts with the new option.

Maybe it's simple to move the existing option to the Blacklists tab and prioritize the new one over the existing option.

**Comment by lwouis** [comment]
Good point. I think we can relocate the global checkbox to the Blacklist tab. Then regarding priorities, i agree that per-app should override global

**Comment by lwouis** [comment]
Regarding implementing the list UI, here are some good StackOverflow threads:

* https://stackoverflow.com/questions/22586313/nstableview-with-buttons-like-in-system-preferences-using-only-interface-bui/22586314#22586314
* https://stackoverflow.com/questions/10706357/nstableview-with-plus-and-minus-buttons

**Comment by lwouis** [comment]
Actually, we can't have name and icon because it can vary

**Comment by lwouis** [comment]
Subsumed by #539
