### ISSUE TITLE
Windows from Craft (craft.do) don't show up

### ISSUE THREAD

**Issue by rsiebeling** [lwouis/alt-tab-macos#778]
Hi,

the window from Craft (which can be found at craft.do) does not show up in AltTab, even not when I set the minimized, hidden and fullscreen windows to show...

Below an overview of my settings
![image](https://user-images.githubusercontent.com/3526846/105327247-f5ca5280-5bce-11eb-9087-282bb2546dd1.png)

An screenshot of Craft
![image](https://user-images.githubusercontent.com/3526846/105327463-32964980-5bcf-11eb-8197-cd0c39d51cab.png)

With regards,
Richard

**Comment by lwouis** [comment]
Hi @rsiebeling! Thanks for sharing this issue.

I downloaded Craft, but couldn't reproduce the issue. The app windows properly show up in AltTab, on my machine:

![image](https://user-images.githubusercontent.com/106195/105354287-aff3a580-5c33-11eb-83d3-7c6e1ea8520f.png)

You screenshot looks like Big Sur. Are you on macOS Big Sur? Note that it is not officially supported by AltTab yet, as indicated on the website and on homebrew. I'll add support eventually, but currently, there are a few of tickets with the label `Big Sur`.

It may also be that the issue lies with the Big Sur version of Craft. It's very likely actually.

**Comment by rsiebeling** [comment]
Hi,

yes I am indeed on Big Sur, probably that’s the issue then.
No problem, I’ll then wait for the updated version with Big Sur support ;-)

Regards,
Richard

**Comment by rsiebeling** [comment]
The issue has been solved, I think it's due to the latest update of Craft. The latest update of AltTab didn't make a difference but I see now that Craft has been updated a week ago and they've updated the major tab and window handling..

![image](https://user-images.githubusercontent.com/3526846/106955232-3e3c5100-6735-11eb-9480-1cf9434e7065.png)

I'll close the issue

**Comment by rsiebeling** [comment]
I'm sorry to say but an update of either of the applications has reverted the situation, the window doesn't show up anymore

**Comment by lwouis** [comment]
Tried in a Big Sur VM, and it shows correctly:

![image](https://user-images.githubusercontent.com/106195/108371485-24286580-7241-11eb-89bb-94fa0e77cffc.png)

Does it reproduce every time for you? Can you share a video, steps to repro, any info that can help? Also can you please contact the developers of craft.do to let them know. It's 99% a problem on their side. AltTab is just an accessibility app, so if AltTab doesn't list them, they have a problem on their side and other apps like screen readers are going to be broken on their app as well.

**Comment by rsiebeling** [comment]
Hi,

I’m very very sorry to say but I think I made a mistake and had hidden the application window when trying.
It indeed works great, it was my workflow using Craft...

Thanks for looking into the issue and sorry for the inconvenience..

Regards,
Richard
