### ISSUE TITLE
hiding child windows

### ISSUE THREAD

**Issue by algkmn** [lwouis/alt-tab-macos#779]
Is it possible to hide child windows which are created by application itself? I want to see only main window per application in the box. 

![ss](https://user-images.githubusercontent.com/801371/105492949-bd5b6f00-5cc9-11eb-8166-5260bb4ff3bb.jpg)

**Comment by lwouis** [comment]
There is no concept of main/child window on macOS. The window circled in red on your screenshot is a window like any other. Turns out from a user perspective, it's a tooltip/dropdown menu, but from a technical standpoint, Jetbrains who wrote PhpStorm used an `NSWindow`. I'm pretty sure that they used Java Swing to implement the cross-platform UI of their app, so it's Swing which is using `NSWindow` for all sorts of custom "windows" on screen.

In any case, while what you ask is not possible / doesn't make sense in the macOS ecosystem, the issue you have with these PhpStorm tooltips showing up in AltTab has already been discussed in #660 #562 #741. A version including this fix will be released soon. I'm waiting for people to confirm testing of some other fixes, and I'll release the bundle of fixes including this one. Probably sometime during next week 👍
