### ISSUE TITLE
Windows from R Commander / XQuartz not showing

### ISSUE THREAD

**Issue by JCKE** [lwouis/alt-tab-macos#787]
I am unable to switch to R commander, an XQuartz app, via <kbd>Cmd</kbd>+<kbd>Tab</kbd>. The app is not minimized and is not full screen, yet the window doesn't show a thumbnail when attempting to switch to it through AltTab. 

R is statistical software that can be found here (current stable version 4.0.3): https://www.r-project.org/ 
R commander/Rcmdr is a package available for R found through R's package installer as demonstrated in the video. It appears R Commander opens through XQuartz, I'm unsure if that may be affecting things.

I have MacOS Catalina 10.15.7 and AltTab 6.13.0

Video and screenshots can be found here: https://imgur.com/a/tmR9g27

**Steps to reproduce:**
1. Download and launch R version 4.0.3 from https://www.r-project.org/ 
2. Open menu option Packages & Data -> Package Installer
3. Select Get List, search for and install Rcmdr
4. In the R console, type `library(Rcmdr)`
5. After R Commander loads, attempt to switch between windows

**Comment by lwouis** [comment]
Hi @JCKE!

First of all, thanks for such a high quality ticket! I see lots of low quality tickets from people here, so I do appreciate when someone actually takes time to make it clear, exhaustive, and illustrated 👍

Regarding the issue, I'm fairly certain AltTab is not showing this window because it's not technically a window. It's a common issue with non-native macOS apps. They don't use native macOS/AppKit windows, so AltTab doesn't show anything. The reason AltTab is filtering non-windows is so you don't see mini-HUDs, popups, small floating UI elements, etc, in AltTab.

You can see here a [list of app which we manually excluded from that scrutiny, so that their "windows" show in AltTab](https://github.com/lwouis/alt-tab-macos/blob/909c1231226ad59a57ba8c355b22fdb49b3dd7c8/src/api-wrappers/AXUIElement.swift#L89). I think this R Commander app will probably require us to hardcode another exception in the code.

[More context in this ticket where we discuss how to deal with these apps better than the current implementation](https://github.com/lwouis/alt-tab-macos/issues/456).

**Comment by lwouis** [comment]
I investigated the issue, and actually got very surprised by what I found. I [shared it visually in this video](https://youtu.be/HfdWbOTgcxU).

**Comment by lwouis** [comment]
It seems that R-Commander should update their app to be visible to accessibility app.

* [Open ticket in the XQuartz repo](https://gitlab.freedesktop.org/xorg/xserver/-/issues/785)
* [Pretty telling discussion about previous attempts for the Witch team](https://groups.google.com/g/witch-talk/c/AUKKmhAGI_M/discussion?pli=1)

I think you should open an issue on their repo. I couldn't find it online. Their project seems pretty messy to be honest. Is this not open-source? In any case, it's about them changing their code to appear as a macOS app with accessibility support. Currently it seems they are lower level and don't support higher-level accessibility APIs which AltTab (and other similar apps) depend on.

**Comment by nayfield** [comment]
The other use case for XQuartz is for people who display remote (via ssh -X) linux apps on their mac.

As you saw making the video, there's nothing of interest provided to OS X accessibility.  (However, Expose can enumerate and render the windows).  

From what I can see the Wich ticket in your previous comment is in the freedesktop.org repo which is upstream to XQuartz, so I have opened a ticket there (since this is on github it will appear in this issue as well). 

@lwouis as I am not a Mac OS dev, it would be great if you could detail the minimum information you'd need in that ticket.  Even if you can't render the window contents, being able to enumerate and get the titles would make things much better for Mac users who display remote linux apps - or use local XQuartz apps like the original reporter.

**Comment by lwouis** [comment]
Closing this ticket as there is nothing to be done on AltTab's sidd
