### ISSUE TITLE
New release ignores all fullscreen windows 

### ISSUE THREAD

**Issue by superlevure** [lwouis/alt-tab-macos#794]
**Describe the bug**

Since last update (v6.13.0), Alt tab ignores all full screen windows 
MacOS Catalina ﻿v﻿10.15.7

**Screenshots / video**

https://www.loom.com/share/e995636731974fa693dad5e9f73651a1

**Steps to reproduce the bug**

1. Open any app in full screen (tested with Alacritty, Slack, Telegram etc) 
2. Go on desktop 
3. hit \<cmd> + \<tab>
3. Only destkop apps appear 

or: 

1. Open any app in full screen (testes with Alacritty, Slack, Telegram etc) 
2. Go to a fullscreen app 
3. hit \<cmd> + \<tab>
3. Only the focused app appears 

Thank you for your help !

**Comment by lwouis** [comment]
Salut @superlevure! Thanks for sharing this issue!

I was able to reproduce! It only happens if you have `Show windows from: Screen showing AltTab` selected. If you select `All screens` instead, it shows the fullscreen windows.

I think it's a regression I introduced when implementing #727. I'll try to fix it.

Thanks again for reporting the issue!

**Comment by superlevure** [comment]
Cool, thanks for the quick feedback ! I'll change that option until there's a fix 

Thanks for the great app
