### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by pfelber** [lwouis/alt-tab-macos#796]
I am not entirely sure this can be considered as a bug or should be a proposed enhancement. I'd like to have shortcuts behave as the main switcher from MacOS, except using CTRL instead of CMD, as follows:
- CTRL+TAB to open the 1st switcher with all windows, then while open, press TAB for next and \` for previous.
- CTRL+\` to open the 2nd switcher with windows of current application, then while open, press \` for next
The combination of CRTL+\` has hence 2 roles: for activation of the 2nd switcher (shortcut 2) when no switcher is open, and for navigation through the windows when one of the switchers is open.

The problem is that I cannot configure keys as described above. If I configure shortcut 2 to use CTRL+\` for activation, this seems to override the configuration of \` to select previous window. I would assume, however, that AltTab could differentiate between typing CRTL+\` when the switcher is not yet open (i.e., for activation) from typing it while the switcher is open (i.e., for navigation in the switcher).

Is there a workaround or can this be fixed? Tanks!

**Comment by lwouis** [comment]
Hi! Thanks for sharing this issue.

This is more of an enhancement. The behavior that should happen when the user binds multiple same shortcuts to different actions is not clearly define. I expect people to use different shortcut for different things.

I looked into how hard it would be to enable the workflow you would like. Unfortunately it's quite complex. We have local shortcuts (when the app is opened already) and global shortcuts (when the app is not opened already), and because of the way macOS APIs are designed, if a global shortcut triggers (in our case, the next-windows-shortcut-2), AltTab doesn't receive an event for a trigger of the local shortcut with the same mapping.

There would be ways around this I can imagine by introducing more complexity to our already extremely complex keyboard management. It could be combined with work needed to enable #510.

**Comment by pfelber** [comment]
Thanks for the response, your clarification is correct, this is what I would like. It is actually the workflow of the default MacOS switcher, and it is very convenient. As you have usually very few windows open for a given application, you don't care going forward only by repeatedly pressing \` (or move your fingers to the arrows). But for all windows you really need to go back and forth, hence you need both TAB and \`.

**Comment by FireFingers21** [comment]
I would also be very interested in seeing this functionality come to AltTab as well. It's the one thing that's stopping me from using it 100% of the time. Is this enhancement currently in the works?

**Comment by lwouis** [comment]
> Is this enhancement currently in the works?

Not to my knowledge. If you have technical abilities, feel free to kickstart it 👍
