### ISSUE TITLE
Intellij IDEA is missing from alt tab

### ISSUE THREAD

**Issue by llowinge** [lwouis/alt-tab-macos#824]
**Describe the bug**

Intellij IDEA closed; altab closed. First i open alttab, then i open intellij idea and it is not visible in alttab.

**Screenshots / video**
<img width="1792" alt="Screenshot 2021-02-16 at 09 35 53" src="https://user-images.githubusercontent.com/12760541/108037885-78adc400-703a-11eb-821a-642375569c79.png">

**Comment by llowinge** [comment]
Interesting fact is that if i open new window/workspace of Intellij IDEA, then i can see it in alttab, but the first window is still missing.

**Comment by lwouis** [comment]
Hi @llowinge! Thanks for sharing this issue!

What's your version of macOS? of AltTab? of Intellij (stable, EAP)?

I use Jetbrains products. I actually develop AltTab on AppCode. I've never experienced this issue you describe 😅

**Comment by llowinge** [comment]
Hi @lwouis, version of macOS: 10.15.7, AltTab: Version 6.15.1, Intellij IDEA: 2020.3.1 (Ultimate Edition).

**Comment by lwouis** [comment]
I'm on the same macOS and AltTab versions. I'm using Intellij IDEA Ultimate as well, daily. It's 2020.3.2 for me. I can't reproduce this issue.

How exactly do you launch IntelliJ? Through the Jetbrains Toolbox? Through the `.app`? Through the `idea` cli? Another way?

When it launches, does it open the last project automatically, or do you see the project selector UI?

A video of the issue may help here to see something you're doing that I'm not for instance 👍

**Comment by llowinge** [comment]
Hi, i'm attaching the video. 

https://user-images.githubusercontent.com/12760541/108168474-a9076800-70f7-11eb-8cc4-0c9cbfe47182.mov

**Comment by lwouis** [comment]
Oh! The first window is fullscreen'ed automatically! That's an issue I've dealt with a lot in the past. Fullscreen windows are terrible to handle because they are on another Space. There is no public API to handle windows on other Spaces, so I use retro-engineered private APIs to do it. It's a lot of workarounds to get AltTab to handle these cases.

I'll see if I can reproduce. Most likely if the window wasn't fullscreen'ed when you launch IntelliJ, the issue wouldn't happen.

**Comment by llowinge** [comment]
@lwouis Thanks for heads up ! It looks you are right, because now it was working OK, but i had two windows opened (one of them went to fullscreen immediately and the second sticked on "main" space) and both windows appeared in AltTab. Then i closed the one which didn't go to fullscreen and closed whole IDEA, restarted alttab, run again IDEA and one window went to fullscreen and it was missing in alttab.

**Comment by lwouis** [comment]
I'm able to consistently reproduce this issue. Here are the steps:

* Open some project in IntelliJ (I think version doesn't matter)
* Fullscreen the window
* Quit IntelliJ
* Start AltTab
* Start IntelliJ
* IntelliJ goes through a sequence of: loading screen window, creates project window, fullscreens it
* AltTab doesn't list the fullscreen'ed window at this point

The issue is that AltTab tries to detect if the new window is tabbed **during the OS animation** of Spaces changing and the window going fullscreen. This results in AltTab detecting that the window is tabbed, and not showing it.

I've developed a workaround using a new private API called `SLSManagedDisplayIsAnimating` and retrying until the display has stopped animating. It is then safe to check if the window is a tab. 

@llowinge could you please try out this [local build with the fix](https://github.com/lwouis/alt-tab-macos/files/6098705/AltTab.app.zip), and share here if it's working for you?

**Comment by lwouis** [comment]
@llowinge oh! I'm surprised it doesn't fix it for you. For me if i turn the fix on, i see it, and off i don't see it.

Could you may be share a video of the issue? Maybe there is something else at play in your case that i could spot by checking it in video. Please show your preferences for AltTab also 👍

**Comment by stevetodd** [comment]
FYI, I also still experience this issue. 

AltTab: 6.18.1
IntelliJ IDEA: 2020.3.3

Same behavior. If IntelliJ was quit in fullscreen and relaunched, it doesn't show up in AltTab. If I take it out of fullscreen, quit, and launch, it does show up.

**Comment by dvcrn** [comment]
This is closed already but I still have repeatedly the issue that jetbrains stuff just vanishes from the alt-tab. Not doing any fullscreen settings here and keep it in a normal window all the time. 

Even after restarting alt-tab or IDEA, it still doesn't show reliably

<img width="686" alt="Screen Shot 2021-11-24 at 11 09 23" src="https://user-images.githubusercontent.com/688326/143158693-e9504a09-7822-4d19-979d-abf141381601.png">

<img width="686" alt="Screen Shot 2021-11-24 at 11 09 24" src="https://user-images.githubusercontent.com/688326/143158671-eb7b608d-d032-4141-a8e1-ac0537fae11c.png">

IDEA Is installed through toolbox

**Comment by lwouis** [comment]
@dvcrn could you please open a new ticket, and use the Bug template to provide nice steps to reproduce, video of the issue, etc? The template will guide you in providing useful info so that we can repro and investigate your issue easier 👍

**Comment by dvcrn** [comment]
Yes sure! I created a new issue. Sadly I still haven't figured out how to reproduce this besides just using the apps for a longer period of time...

**Comment by Akazm** [comment]
> Yes sure! I created a new issue. Sadly I still haven't figured out how to reproduce this besides just using the apps for a longer period of time...

That's even more confusing since I'm constantly facing this issue. Like - Neither WebStorm nor IntelliJ appear.

Damn, wish I'd had time to dive into this.

**Comment by HYDROGRID** [comment]
Same problem. Happens regularly that IntelliJ (and also it's related windows) are missing on AltTab.
