### ISSUE TITLE
Tell users about incompatible shortcuts

### ISSUE THREAD

**Issue by huyang531** [lwouis/alt-tab-macos#832]
**Describe the bug**

I tried to use the `` ` `` key to select the previous window, as the original `cmd-tab` on macOS does, but it didn't work. Note that all other keys including the default `shift` key worked.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/61642227/108799044-48ca6780-75ca-11eb-8dd7-f08dfcbc28a8.png)
(I also set the trigger key to `cmd` instead of the default `opt`)

**Steps to reproduce the bug**

1. Set the `Select previous window` key to `` ` ``, the backtick.

**Comment by lwouis** [comment]
Hi @huyang531,

It doesn't work because by default the ``` command-` ``` is already assigned in Shortcut 2. Please un-assign it there, and you will be able to bind it to `previous window`.

I'll keep this issue open, because ideally we would outline shortcuts that are already used in red, or maybe even prevent the user from setting incompatible shortcuts.
