### ISSUE TITLE
System app switcher shortcut is not restored on crash

### ISSUE THREAD

**Issue by nfekete** [lwouis/alt-tab-macos#834]
Sometimes, when AltTab crashes, I can't switch between apps anymore since the system app switcher is not receiving shortcuts (I use the same `Cmd+Tab` shortcut). To be able to go back to the system app switcher, I have to start AltTab and quit it normally so that the system app switcher is receiving events again.

Is there a crash handler installed, which restores the keyboard shortcuts of the original app switcher? If so, could it be that in some crash cases it doesn't execute? If not, could it be included in the app, so in case AltTab crashes, the user can still switch between apps?

**Comment by lwouis** [comment]
Hi @nfekete!

You have correctly guessed what was happening. I put code to restore the OS shortcut on app exit. However in case of a crash that code is skipped.

I'll see what i can do. An app on macOS can crash in a variety of ways because of the layers (mach, objc, swift) and types of error. I know that from when i added AppCenter Crashlytics to the app. I'll see if there is a way to call cleanup code in those scenarios 👍

**Comment by lwouis** [comment]
I found [this conversation](https://github.com/microsoft/appcenter-sdk-apple/issues/1719#issuecomment-681902816) on AppCenterCrashes repo. Quoting from the code referenced there (emphasis mine):

> * Plausible CrashReporter provides support for executing an application specified function in the context of the crash reporter's signal handler, after the crash report has been written to disk. This was a regularly requested feature, and provides the ability to implement application finalization in the event of a crash. However, **writing code intended for execution inside of a signal handler is exceptionally difficult, and is not recommended**.

It seems that indeed, the app can crash in many ways, and even if we could hijack the catch-all exception handled from AppCenter (which uses [plcrashreporter](https://github.com/microsoft/plcrashreporter) internally), then executing our code to restore the command-tab shortcut may not be a good idea there. I imagine the app is in such a bad/unpredictable state that it may not execute the command we want, or execute it with the wrongs arguments (could be terrible in our case).

I'm afraid we can't do much here.

What I've done is implement a more careful logic to disable/re-enable the built-in command-tab/command-shift-tab shortcuts. Users who don't re-bind to these will not have anything touched on their system, and if you unbind these, it will also restore the built-in shortcuts. It's not as good as restoring them on crash, so some issues can happen, but I think it's the best I can do

**Comment by lwouis** [comment]
I asked a follow-up on the AppCenter thread: https://github.com/microsoft/appcenter-sdk-apple/issues/1719#issuecomment-786585852

**Comment by nfekete** [comment]
I would still consider adding that code to the crash handler. I don't think the outcome would be any worse than having no app switcher available and there's a good chance that the shortcut restoration code would run successfully and have a graceful crash as a result.

Also, it could be somewhat tested by explicitly triggering crashes within the app and see how the crash handler execution behaves.

**Comment by lwouis** [comment]
> Also, it could be somewhat tested by explicitly triggering crashes within the app and see how the crash handler execution behaves.

As I said, there are many crash types. You can divide by 0, throw an uncaught exception, have a library in objc crash bellow the swift code, have a crash from the mach layer, etc.

So testing all types of crashes is its on whole project. I tested a few, and they were not caught by my `NSSetUncaughtExceptionHandler` callback.

It's a hard problem because swift is a multi-layer platform. We are not in a Java app for instance were crashes are straightforward and homogeneous.
