### ISSUE TITLE
Add preferences: thumbnails layout

### ISSUE THREAD

**Issue by adityakaulagi** [lwouis/alt-tab-macos#89]
Firstly, thanks for creating this! I've been looking for a replacement for HyperSwitch for a long time since its quite buggy and not updated as frequently as it used to be.

Anyway, here are some features I think would be a great addition to make this look as close to HyperSwitch:

1. Allow previews to be justified to left when spanning across multiple rows. Currently, they are justified to center, and I personally prefer them to be justified to left. Since this is just a personal preference, an option to be able to choose preview alignment would be great.

2. Make previews equal sized (aligned to a grid) so they take up the same size even if window size is different. The window image can be of different size to show that window size is different, but the whole preview would look better if all previews were the same size.

3. Add option to control transparency / color of blurred background for the previews. Also allow to control border radius of the same blurred background if possible.

Sorry if any of these are already in work or already asked for previously. Please edit/remove as you feel necessary. Thanks again for the fantastic app!

**Comment by lwouis** [comment]
Thank you for sharing these ideas @adityakaulagi! Here is some feedback:

1. That would be quite easy to do. Would you like to try? There are few things to touch, so that would be a great first ticket!

* [Here](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/ui/CollectionViewCenterFlowLayout.swift#L42) is where we would need to add the left-center logic
* [Here](https://github.com/lwouis/alt-tab-macos/blob/21a4587e775202ff468e180a4c64c9b71e199b6c/alt-tab-macos/ui/PreferencesPanel.swift#L89) is where you would add the preference UI
* [Here](https://github.com/lwouis/alt-tab-macos/blob/eabc327edcea85b39c729255db903cdabf7b1f27/alt-tab-macos/logic/Preferences.swift#L20) you would add the preference so it's saved on disk between runs

2. Personally I prefer the current implem which is: each thumbnail has a max width and a max height, and the we pick one of the other depending on if the window is wide or tall. This means we have better visibility on wide and tall windows. This is also what Windows 10 does. If you explore [this folder](https://github.com/lwouis/alt-tab-macos/tree/master/docs/img/windows-10) you can see examples of that. Could you elaborate on why you think same height is a better design? Especially some mockups or screenshots so it helps visualize the situation for the discussion

3. Again that would be quite easy to do. It would be adding a slider preference. Very similar to what I linked above for 1). [Here](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/ui/ThumbnailsPanel.swift#L30) is the background object.

Let me know if you are interested in trying to raise a PR. I would like to be convinced for #2, but 1) and 3) are very simple changes, ideal for a first contribution here :)

**Comment by lwouis** [comment]
@adityakaulagi note that in the v3 branch #114, I kind of touched on your point 2. The new layout logic is:

- Cells have a all the same height (to visually notices rows better)
- Cells have a minimum width (to help read titles of tall and thin windows)
- Cells have a maximum width (actual width will be between minWidth and maxWidth, to accommodate different aspect ratios)
- Main UI window size is a ratio of screen size (to scale with display size)
- Cells height and width is a percentage of main UI window size (to get a number of rows for which they are still easy to read)
- As you open more windows, the cells shrink to fit more on screen (to support users who have lots of open windows)

**Comment by lwouis** [comment]
@adityakaulagi I was working on #171 and while reworking the layout code, I took the opportunity to implement the layout preference (thumbnails aligned: left or center). Could you give it a try? Here is a build for convenience: [AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/4373701/AltTab.app.zip)
