### ISSUE TITLE
Broken VSCode icon on secondary display

### ISSUE THREAD

**Issue by danilofuchs** [lwouis/alt-tab-macos#901]
**Describe the bug**

Using a secondary 1080p monitor, VSCode icon is broken.
On my Macbook primary monitor, it looks fine.

**Screenshots / video**

Primary display:
![20210407_150845](https://user-images.githubusercontent.com/17657014/113914342-d1384c80-97b3-11eb-91a4-9869c6581e28.jpg)

Secondary display:
![20210407_150905](https://user-images.githubusercontent.com/17657014/113914350-d39aa680-97b3-11eb-858f-c1bb067fce6b.jpg)
_Notice the weird colors of VSCode icon_

**Steps to reproduce the bug**

1. Open multiple VSCode windows
2. Focus on secondary display
3. Run the alt-tab shortcut

**Comment by lwouis** [comment]
That bug is pretty rad! Looks so unique I would guess it could be some GPU driver / display driver / OS bug.

Not much I can do since I can't reproduce it. You could try poking around to try and guess at the root cause. Things I would try:

* Try another external monitor -> does it have the issue?
* Does it happen with both monitor on, or just the external one? Try the other config to see?
* What if you change the resolution?
* What if you reinstall VSCode?
* Is it persistent? What if you restart AltTab? VSCode? The computer?

Maybe through these you could triangulate if the issue lies with: the display hardware/firmware, the OS drivers, VSCode, AltTab.

**Comment by danilofuchs** [comment]
Ok, so this is weird.

I restarted the computer, no change.

Then, I edited the 'Window App Icon Size' appearence setting. Some values are broken but others work fine: 
- 0~32: Broken
- 32 (default): Broken
- 33: Broken
- 34: Fine
- 35~128: Fine

It seems like an issue with the resizing algorithm. Any value from 34 and above is rendered correctly.

The weird thing is it only happens with VSCode. They updated the icons in the latest update, perhaps some issue in the new asset?

**Comment by danilofuchs** [comment]
Also, changing monitor resolution (900p and 720p) did not fix it

**Comment by statico** [comment]
I get this too without using Alt-Tab, so I don't think it's related to this project.

In case anyone else comes across this: it only seems to happen with VS Code, and only on my low-DPI 1080p display. It works fine on my hi-dpi 4k display.

Low-DPI 1080p display:
![image](https://user-images.githubusercontent.com/137158/114096758-02785180-9874-11eb-9ff4-de5ab9c26b3a.png)

High-DPI 4k display:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/137158/114096799-115f0400-9874-11eb-9f1e-cece21316147.png">

**Comment by lwouis** [comment]
Thanks for sharing @statico! So now I suggest you guys follow it up with the VSCode team. They have 5000 open tickets on their repos, so maybe one already exists for this? I did some search and found this [different but kind of similar issue](https://github.com/microsoft/vscode/issues/69665).

I suggest your try to find the icon issue in the big pile of open tickets, or you create a new ticket, explaining the issue above 👍
