### ISSUE TITLE
Microsoft To Do crashing

### ISSUE THREAD

**Issue by rawbertp** [lwouis/alt-tab-macos#903]
**Describe the bug**

- In Microsoft To Do just edit a task and add a note.
- When trying to delete the node again, "To Do" crashes (either after deleting the last character or immediately after selecting all + delete)

**Screenshots / video**

https://www.loom.com/share/528dc9c9abbb4911a90f270aa35e23b1

**Steps to reproduce the bug**

See (1).

To Do doesn't crash when AltTab is not running.

**Comment by lwouis** [comment]
I'm afraid there is not much I can do to investigate this. To Do is crashing due to a logic bug on their side. AltTab doesn't interact with any app. There have been cases of Java apps in the past that have bugs in the macOS events code that would get affected by AltTab watching their accessibility events. Maybe this app is in that category, maybe it's something else.

Could you please open a ticket with their customer service? If there is a public bug tracker, please reference your ticket here so we can follow their investigation, or I can help them if they have questions 👍
