### ISSUE TITLE
monal alpha builds not shutting down when alt-tab is running

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#904]
**Describe the bug**

Monal alpha builds from https://www.eightysoft.de/monal/ will not shut down when closing app via `⌘Q`. When alt-tab is not running monal alpha will close as expected. Curiously this problem does not exist with the stable release of monal. Unsure if this is a problem in alt-tab or monal itself, in which case please close this bug and maybe add some info what to report to monal.

**Steps to reproduce the bug**

1. download monal alpha from link above
2. unpack and drag to programs
3. right-click > open twice as alpha builds are unsigned
4. with alt-tab running select monal and press ⌘Q to quit

**Currently**
Although the app window is gone the app will remain open and never close.

**Comment by lwouis** [comment]
Hi @foss-, long time no see!

> this problem does not exist with the stable release of monal

Well there it is. They can diff alpha/stable and see where they regressed. If you open a ticket in their tracker somewhere, could you please reference it here. I'm curious what they are doing wrong. AltTab is not supposed to interact with other apps in any ways, but there are known apps that have issues. I think so far it's been mostly Java app, and it issue stems from some macOS event bug in the Swing/AWS stack.

**Comment by foss-** [comment]
This is now affecting both stable and nightly builds of Monal. Latest nightly is still at https://www.eightysoft.de/monal/ 
Thilo brought up the question if this could be a [problem with alt-tab and Catalyst apps](https://github.com/monal-im/Monal/issues/615#issuecomment-879380265). Can you share any insight on this or even try reproducing and let us know if you think this is mroe on alt-tab side of things or needs to be addressed in Monal and if the latter any hint where to look at would be much appreciated.

**Comment by lwouis** [comment]
I downloaded Monal alpha through your link. The first time I opened it, it had no window. I could see the app running in the Dock, but there was no UI I could bring up. I pressed `⌘Q` and it quit successfully. I launched the app again, and this time it showed some windows.

Now when I press `⌘Q`, it quits, but indeed a thumbnail remains in AltTab. However, after maybe 5s, it goes away. After a little debug session, I found the issue. The issue is that Monal is not quitting right away. It's hiding itself, then after 5s, it's really quitting. I imagine they may be doing this in order to take some time to save some data on disk, or make sure something is cleaning terminated. Not sure, but it's clearly a strategy from Monal to not terminate right away and instead hide for a few seconds first.

Could you bring this to the monal maintainers? Here is a [video showcasing the issue very clearly](https://youtu.be/7NUO5gqLT8Q).

**Comment by tmolitor-stud-tu** [comment]
That's right, the app runs in the background for a few seconds after the window was closed, just like on iOS when you switch to another app but don't swipe away Monal.

More than that: because Monal is a Catalyst app it can be started in the background by the OS any time (for example on connectivity change).

I guess such a background tart would show up in alt-tab, too, right?

**Comment by lwouis** [comment]
From @foss- on Discord:

> so on big sur I discovered that when alt tabbing into a lingering monal, it would "reopen" so to say and once that happens it will never close. this was the actual problematic behavior I saw when filing the bug. back then I was unaware of the lingering situation though.

This scenario is interesting. We have a ticket to have another behavior when focusing an app: https://github.com/lwouis/alt-tab-macos/issues/999. Instead of launching it, it would simply focus/activate it.

While that may help with Monal and other "dormant" apps, I think these apps shouldn't break in that scenario. I don't know if it's Apple's Catalyst technology that's the issue here, or a logic bug in Monal code, but Monal should deal with a re-launch event properly without softlocking.
