### ISSUE TITLE
can't expand the menu panel, "close" button overlays ">>"

### ISSUE THREAD

**Issue by meiser79** [lwouis/alt-tab-macos#914]
Hi,

first of all, thanks for this great tool!

I just upgraded to version 6.19.0, and I can't expand the menu panel anymore, "close" button overlays ">>", see attached screenshot.
![screenshot](https://user-images.githubusercontent.com/1272168/114678753-d7767d80-9d0b-11eb-86a5-558865c5d79a.jpg)

Thanks for having a look!
Kind Regards,
meiser

**Comment by lwouis** [comment]
I was able to reproduce the issue by updating in a BigSur VM:

![Uploading image.png…]()

**Comment by lwouis** [comment]
After looking at the code diff between the 2 releases, it's hard to see anything that would trigger this. My guess is that it's happening because I updated the CI VM from Xcode 11.5 to 12.2:

![image](https://user-images.githubusercontent.com/106195/114847606-d717d880-9e18-11eb-98ec-f3976d12949e.png)

The bug seems to be caused by XCode using a BigSur-specific implementation of tabs on NSWindow. Maybe the same code builds to UI on the first screenshot above, starting from XCode 12?

**Comment by meiser79** [comment]
Works fine again, thanks a lot!
