### ISSUE TITLE
Remaining window controls

### ISSUE THREAD

**Issue by decodism** [lwouis/alt-tab-macos#925]
**Describe the bug**

In some cases, when a window is closed by the UI button in AltTab, the window controls move to another element.

**Steps to reproduce the bug**

- Open a single window
- Close the window with the button in AltTab
- Open another window
- Invoke AltTab

Or

- Open 3+ windows
- Close one of the central windows with the button in AltTab

**Possible solution**

Add `showOrHideWindowControls(false)` in "updateRecycledCellWithNewContent".

**Comment by lwouis** [comment]
Hi @decodism, thanks for sharing this issue

I'm not understanding the scenario completely. Could you please share a video of the issue in motion?

I tried to follow the steps you provided, but what I see seems correct to me

**Comment by decodism** [comment]
Done:

[](https://user-images.githubusercontent.com/77468771/115411481-cd64eb00-a1f3-11eb-9343-514a7a30864d.mov)

**Comment by lwouis** [comment]
The video shows correct behavior to me.

* `Untitled 2` is selected (black background)
* `Untitled 2` is closed
* `Untitled 3` gets selected since it takes the second position in the list now that `Untitled 2` doesn't exist anymore
* The mouse has not moved at all since clicking the red button, so there is no selection of the window under the mouse

In short, the mouse needs to move to trigger re-selection of what's under it. This is very much on purpose, to avoid users moving the mouse by mistake when they use the keyboard shortcuts to move around. You can see #286 for more in-depth discussion around these mouse + keyboard scenarios.

For now I'll close the ticket as this is working correctly.

**Comment by decodism** [comment]
I am not questioning the selection behavior, but the fact that the window control buttons get "recycled" to the newly selected window. You can even see that they are in a "pressed" state.

**Comment by lwouis** [comment]
Oh I missed the point indeed!

The buttons are supposed to only appear on mouse hover, so they shouldn't show after the click. I'll look into it!

Thank you for insisting and helping me understand the issue 👍
