### ISSUE TITLE
command-tab + arrow selection

### ISSUE THREAD

**Issue by gitbuckley** [lwouis/alt-tab-macos#957]
Side arrows don't work for selection if using command-tab mapping stead of option-tab.

**Comment by lwouis** [comment]
I just tested and it works for me. Could you please share a video of the issue in motion, to help visualize the conditions and behavior?

**Comment by gitbuckley** [comment]
I'm afraid a video doesn't do much since it's just lack of motion. While holding command, repeated tab and up and down arrows work to change selection but side to side arrows do not, but they do if I keep the default option-tab setting instead of changing it to command-tab. Here's a screen shot of the settings, I've tested on two different Macs now, same thing happens. 
![image](https://user-images.githubusercontent.com/10285248/118766196-f5fef580-b830-11eb-9a57-d174920c8686.png)

**Comment by lwouis** [comment]
I'm also on Catalina. I reproduced your preferences. I do `cmd+tab`, and the side arrows work as expected.

* Are you using an external keyboard?
* Could you verify that your arrow keys are working properly? I used [this web tool](https://w3c.github.io/uievents/tools/key-event-viewer.html), and pressed `left arrow` then `right arrow`. Do you see the same exact lines in the tool when you do that?
  
![image](https://user-images.githubusercontent.com/106195/118775309-c21fe080-b8c1-11eb-8c77-bc8a2525aebb.png)

**Comment by gitbuckley** [comment]
Yeah I get exactly the same output on my MBP keyboard and my desktop keyboard.

**Comment by lwouis** [comment]
So you use the built-in macbook pro keyboard, and yet you get this issue? Very surprising. Do you have any software involved with the key mappings? I use BetterTouchTool for instance, and my logicool mouse driver app. Some people use Karabiner Elements for example. Did you modify the built-in shortcuts or keyboard preferences in System Preferences? Any modification of system .plist or shell conf files regarding keyboard bindings?

If you don't do any custom remapping from what I listed here, then I don't know how I can help with the issue since I can't reproduce it on my machine, and I have nothing to work with to investigate. Could you share a video from your mobile phone of you filming the screen and your physical keyboard, and showing the sequence of key presses, and what happens on screen? Maybe I could detect something we didn't think about by watching

**Comment by gitbuckley** [comment]
Resolved, thanks for the suggestions. The issue was that years ago I mapped mission control space switching from control-arrows to command arrows. Thanks for taking the time build this great tool and being so responsive to this issue / self-inflicted wound. 

![image](https://user-images.githubusercontent.com/10285248/118919002-9106d680-b8e8-11eb-921a-bee6f6a8eb43.png)

**Comment by lwouis** [comment]
Glad I could help you 👍

**Comment by dimisjim** [comment]
https://github.com/lwouis/alt-tab-macos/issues/957#issuecomment-844676364
Same issue for me, however, I had never mapped that, it was there by default
