### ISSUE TITLE
Esc does not close the AltTab switcher when ⌘Esc is defined as a shortcut in the system

### ISSUE THREAD

**Issue by ilyabirman** [lwouis/alt-tab-macos#961]
I have ⌘Esc set up to show Launchpad. When I press ⌘Tab and then change my mind, I press Esc while still holding ⌘ (obviously), expecting AltTab to disappear, but get Launchpad shown instead.

This problem does not happen with the system app switcher. Somehow Esc gets captured by the switcher itself before it gets to the system shortcuts dispatcher.

1. Go to System Preferences → Keyboard → Shortcuts → Launchpad & Dock
2. Set ⌘Esc as a shortcut for Launchpad
3. Press ⌘Tab to summon AltTab switcher interface.
4. While still holding, press Tab couple of times to get to another item in the list.
5. Change your mind and press Esc, expecting to just get rid of AltTab switcher interface.
6. Get Launchpad instead.

**Comment by lwouis** [comment]
I don't believe we could implement that behavior. AltTab probably doesn't see the key event since the shortcuts from System Preferences > Keyboard > Shortcuts take priority over any app, and absorb them when there is a match

Interestingly you may ask then how AltTab is able to work when set to use command+tab, since that's a system shortcut, and would then trigger first. Well when the user sets the shortcut to command+tab, i call a private API and disables the system shortcut by ID. It's pretty bad but it's the only way to provide that feature for users.

i'll close this for now as it's not a common use-case and can be worked around using a different shortcut or maybe a tool like BTT

**Comment by ilyabirman** [comment]
Ok, thanks for explanation :–)
