### ISSUE TITLE
Support [,] while holding [⌘] to quickly get to AltTab Preferences

### ISSUE THREAD

**Issue by ilyabirman** [lwouis/alt-tab-macos#962]
Now to change something about AltTab, you need to launch it as an app, which will open its Preferences window.

I have pressed the [,] key instinctively several times while the AltTab switcher interface was displayed (so ⌘ was pressed), expecting the Preferences window to appear, but it did not. Make it work :-)

**Comment by lwouis** [comment]
This seems quite convoluted to be honest. I too am an avid user of command+, but pressing it while the switcher UI is up, i wouldn't expect it to trigger personally.

What would happen then? It would close the switcher without focusing any new window, then bring up the preference window?

I'll test it out and see how it feels

**Comment by ilyabirman** [comment]
It’s hard to argue about convoluted-ness, but pressing [,] while holding [⌘] was the first thing that came to my mind when I wanted to go to Preferences, and when it didn’t work and I was stuck for a moment: OK, so how do I change Preferences now? As to particular implementation, yes, I’d just dismiss the switcher as if nothing happened and show the Preferences window.

**Comment by lwouis** [comment]
Apps can be shown: in the Dock or in the menubar. There are more exotic ways, but these 2 are the main place a user should look for an app. AltTab is a utility app, so it lives in the menubar. That's where you can go to find the preferences. Some people wanted no icon even in the menubar, so there is a preference to have no icon.

That's why, like other apps such as The Unarchiver, there is a second way to open AltTab's preferences: double-clicking the app icon while the app is already running.

Regarding the 3rd way you would like to see implemented, part of why I find the idea un-intuitive is that the defaut shortcut is `option+tab`, not `command+tab`. Which means someone would press `option+tab`, then would release `tab`, and have to do the gymnastic of pressing `command` in (without releasing `option`), then pressing `,`. And that's for people with `option` as the modifier. You can imagine people with keyboard mappings that make this even harder.

**Comment by lwouis** [comment]
Based on my previous message above, and the rationale within it, I'm going to close this ticket for now. If more users request it, we can reopen the discussion, and discuss how to deal with:

* People not using `command` as the main modifier
* People already binding `,` to a shortcut in AltTab

Maybe a solution for both those issues would be exposing this shortcut in `Preferences > Controls`. In any case I'm closing this ticket until more demand is expressed.
