### ISSUE TITLE
Add a full screen live preview when cycling through the apps

### ISSUE THREAD

**Issue by mlubej** [lwouis/alt-tab-macos#967]
**Is your feature suggestion related to a problem? Please describe.**
Sometimes seeing just the icon or the small window tile is not enough, I'd like to see the focused app also focused for real, no matter which space/display it occupies.

**Describe alternatives you've considered**
Hyper-switch has a similar functionality, but it's very slow and it ignores any preferences I specify.

**Comment by lwouis** [comment]
It would be an interesting feature. It would need to be shaped a bit more though. Would we show it on mouse-hover like HyperSwitch, or maybe just when cycling through the thumbnail with the keyboard shortcut?

Regarding implementation, I'm not sure how they do it. I was guessing that they create a fake window and print the screenshot of the actual window on it. But then I took a slow-motion video, and the animation is seamless. This gets me thinking that they may be using the private SPI to bring a window up without focusing it (focus order is not messed up by the preview; as is the top left app name not changing).

**Comment by mlubej** [comment]
> It would be an interesting feature. It would need to be shaped a bit more though. Would we show it on mouse-hover like HyperSwitch, or maybe just when cycling through the thumbnail with the keyboard shortcut?

I guess both, or related to the focus of the app, so if the app is selected (either with cycling through or with the mouse), the app is brought to the front.

I'm not exactly sure how to achieve this. I'm fairly new to mac and just thought I'd make the suggestion though. I really like the tool!

**Comment by safield** [comment]
I think it would be nice if the window associated with the currently selected thumbnail would simmply be brought to the foreground as you cycled through the thumbnails.

**Comment by XInTheDark** [comment]
This feature is very similar to the one that Windows offers, and it has proven quite useful:

https://user-images.githubusercontent.com/61100393/196666609-783e1e5f-6cd3-445f-8cd5-5f54164419a8.mov

**Comment by bishshoy** [comment]
I have got a great idea to have this feature implemented, without requiring too many modifications to the existing way of doing things. Instead of making the selected app come to foreground, AltTab could draw the screenshot of the app on the location of the app itself. If the app is behind another app, then it could draw it over the top app. The size of the screenshot would match the size of the window. And every time the user presses Cmd+Tab, the screenshot and the location of the screenshot gets updated. Also, at any given time only one app's screenshot is displayed on the switcher pane. This would make the user feel that AltTab is switching amongst the windows in realtime. Makes sense?
