### ISSUE TITLE
Alt tab hanging repeatedly  on macOS 11.2.3

### ISSUE THREAD

**Issue by mikekaminsky** [lwouis/alt-tab-macos#978]
**Describe the bug**

Alt tab is freezing up and hanging repeatedly on macOS 11.2.3. 
![Screen Shot 2021-06-01 at 6 40 39 PM](https://user-images.githubusercontent.com/5394529/120403055-0a4ef200-c309-11eb-8a62-3026d7a7569c.png). It looks like it's trying to use 6.4GB of virtual mem which seems ... high.

I'm not sure what other information is useful -- i've force-quit and restarted the app a handful of times and this keeps happening.

I also removed the app from `applications` and reinstalled (via download installer) and this is still happening.

Let me know what other information I can provide :)

![Screen Shot 2021-06-01 at 6 43 58 PM](https://user-images.githubusercontent.com/5394529/120403188-5437d800-c309-11eb-84d2-fda1da5ada22.png)

**Comment by afrancht** [comment]
I have noticed that since I upgraded to Big Sur my laptop is way slower too, I'm on an i5 macbook pro 2016 and I see WindowServer taking up a lot of resoruces. Somehow I feel its alttab but I could be wrong?

**Comment by lwouis** [comment]
@mikekaminsky I don't have enough knowledge about macOS memory model and low-level programming in general to really understand what this Virtual Memory Size high number represents. I researched a bit, and my best guess is that it's memory theoretically usable but actually unused by AltTab. I'm guessing that this comes from inner mechanics of AppKit which is the source of APIs for macOS apps, and what AltTab uses to interact with macOS objects such as windows. I'm guessing that because when profiling in Instruments, this VM seems to come from MALLOC statements from pieces of code not in the source code of AltTab.

This VM is not used in reality. The "Real Memory Size" is what the process actually requires. You can see in your case around 100MB which is decent I think. AltTab stores very little at the end of the day:

* The list of running processes (only the ones that could spawn windows)
* The list of open windows
* Some event handlers to get notified from OS events such as "new window spawned" or "accessibility permission was removed"

I've spent quite a lot of time and effort making AltTab:

* Small on the disk
* Use low CPU
* Use low memory

You can see how I go in details in the tickets tagged with "performance": https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aissue+label%3Aperformance+is%3Aclosed

All this to say, I don't think memory is wrong here. Any app takes many GBs of this Virtual Memory if you check on your system.

Regarding the hanging, that's definitely not normal. Something seems to be stuck in a loop in your case. Sharing one of these would help to locate what the looping code is:

![image](https://user-images.githubusercontent.com/106195/129535527-d9527ee3-d877-4feb-b099-1387c6c93ad6.png)

Do you get the prompt to send a report when you reboot AltTab? If so, did you accept? This sends a crash report to AppCenter where I periodically look at user submitted crashes and try to work on fixes. If you didn't get the prompt, a manually generated sample, spindump, etc, shared here as a zip would help me diagnose.

---

@afrancht quit AltTab and see if "performance" improves. It's well know that after an OS upgrade, users experience slow downs. This is because the OS is recreating a number of caches/indexes for a few days after the upgrade. It could also be that Apple had performance regressions, which they almost always introduce these days.

Try to quit AltTab and see if your experience improves. Report here and you find proof that AltTab is doing something wrong. It's impossible to investigate such a vague statement as "I think it may be slow due to AltTab. Oh I just upgraded my operating system btw" without more specifics.
